- README.md
- ROADMAP.md
- ci/pingcap_tidb_operator_build_dind.groovy
- docs/local-dind-tutorial.md
> *: refine TiDB Operator docs

- pkg/apis/pingcap.com/v1alpha1/types.go
- pkg/controller/tidbcluster/tidb_cluster_control_test.go
- pkg/controller/tidbcluster/tidb_cluster_controller.go
- pkg/controller/tidbcluster/tidb_cluster_controller_test.go
- pkg/manager/member/pd_member_manager.go
- pkg/manager/member/pd_member_manager_test.go
- pkg/manager/member/pd_scaler.go
- pkg/manager/member/pd_scaler_test.go
- pkg/manager/member/scaler.go
- pkg/manager/member/tidb_member_manager.go
- pkg/manager/member/tidb_member_manager_test.go
- pkg/manager/member/tikv_member_manager.go
- pkg/manager/member/tikv_member_manager_test.go
This PR only extract pd's scale down logic, when accepted, i will do other, include defer deletion of PVC.
@tennix @onlymellb @xiaojingchen @gregwebs PTAL
> *: extract scale in as scaler interface

- pkg/manager/member/pd_member_manager.go
- pkg/manager/member/tidb_member_manager.go
- pkg/manager/member/tidb_member_manager_test.go
- pkg/manager/member/tikv_member_manager.go
- pkg/manager/member/utils.go
- tests/e2e/e2e_test.go
- tests/e2e/upgrade.go
this pr add e2e test case to check upgrade feature
PTAL
> add upgrade e2e test

- docs/local-dind-tutorial.md
- hack/dind-run-operators.sh
* Add a warning about problems with flannel which I experienced on Ubuntu
* Use Kubernetes version 11
* Add restart instructions
* update dind-run-operators, most importantly to always pull
> update local dind documentation

- docs/google-kubernetes-tutorial.md
fix [issue42](https://github.com/pingcap/tidb-operator/issues/42)
> fix typo in docs/google-kubernetes-tutorial.md

- charts/tidb-cluster/templates/monitor-deployment.yaml
- charts/tidb-cluster/templates/privileged-tidb-deployment.yaml
- charts/tidb-cluster/templates/tidb-cluster.yaml
- charts/tidb-cluster/values.yaml
- pkg/apis/pingcap.com/v1alpha1/types.go
- pkg/apis/pingcap.com/v1alpha1/zz_generated.deepcopy.go
- pkg/manager/member/pd_member_manager.go
- pkg/manager/member/tidb_member_manager.go
- pkg/manager/member/tikv_member_manager.go
This PR allows users to add tolerations to TiDB pods.
Fix issue #44.
> add tolerations configuration to tidb pods

- pkg/controller/tidbcluster/tidb_cluster_control_test.go
- pkg/controller/tidbcluster/tidb_cluster_controller.go
- pkg/controller/tidbcluster/tidb_cluster_controller_test.go
- pkg/manager/member/pd_member_manager.go
- pkg/manager/member/pd_member_manager_test.go
- pkg/manager/member/pd_upgrader.go
- pkg/manager/member/pd_upgrader_test.go
- pkg/manager/member/tidb_member_manager.go
- pkg/manager/member/tikv_member_manager.go
- pkg/manager/member/upgrader.go
- pkg/manager/member/utils.go
this pr just abstracting the pd upgrader function into Upgrader interface, the changes is also to prepare for the feature of graceful upgrade feature. the tikv/tidb's  upgrade refactor will be committed by another pr
@weekface @tennix @onlymellb @gregwebs  PTAL
> pd upgrade refactor

- docs/google-kubernetes-tutorial.md
- Update description to make it clearer
- Fix typo and format
- Update one code
- Add the scaling out section
> docs: update GKE wording, code and add scaling out

- ROADMAP.md
This PR updates roadmap. As TiDB Lightning is not production ready, we'll integrate it when it's ready. And TiDB cluster configurations should be managed by an [external tool](https://github.com/tennix/tidb-release), so configuration management is removed from roadmap too.
During the following months, we should improve the stability of TiDB Operator while adding new features. The stability test is a long-term task, so not adding it to the roadmap.
> roadmap: update roadmap for completed features and future features

- charts/tidb-cluster/templates/monitor-deployment.yaml
- charts/tidb-cluster/templates/monitor-pvc.yaml
- charts/tidb-cluster/values.yaml
This PR allows the monitor to store its data persistently, so when update monitor Deployment or delete monitor pod, its data can be persistent.
> allow monitor data to be persistent

- pkg/manager/member/pd_member_manager.go
- pkg/manager/member/tidb_member_manager.go
- pkg/manager/member/tikv_member_manager.go
the PR fixes #117 issue
@tennix @weekface @onlymellb PTAL
> fix parallel upgrade bug

- manifests/gke-storage.yml
> remove binding mode for GKE pd-ssd storageclass

- pkg/manager/member/tidb_member_manager.go
fixes #146 
@tennix @onlymellb @xiaojingchen PTAL
> TiDB readiness probes

- charts/tidb-cluster/templates/fullbackup-cronjob.yaml
- charts/tidb-cluster/templates/monitor-deployment.yaml
- charts/tidb-cluster/templates/monitor-job.yaml
- charts/tidb-cluster/templates/privileged-tidb-deployment.yaml
- charts/tidb-cluster/templates/pump-statefulset.yaml
- charts/tidb-cluster/templates/tidb-cluster.yaml
- charts/tidb-cluster/values.yaml
- docs/aws-eks-tutorial.md
- images/tidb-operator-e2e/tidb-cluster-values.yaml
- manifests/gp2-storage.yaml
- pkg/apis/pingcap.com/v1alpha1/types.go
- pkg/manager/member/pd_member_manager.go
- pkg/manager/member/tidb_member_manager.go
- pkg/manager/member/tikv_member_manager.go
Add TiDB docker image pull policy support, fix:#103
> Add imagePullPolicy support

- manifests/local-dind/pv-hosts.sh
> filter out master by role without relying on name

- pkg/controller/pd_control.go
fix #154 
@tennix @weekface @xiaojingchen PTAL, thanks
> increase HTTP client timeout to 5 seconds when to sync pd status

- pkg/manager/member/tidb_member_manager.go
- pkg/manager/member/tidb_member_manager_test.go
> add more unit tests to tidb_member_manager

- charts/tidb-cluster/templates/config/_prometheus-config.tpl
> fix monitor configuration

- pkg/label/label.go
- pkg/label/label_test.go
- add unit tests to labels
- remove unuse codes
> add unit tests to labels

- charts/tidb-cluster/templates/tidb-service.yaml
> Allow specifying tidb service load balancer IP

- charts/tidb-backup/templates/scripts/_start_backup.sh.tpl
- charts/tidb-backup/templates/scripts/_start_restore.sh.tpl
- charts/tidb-cluster/templates/scripts/_start_scheduled_backup.sh.tpl
this PR fixes #250 
@weekface @tennix @onlymellb  @gregwebs  PTAL
> fix backup restore script

- charts/tidb-backup/templates/scripts/_start_backup.sh.tpl
- charts/tidb-backup/templates/scripts/_start_restore.sh.tpl
- charts/tidb-cluster/templates/scripts/_start_scheduled_backup.sh.tpl
- cmd/controller-manager/main.go
fix script bug
PTAL @weekface @tennix
> fix script bugs

- .gitignore
- Makefile
- README.md
- ci/pingcap_tidb_operator_build_dind.groovy
This PR adds code coverage like this [![codecov](https://codecov.io/gh/pingcap/tidb-operator/branch/master/graph/badge.svg)](https://codecov.io/gh/pingcap/tidb-operator)
*Note*: We need to set token in Jenkins CI before it is merged.
> add code coverage

- charts/tidb-cluster/values.yaml
- images/tidb-operator-e2e/tidb-cluster-values.yaml
This matches the golang source code representation of values.yml
> in values.yml, omit just the empty leaves

- charts/tidb-cluster/templates/monitor-deployment.yaml
Just add startup parameter for prometheus for dumping TSDB data
> Enable admin privilege API for Prometheus

- charts/tidb-cluster/templates/tidb-cluster.yaml
- charts/tidb-cluster/values.yaml
- images/tidb-operator-e2e/tidb-cluster-values.yaml
- add additional custom TidbCluster labels
> add extraLabels variable in tidb-cluster chart

- cmd/controller-manager/main.go
Deprecated: use NewSharedInformerFactoryWithOptions instead
refer: https://godoc.org/k8s.io/client-go/informers#NewFilteredSharedInformerFactory
> Deprecated: NewFilteredSharedInformerFactory

- pkg/apis/pingcap.com/v1alpha1/tidbcluster.go
add TiDBUpgrading instance method, like tc.PDUpgrading() || tc.TiKVUpgrading()
> add TiDBUpgrading func

- charts/tidb-operator/templates/controller-manager-deployment.yaml
- charts/tidb-operator/templates/scheduler-deployment.yaml
> fix operator chart issue

- docs/operation-guide.md
refer: https://github.com/pingcap/tidb-operator/blob/master/charts/tidb-cluster/templates/tidb-cluster.yaml#L8
Tests 
- No code
Code changes
> Docs: fix label selector

- charts/tidb-cluster/values.yaml
- tests/actions.go
- tests/backup.go
- tests/cmd/e2e/main.go
- tests/cmd/stability/main.go
- tests/pkg/webhook/pods.go
* update drainer config document
* increase tidb-controller-manager and tidb-scheduler replicas to 2
* update grafana query
* increase drainer workerCount
* move binlog above scheduled backup
Tests 
- E2E test
Code changes
Side effects
> Fix binlog problem on large scale

- docs/minikube-tutorial.md
Testing current documentation of Minikube installation and keep it up to date.
Tested all instructions in the Minikube installation documentation on a Dell XPS13 9360 laptop with latest ArchLinux and VirtualBox, updated them to fit testing results and added some detailed notes.
Tests 
- No code
Code changes
Side effects
- N/A
- N/A
> docs/minikube: update documentation of minikube installation

- docs/minikube-tutorial.md
Add instructions to access Grafana to the Minikube installation documentation.
Tested on a Dell XPS13 9360 laptop with latest ArchLinux.
Tests 
- No code
Code changes
Side effects
- N/A
- N/A
> docs/minikube: add instructions to access Grafana

- README.md
> readme: fix a broken link

- .github/pull_request_template.md
- add the release-note section to pull request template as [kubernetes](https://github.com/kubernetes/kubernetes/blob/master/.github/PULL_REQUEST_TEMPLATE.md) does
Tests 
- No code
Code changes
Side effects
```release-note
NONE
```
> add release-note to pull_request_template.md

- charts/tidb-backup/values.yaml
- charts/tidb-cluster/values.yaml
- images/tidb-operator-e2e/tidb-cluster-values.yaml
- tests/config.go
- tests/manifests/e2e/e2e.yaml
Default TiDB version to v3.0.0-rc.1
Bump TiDB versions.
Tests 
- Manual test
Code changes
Side effects
- None
```release-note
Upgrade default TiDB version to v3.0.0-rc.1
```
> upgrade default tidb to v3.0.0-rc.1

- deploy/aliyun/templates/local-volume-provisioner.yaml.tpl
- deploy/aws/manifests/local-volume-provisioner.yaml
- deploy/gcp/manifests/local-volume-provisioner.yaml
- manifests/local-dind/local-volume-provisioner.yaml
- fixes #572 
Tests 
- No code
Code changes
Side effects
```release-note
NONE
```
> fix resource unit

- .github/pull_request_template.md
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
```
> fix pull request template grammar

- deploy/aws/README.md
https://github.com/pingcap/tidb-operator/issues/635
`deploy/aws/README.md`
Tests 
- No code
Code changes
Side effects
- N/A
- N/A
```release-note
NONE
```
> Add new terraform version requirement to AWS deployment

- charts/tidb-cluster/values.yaml
Tests 
- Unit test
- E2E test
- No code
Code changes
```release-note
```
> Add tikv raftstore parameters

- cmd/controller-manager/main.go
Now watch backup CRD object will cause an error
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
None
```
> turn off backup related controllers

- CHANGELOG.md
- README.md
- ROADMAP.md
- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- deploy/modules/aws/tidb-operator/variables.tf
- tests/manifests/stability/stability.yaml
Tests 
- No code
Code changes
Side effects
```release-note
NONE
```
> release v1.0.0

- hack/gcp-rm-unused-disks.sh
I think a release note was missing from a prior PR
```release-note
GKE: add a script to delete unused disk
```
> add a DRY_RUN setting to gcp-rm-unused-disks.sh

- charts/tidb-backup/templates/scripts/_start_backup.sh.tpl
- charts/tidb-backup/values.yaml
- charts/tidb-cluster/templates/scripts/_start_scheduled_backup.sh.tpl
- charts/tidb-cluster/values.yaml
(cherry picked from commit e22e4806e89480b810a54727ea6b17859156ff16)
> cherry-pick: add tikvGCLifeTime option (#835) to release-1.0

- cmd/controller-manager/main.go
- pkg/controller/pod_control.go
- pkg/controller/tidbcluster/tidb_cluster_controller.go
- pkg/manager/member/orphan_pods_cleaner.go
- pkg/manager/member/orphan_pods_cleaner_test.go
cherry pick https://github.com/pingcap/tidb-operator/pull/878 into release-1.0
```release-note
```
> cherry-pick-1.0: clean orphan pods bugfix

- cmd/controller-manager/main.go
- pkg/controller/backup/backup_controller.go
- pkg/controller/backupschedule/backup_schedule_controller.go
- pkg/controller/pod_control.go
- pkg/controller/restore/restore_controller.go
- pkg/controller/tidbcluster/tidb_cluster_controller.go
- pkg/manager/member/orphan_pods_cleaner.go
- pkg/manager/member/orphan_pods_cleaner_test.go
cherry-pick #878 into release-1.1
> cherry-pick-1.1: fix some orphan pods cleaner bugs (#878)

- docs/CONTRIBUTING.md
- hack/kind-cluster-build.sh
- tests/manifests/e2e/e2e.yaml
fix some issues in kind e2e environment
```release-note
NONE
```
> hack/kind: fix some issues in kind e2e environment

- deploy/aws/aws-tutorial.tfvars
- deploy/aws/versions.tf
- deploy/modules/aws/tidb-operator/main.tf
Cherry pick of #926 on release-1.1.
#926: add provider and module versions for aws
> Automated cherry pick of #926: add provider and module versions for aws

- charts/tidb-cluster/values.yaml
- tests/actions.go
Cherry pick of #939 on release-1.0.
#939: fix drainer misconfiguration
> Automated cherry pick of #939: fix drainer misconfiguration

- deploy/modules/aws/tidb-cluster/local.tf
- deploy/modules/aws/tidb-cluster/templates/userdata.sh.tpl
- deploy/modules/aws/tidb-cluster/variables.tf
Cherry pick of #871 on release-1.1.
#871: AWS terraform: add zone label and reserved resources for
> Automated cherry pick of #871: AWS terraform: add zone label and reserved resources for

- cmd/backup-manager/app/backup/backup.go
- cmd/backup-manager/app/backup/manager.go
- cmd/backup-manager/app/restore/manager.go
- cmd/backup-manager/app/restore/restore.go
- manifests/backup/backup.yaml
- manifests/backup/restore.yaml
- pkg/apis/pingcap.com/v1alpha1/types.go
- pkg/backup/backup/backup_manager.go
- pkg/backup/restore/restore_manager.go
- pkg/backup/util/util.go
Output error log，improve logs and fix some problems
Tests 
- Manual test
Code changes
Side effects
```release-note
None
```
> Fix backup restore

- cmd/backup-manager/app/backup/backup.go
- cmd/backup-manager/app/backup/manager.go
- cmd/backup-manager/app/restore/manager.go
- cmd/backup-manager/app/restore/restore.go
- manifests/backup/backup.yaml
- manifests/backup/restore.yaml
- pkg/apis/pingcap.com/v1alpha1/types.go
- pkg/backup/backup/backup_manager.go
- pkg/backup/restore/restore_manager.go
- pkg/backup/util/util.go
Cherry pick of #964 on release-1.1.
#964: fix backup restore
> Automated cherry pick of #964: fix backup restore

- pkg/manager/member/pd_upgrader.go
- pkg/manager/member/pd_upgrader_test.go
- pkg/manager/member/tidb_upgrader.go
- pkg/manager/member/tidb_upgrader_test.go
- pkg/manager/member/tikv_upgrader.go
- pkg/manager/member/tikv_upgrader_test.go
Cherry pick of #830 on release-1.1.
#830: fix setting StatefulSet partition bug
> Automated cherry pick of #830: fix

- charts/tidb-cluster/templates/tidb-cluster.yaml
- charts/tidb-cluster/values.yaml
- images/tidb-operator-e2e/tidb-cluster-values.yaml
- pkg/apis/pingcap.com/v1alpha1/types.go
- pkg/controller/controller_utils.go
- pkg/manager/member/tidb_failover.go
- pkg/manager/member/tikv_failover.go
- pkg/manager/member/tikv_failover_test.go
Cherry pick of #965 on release-1.0.
#965: add maxFailoverCount limit to TiKV
> Automated cherry pick of #965: add maxFailoverCount limit to TiKV

- deploy/aliyun/main.tf
- deploy/aliyun/variables.tf
Cherry pick of #971 on release-1.1.
#971: fix values file customization for tidb-operator on aliyun
> Automated cherry pick of #971: fix values file customization for tidb-operator on aliyun

- README.md
Migrate master job to `build_tidb_operator_master_kind`.
Tests 
- E2E test
```release-note
```
> update master job link

- tests/actions.go
- tests/cmd/stability/main.go
> Manually cherry-pick #1030 to release-1.0

- pkg/manager/member/tidb_member_manager.go
- pkg/manager/member/tikv_member_manager.go
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
```
> fixbug: invalid variable used

- pkg/controller/backupschedule/backup_schedule_controller_test.go
fix invalid import
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
```
> fix invalid import

- deploy/modules/aliyun/tidb-operator/operator.tf
- deploy/modules/gcp/tidb-cluster/main.tf
- deploy/modules/share/tidb-cluster-release/data.tf
- deploy/modules/share/tidb-cluster-release/main.tf
Cherry pick of #1045 on release-1.1.
#1045: tidb lb is empty after terraform apply
> Automated cherry pick of #1045: tidb lb is empty after terraform apply

- tests/actions.go
- tests/cmd/stability/main.go
cherry-pick #1036 to release-1.0
@weekface PTAL
> Cherry-pick #1036 to release-1.0

- pkg/tkctl/readable/print_flags_test.go
- pkg/tkctl/readable/printers.go
more unit tests to verify code
xref: https://github.com/pingcap/tidb-operator/issues/1064
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
```
> add unit tests for internal printer handlers

- manifests/webhook.yaml
- pkg/webhook/statefulset/statefulset.go
- tests/actions.go
Cherry pick of #1054 on release-1.0.
#1054: fix stability test, add `v1` to statefulset apiVersions
> Automated cherry pick of #1054: fix stability test, add `v1` to statefulset apiVersions

- CHANGELOG.md
- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- deploy/modules/aliyun/tidb-cluster/variable.tf
- deploy/modules/aliyun/tidb-operator/variables.tf
- deploy/modules/aws/tidb-cluster/variables.tf
- deploy/modules/aws/tidb-operator/variables.tf
- deploy/modules/gcp/tidb-cluster/variables.tf
- deploy/modules/gcp/tidb-operator/variables.tf
- deploy/modules/share/tidb-cluster-release/variables.tf
- tests/manifests/stability/stability.yaml
Cherry pick of #1080 on release-1.0.
#1080: release v1.0.2
> Automated cherry pick of #1080: release v1.0.2

- go.mod
- go.sum
- hack/codegen.sh
- tools/tools.go
xref: https://github.com/pingcap/tidb-operator/issues/1095
Tests 
- Unit test
```release-note
```
> workaround for go mod issue (go #31248)

- tests/actions.go
fixed #1105 
Tests 
- E2E test
Code changes
```release-note
None
```
> fix get backup dir failed

- README.md
fix the 404 error. When clicking the Simplified Chinese button
fix the 404 error. When clicking the Simplified Chinese button
only update doc.
Tests 
- Unit test
- E2E test
- No code
only update doc.
Code changes
only update doc.
Side effects
```release-note
```
> fix the 404 error. When clicking the Simplified Chinese button

- CHANGELOG.md
- charts/tidb-cluster/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/clusters.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- deploy/modules/aws/tidb-cluster/variables.tf
- deploy/modules/gcp/tidb-cluster/variables.tf
- deploy/modules/share/tidb-cluster-release/variables.tf
- images/tidb-operator-e2e/tidb-cluster-values.yaml
- tests/config.go
- tests/manifests/e2e/e2e.yaml
https://github.com/pingcap/tidb-operator/issues/1089
Upgrade TiDB component's images.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
```
> upgrade default TiDB version to v3.0.5

- CHANGELOG.md
- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- deploy/modules/aliyun/tidb-cluster/variables.tf
- deploy/modules/aliyun/tidb-operator/variables.tf
- deploy/modules/aws/tidb-cluster/variables.tf
- deploy/modules/aws/tidb-operator/variables.tf
- deploy/modules/gcp/tidb-cluster/variables.tf
- deploy/modules/gcp/tidb-operator/variables.tf
- deploy/modules/share/tidb-cluster-release/variables.tf
- tests/manifests/stability/stability.yaml
Tests 
Code changes
Side effects
```release-note
NONE
```
> release v1.0.3

- CHANGELOG.md
- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- deploy/modules/aliyun/tidb-cluster/variable.tf
- deploy/modules/aliyun/tidb-operator/variables.tf
- deploy/modules/aws/tidb-cluster/variables.tf
- deploy/modules/aws/tidb-operator/variables.tf
- deploy/modules/gcp/tidb-cluster/variables.tf
- deploy/modules/gcp/tidb-operator/variables.tf
- deploy/modules/share/tidb-cluster-release/variables.tf
- tests/manifests/stability/stability.yaml
Cherry pick of #1130 on release-1.0.
#1130: release v1.0.3
> Automated cherry pick of #1130: release v1.0.3

- tests/actions.go
- tests/cmd/e2e/main.go
fix #1137 
Tests 
- E2E test
Code changes
Side effects
```release-note
```
> fix webhook does not take effect

- .gitignore
- hack/check-terraform.sh
- hack/lib.sh
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
```
> install terraform locally

- .gitignore
- hack/crd-groups.sh
- manifests/crd.yaml
- pkg/util/crdutil.go
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
```
> fix pd READY column and use tmp file in verify script

- charts/tidb-cluster/templates/_helpers.tpl
- charts/tidb-cluster/templates/tikv-importer-configmap.yaml
- charts/tidb-cluster/templates/tikv-importer-service.yaml
- charts/tidb-cluster/templates/tikv-importer-statefulset.yaml
- charts/tidb-cluster/values.yaml
- charts/tidb-lightning/.helmignore
- charts/tidb-lightning/Chart.yaml
- charts/tidb-lightning/secret.yaml
- charts/tidb-lightning/templates/NOTES.txt
- charts/tidb-lightning/templates/_helpers.tpl
- charts/tidb-lightning/templates/configmap.yaml
- charts/tidb-lightning/templates/job.yaml
- charts/tidb-lightning/templates/persistentvolumeclaim.yaml
- charts/tidb-lightning/templates/scripts/_start_data_retriever.sh.tpl
- charts/tidb-lightning/templates/scripts/_start_lightning.sh.tpl
- charts/tidb-lightning/templates/service.yaml
- charts/tidb-lightning/values.yaml
Cherry pick of #817 on release-1.0.
#817: Add tidb-lightning support
> Automated cherry pick of #817: Add tidb-lightning support

- charts/tidb-drainer/values.yaml
Cherry pick of #793 on release-1.0.
#793: Fix default tidb-drainer config to be compatible with the
> Automated cherry pick of #793: Fix default tidb-drainer config to be compatible with the

- ci/pingcap_tidb_operator_build_kind.groovy
- tests/manifests/e2e/e2e.yaml
Cherry pick of #1135 on release-1.0.
#1135: put e2e jenkinsfile from jenkins into repo
> Automated cherry pick of #1135: put e2e jenkinsfile from jenkins into repo

- charts/tidb-lightning/templates/job.yaml
- charts/tidb-lightning/templates/persistentvolumeclaim.yaml
- charts/tidb-lightning/templates/scripts/_start_lightning.sh.tpl
- charts/tidb-lightning/values.yaml
Cherry pick of #827 on release-1.0.
#827: add adhoc data source for lightning
> Automated cherry pick of #827: add adhoc data source for lightning

- tests/actions.go
Cherry pick of #1106 on release-1.0.
#1106: fix get backup dir failed
> Automated cherry pick of #1106: fix get backup dir failed

- tests/actions.go
- tests/cmd/e2e/main.go
fixes: #807 
Tests 
- E2E test
Code changes
Side effects
```release-note
NONE
```
> e2e: add init sql case

- Makefile
- ci/pingcap_tidb_operator_build_kind.groovy
- deploy/modules/gcp/tidb-operator/versions.tf
- hack/e2e.sh
- hack/lib.sh
- hack/run-e2e.sh
- pkg/apis/pingcap.com/v1alpha1/types.go
- tests/actions.go
- tests/manifests/e2e/e2e.yaml
cherry-pick #1102 into release-1.0
> Cherry pick pr 1102: add e2e scripts and simplify e2e jenkins file

- ci/pingcap_tidb_operator_build_kind.groovy
* upload unit tests coverage report to codecov
* fix master job build failed. The solution comes from @cofyc 
Tests 
- Unit test
Code changes
```release-note
None
```
> upload unit tests coverage report to codecov

- ci/pingcap_tidb_operator_build_kind.groovy
Make tag build job also use CI script
Tests 
- Unit test
- E2E test
Code changes
```release-note
```
> support build specific tag

- ci/pingcap_tidb_operator_build_kind.groovy
Cherry pick of #1219 on release-1.0.
#1219: support build specific tag
> Automated cherry pick of #1219: support build specific tag

- CHANGELOG.md
> v1.0.4 release

- ci/pingcap_tidb_operator_build_kind.groovy
- tests/actions.go
Cherry pick of #1221 on release-1.0.
#1221: fix e2e nil point dereference
> Automated cherry pick of #1221: fix e2e nil point dereference

- charts/tidb-cluster/values.yaml
https://github.com/pingcap/tidb-operator/issues/1234
Add recommended affinity setting for tidb and pump in note for enabling binlog.
> Add recommended affinity setting for tidb and pump in note 

- CHANGELOG.md
- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- deploy/modules/aliyun/tidb-cluster/variables.tf
- deploy/modules/aliyun/tidb-operator/variables.tf
- deploy/modules/aws/tidb-cluster/variables.tf
- deploy/modules/aws/tidb-operator/variables.tf
- deploy/modules/gcp/tidb-cluster/variables.tf
- deploy/modules/gcp/tidb-operator/variables.tf
- deploy/modules/share/tidb-cluster-release/variables.tf
- tests/manifests/stability/stability.yaml
Tests 
- No code
Code changes
Side effects
```release-note
NONE
```
> release v1.0.5

- CHANGELOG.md
- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- deploy/modules/aliyun/tidb-cluster/variable.tf
- deploy/modules/aliyun/tidb-operator/variables.tf
- deploy/modules/aws/tidb-cluster/variables.tf
- deploy/modules/aws/tidb-operator/variables.tf
- deploy/modules/gcp/tidb-cluster/variables.tf
- deploy/modules/gcp/tidb-operator/variables.tf
- deploy/modules/share/tidb-cluster-release/variables.tf
- tests/manifests/stability/stability.yaml
Cherry pick of #1295 on release-1.0.
#1295: release v1.0.5
> Automated cherry pick of #1295: release v1.0.5

- ci/release_tidb_operator_binary_and_image.groovy
The release-1.0 branch has no backup component, so remove it from release  CI script
Tests 
Code changes
```release-note
None
```
> adjust release CI script for release-1.0 branch

- .gitignore
- ci/pingcap_tidb_operator_build_kind.groovy
- hack/run-e2e.sh
fixes #1256 
Tests 
- Unit test
- E2E test
> export e2e results in JUnit format and save in Jenkins artifacts

- Makefile
- hack/e2e.sh
- hack/run-e2e.sh
- tests/apiserver/example.go
- tests/config.go
- tests/e2e/config/config.go
- tests/e2e/tidbcluster/tidbcluster.go
- tests/images/e2e/Dockerfile
pack all e2e resources in one image
Tests 
- Unit test
- E2E test
> merge test apiserver with e2e image

- ci/pingcap_tidb_operator_build_kind.groovy
- tests/actions.go
- tests/cmd/stability/main.go
- tests/config.go
- tests/e2e/config/config.go
- tests/e2e/e2e.go
- tests/e2e/tidbcluster/serial.go
- tests/e2e/tidbcluster/tidbcluster.go
fixes #1232 
- add serial tests job without default operator
- a simple deploy test spec with AdvancedStatefulset enabled
Tests 
- Unit test
- E2E test
> add serial tests job and a test spec with AdvancedStatefulset enabled

- go.mod
- tests/actions.go
- tests/cluster_info.go
- tests/cmd/stability/main.go
Cherry pick of #955 on release-1.0.
#955: ensure pods unchanged when upgrading
> Automated cherry pick of #955: ensure pods unchanged when upgrading

- ci/pingcap_tidb_operator_build_kind.groovy
- hack/e2e.sh
configure mirrors for more registries (gcr.io/quay.io) 
Tests 
- Unit test
- E2E test
> add GCR_IO_MIRROR/QUAY_IO_MIRROR

- charts/tidb-operator/templates/scheduler-rbac.yaml
this pr cherry pick #1410 from master to release-1.0, only `RBAC` rules codes.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
make tidb-operator compatible with k8s v1.17
```
> cherry-pick(#1410): fix k8s v1.17 compatibility

- charts/tidb-operator/templates/scheduler-rbac.yaml
Tests 
Code changes
Side effects
```release-note
NONE
```
> add rbac for k8s v1.17

- CHANGELOG.md
- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- deploy/modules/aliyun/tidb-cluster/variables.tf
- deploy/modules/aliyun/tidb-operator/variables.tf
- deploy/modules/aws/tidb-cluster/variables.tf
- deploy/modules/aws/tidb-operator/variables.tf
- deploy/modules/gcp/tidb-cluster/variables.tf
- deploy/modules/gcp/tidb-operator/variables.tf
- deploy/modules/share/tidb-cluster-release/variables.tf
- tests/manifests/stability/stability.yaml
Tests 
- No code
Code changes
Side effects
```release-note
NONE
```
> Release v1.0.6

- hack/codegen.sh
fix https://github.com/pingcap/tidb-operator/issues/1432
> remove GO111MODULEON=off in codegen.sh

- CHANGELOG.md
- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- deploy/modules/aliyun/tidb-cluster/variable.tf
- deploy/modules/aliyun/tidb-operator/variables.tf
- deploy/modules/aws/tidb-cluster/variables.tf
- deploy/modules/aws/tidb-operator/variables.tf
- deploy/modules/gcp/tidb-cluster/variables.tf
- deploy/modules/gcp/tidb-operator/variables.tf
- deploy/modules/share/tidb-cluster-release/variables.tf
- tests/manifests/stability/stability.yaml
Cherry pick of #1431 on release-1.0.
#1431: release v1.0.6
> Automated cherry pick of #1431: release v1.0.6

- Makefile
- checkout-pr-branch.sh
- hack/check-EOF.sh
- hack/check-terraform.sh
- hack/crd-groups.sh
- hack/e2e.sh
- hack/gcp-rm-unused-disks.sh
- hack/kind-cluster-build.sh
- hack/lib.sh
- hack/pin-deps.sh
- hack/retool-install.sh
- hack/run-e2e.sh
- hack/verify-boilerplate.sh
- hack/verify-codegen.sh
- hack/version.sh
- images/backup-manager/entrypoint.sh
- manifests/local-dind/deploy-registry.sh
- misc/images/debug-launcher/entry-point.sh
- misc/images/tidb-debug/run_flamegraph.sh
- pkg/apis/pingcap/v1alpha1/tidbcluster_component.go
- add license header for shell scripts
- verify license header in the check phase
Tests 
- Unit test
- E2E test
> add license header for shell scripts

- README.md
add more badges
preview: https://github.com/pingcap/tidb-operator/blob/56c056b9d13c6919f9e3cc0d67a662e4b1288258/README.md
Tests 
- Unit test
- E2E test
> More badges in README.md

- charts/tidb-backup/templates/restore-job.yaml
fix #1472 
fix pvc name
Tests 
- Unit test
- E2E test
- No code
Code changes
- Has helm chart change
Side effects
```release-note
NONE
```
> fix pvc name of restore job

- README.md
fix invite link, the old one is no longer active.
Tests 
- Unit test
- E2E test
> Update slack community invite link

- hack/e2e.sh
- hack/lib.sh
fixes #1517 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> add some retries for "kind create cluster"

- ci/pingcap_tidb_operator_build_kind.groovy
fixes #1526 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> configure QUAY_IO_MIRROR

- ci/pingcap_tidb_operator_build_kind.groovy
- hack/e2e.sh
- hack/lib.sh
Cherry pick of #1550 on release-1.1.
#1550: upgrade to use kind 0.7.0
> Automated cherry pick of #1550: upgrade to use kind 0.7.0

- tests/e2e/tidbcluster/serial.go
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/operator_ghpr_e2e_test_kind/detail/operator_ghpr_e2e_test_kind/2188/tests
```
/home/jenkins/agent/workspace/operator_ghpr_e2e_test_kind/go/src/github.com/pingcap/tidb-operator/tests/e2e/tidbcluster/serial.go:133
Jan 9 06:33:17.701: Unexpected error:
<*errors.StatusError | 0xc0005b2320>: {
ErrStatus: {
TypeMeta: {Kind: "", APIVersion: ""},
ListMeta: {
SelfLink: "",
ResourceVersion: "",
Continue: "",
RemainingItemCount: nil,
},
Status: "Failure",
Message: "Operation cannot be fulfilled on tidbclusters.pingcap.com \"deploy\": the object has been modified; please apply your changes to the latest version and try again",
Reason: "Conflict",
Details: {Name: "deploy", Group: "pingcap.com", Kind: "tidbclusters", UID: "", Causes: …
```
> e2e: use controller.GuaranteedUpdate to retry on version conflict

- charts/tidb-cluster/values.yaml
Cherry pick of #1501 on release-1.0.
#1501: fix some broken urls
> Automated cherry pick of #1501: fix some broken urls

- ci/pingcap_tidb_operator_build_kind.groovy
- hack/prepare-e2e.sh
- tests/backup.go
- tests/e2e/tidbcluster/tidbcluster.go
fixes https://github.com/pingcap/tidb-operator/issues/1603
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> limit nodes and reduce CI jobs

- ci/pingcap_tidb_operator_build_kind.groovy
fixes #1603 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> clean containers on TERM signal to avoid cgroup leaking

- tests/e2e/tidbcluster/tidbcluster.go
```
/home/jenkins/agent/workspace/operator_ghpr_e2e_test_kind/go/src/github.com/pingcap/tidb-operator/tests/e2e/tidbcluster/tidbcluster.go:402
Feb 4 14:51:33.121: Expected update tc
Unexpected error:
<*errors.StatusError | 0xc0002705a0>: {
ErrStatus: {
TypeMeta: {Kind: "", APIVersion: ""},
ListMeta: {
SelfLink: "",
ResourceVersion: "",
Continue: "",
RemainingItemCount: nil,
},
Status: "Failure",
Message: "Operation cannot be fulfilled on tidbclusters.pingcap.com \"pump-it\": the object has been modified; please apply your changes to the latest version and try again",
Reason: "Conflict",
Details: {Name: "pump-it", Group: "pingcap.com", Kind: "tidbclusters", UID: "", Causes: nil, RetryAfterSeconds: 0},
Code: 409,
},
}
Operation cannot be …
```
> use controller.GuaranteedUpdate to update TiDB Cluster CRD in e2e

- go.mod
- go.sum
- pkg/controller/pv_control.go
- pkg/controller/tidbmonitor/tidb_monitor_controller.go
- pkg/monitor/monitor/monitor_manager.go
- pkg/monitor/monitor/template.go
- pkg/monitor/monitor/template_test.go
- pkg/monitor/monitor/util.go
- tests/e2e/tidbcluster/tidbcluster.go
- tests/pkg/fixture/fixture.go
cherry-pick
https://github.com/pingcap/tidb-operator/pull/1625
https://github.com/pingcap/tidb-operator/pull/1474
https://github.com/pingcap/tidb-operator/pull/1599
> Manually check-pick Monitor commit

- cmd/backup-manager/app/backup/backup.go
- cmd/backup-manager/app/cmd/cmd.go
- cmd/backup-manager/app/cmd/import.go
- cmd/backup-manager/app/import/manager.go
- cmd/backup-manager/app/import/restore.go
- cmd/backup-manager/app/restore/manager.go
- cmd/backup-manager/app/restore/restore.go
- cmd/backup-manager/app/util/remote.go
- cmd/backup-manager/app/util/util.go
- images/backup-manager/entrypoint.sh
- manifests/backup/restore-s3-br.yaml
- manifests/crd.yaml
- pkg/apis/pingcap/v1alpha1/openapi_generated.go
- pkg/apis/pingcap/v1alpha1/restore.go
- pkg/apis/pingcap/v1alpha1/types.go
- pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
- pkg/backup/restore/restore_manager.go
- pkg/backup/util/util.go
- pkg/controller/restore/restore_controller.go
close #1673. Support restore from S3 by BR. 
Tests 
Code changes
> Cherry-pick #1342 to release-1.1

- charts/tidb-operator/values.yaml
- cmd/controller-manager/main.go
- pkg/apis/pingcap/v1alpha1/register.go
- pkg/controller/autoscaler/tidbcluster_autoscaler_control.go
- pkg/controller/autoscaler/tidbcluster_autoscaler_controller.go
- pkg/features/features.go
> Add Controller for TidbClusterAutoScale (#1672)

- charts/tidb-lightning/templates/job.yaml
- charts/tidb-lightning/templates/rclone-conf.yaml
- charts/tidb-lightning/templates/scripts/_start_lightning.sh.tpl
- charts/tidb-lightning/values.yaml
Cherry pick of #1678 on release-1.1.
#1678: migrate the private changes for lightning chart in dbaas to
> Automated cherry pick of #1678: migrate the private changes for lightning chart in dbaas to

- cmd/controller-manager/main.go
- pkg/autoscaler/autoscaler.go
- pkg/autoscaler/autoscaler/autoscaler_manager.go
- pkg/autoscaler/autoscaler/tidb_autoscaler.go
- pkg/autoscaler/autoscaler/tikv_autoscaler.go
- pkg/autoscaler/autoscaler/util.go
- pkg/controller/autoscaler/tidbcluster_autoscaler_control.go
- pkg/controller/autoscaler/tidbcluster_autoscaler_controller.go
- pkg/label/label.go
- pkg/util/util.go
- pkg/webhook/pod/pd_deleter.go
- pkg/webhook/pod/tikv_deleter.go
- pkg/webhook/pod/util.go
#1651 
This request build the auto-scaler controller logic without the recommended tikv/tidb replicas algorithm / update TidbCluster replicas / update TidbClusterAutoScaler Status.
```release-note
NONE
```
> Sync Auto-Scaler Controller

- charts/tidb-cluster/templates/scripts/_initialize_tidb_users.py.tpl
close connection after set privilege
Tests 
- E2E test
Code changes
> deploy: close connection after set privilege

- charts/tidb-cluster/templates/_helpers.tpl
fixes #1687 
Tests 
- No code
Code changes
Side effects
```release-note
NONE
```
> fix tls client cert bug

- charts/tidb-lightning/templates/rclone-conf.yaml
fixes for https://github.com/pingcap/tidb-operator/commit/9a3b1e27603dd28deac8dae43e34d21e1a678629
> fix tidb-lightning errors

- ci/deploy_tidb_operator_staging.groovy
> Enable Auto-scaling in IDC

- .github/workflows/stale.yaml
add [stale](https://github.com/actions/stale) github action to close stale issues/prs
xref: https://github.com/pingcap/tidb-operator/issues/1024
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> add stale github action to close stale issues/prs

- pkg/monitor/monitor/template.go
- pkg/monitor/monitor/template_test.go
Fix the template error which would cause tikv scraping missing
```release-note
NONE
```
> Fix TidbMonitor template error

- manifests/local-dind/local-volume-provisioner.yaml
upgrade local volume provisioner to 2.3.4
https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/releases/tag/v2.3.4
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> upgrade local volume provisioner to 2.3.4

- deploy/gcp/examples/multi-zonal.tfvars
- deploy/gcp/examples/single-zonal.tfvars
I was using the chart as a submodule, and terraform keeps reformatting the code. Might as well check it in.
> terraform fmt

- pkg/manager/member/template.go
This fixes: #1806 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
Fix a bug that TiKV failed to start while creating cluster using CR with cluster tls enabled
```
> Fix a bug that TiKV failed to start while creating cluster using CR with cluster tls enabled

- charts/tidb-cluster/templates/_helpers.tpl
- charts/tidb-cluster/templates/config/_prometheus-config.tpl
- charts/tidb-cluster/templates/config/_pump-config.tpl
- charts/tidb-cluster/values.yaml
- charts/tidb-drainer/templates/_helpers.tpl
- hack/create-cert.sh
- pkg/controller/secret_control.go
- pkg/manager/member/pd_member_manager.go
- pkg/manager/member/pump_member_manager.go
- pkg/manager/member/tidb_member_manager.go
- pkg/manager/member/tidb_member_manager_test.go
- pkg/manager/member/tikv_member_manager.go
- pkg/monitor/monitor/template.go
- pkg/pdapi/pdapi.go
fix #1819
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> use k8s standard tls secret format

- pkg/apis/pingcap/v1alpha1/defaulting/tidbcluster.go
fix tidb defaulting
```release-note
Fix the bug which would cause tidb image property broken
```
> Fix tidb defaulting

- charts/tidb-cluster/templates/scripts/_start_tikv.sh.tpl
- charts/tidb-cluster/values.yaml
- charts/tidb-operator/templates/admission/admission-webhook-rbac.yaml
- charts/tidb-operator/templates/admission/admission-webhook-registration.yaml
- charts/tidb-operator/values.yaml
- pkg/autoscaler/autoscaler/tidb_autoscaler.go
- pkg/autoscaler/autoscaler/tikv_autoscaler.go
- pkg/label/label.go
- pkg/manager/member/pd_scaler.go
- pkg/manager/member/scaler.go
- pkg/manager/member/template.go
- pkg/manager/member/tikv_member_manager.go
- pkg/manager/member/tikv_scaler.go
- pkg/manager/member/utils.go
- pkg/util/util.go
- pkg/webhook/admission_hooks.go
- pkg/webhook/pod/pod_mutater.go
- pkg/webhook/pod/pods.go
- pkg/webhook/pod/util.go
git cherry-pick 25f488ef  
git cherry-pick 1308c28d
> Manually cp 1833 and 1801

- ci/aws-clean-eks.sh
- ci/e2e_eks.groovy
- ci/pingcap_tidb_operator_build_kind.groovy
- hack/e2e.sh
- hack/lib.sh
- hack/run-e2e.sh
- hack/run-in-container.sh
- tests/e2e/e2e.go
fixes #1879 
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-e2e-eks-ci-master/detail/tidb-operator-e2e-eks-ci-master/10/pipeline
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> Add periodical e2e job for EKS

- charts/tidb-cluster/templates/config/_prometheus-config.tpl
- pkg/monitor/monitor/template.go
- pkg/monitor/monitor/template_test.go
Cherry pick of #1919 on release-1.1.
#1919: fix prometheus scrape config while tls is enabled
> Automated cherry pick of #1919: fix prometheus scrape config while tls is enabled

- .gitignore
- docs/api-references/config.json
- docs/api-references/docs.html
- docs/api-references/template/members.tpl
- docs/api-references/template/pkg.tpl
- docs/api-references/template/type.tpl
- hack/lib.sh
- hack/update-crd-groups.sh
- hack/verify-crd-groups.sh
cp 1929
```release-note
Add API document and its generating util
```
> Manually cp api util

- charts/tidb-cluster/values.yaml
Cherry pick of #1850 on release-1.1.
#1850: re comment pd service yaml value
> Automated cherry pick of #1850: re comment pd service yaml value

- cmd/backup-manager/app/backup/backup.go
- cmd/backup-manager/app/constants/constants.go
- cmd/backup-manager/app/restore/restore.go
- cmd/backup-manager/app/util/util.go
- docs/api-references/docs.html
- manifests/crd.yaml
- pkg/apis/pingcap/v1alpha1/openapi_generated.go
- pkg/apis/pingcap/v1alpha1/types.go
- pkg/backup/backup/backup_manager.go
- pkg/backup/backupschedule/backup_schedule_manager.go
- pkg/backup/constants/constants.go
- pkg/backup/restore/restore_manager.go
- pkg/backup/util/util.go
Cherry pick of #1836 on release-1.1.
#1836: backup: add TLS to backup br
> Automated cherry pick of #1836: backup: add TLS to backup br

- charts/tidb-cluster/templates/discovery-deployment.yaml
- charts/tidb-cluster/values.yaml
Solve the issue https://github.com/pingcap/tidb-operator/issues/1701
Setting values in the tidb-cluster Helm chart
> Adding tolerations and affinity to the discovery chart template

- pkg/backup/backup/backup_cleaner.go
- pkg/backup/backup/backup_manager.go
- pkg/backup/restore/restore_manager.go
- pkg/backup/util/util.go
fix problem when kms is used and without set default aws region
set region in operator when kms is used
Tests 
Code changes
> backup： fix kms bug

- pkg/controller/pod_control.go
- pkg/manager/member/orphan_pods_cleaner.go
- pkg/manager/member/orphan_pods_cleaner_test.go
- check pod has been scheduled or not
- use ResourceVersion precondition
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> improve orphan pods clean logic

- ci/pingcap_tidb_operator_build_kind.groovy
- ci/upload-binaries-charts.sh
fixes #1438 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> remove dependencies on k8s-node

- examples/advanced-statefulset/tidb-cluster-scaled.yaml
- examples/advanced-statefulset/tidb-cluster.yaml
https://github.com/pingcap/tidb-operator/issues/1449
examples used in https://github.com/pingcap/docs-tidb-operator/pull/52
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> examples for advanced statefulset

- tests/e2e/tidbcluster/serial.go
- tests/e2e/tidbcluster/stability.go
fixes #1993
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> install tidb-operator in test namespace in non-parallel test specs

- docs/api-references/docs.html
- manifests/crd.yaml
- pkg/apis/pingcap/v1alpha1/openapi_generated.go
- pkg/apis/pingcap/v1alpha1/tidbcluster_component.go
- pkg/apis/pingcap/v1alpha1/types.go
- pkg/apis/pingcap/v1alpha1/validation/validation.go
- pkg/apis/pingcap/v1alpha1/validation/validation_test.go
- pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
- pkg/manager/member/pd_member_manager.go
- pkg/manager/member/pd_member_manager_test.go
- pkg/manager/member/pump_member_manager.go
- pkg/manager/member/tidb_member_manager.go
- pkg/manager/member/tikv_member_manager.go
- pkg/monitor/monitor/util.go
- pkg/util/util.go
- pkg/util/utils_test.go
fixes #1922 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
Able to configure custom env for components.
```
> Able to configure custom env for components

- docs/api-references/docs.html
- manifests/crd.yaml
- pkg/apis/pingcap/v1alpha1/openapi_generated.go
- pkg/apis/pingcap/v1alpha1/types.go
- pkg/manager/member/pd_member_manager.go
- pkg/manager/member/pump_member_manager.go
- pkg/manager/member/tidb_member_manager.go
- pkg/manager/member/tikv_member_manager.go
- tests/e2e/tidbcluster/tidbcluster.go
Cherry pick of #2013 on release-1.1.
#2013: add spec.paused field to pause the tidb cluster syncing
> Automated cherry pick of #2013: add spec.paused field to pause the tidb cluster syncing

- pkg/monitor/monitor/template.go
- pkg/monitor/monitor/template_test.go
Fix AlertManager setting error
```release-note
Fix the error that alertmanager couldn't be setted in TidbMonitor
```
> Fix AlertManager setting error

- docs/api-references/docs.md
- docs/api-references/template/pkg.tpl
- hack/update-crd-groups.sh
- hack/verify-crd-groups.sh
Revise the document util
```release-note
NONE
```
> Update Doc util

- tests/e2e/tidbcluster/serial.go
- tests/util.go
manually cp #2145
```release-note
NONE
```
> manually cp 2145

- pkg/backup/util/util.go
> fix a typo

- ci/run-in-vm.sh
- hack/e2e-openshift.sh
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> Wait for the VM to be ready in CI

- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/gcp/variables.tf
- tests/manifests/stability/stability.yaml
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> Update version in deployment files

- tests/e2e/tidbcluster/serial.go
- tests/e2e/tidbcluster/stability.go
fixes #1338
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> make sure we don't introduce backward incompatibility changes in the same minor series

- ci/pingcap_tidb_operator_build_kind.groovy
- hack/run-e2e.sh
- tests/e2e/config/config.go
- tests/e2e/e2e.go
- tests/e2e/tidbcluster/serial.go
- tests/e2e/tidbcluster/tidbcluster.go
- tests/e2e/util/image/image.go
- tests/images/e2e/Dockerfile
- tests/pkg/fixture/fixture.go
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> e2e: reduce ephemeral storage usage and request more 

- charts/tidb-cluster/values.yaml
- charts/tidb-drainer/values.yaml
- charts/tidb-lightning/values.yaml
- charts/tikv-importer/values.yaml
- deploy/aliyun/manifests/db-monitor.yaml.example
- deploy/aliyun/manifests/db.yaml.example
- deploy/aliyun/variables.tf
- deploy/aws/manifests/db-monitor.yaml.example
- deploy/aws/manifests/db.yaml.example
- deploy/aws/variables.tf
- deploy/gcp/manifests/db-monitor.yaml.example
- deploy/gcp/manifests/db.yaml.example
- deploy/gcp/variables.tf
- deploy/modules/aliyun/tidb-cluster/variables.tf
- deploy/modules/aws/tidb-cluster/variables.tf
- deploy/modules/gcp/tidb-cluster/variables.tf
- deploy/modules/share/tidb-cluster-release/variables.tf
- examples/advanced-statefulset/tidb-cluster-scaled.yaml
- examples/advanced-statefulset/tidb-cluster.yaml
- examples/auto-scale/tidb-cluster.yaml
- examples/auto-scale/tidb-monitor.yaml
- examples/basic/tidb-cluster.yaml
- examples/basic/tidb-monitor.yaml
- examples/initialize/tidb-cluster.yaml
- examples/selfsigned-tls/tidb-cluster.yaml
- images/tidb-backup-manager/Dockerfile
- manifests/monitor/tidb-monitor.yaml
update tidb-toolkit version
update tidb-toolkit version
Tests 
- Unit test
- E2E test
- No code
Code changes
```release-note
NONE
```
> update tidb-toolkit version

- docs/api-references/docs.md
- docs/api-references/template/pkg.tpl
- docs/api-references/template/type.tpl
- hack/lib.sh
fix the document error which would cause the anchor link wouldn't work in tidb-operator document
```release-note
NONE
```
> Revise document tool

- ci/upload-binaries-charts.sh
ucloud updated the format of http://tools.ufile.ucloud.com.cn/filemgr-linux64.tar.gz, and we should update our script too
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> update filemgr tar format

- charts/tidb-operator/templates/controller-manager-deployment.yaml
Cherry pick of #1877 on release-1.0.
fixes: https://github.com/pingcap/tidb-operator/issues/2211
#1877: fix operator failover config invalid
> Automated cherry pick of #1877: fix operator failover config invalid

- manifests/crd.yaml
- pkg/apis/pingcap/v1alpha1/openapi_generated.go
- pkg/apis/pingcap/v1alpha1/tikv_config.go
forget to cherry-pick some changes in https://github.com/pingcap/tidb-operator/pull/2198.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> fix missing code in release-1.1

- hack/e2e.sh
- hack/run-e2e.sh
- pkg/apis/pingcap/v1alpha1/tidbcluster.go
- pkg/label/label.go
- pkg/manager/member/pd_failover.go
- pkg/manager/member/pd_member_manager.go
- pkg/manager/member/pd_member_manager_test.go
- tests/e2e/tidbcluster/stability.go
- tests/e2e/util/cloud/cloud.go
Cherry pick of #2300 on release-1.1.
#2300: PD: auto-created failover pods should be deleted when
> Automated cherry pick of #2300: PD: auto-created failover pods should be deleted when

- examples/basic/README.md
- examples/tiflash/README.md
- examples/tiflash/tidb-cluster.yaml
- examples/tiflash/tidb-monitor.yaml
example for tiflash
Add example for tiflash
Tests 
```release-note
NONE
```
> example for tiflash

- ci/e2e_eks.groovy
- ci/e2e_gke.groovy
we need large local storage to build images in container
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> configure ephemeral storage for eks/gke jobs

- ci/release_tidb_operator_binary_and_image.groovy
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> update image tag in releasing

- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> update operator image to v1.1.0-rc.3

- go.mod
- go.sum
- manifests/crd.yaml
- pkg/to-crdgen/cmd/cmd.go
- pkg/to-crdgen/cmd/generate/generate.go
- pkg/util/crdutil.go
cherry-pick f772201b
```release-note
NONE
```
> Shorten CRD

- ci/pingcap_tidb_operator_build_kind.groovy
- hack/e2e.sh
fixes #1254
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> dump cluster logs into artifacts directory

- ci/e2e_eks.groovy
- ci/e2e_gke.groovy
- ci/e2e_kind.groovy
- ci/pingcap_tidb_operator_build_kind.groovy
- hack/e2e.sh
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> fix e2e periodical jobs

- tests/monitor.go
Tests 
- Unit test
- E2E test
Code changes
Side effects
```release-note
NONE
```
> remove one line log which is in wrong position

- charts/tidb-cluster/values.yaml
- deploy/aliyun/manifests/db-monitor.yaml.example
- deploy/aws/manifests/db-monitor.yaml.example
- deploy/gcp/manifests/db-monitor.yaml.example
- examples/auto-scale/tidb-monitor.yaml
- examples/basic/tidb-monitor.yaml
- examples/prometheus-operator/prometheus.yaml
- examples/tiflash/tidb-monitor.yaml
- manifests/monitor/tidb-monitor.yaml
- tests/e2e/util/image/image.go
Signed-off-by: yeya24 <yb532204897@gmail.com>
Compared to `v2.11.1`, `v2.18.1` release has many important improvements, including performance, new query function, and a new UI, etc.
> Bump prometheus version to latest

- images/tidb-backup-manager/Dockerfile
- tests/e2e/tidbcluster/tidbcluster.go
update br to v4.0.0-rc.2 to include the auto_random fix
update br to v4.0.0-rc.2 to include the auto_random fix
Tests 
- Backup and restore using BR with AWS S3
```release-note
Update BR to v4.0.0-rc.2 to include the auto_random fix
```
> update br to v4.0.0-rc.2 to include the auto_random fix

- tests/cmd/stability/main.go
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> simplify tests/cmd/stability

- ci/pingcap_tidb_operator_build_kind.groovy
- tests/actions.go
- tests/cmd/blockwriter/main.go
- tests/e2e/tidbcluster/tidbcluster.go
Create new database in e2e test
```release-note
NONE
```
> Create New DB during test

- tests/e2e/tidbcluster/serial.go
- tests/e2e/tidbcluster/stability-asts.go
- tests/e2e/tidbcluster/util.go
#2549
these cases can run in periodical jobs 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> move asts tests from serial to periodical job

- pkg/monitor/monitor/monitor_manager.go
Fix the error when tidbmonitor sync PVC failed which will cause panic
```release-note
Fix the error when `TidbMonitor` sync `PVC` failed which will cause controller manager panic
```
> Fix Monitor log error

- tests/e2e/tidbcluster/stability-asts.go
- tests/e2e/tidbcluster/tidbcluster.go
Move AdvancedStatefulSet test case to asts context job
```release-note
NONE
```
> Move AdvancedStatefulSet test case to asts context job

- images/tidb-backup-manager/Dockerfile
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
Update BR to v4.0.0 and Lightning to v3.0.14 in the tidb-backup-manager image
```
> update toolkit version

- ci/e2e_kind.groovy
- ci/pingcap_tidb_operator_build_kind.groovy
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> reduce resource requests of e2e pods

- pkg/manager/member/pd_failover.go
- pkg/manager/member/pd_member_manager.go
- pkg/manager/member/pd_member_manager_test.go
Enrich unit tests and add comment for pd failover
```release-note
None
```
> Enrich unit tests and add comment for pd failover

- ci/pingcap_tidb_operator_build_kind.groovy
Remove unnecessary e2e job
Side effects
```release-note
NONE
```
> Remove unnecessary e2e job

- pkg/monitor/monitor/monitor_manager.go
Signed-off-by: yeya24 <yb532204897@gmail.com>
fixes: #2635
Tested locally.
> Fix tidb monitor panic

- pkg/manager/member/ticdc_member_manager.go
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> pirint the errors while failed to sync ticdc status

- charts/tidb-operator/templates/controller-manager-deployment.yaml
- charts/tidb-operator/values.yaml
Tests 
```
helm template charts/tidb-operator -f charts/tidb-operator/values.yaml | kubectl apply -f -
```
Side effects
```release-note
NONE
```
> optionally set resources and priorityclass

- docs/design-proposals/2020-03-23-pause-tidb-cluster.md
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> add docs for tidb cluster pause feature

- pkg/scheduler/predicates/ha_test.go
fix #2672
Sort before comparing zones
Tests 
- Unit test
Code changes
Side effects
- None
```release-note
NONE
```
> fix ha filter test is not stable

- docs/design-proposals/2020-04-13-record-conditions-in-tidbcluster-status.md
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> add docs for tidbcluster conditions

- docs/api-references/docs.md
- manifests/crd.yaml
- pkg/apis/pingcap/v1alpha1/openapi_generated.go
- pkg/apis/pingcap/v1alpha1/tikv_config.go
- pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Add some missing configs for TiKV.
add item in TiKV.
Tests 
- Unit test
```release-note
NONE
```
> apis: add raft message config for TiKV

- docs/api-references/docs.md
- pkg/apis/pingcap/v1alpha1/pd_config.go
- pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Update configuration to v4.0.1. Only PD Configuration changes.
```release-note
Update Configuration to v4.0.1
```
> Update Configuration to v4.0.1

- images/tidb-backup-manager/Dockerfile
Fix https://github.com/pingcap/tidb-operator/issues/2627
Update the lightning and BR versions
Tests 
- Unit test
- E2E test
- Backup & restore with BR for v3.1.2
- Backup & restore with BR for v4.0.1
- Backup & restore with Lightning for v4.0.1
```release-note
NONE
```
> update binaries in backup-manager image

- deploy/aws/demo.tfvars
- deploy/aws/prod.tfvars
Fix #2668
Add different configurations for demo and product deployment on eks
Tests 
- Unit test
- E2E test
- Deploy TiDB Clusters with the two configurations on EKS
Code changes
```release-note
NONE
```
> add configurations for demo and product deployment on eks

- tests/e2e/tidbcluster/serial.go
Fix e2e auto-scaling test case meeting error in e2e case somtimes.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> Fix e2e auto-scaling test case

- docs/design-proposals/template.md
Add a template for the design proposal. This provides a common structure.
It's a simplified version of [Kubernetes KEP template](https://github.com/kubernetes/enhancements/blob/master/keps/NNNN-kep-template/README.md).
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> Add design proposal template

- charts/tidb-operator/templates/NOTES.txt
This PR fixes: https://github.com/pingcap/tidb-operator/issues/2737
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> fix following steps of install tidb-operator

- charts/tidb-lightning/templates/scripts/_start_lightning.sh.tpl
fixes: https://github.com/pingcap/tidb-operator/issues/2683
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> fix lightning log

- examples/basic/tidb-cluster.yaml
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> Use minimum resource requirements in basic examples

- ci/release_cli_binary_and_debug_image.groovy
- ci/release_tidb_operator_binary_and_image.groovy
fix #2779 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> update release scripts

- images/tidb-backup-manager/Dockerfile
Data export with mydumper may hang and the following errors will be printed in the tidb logts:
```
[2020/06/24 09:36:38.929 +00:00] [WARN] [session.go:1136] ["compile SQL failed"] [conn=145] [error="[variable:1193]Unknown system variable 'tokudb_version'"] [SQL="SELECT @@tokudb_version"]
[2020/06/24 09:36:38.929 +00:00] [WARN] [session.go:1136] ["compile SQL failed"] [conn=145] [error="[planner:1054]Unknown column '_tidb_rowid' in 'field list'"] [SQL="SELECT _tidb_rowid FROM `sbtest`.`sbtest1` LIMIT 0"]
```
Use the pingcap forked mydumper
Tests 
- Unit test
- E2E test
- Run backup & restore with mydumper+lightning
Code changes …
> use the pingcap forked mydumper

- docs/api-references/docs.md
- manifests/crd.yaml
- pkg/apis/pingcap/v1alpha1/openapi_generated.go
- pkg/apis/pingcap/v1alpha1/pd_config.go
- pkg/apis/pingcap/v1alpha1/tidb_config.go
- pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Cherry pick of #2828 on release-1.1.
#2828: update pd/tidb/tikv config to v4.0.2
> Automated cherry pick of #2828: update pd/tidb/tikv config to v4.0.2

- manifests/dm/README.md
The README.md for the DM manifests didn't really give any information about how to proceed, so I added a simple link to the DM documentation.
Tests 
- No code
```release-note
NONE
```
> Added instructions to DM README.md

- .vscode/settings.json
- pkg/apis/pingcap/v1alpha1/tidbcluster.go
- pkg/manager/member/tidb_member_manager.go
- pkg/manager/member/tidb_member_manager_test.go
add TiDBScaling function
add TiDBScaling function
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
v1.1
```release-note
NONE
```
> add TiDBScaling function

- docs/api-references/docs.md
- manifests/crd.yaml
- pkg/apis/pingcap/v1alpha1/openapi_generated.go
- pkg/apis/pingcap/v1alpha1/types.go
- pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
- pkg/manager/member/tidb_member_manager.go
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> Automated cherry pick of #2810 upstream release 1.1

- examples/basic-cn/tidb-cluster.yaml
the `reserve-space` is under `storage` section
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> fix a bug in PR 2852

- README.md
- ci/pull_e2e_kind.groovy
https://github.com/pingcap/tidb-operator/issues/1443
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> add new pull e2e Jenkins file

- deploy/aliyun/manifests/db.yaml.example
- deploy/aws/manifests/db.yaml.example
The TLS config in the db.yaml.example for EKS and ACK is outdated.
Update tls config for eks and ack
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> update tls config for eks and ack

- hack/lib.sh
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> update kubetest2 release repo

- pkg/autoscaler/autoscaler/tikv_autoscaler.go
Fix externalendpoint judgement in tikv auto-scaling.
> Fix externalendpoint judgement in tikv auto-scaling

- .github/.codecov.yml
- .github/workflows/ci.yaml
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> reporting test coverage for PRs

- Makefile
- cmd/backup-manager/app/util/util_test.go
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> test cmd/backup-manager/app

- cmd/discovery/main.go
- pkg/discovery/discovery.go
- pkg/discovery/discovery_test.go
- pkg/discovery/server/interface.go
- pkg/discovery/server/proxy.go
- pkg/discovery/server/proxy_test.go
- pkg/discovery/server/server.go
- pkg/discovery/server/server_test.go
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> add UTs for discovery

- pkg/webhook/statefulset/statefulset.go
- pkg/webhook/statefulset/statefulset_test.go
- pkg/webhook/util/scheme.go
https://github.com/pingcap/tidb-operator/issues/2821
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> check the StatefulSet in the incoming request and add UTs

- images/tidb-backup-manager/Dockerfile
resolve https://github.com/pingcap/tidb-operator/issues/2995
update version
Tests 
- Unit test
- E2E test
* Manual version check in pod
```release-note
update tools in backup manager to v4.0.3
```
> update tools in backup manager to v4.0.3

- charts/tidb-cluster/templates/scripts/_start_drainer.sh.tpl
- charts/tidb-drainer/templates/scripts/_start_drainer.sh.tpl
- pkg/autoscaler/autoscaler/query/external.go
- pkg/manager/member/template.go
- pkg/pdapi/pd_control.go
- pkg/pdapi/pdapi.go
- pkg/util/crypto/certs.go
- tests/actions.go
- tests/backup.go
- tests/e2e/tidbcluster/serial.go
- tests/e2e/tidbcluster/stability.go
- tests/e2e/tidbcluster/tidbcluster.go
- tests/e2e/tidbcluster/tls.go
- tests/e2e/util/proxiedpdclient/proxiedpdclient.go
Fix #2547
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> fix flakiness in "TLS for MySQL Client and TLS between TiDB components"

- .github/workflows/chaos.yaml
https://github.com/chaos-mesh/chaos-mesh-actions
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> add a chaos e2e job

- .github/workflows/chaos.yaml
- .golangci.yml
- hack/run-e2e.sh
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> create a small cluster in github actions job

- docs/design-proposals/2020-08-03-deploy-tidb-cluster-across-mulitple-kubernetes-clusters.md
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> add proposal for deploy tidb cluster across kubernetes clusters

- pkg/discovery/server/server_test.go
- pkg/manager/member/pod_restarter.go
- pkg/manager/member/pod_restarter_test.go
- pkg/manager/member/pvc_cleaner.go
- pkg/manager/member/pvc_cleaner_test.go
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> improve UT for pod_restarter and pvc_cleaner

- pkg/manager/member/orphan_pods_cleaner.go
Fix some logic error in the orphan pod cleaner introduced in #2709
Tests 
- Unit test
- E2E test
Code changes
```release-note
NONE
```
> update logic of orphan pod cleaner

- go.mod
- go.sum
- pkg/pdapi/pdapi.go
PD has transferred from pingcap/pd to [tikv/pd](https://github.com/tikv/pd).
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> update pd import path

- charts/tidb-operator/templates/controller-manager-rbac.yaml
- pkg/controller/tidbcluster/tidb_cluster_control.go
- pkg/controller/tidbcluster/tidb_cluster_control_test.go
- pkg/controller/tidbcluster/tidb_cluster_controller.go
- pkg/manager/member/pvc_resizer.go
- pkg/manager/member/pvc_resizer_test.go
- pkg/util/util.go
Cherry pick of #3096 on release-1.1.
#3096: Patch PVC when storage request is increased
> Automated cherry pick of #3096: Patch PVC when storage request is increased

- pkg/manager/meta/reclaim_policy_manager.go
Reverts pingcap/tidb-operator#3105
> Revert "Refactor the reclaim_policy_manager and fix TiKVGroup.GetName()"

- pkg/monitor/monitor/template.go
- pkg/monitor/monitor/template_test.go
Fix #3084
Tests 
- Unit test
- E2E test
- Deploy TiFlash with TLS enabled and the monitoring dashboards work well
Code changes
```release-note
NONE
```
> monitoring for tiflash when tls enabled

- deploy/aws/demo.tfvars
- deploy/aws/manifests/db.yaml.example
- deploy/aws/prod.tfvars
Update instance type for tikv since we do not recommend to use local SSD anymore.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> update instance type for tikv

- docs/design-proposals/2020-08-21-auto-scaling-with-pdapi.md
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> add proposal for auto-scaling with pd api

- pkg/webhook/pod/pods_test.go
- pkg/webhook/statefulset/statefulset_test.go
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> more webhook tests

- pkg/scheduler/predicates/ha.go
- pkg/scheduler/predicates/ha_test.go
fix #1594 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> use the real desired replicas in HA predicate

- docs/api-references/docs.md
- manifests/crd.yaml
- pkg/apis/pingcap/v1alpha1/openapi_generated.go
- pkg/apis/pingcap/v1alpha1/tidb_config.go
- pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Signed-off-by: Howard Lau <howardlau1999@hotmail.com>
Close https://github.com/pingcap/tidb-operator/issues/3181
Add `labels` field in TiDBConfig
Tests 
- Manual Test
- Create TiDB cluster with labels configured for TiDB Server and verify the labels are applied
Code changes
Side effects
```release-note
Support labels configuration for TiDB Server
```
> support labels configuration for tidb server

- pkg/monitor/monitor/monitor_manager.go
- pkg/monitor/monitor/util.go
fixes: https://github.com/pingcap/tidb-operator/issues/3179, removed `Clusterrole` for `TidbMonitor` CR.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
Fix RBAC issue for TidbMonitor
```
> Fix RBAC issue for TidbMonitor

- .github/workflows/stale.yaml
There are many valid issues that may be stale by the stale action, with this PR, we will only stale the issues with the label `status/needs-info`.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> update labels for stale action

- .golangci.yml
- pkg/autoscaler/autoscaler/calculate/util.go
- pkg/autoscaler/autoscaler/util.go
- pkg/controller/generic_control_test.go
- pkg/manager/member/dm_master_member_manager.go
- pkg/manager/member/orphan_pods_cleaner.go
- pkg/manager/member/pd_failover.go
- pkg/manager/member/pd_member_manager.go
- pkg/manager/member/pvc_cleaner.go
- pkg/manager/member/tidb_failover.go
- pkg/manager/member/tiflash_failover.go
- pkg/manager/member/tikv_failover.go
- pkg/manager/member/tikv_upgrader.go
- pkg/manager/member/utils_test.go
- pkg/pdapi/pdapi.go
- pkg/tkctl/cmd/get/get.go
- pkg/util/crdutil.go
- tests/actions.go
- tests/cmd/blockwriter/main.go
- tests/crd_test_util.go
- tests/e2e/framework/framework.go
- tests/e2e/tidbcluster/stability.go
- tests/e2e/tidbcluster/tidbcluster.go
- tests/pkg/fault-trigger/manager/vm_qm.go
- tests/pkg/fault-trigger/manager/vm_virsh.go
- tests/pkg/mock/monitor.go
Fix all issues reported by gosimple
cc #3202 
Fix all issues reported by gosimple.
Enable gosimple in `.golangci.yml` and ignore some generated code files.
https://github.com/pingcap/tidb-operator/pull/3204/files#diff-6a6b24b5bc137650d7d0b9ebefcea6a1L78 might cause potential bugs others just trivial fix.
Tests 
```release-note
NONE
```
> Fix all issues reported by gosimple

- pkg/manager/member/pump_member_manager.go
fixes: https://github.com/pingcap/tidb-operator/issues/3211
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
Fix Pump imagePullSecrets issue
```
> Fix Pump imagePullSecrets issue

- charts/tidb-operator/values.yaml
- docs/api-references/docs.md
- manifests/crd.yaml
- pkg/apis/pingcap/v1alpha1/crd_kinds.go
- pkg/apis/pingcap/v1alpha1/types.go
1. Fix spelling error: `josn` -> `json`
2. Tidbmonitors supports shortname 'tm'
3. Change advanced statefulset controller log level from 2 to 4
Tests 
- No code
Code changes
```release-note
NONE
```
> Some small optimizations

- docs/api-references/docs.md
- manifests/crd.yaml
- pkg/apis/pingcap/v1alpha1/openapi_generated.go
- pkg/apis/pingcap/v1alpha1/tikv_config.go
- pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Add some missing configs for TiKV.
add item in TiKV.
Tests 
- Unit test
```release-note
NONE
```
> apis: add gc config for TiKV

- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
update chart version to v1.1.5
Tests 
- Unit test
- E2E test
```release-note
NONE
```
> update chart version to v1.1.5

- docs/api-references/docs.md
- manifests/crd.yaml
- pkg/apis/pingcap/v1alpha1/openapi_generated.go
- pkg/apis/pingcap/v1alpha1/tikv_config.go
- pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Signed-off-by: lhy1024 <admin@liudos.us>
Add some gc configs for TiKV.
add item in TiKV.
Tests 
- Unit test
```release-note
NONE
```
> apis: add gc config `compaction-filter-skip-version-check` for TiKV

- README.md
Signed-off-by: mike.cwwmy@gmail.com
Add heterogeneous cluster function to README.md.
> Add heterogeneous cluster feature to readme.md

- pkg/manager/member/tidb_init_manager.go
- pkg/manager/member/tidb_member_manager.go
- pkg/manager/member/tidb_member_manager_test.go
- pkg/manager/member/tiflash_member_manager.go
- pkg/manager/member/tikv_member_manager.go
- pkg/manager/member/tikv_member_manager_test.go
Fix #3302 
Tests 
- Unit test
- E2E test
Code changes
Side effects
```release-note
Support to specify spec.helper.requests and  spec.helper.limits for all initcontainers
```
> add initcontainer ResourceRequirements

- .gitignore
- Makefile
- hack/version.sh
- pkg/monitor/monitor/template_test.go
- pkg/monitor/monitor/util_test.go
Add some unit test cases for `pkg/monitor/monitor`.
Tests 
- Unit test
Code changes
- None
Side effects
- None
- None
```release-note
NONE
```
> tests: add some test cases for pkg/monitor/monitor

- pkg/manager/member/pd_member_manager.go
- pkg/manager/member/tiflash_member_manager.go
- pkg/manager/member/tikv_member_manager.go
Use correct spec.
the strategy will always as the same value of TiDBCluster
Use correct spec
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> Use correct spec

- pkg/monitor/monitor/util.go
- pkg/monitor/monitor/util_test.go
Cherry pick of #3390 on release-1.1.
#3390: monitor: fix surprising prometheus commandOptions behavior
> Automated cherry pick of #3390: monitor: fix surprising prometheus commandOptions behavior

- pkg/apis/pingcap/v1alpha1/tidbcluster.go
- pkg/manager/member/pd_failover.go
- pkg/manager/member/pd_member_manager.go
Fix https://github.com/pingcap/tidb-operator/issues/3410
Tests 
Code changes
```release-note
NONE
```
> Optimize the calculation of `PDStsDesiredReplicas`

- pkg/backup/util/util.go
- pkg/backup/util/utils_test.go
```
➜  util git:(backup_test) ✗ go test -cover
PASS
coverage: 98.8% of statements
ok      github.com/pingcap/tidb-operator/pkg/backup/util        0.033s
```
ref #2920
```release-note
NONE
```
> Add test for pkg/backup/util/util.go

- pkg/manager/member/tikv_scaler.go
- pkg/manager/member/tikv_scaler_test.go
https://github.com/pingcap/tidb-operator/issues/3421
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> heterogeneous TiKV cluster cannot be scaled in to less than 3 replicas

- .github/workflows/stale.yaml
Signed-off-by: Ran <huangran@pingcap.com>
Found this by accident :) 
- No code
```release-note
NONE
```
> Fix invalid args in stale action

- pkg/manager/member/tidb_member_manager_test.go
Remove duplicate code in tidb_member_manager_test.go file.
Tests 
- Unit test
> Remove duplicate code in tidb_member_manager_test.go file.

- tests/e2e/tidbcluster/tidbcluster.go
Improve the e2e for auto-scaling to make it stable.
Tests 
- Unit test
- E2E test
- No code
Code changes
```release-note
NONE
```
> update e2e for auto-scaling

- .codecov.yml
- pkg/controller/controller_utils_test.go
- pkg/controller/generic_control_test.go
- pkg/manager/member/tikv_member_manager_test.go
Add some unit test cases
Tests 
- Unit test
Code changes
```release-note
NONE
```
> add some unit tests for pkg/controller

- hack/verify-lint.sh
- pkg/backup/backupschedule/backup_schedule_manager_test.go
cherry-pick #3480 to release-1.1
```release-note
NONE
```
> Increase timeout of lint in case timeout at ci (#3480)

- manifests/monitor/tidb-monitor.yaml
Fix https://github.com/pingcap/tidb-operator/issues/3472
Tests 
- Unit test
- E2E test
- Deploy TiDB Monitor with resource configured for all containers and the deployment is created successfully with resources specified.
```release-note
NONE
```
> update resources config for tidb-monitor

- ci/upload-binaries-charts.sh
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> update the path of filemgr

- ci/upload-binaries-charts.sh
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```
> update filemgr config file

- cmd/backup-manager/app/util/util_test.go
Add some unit tests for `cmd/backup-manager/app/util`.
Tests 
- Unit test
Code changes
```release-note
NONE
```
> add some unit tests for cmd/backup-manager/app/util

- examples/multi-cluster/tidb-cluster-1.yaml
- examples/multi-cluster/tidb-cluster-2.yaml
Update example yaml for multi-cluster.
Tests 
- No code
```release-note
NONE
```
> Update examples for multi-cluster

- .github/pull_request_template.md
fix unordered list indentation in github pull request template
change the template markdown
Tests 
- No code
Code changes
None
Side effects
None
None
```release-note
NONE
```
> fix list indentation

- docs/CONTRIBUTING.md
- hack/update-codegen.sh
improve k8s codegen so that we don't need to do `hack/update-all.sh` in `$GOPATH` anymore!
change generator invocation script
Tests 
- No code
Code changes
Side effects
None
None
```release-note
NONE
```
> improve codegen for golang code

- pkg/controller/stateful_set_control.go
- pkg/monitor/monitor/monitor_manager.go
- pkg/monitor/monitor/monitor_manager_test.go
- pkg/monitor/monitor/template.go
- pkg/monitor/monitor/template_test.go
- pkg/monitor/monitor/util.go
#3531 
Every cluster generate a scrape job.
Tests
- Unit test
- E2E test
Code changes
> fix consistency question for  tidbmonitor monitor  multiple cluster 

- pkg/monitor/monitor/template.go
- pkg/monitor/monitor/template_test.go
solve issue #3531 
Monitor lighting tls configuration bug.
> fix monitor lighting bug

- pkg/manager/member/tidb_init_manager.go
If SkipTLSWhenConnectTiDB is enabled, `tidb-client-tls` secret will not be mounted. But script in init job still add TLS parameters.
```
Traceback (most recent call last):
File "/usr/local/bin/start_script.py", line 5, in <module>
conn = MySQLdb.connect(host=host, port=port, user='root', connect_timeout=5, ssl={'ca': '/var/lib/tidb-client-tls/ca.crt', 'cert': '/var/lib/tidb-client-tls/tls.crt', 'key': '/var/lib/tidb-client-tls/tls.key'})
File "/usr/local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 84, in Connect
return Connection(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 179, in __init__
super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2026, 'SSL connection error: No such file or …
```
> TidbInitializer: support skip TLS when connecting to TiDB Server

- pkg/manager/member/tidb_init_manager.go
Fix #3565
Update code to sync the Job status to the status of TidbInitializer CR
Tests 
- Unit test
- E2E test
Create a TidbCluster and a TidbInitializer, check that after the initializer job is finished, the status of TidbInitializer is synced:
```
kind: TidbInitializer
metadata:
creationTimestamp: "2020-11-30T03:22:08Z"
generation: 1
name: demo
namespace: default
resourceVersion: "11491845"
selfLink: /apis/pingcap.com/v1alpha1/namespaces/default/tidbinitializers/demo
uid: 3a7e64dd-32bb-11eb-87fe-06b1f522197d
spec:
cluster:
name: t
namespace: default
image: tnir/mysqlclient
initSql: create database app;
passwordSecret: tidb-secret
status:
completionTime: "2020-11-30T03:22:22Z"
conditions:
- …
```
> update status for tidb initializer

- examples/tiflash/tidb-cluster.yaml
Fix tiflash example yaml after TiDB Operator v1.1.6
Fixes #3563
tiflash example yaml, fix the value type
Tests 
- No code
Code changes
None
Side effects
None
```release-note
NONE
```
> fix tiflash example

- .github/pull_request_template.md
Improve the github PR template
Changed the github PR template, which encourages committer to write more understandable PR description.
Hopefully this will make people in the community feels easier to engage in the development process :wink:
Tests 
- No code
Code changes
None
Side effects
None
```release-note
NONE
```
> improve github PR template

- pkg/controller/tidbmonitor/tidb_monitor_controller.go
#3585 
Change TiDBMonitor controller watch from deployment to statefulset.
> Fix tidbmonitor watch from deployment to statefulset

- charts/tidb-lightning/templates/_helpers.tpl
- charts/tidb-lightning/templates/job.yaml
- charts/tidb-lightning/templates/scripts/_start_lightning.sh.tpl
- charts/tidb-lightning/values.yaml
- charts/tikv-importer/templates/_helpers.tpl
- charts/tikv-importer/templates/tikv-importer-statefulset.yaml
- charts/tikv-importer/values.yaml
Add TLS support for TiDB-Lightning and TiKV-Importer charts
close #1631
1. mount TLS secret if specified
2. add TLS args in the config file if specified
1. prepare data need to be imported into the TiDB cluster
2. create a cluster Secrect for TiKV-Importer
an YAML example with cert-manager is:
```yaml
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
name: ${cluster_name}-importer-cluster-secret
namespace: ${namespace}
spec:
secretName: ${cluster_name}-importer-cluster-secret
duration: 8760h # 365d
renewBefore: 360h # 15d
organization:
- PingCAP
commonName: "TiDB"
usages:
- server auth
- client auth
dnsNames:
- "${cluster_name}-importer"
- "${cluster_name}-importer.${namespace}"
- "${cluster_name}-importer.${namespace}.svc"
ipAddresses:
- 127.0.0.1
- ::1
issuerRef:
name: …
```
> charts: add TLS support for TiDB-Lightning and TiKV-Importer

- charts/tidb-lightning/values.yaml
- cmd/backup-manager/app/import/import.go
fix #3615
set `file = "-"` for TiDB-Lighting
1. install TiDB-Lighting chart
2. `kubectl logs` to fetch the log of TiDB-Lighting, then something like bellow will get:
```
[2020/12/17 04:18:24.548 +00:00] [INFO] [lightning.go:159] ["starting HTTP server"] [address="[::]:8289"]
[2020/12/17 04:18:24.548 +00:00] [WARN] [config.go:436] ["currently only per-task configuration can be applied, global configuration changes can only be made on startup"] ["global config changes"="[lightning.level,lightning.file]"]
[2020/12/17 04:18:24.553 +00:00] [INFO] [version.go:52] ["Welcome to lightning"] ["Release Version"=v4.0.8] ["Git Commit Hash"=6887f4e6b49bb9f32f3d3f137e00bc7bfa248074] ["Git Branch"=heads/refs/tags/v4.0.8] ["UTC Build Time"="2020-10-30 08:14:25"] ["Go Version"="go version go1.13 …
```
> charts: write TiDB-Lighting logs to stdout

- ci/release_tidb_operator_binary_and_image.groovy
> update upload script

- charts/tidb-cluster/templates/discovery-rbac.yaml
- charts/tidb-cluster/templates/monitor-rbac.yaml
- charts/tidb-operator/templates/controller-manager-rbac.yaml
- charts/tidb-operator/templates/scheduler-rbac.yaml
Close #3604
```release-note
```
> fix Chart resource version

- examples/monitor-with-externalConfigMap/tidb-monitor.yaml
fix `commandOptions` example because we have changed the behavior in #3390 (use `append` instead of `=` to keep hardcode options)
```release-note
None
```
> monitor: fix the commandOptions example

- docs/api-references/docs.md
- pkg/apis/pingcap/v1alpha1/tidb_config.go
Modify config parameter to suite for the TiKV configs
```release-note
Fix config parameter error 
```
> Fix copr-cache.enable config error

- ci/pull_e2e_kind.groovy
add param to set --delete-namespace-on-failure
add parameter in ci pipeline
tested in https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/3792/pipeline
The log of `Run` stage shows that `--delete-namespace-on-failure=false` is set correctly
```release-note
None
```
> add param to set --delete-namespace-on-failure

- ci/pull_e2e_kind.groovy
temporarily
change hub.pingcap.net to hub-dev.pingcap.net in ci pipeline
```release-note
None
```
> temporarily change to hub-dev.pingcap.net

- README.md
update links and add info
- Optimized some links in the README file
- Added some related content
```release-note
`NONE`
```
> README: update links and add info

- charts/tidb-cluster/values.yaml
- deploy/aliyun/manifests/db.yaml.example
- deploy/aws/manifests/db.yaml.example
- docs/api-references/docs.md
- examples/tiflash/tidb-cluster.yaml
- pkg/apis/pingcap/v1alpha1/openapi_generated.go
- pkg/apis/pingcap/v1alpha1/tidbcluster.go
- pkg/apis/pingcap/v1alpha1/types.go
- pkg/manager/member/pd_member_manager_test.go
- pkg/manager/member/tidb_member_manager_test.go
- pkg/manager/member/tiflash_util_test.go
- pkg/manager/member/tikv_member_manager_test.go
Closes #3787
upgrade busybox image version to 1.33.0
```release-note
None
```
> upgrade busybox image version to 1.33.0

- hack/e2e-patch-codecov.sh
fix code coverage patch script
ensure that `{{- end }}` is at the end of files after patch
```release-note
None
```
> fix code coverage patch script

- tests/actions.go
- tests/backup.go
- tests/dt.go
- tests/e2e/tidbcluster/serial.go
- tests/e2e/tidbcluster/stability-asts.go
- tests/e2e/tidbcluster/stability-br.go
- tests/e2e/tidbcluster/stability.go
- tests/e2e/tidbcluster/tidbcluster.go
- tests/failover.go
- tests/log_dump.go
- tests/webhook.go
There is an unnecessary interface `OperatorActions` which is ill-designed.
remove interface, use struct directly.
```release-note
None
```
> remove interface OperatorActions

- tests/e2e/tidbcluster/serial.go
- tests/e2e/tidbcluster/stability-asts.go
- tests/e2e/tidbcluster/stability.go
- tests/e2e/tidbcluster/tidbcluster.go
Ref #3652
```release-note
None
```
> Remove unnecessary Helm Chart deployment

- .github/workflows/ci.yaml
run UT and upload coverage after PR merged
trigger CI Github Actions workflow for `push` events.
- **I don't know whether need to cherry-pick.**
```release-note
None
```
> run UT and upload coverage after PR merged

- docs/api-references/docs.md
- go.sum
- manifests/crd.yaml
- pkg/apis/pingcap/v1alpha1/openapi_generated.go
- pkg/apis/pingcap/v1alpha1/types.go
- pkg/manager/member/tidb_discovery_manager.go
- pkg/manager/member/tikv_member_manager.go
tikv deploy pods export status port(20180) Fix https://github.com/pingcap/tidb-operator/issues/2410
> add tikv status port(20180)

- ci/pull_e2e_release.groovy
in #3725, we add `E2E=y` to patch some files for E2E tests but this should not happen for release.
NOTE: We may also use `properties.parameters` to distinguish these purposes or we may give the groovy a better name?
add a new jenkins groovy with previous content.
```release-note
None
```
> add a jenkins groovy for release

- examples/advanced/tidb-cluster.yaml
[in the doc](https://docs.pingcap.com/tidb-in-kubernetes/stable/configure-a-tidb-cluster#configure-high-availability), we said `Currently, the TiDB cluster uses this scheduler as the default scheduler`, so it's better to set `spec.schedulerName` for our advanced example.
```release-note
None
```
> set schedulerName for advanced example

- pkg/monitor/monitor/monitor_manager.go
- pkg/monitor/monitor/template.go
- pkg/monitor/monitor/template_test.go
- pkg/monitor/monitor/util.go
- pkg/monitor/monitor/util_test.go
#3292 
Optimize tidbmonitor monitor  tls dm cluster . 
None.
```release-note
Optimize tidbmonitor monitor  tls dm cluster . 
```
> Optimize tidbmonitor monitor  tls dm cluster . 

- pkg/manager/member/tidbcluster_status_manager.go
fix #3964 
```release-note
NONE
```
> fix no tidb

- examples/advanced/tidb-cluster.yaml
Signed-off-by: swartz-k <9215868@gmail.com>
TiFlash in Advanced TiDBClsuter Example logger & cert-allowed-cn need quote
Closes #3967
```release-note
NONE
```
> fix: advanced example TiFlash conf

- charts/tidb-operator/templates/controller-manager-deployment.yaml
- charts/tidb-operator/templates/scheduler-deployment.yaml
- charts/tidb-operator/values.yaml
feat: helm chart add support for setting custom pod annotations for scheduler
Closes #3957 
in helm chart provide scheduler.podAnnotations, and go along with helm install
```release-note
```
> add custom annotations in the tidb-operator helm chart (#3957)

- README.md
We'll deprecate TiDB Weekly and Monthly, so I remove the link.
```release-note
```
> README: remove the TiDB Monthly link

- tests/actions.go
- tests/dm.go
- tests/e2e/dmcluster/dmcluster.go
- tests/e2e/util/image/image.go
- add delete dc case
- add auto failover for DM case
- add upgrade DM case
part of #2868
```release-note
None
```
> e2e: add delete dc, auto failover, upgrade test cases

- cmd/backup-manager/app/export/export.go
- cmd/backup-manager/app/export/manager.go
- pkg/util/util.go
- tests/e2e/br/br.go
- tests/e2e/br/framework/br/data.go
- tests/e2e/br/framework/br/wait.go
- tests/e2e/br/framework/framework.go
- tests/e2e/br/utils/blockwriter/writer.go
- tests/e2e/br/utils/feature/feature.go
- tests/e2e/br/utils/once/once.go
- tests/e2e/br/utils/portforward/helper.go
- tests/e2e/br/utils/portforward/portforward.go
- tests/e2e/br/utils/s3/interface.go
- tests/e2e/br/utils/s3/minio.go
- tests/e2e/br/utils/tls/manager.go
- tests/e2e/br/utils/yaml/dynamic.go
- tests/e2e/e2e.go
- tests/e2e/e2e_test.go
- tests/e2e/util/image/image.go
> add backup and restore e2e test

- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- examples/dm/dm-cluster.yaml
- hack/bump-version.sh
ref #3998.
run script hack/bump-version.sh, and correct some comments by hand.
```release-note
None
```
> Bump operator to v1.2.0-rc.1 and DM to v2.0.3

- ci/e2e_eks.groovy
- ci/e2e_gke.groovy
- ci/e2e_kind.groovy
- ci/pull_e2e_kind.groovy
- ci/pull_e2e_release.groovy
- ci/release-nightly.groovy
Fix ci checkout code timeout from github when encounter insufficient bandwidth, retry 3 times
Retry checkout code when encounter checkout timeout
> Retry checkout if checkout code failed

- pkg/monitor/monitor/util.go
- pkg/monitor/monitor/util_test.go
> Remove some useless code

- .github/workflows/chaos.yaml
- .github/workflows/ci.yaml
Update go version of workflow to 1.16
```release-note
None
```
> Update go version of workflow to 1.16

- pkg/binlog/binlog.go
- pkg/controller/equality.go
- pkg/manager/member/tidb_member_manager.go
Fix #4007 
remove the useless continuously updated status in tc and keep last apply ann of tidb service
check no "update Service" log after update to this version and no continuously re-sync
```release-note
Fix tidb service and tc is updated continuously
```
> fix tidb service and tc is updated continuously

- examples/advanced/tidb-cluster.yaml
Update  `terminationGracePeriodSeconds` in example file 'tidb-cluster.yaml' to be Int.
Closes #4024 
```release-note
```
> Update example file "tidb-cluster.yaml"

- docs/api-references/docs.md
- pkg/apis/pingcap/v1alpha1/types.go
- pkg/controller/ticdc_control.go
- pkg/manager/member/ticdc_member_manager.go
Closes #4001 
* Upgrade tidb-operator and check whether the *status* of 'TiCDC' contains field `version` and `isOwner`. 
```release-note
```
> Update the TiCDC capture status info in the `status.ticdc`

- charts/tidb-lightning/values.yaml
Update `rcloneImage` field of tidb-lightning's `values.yaml` to be compatible with ARM64 architecture.
Use new `values.yaml` to deploy *tidb-lightning*
```release-note
```
> Update tidb-lightning's rclone image

- deploy/aliyun/manifests/db-monitor.yaml.example
- deploy/aws/manifests/db-monitor.yaml.example
- deploy/gcp/manifests/db-monitor.yaml.example
- examples/auto-scale/tidb-monitor.yaml
- examples/aws/tidb-monitor.yaml
- examples/basic-cn/tidb-monitor.yaml
- examples/basic-tls/tidb-monitor.yaml
- examples/basic/tidb-monitor.yaml
- examples/dm/dm-monitor.yaml
- examples/gcp/tidb-monitor.yaml
- examples/heterogeneous-tls/tidb-monitor.yaml
- examples/heterogeneous/tidb-monitor.yaml
- examples/monitor-multiple-cluster-non-tls/tidb-monitor.yaml
- examples/monitor-multiple-cluster-tls/tidb-monitor.yaml
- examples/monitor-prom-remotewrite/tidb-monitor.yaml
- examples/monitor-with-externalConfigMap/grafana/tidb-monitor.yaml
- examples/monitor-with-externalConfigMap/prometheus/tidb-monitor.yaml
- examples/monitor-with-thanos/tidb-monitor-with-additional-volumes.yaml
- examples/monitor-with-thanos/tidb-monitor.yaml
- examples/namespaced/tidb-monitor.yaml
- examples/tiflash/tidb-monitor.yaml
- manifests/monitor/tidb-monitor.yaml
Close #4060
```release-note
```
> Update version of grafana to 7.5.7

- docs/api-references/docs.md
- manifests/crd.yaml
- pkg/apis/pingcap/v1alpha1/openapi_generated.go
- pkg/apis/pingcap/v1alpha1/types.go
- pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
- pkg/backup/backup/backup_cleaner.go
- pkg/backup/backup/backup_manager.go
- pkg/backup/restore/restore_manager.go
Fix #4052 .
```release-note
Backup job support specify priorityClassName.
```
> Backup job support specify priorityClassName.

- ci/release_tidb_operator_binary_and_image.groovy
> Fix publish 'nightly' charts

- pkg/monitor/monitor/monitor_manager_test.go
- pkg/monitor/monitor/util.go
- pkg/monitor/monitor/util_test.go
fix remoteWrite parse error
use golang standard library `https://pkg.go.dev/net/url#Parse` to parse remoteWrite
add UT TestGenerateRemoteWrite only for url
- [*] Has Go code change
- [*] Unit test 
```release-note
```
> fix remoteWrite parse error

- pkg/manager/member/pd_member_manager.go
- pkg/manager/member/pd_member_manager_test.go
- pkg/manager/member/pump_member_manager.go
- pkg/manager/member/tidb_member_manager.go
- pkg/manager/member/tikv_member_manager.go
Reverts pingcap/tidb-operator#4088
> Revert "use tc.Timezone()"

- ci/release_tidb_operator_binary_and_image.groovy
Update download address of `helm`
```release-note
```
> Update download address of `helm`

- tests/e2e/br/br.go
- tests/e2e/tidbcluster/tidbcluster.go
- tests/e2e/util/image/image.go
upgrade tidb to v5.2.0 in e2e
```release-note
```
> upgrade tidb to v5.2.0 in e2e

- tests/e2e/tidbcluster/tidbcluster.go
Fix tidbmonitor shard e2e test.
> Fix tidbmonitor shard e2e test

- README.md
Optimize tidbmonitor readme document.
> Optimize tidbmonitor readme document.

- go.mod
- go.sum
Close #4237 
```release-note
Fix some high security issues
```
> Fix some high security issues 

- ci/pull_e2e_kind.groovy
Adjust ephemeral storage size to 150Gi
```release-note
```
> Adjust ephemeral storage size to 250Gi

- pkg/manager/member/tidb_discovery_manager.go
Reverts pingcap/tidb-operator#4259
> Revert "support PodSecurityContext for Discovery"

- manifests/crd.yaml
- manifests/crd_v1beta1.yaml
- pkg/apis/pingcap/v1alpha1/types.go
- pkg/client/clientset/versioned/typed/pingcap/v1alpha1/fake/fake_tidbcluster.go
- pkg/client/clientset/versioned/typed/pingcap/v1alpha1/tidbcluster.go
> types.go: Do not generate the UpdateStatus

- manifests/crd.yaml
- manifests/crd/v1/pingcap.com_dmclusters.yaml
- manifests/crd/v1/pingcap.com_tidbclusters.yaml
- manifests/crd/v1beta1/pingcap.com_dmclusters.yaml
- manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
- manifests/crd_v1beta1.yaml
- pkg/apis/pingcap/v1alpha1/types.go
All components should support 0 replicas for graceful shutdown, especially in multicluster TiDB.
```release-note
set all components minimum replicas to 0
```
> set all components minimum replicas to 0

- pkg/tikvapi/tikvapi.go
Fix #4281 
Read the metrics from the channel first and then process the metrics.
- Deploy a TiDB cluster with 3 TiKVs, upgrade the cluster, and the upgrade succeeds
```release-note
Fix potential goroutine leak when checking the region leader count of TiKV
```
> fix potential goroutine leak

- manifests/crd.yaml
- manifests/crd/v1/pingcap.com_dmclusters.yaml
- manifests/crd/v1beta1/pingcap.com_dmclusters.yaml
- manifests/crd_v1beta1.yaml
- pkg/apis/pingcap/v1alpha1/types.go
ref #4317 and https://github.com/pingcap/tidb-operator/pull/4322#discussion_r774251514
```release-note
None
```
> remove default for DmClusterSpec

- examples/aks/tidb-cluster.yaml
- examples/aws/tidb-cluster.yaml
- examples/gcp/tidb-cluster.yaml
add podAntiAffinity for aws/gcp/aks examples
```release-note
```
> add podAntiAffinity for aws/gcp/aks examples

- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- hack/bump-version.sh
> Bump operator version to v1.2.6

- tests/e2e/util/image/image.go
Closes #4347
```release-note
```
> Update version in E2E

- tests/actions.go
- tests/e2e/e2e_test.go
- tests/e2e/tidbcluster/tidbcluster.go
- tests/e2e/tidbcluster/tls.go
- tests/e2e/tidbngmonitoring/ngm.go
- tests/e2e/util/image/image.go
- tests/e2e/util/ngm/ng_monitoring_client.go
- tests/e2e/util/tidbcluster/tidbcluster.go
- tests/e2e/util/tngm/ng_monitoring_client.go
- tests/e2e/util/tngm/tngm.go
- tests/pkg/fixture/fixture.go
> Add basic e2e for NGM

- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- go.mod
- hack/bump-version.sh
- pkg/client/go.mod
> bump operator version to v1.3.0-beta.1

- tests/e2e/tidbcluster/across-kubernetes.go
1. Address comments in https://github.com/pingcap/tidb-operator/pull/4377#discussion_r788313283
2. refactor e2e test code for faster cluster creation and avoid duplicated code.
```release-note
None
```
> check tikv restart status when pd failed and refactor e2e test code

- docs/api-references/docs.md
- manifests/crd.yaml
- manifests/crd/v1/pingcap.com_tidbclusters.yaml
- manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
- manifests/crd_v1beta1.yaml
- pkg/apis/pingcap/v1alpha1/openapi_generated.go
- pkg/apis/pingcap/v1alpha1/tidbcluster.go
- pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
- pkg/apis/pingcap/v1alpha1/types.go
- pkg/discovery/discovery.go
- pkg/manager/member/pd_member_manager.go
- pkg/manager/member/pump_member_manager.go
- pkg/manager/member/pump_scaler_test.go
- pkg/manager/member/template.go
- pkg/manager/member/template_test.go
- pkg/manager/member/ticdc_member_manager.go
- pkg/manager/member/tidb_discovery_manager.go
- pkg/manager/member/tidb_member_manager.go
- pkg/manager/member/tiflash_member_manager.go
- pkg/manager/member/tiflash_util.go
- pkg/manager/member/tiflash_util_test.go
- pkg/manager/member/tikv_member_manager.go
- tests/e2e/tidbcluster/across-kubernetes.go
* Deploy cluster without PD across Kubernetes
* Deploy cluster across Kubernetes
```release-note
```
> Add new field to decide if tc is deployed across kubernetes

- cmd/backup-manager/app/backup/backup.go
- cmd/backup-manager/app/cmd/backup.go
- cmd/backup-manager/app/cmd/export.go
- cmd/backup-manager/app/cmd/import.go
- cmd/backup-manager/app/cmd/restore.go
- cmd/backup-manager/app/export/export.go
- cmd/backup-manager/app/import/import.go
- cmd/backup-manager/app/util/generic.go
- docs/api-references/docs.md
- manifests/crd.yaml
- manifests/crd/v1/pingcap.com_tidbclusters.yaml
- manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
- manifests/crd_v1beta1.yaml
- pkg/apis/pingcap/v1alpha1/openapi_generated.go
- pkg/apis/pingcap/v1alpha1/types.go
- pkg/backup/backup/backup_manager.go
- pkg/backup/restore/restore_manager.go
- pkg/manager/member/pd_member_manager.go
- pkg/manager/member/pd_member_manager_test.go
- pkg/manager/member/template.go
- pkg/manager/member/template_test.go
- pkg/manager/member/tidb_init_manager.go
- tests/e2e/br/br.go
- tests/e2e/br/framework/framework.go
- tests/e2e/br/utils/tls/manager.go
- tests/e2e/tidbcluster/tidbcluster.go
Support insecure client for internal components
Fix #4251
```release-note
support insecure client for internal components 
```
> support insecure client for internal components

- pkg/controller/pd_control.go
- pkg/discovery/discovery.go
- pkg/manager/member/template.go
- pkg/manager/member/template_test.go
- pkg/manager/member/tidbcluster_status_manager.go
- pkg/manager/member/tiflash_util_test.go
- pkg/pdapi/pd_control.go
- pkg/pdapi/pd_control_test.go
- tests/e2e/br/br.go
- tests/e2e/tidbcluster/across-kubernetes.go
- tests/e2e/tidbcluster/tidbcluster.go
> Use `clusterDomain` just to generate addr and add e2e case

- docs/api-references/docs.md
- manifests/crd.yaml
- manifests/crd/v1/pingcap.com_dmclusters.yaml
- manifests/crd/v1/pingcap.com_tidbclusters.yaml
- manifests/crd/v1/pingcap.com_tidbngmonitorings.yaml
- manifests/crd/v1beta1/pingcap.com_dmclusters.yaml
- manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
- manifests/crd/v1beta1/pingcap.com_tidbngmonitorings.yaml
- manifests/crd_v1beta1.yaml
- pkg/apis/pingcap/v1alpha1/openapi_generated.go
- pkg/apis/pingcap/v1alpha1/tidbcluster_component.go
- pkg/apis/pingcap/v1alpha1/types.go
- pkg/manager/member/dm_master_member_manager.go
- pkg/manager/member/dm_worker_member_manager.go
- pkg/manager/member/pd_member_manager.go
- pkg/manager/member/tidb_member_manager.go
- pkg/manager/member/tiflash_member_manager.go
- pkg/manager/member/tikv_member_manager.go
Add DNSPolicy in spec, unify the dnspolicy in podspec to buildpodspec function.
You can set `DNSPolicy: none` and use `DNSConfig` to modify the pod DNS config.
```release-note
add dnspolicy in spec, unify the dnspolicy in podspec to buildpodspec function.
```
> add dnspolicy in spec, unify the dnspolicy in podspec to buildpodspec function

- charts/tidb-lightning/values.yaml
```release-note
change default backend of lightning from impoter to local
```
> change default backend for lightning

- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- go.mod
- hack/bump-version.sh
- pkg/client/go.mod
> Bump operator version to 1.3.1

- cmd/discovery/main.go
```release-note
Fix an issue that Discovery may be blocked during start
```
> fix(discovery): fix bug that discovery may be blocked when start

- tests/e2e/tidbcluster/serial.go
- tests/e2e/tidbcluster/tidbcluster.go
- tests/e2e/util/image/image.go
- tests/e2e/util/pod/pod.go
upgrade tidb version in e2e
```release-note
None
```
> upgrade tidb version in e2e

- pkg/util/cmpver/cmpver.go
Optimize code.
Change method name.
```release-note
```
> Optimize tiflash compare code

- Makefile
- ci/deploy_tidb_operator_staging.groovy
- ci/pull_e2e_release.groovy
- ci/release-nightly.groovy
- ci/release_tidb_operator_binary_and_image.groovy
- images/tidb-backup-manager/Dockerfile
- images/tidb-backup-manager/Dockerfile.e2e
- images/tidb-operator/Dockerfile
Support multi-arch docker images
```release-note
```
> support multi-arch docker images

- ci/pull_e2e_kind.groovy
refine resource usage of ci jobs to prevent long job queues.
```release-note
```
> chore(ci): refine resource usage of ci jobs

- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- go.mod
- hack/bump-version.sh
- pkg/client/go.mod
> bump operator version to v1.3.2

- images/tidb-backup-manager/Dockerfile
Fix br in arm env
```release-note
```
> fix br in arm env

- pkg/manager/member/tidb_member_manager.go
Fix #4492 
validate `eps.Subsets` field.
```release-note
```
> fix tidb syncInitializer error

- ci/e2e_eks.groovy
- ci/e2e_gke.groovy
- ci/e2e_kind.groovy
- ci/pull_e2e_kind.groovy
- ci/pull_e2e_release.groovy
- ci/release-nightly.groovy
- ci/release_cli_binary_and_debug_image.groovy
- ci/release_tidb_operator_binary_and_image.groovy
- ci/vm.groovy
- hack/e2e.sh
> ci use new cluster

- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- go.mod
- hack/bump-version.sh
- pkg/client/go.mod
> bump operator to v1.3.4

- ci/pull_e2e_kind.groovy
- ci/pull_e2e_release.groovy
> Fix release ci

- ci/deploy_tidb_operator_staging.groovy
- ci/pull_e2e_kind.groovy
- ci/pull_e2e_release.groovy
- ci/release-nightly.groovy
- ci/release_tidb_operator_binary_and_image.groovy
- ci/upload-binaries-charts.sh
> use internal fileserver to save binary and charts

- examples/advanced-statefulset/tidb-cluster.yaml
- examples/advanced/tidb-cluster.yaml
- examples/aks/tidb-cluster.yaml
- examples/auto-scale/tidb-cluster.yaml
- examples/aws/tidb-cluster.yaml
- examples/basic-cn/tidb-cluster.yaml
- examples/basic-random-password/tidb-cluster.yaml
- examples/basic-storagevolumes/tidb-cluster.yaml
- examples/basic-tls/tidb-cluster.yaml
- examples/basic/tidb-cluster.yaml
- examples/gcp/tidb-cluster.yaml
- examples/heterogeneous-tls/tidb-cluster.yaml
- examples/heterogeneous/tidb-cluster.yaml
- examples/initialize/tidb-cluster.yaml
- examples/istio/tidb-cluster.yaml
- examples/monitor-prom-remotewrite/tidb-cluster.yaml
- examples/monitor-shards/tidb-cluster.yaml
- examples/multiple-pv-tikv/tidb-cluster.yaml
- examples/namespaced/tidb-cluster.yaml
- examples/prometheus-operator/tidb-cluster.yaml
- examples/selfsigned-tls/tidb-cluster.yaml
- examples/tiflash/tidb-cluster.yaml
- examples/tngm/tidb-cluster.yaml
- tests/e2e/util/image/image.go
- tests/pkg/fixture/fixture.go
> Use alpine:3.16.0 as helper image

- cmd/backup-manager/app/backup/backup.go
- cmd/backup-manager/app/restore/restore.go
- docs/api-references/docs.md
- examples/advanced/backup.yaml
- examples/advanced/restore.yaml
- manifests/crd.yaml
- manifests/crd/v1/pingcap.com_backups.yaml
- manifests/crd/v1/pingcap.com_backupschedules.yaml
- manifests/crd/v1/pingcap.com_restores.yaml
- manifests/crd/v1beta1/pingcap.com_backups.yaml
- manifests/crd/v1beta1/pingcap.com_backupschedules.yaml
- manifests/crd/v1beta1/pingcap.com_restores.yaml
- manifests/crd_v1beta1.yaml
- pkg/apis/pingcap/v1alpha1/openapi_generated.go
- pkg/apis/pingcap/v1alpha1/types.go
- pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
Ref [doc](https://docs.pingcap.com/tidb/stable/backup-and-restore-faq#why-does-br-report-new_collations_enabled_on_first_bootstrap-mismatch), if we want to  back up the data in a TiDB cluster of an earlier version of v6.0.0, and restore this data to a TiDB cluster of v6.0.0 or later versions, we must support the arg
```release-note
Support to set `--check-requirements` arg for BR
```
> Support to set `--check-requirements` arg for BR

- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- examples/podpatch/tidb-cluster.yaml
- examples/podpatch/tidb-monitor.yaml
- go.mod
- hack/bump-version.sh
- pkg/client/go.mod
> bump operator to v1.3.8

- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- go.mod
- hack/bump-version.sh
- pkg/client/go.mod
> bump operator to v1.3.8 for release 1.3

- ci/pull_e2e_release.groovy
- ci/release_cli_binary_and_debug_image.groovy
Close #4708 
Replay CI to test
```release-note
```
> upgrade go to 1.16 for release

- .github/workflows/ci.yaml
Fix the issue in the `e2e-example` workflow
```release-note
```
> upgrade ubuntu to 22.04 for workflow

- misc/images/tidb-debug/Dockerfile
> Fix tidb-debug image build

- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- go.mod
- hack/bump-version.sh
- pkg/client/go.mod
> bump operator to v1.3.9

- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- go.mod
- hack/bump-version.sh
- pkg/client/go.mod
> bump operator to 1.4.0-alpha.2

- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- go.mod
- hack/bump-version.sh
- pkg/client/go.mod
ref #4755 
```release-note
NONE
```
> bump operator to 1.4.0-beta.1

- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- go.mod
- hack/bump-version.sh
- pkg/client/go.mod
Ref #4775
```release-note
None
```
> bump operator to 1.4.0-beta.2

- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- go.mod
- hack/bump-version.sh
- pkg/client/go.mod
Signed-off-by: xhe <xw897002528@gmail.com>
Mark a new version supporting tiproxy for QA test-infra.
```release-note
```
> bump operator to 1.4.0-beta.3

- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- go.mod
- hack/bump-version.sh
- pkg/client/go.mod
> bump operator to 1.4.0-beta.4

- examples/basic-tls/tidb-dashboard.yaml
- pkg/manager/tidbdashboard/manager.go
> Fix mysql client cert parameters

- examples/aks/tidb-dashboard.yaml
- examples/aws/tidb-dashboard.yaml
- examples/basic-cn/tidb-dashboard.yaml
- examples/basic/tidb-dashboard.yaml
- examples/gcp/tidb-dashboard.yaml
> Fix example tidb-dashboard image

- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- go.mod
- hack/bump-version.sh
- pkg/client/go.mod
bump TiDB Operator to v1.4.1, but without bump for TiDB and Tools as no new version released.
```release-note
```
> bump operator to v1.4.1

- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- go.mod
- hack/bump-version.sh
- pkg/client/go.mod
> bump operator version to v1.4.2

- Makefile
- images/tidb-operator/Dockerfile.new
- pkg/apis/pingcap/v1alpha1/tidbcluster.go
- pkg/manager/member/tidb_member_manager.go
- pkg/monitor/monitor/template.go
- pkg/monitor/monitor/template_test.go
Signed-off-by: xhe <xw897002528@gmail.com>
1. A util function for tidbcloud.
2. Automatically set session token(used by tiproxy&tidb) if tiproxy and tls is avaiable. One can still set session token manually if TLS is not enabled.
3. Prometheus fixes for tiproxy
4. A new dockerfile using buildx
```release-note
Automatically enable load-balance for tidb if TLS and tiproxy are enabled
```
> manager: better tiproxy experience

- go.mod
- go.sum
- hack/lib.sh
- pkg/apis/go.mod
- pkg/apis/go.sum
- pkg/client/clientset/versioned/fake/register.go
- pkg/client/clientset/versioned/scheme/register.go
- pkg/client/go.mod
- pkg/client/go.sum
- tests/images/kubekins-e2e/Dockerfile
> Upgrade go version to 1.19

- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- go.mod
- hack/bump-version.sh
- pkg/client/go.mod
> bump operator version to 1.3.10

- Makefile
- hack/localtest/test.sh
- pkg/backup/backup/backup_manager.go
- pkg/backup/restore/restore_manager.go
- pkg/controller/tiproxy_control.go
- pkg/manager/member/pd_member_manager.go
- pkg/manager/member/tidb_init_manager.go
- pkg/manager/member/tiproxy_member_manager.go
- pkg/manager/tidbdashboard/tc_tls_manager.go
- pkg/monitor/monitor/template.go
- pkg/monitor/monitor/template_test.go
- pkg/util/util.go
- pkg/util/utils_test.go
- tests/e2e/br/utils/tls/manager.go
- tests/e2e/tidbcluster/tls.go
1. Correctly set tiproxy certs for new tiproxy version. It is set to tidb certs directly to share same certs as tidb to conform components using tidb certs to connect tiproxy. It also simplifies the configruation of tiproxy, now, no need for configs of tiproxy TLS by default.
2. Use `TiDBClientTLSSecretName(tc.Name, xx)` to simply if statement
```release-note
share same certs for TiProxy and TiDB
```
> manager: fix TLS certs for tiproxy

- ci/pull_e2e_kind.groovy
- ci/pull_e2e_release.groovy
> Fix the issue failed to checkout repo in CI 

- hack/localtest/operator.yaml
- hack/localtest/test.sh
- pkg/apis/label/label.go
- pkg/apis/pingcap/v1alpha1/tidbcluster.go
- pkg/apis/pingcap/v1alpha1/validation/validation.go
- pkg/manager/member/tiproxy_scaler.go
- pkg/manager/member/utils.go
- pkg/upgrader/upgrader.go
- pkg/util/util.go
1. no PVC for tiproxy
2. fix delete-slots scaling
```release-note
Fix tiproxy with advanced statefulset controller
```
> manager: fix tiproxy scale & delete-slots

- docs/api-references/docs.md
- manifests/crd.yaml
- manifests/crd/v1/pingcap.com_backups.yaml
- manifests/crd/v1/pingcap.com_backupschedules.yaml
- manifests/crd/v1beta1/pingcap.com_backups.yaml
- manifests/crd/v1beta1/pingcap.com_backupschedules.yaml
- manifests/crd_v1beta1.yaml
- pkg/apis/pingcap/v1alpha1/types.go
- pkg/backup/util/util.go
- pkg/controller/backup/backup_controller.go
- tests/e2e/br/br.go
Ref https://github.com/pingcap/tidb-operator/issues/4805
To simplify users' consideration of time units, it change `MinRetryDuration` and `RetryTimeout` to format duration string, ref https://golang.org/pkg/time/#ParseDuration.
```release-note
```
> br: refine BackoffRetryPolicy time format

- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- go.mod
- hack/bump-version.sh
- pkg/client/go.mod
> bump operator version to 1.4.4

- images/tidb-backup-manager/Dockerfile
- images/tidb-backup-manager/Dockerfile.e2e
Fix panic issue caused by missing dependencies when calling br.
```
/ # /var/lib/br-bin/br
Error loading shared library libresolv.so.2: No such file or directory (needed by /var/lib/br-bin/br)
```
```release-note
none
```
> br: fix dockerfile base

- README.md
- docs/CONTRIBUTING.md
- hack/lib.sh
> *: refine Development Guide

- hack/run-in-container.sh
update `kubekins-e2e:v5-go1.19` in `run-in-container.sh` to docker hub so that external users can pull it.
NOTE: CI Jenkins pipelines are still use `hub-new.pingcap.net` to avoid docker hub rate limit.
```release-note
```
> ci: update e2e image for docker hub

- go.mod
- go.sum
- pkg/client/go.mod
- pkg/client/go.sum
bump 
- `golang.org/x/crypto`
- `github.com/prometheus/client_golang`
```release-note
```
> bump go mod for CVE fix

- manifests/crd.yaml
- manifests/crd/v1/pingcap.com_backupschedules.yaml
- manifests/crd/v1beta1/pingcap.com_backupschedules.yaml
- manifests/crd_v1beta1.yaml
- pkg/apis/pingcap/v1alpha1/types.go
close https://github.com/pingcap/tidb-operator/issues/4955
as title
```release-note
none
```
> backup: make LogBackupTemplate optional

- docs/api-references/docs.md
- pkg/apis/pingcap/v1alpha1/openapi_generated.go
releatd to https://github.com/pingcap/tidb-operator/issues/4955
fix broken verify ci
```release-note
none
```
> *: fix br openapi generated field

- docs/api-references/docs.md
- manifests/crd.yaml
- manifests/crd/v1/pingcap.com_backupschedules.yaml
- manifests/crd/v1beta1/pingcap.com_backupschedules.yaml
- manifests/crd_v1beta1.yaml
- pkg/apis/pingcap/v1alpha1/openapi_generated.go
- pkg/apis/pingcap/v1alpha1/types.go
- pkg/backup/backupschedule/backup_schedule_manager.go
cherry-pick:
* https://github.com/pingcap/tidb-operator/pull/4940
* https://github.com/pingcap/tidb-operator/pull/4965
* https://github.com/pingcap/tidb-operator/pull/4956
```release-note
```
> br: cp some bugfix to release-1.4

- docs/api-references/docs.md
- manifests/crd.yaml
- manifests/crd/v1/pingcap.com_dmclusters.yaml
- manifests/crd/v1/pingcap.com_tidbdashboards.yaml
- manifests/crd/v1/pingcap.com_tidbmonitors.yaml
- manifests/crd/v1/pingcap.com_tidbngmonitorings.yaml
- manifests/crd/v1beta1/pingcap.com_dmclusters.yaml
- manifests/crd/v1beta1/pingcap.com_tidbdashboards.yaml
- manifests/crd/v1beta1/pingcap.com_tidbmonitors.yaml
- manifests/crd/v1beta1/pingcap.com_tidbngmonitorings.yaml
- manifests/crd_v1beta1.yaml
- pkg/apis/pingcap/v1alpha1/openapi_generated.go
- pkg/apis/pingcap/v1alpha1/tidbdashboard_types.go
- pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
- pkg/apis/pingcap/v1alpha1/tidbngmonitoring_types.go
- pkg/apis/pingcap/v1alpha1/types.go
- pkg/manager/member/dm_master_member_manager.go
- pkg/manager/member/dm_worker_member_manager.go
- pkg/manager/member/tidb_discovery_manager.go
- pkg/manager/tidbdashboard/manager.go
- pkg/manager/tidbngmonitoring/ng_monitoring_manager.go
- pkg/monitor/monitor/util.go
Deploy cluster and components, and check all services are set with `ipFamilyPolicy: PreferDualStack`.
```release-note
```
> Add a field `preferIPv6` for DM, TD, TM, TNGM

- ci/pull_e2e_kind.groovy
> increase E2E pod storage

- ci/pull_e2e_kind.groovy
> increase E2E pod resources

- manifests/crd.yaml
- manifests/crd/v1/pingcap.com_tidbclusters.yaml
- manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
- manifests/crd_v1beta1.yaml
- pkg/apis/pingcap/v1alpha1/types.go
fix
Fix `pkg/apis/pingcap/v1alpha1/types.go` code description
Change description
```release-note
Fix TiDB Operator printcolumn description
```
> Update apis/types.go printcolumn description

- tests/e2e/tidbcluster/serial.go
bump operation version in serial tests to match the current versions
```release-note
```
> bump operator version in serial tests

- docs/api-references/docs.md
- manifests/crd.yaml
- manifests/crd/v1/pingcap.com_tidbclusters.yaml
- manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
- manifests/crd_v1beta1.yaml
- pkg/apis/pingcap/v1alpha1/openapi_generated.go
- pkg/apis/pingcap/v1alpha1/types.go
- pkg/manager/member/tiproxy_member_manager.go
This PR adds another higher priority option to enable/disable tiproxy TLS.
```release-note
```
> tiproxy: enable SSL by default

- charts/br-federation/values.yaml
- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- go.mod
- hack/bump-version.sh
- pkg/client/go.mod
> bump operator version to 1.6.0-alpha.1

- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- go.mod
- hack/bump-version.sh
- pkg/client/go.mod
> Bump operator version to 1.4.5

- charts/br-federation/values.yaml
- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- go.mod
- hack/bump-version.sh
- pkg/client/go.mod
> bump operator version to 1.6.0-alpha.2

- charts/br-federation/values.yaml
- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- go.mod
- hack/bump-version.sh
- pkg/apis/pingcap/v1alpha1/component_spec.go
- pkg/client/go.mod
> bump operator version to 1.6.0-alpha.3 

- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- go.mod
- hack/bump-version.sh
- pkg/client/go.mod
> bump operator to v1.4.6

- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- go.mod
- hack/bump-version.sh
- pkg/client/go.mod
> bump operator to v1.4.7

- charts/br-federation/values.yaml
- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- go.mod
- hack/bump-version.sh
- pkg/client/go.mod
> bump to v1.6.0-alpha.6

- manifests/crd/federation/v1beta1/federation.pingcap.com_volumerestores.yaml
- manifests/crd/v1beta1/pingcap.com_restores.yaml
- manifests/crd_v1beta1.yaml
- manifests/federation-crd_v1beta1.yaml
> br: add manifests of v1beta1

- charts/br-federation/values.yaml
- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- go.mod
- hack/bump-version.sh
- pkg/client/go.mod
> bump to v1.6.0-alpha.7

- pkg/manager/member/tiproxy_scaler.go
> typo: Update tiproxy_scaler.go

- pkg/controller/tidbcluster/tidb_cluster_control.go
> fix: spec_replicas metric add tiproxy

- cmd/http-service/server/cluster.go
init username and password via TidbInitializer CR
```release-note
```
> http-service: init username and password

- cmd/http-service/main.go
before this fix, the application will not exit when port conflicting:
```
[2023/10/09 06:11:41.023 +00:00] [INFO] [main.go:149] ["The gRPC gateway returned with error"] [addr=0.0.0.0:3000] [error="listen tcp 0.0.0.0:3000: bind: address already in use"]
```
after this fix:
```
[2023/10/09 07:55:37.352 +00:00] [FATAL] [main.go:140] ["Failed to listen for gRPC gateway"] [addr=0.0.0.0:3000] [error="listen tcp 0.0.0.0:3000: bind: address already in use"] [stack="main.setupAndRunGRPCGateway\n\t/home/ubuntu/go/src/github.com/csuzhangxc/tidb-operator/cmd/http-service/main.go:140\nmain.main.func2\n\t/home/ubuntu/go/src/github.com/csuzhangxc/tidb-operator/cmd/http-service/main.go:93"]
```
Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/r …
> http: split gateway listen and serve

- cmd/http-service/server/cluster.go
before
```json
{
"profiles": {
"default": {
"max_memory_usage_for_all_queries": 0.9
}
}
}
```
after
```json
{
"profiles.default.max_memory_usage_for_all_queries": 0.9
}
```
```release-note
```
> http-service: flatten config map to single layer

- charts/br-federation/values.yaml
- charts/tidb-cluster/values.yaml
- charts/tidb-operator/values.yaml
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- go.mod
- hack/bump-version.sh
- pkg/client/go.mod
> bump TiDB Operator to 1.5.1

- cmd/http-service/server/cluster.go
When deleting the cluster, the TidbCluster CR may disappear, but the Pods and PVCs are still in deleting phase.
Return the `deleting` status for the cluster instead of "not found"
```release-note
```
> http-service: return deleting for get-cluster if pods/pvcs exist

- cmd/http-service/server/cluster.go
> http-service: delete restores when deleting the cluster

- images/tidb-backup-manager/e2e-entrypoint.sh
- images/tidb-backup-manager/entrypoint.sh
Fix backup pod error due to creating file error
Closes #5468 
```release-note
```
> br: fix file creating error due to directory not exists

- images/ebs-warmup/warmup-steps.sh
Closes #5468 
```release-note
```
> br: fix warmup tmp file creating error

- charts/br-federation/values.yaml
- charts/tidb-operator/values.yaml
- cmd/http-service/go.mod
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- go.mod
- hack/bump-version.sh
- pkg/client/go.mod
> bump operator to v1.6.0-alpha.10

- examples/basic/pd-micro-service-cluster.yaml
- tests/pkg/fixture/fixture.go
> pdms: replace pd image

- docs/api-references/docs.md
- examples/initialize/tidb-initializer.yaml
- manifests/crd.yaml
- manifests/crd/v1/pingcap.com_tidbinitializers.yaml
- manifests/federation-crd.yaml
- pkg/apis/pingcap/v1alpha1/openapi_generated.go
- pkg/apis/pingcap/v1alpha1/tidbinitializer_types.go
- pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
- pkg/manager/member/tidb_init_manager.go
add `nodeSelector` support for TidbInitializer Pod
```yaml
kind: TidbInitializer
spec:
nodeSelector:
kubernetes.io/hostname: kind-control-plane
```
```yaml
apiVersion: v1
kind: Pod
spec:
nodeSelector:
kubernetes.io/hostname: kind-control-plane
```
```release-note
```
> add nodeSelector support for TidbInitializer Pod

- hack/lib.sh
- hack/update-crd.sh
- manifests/crd.yaml
- manifests/crd/federation/v1/federation.pingcap.com_volumebackups.yaml
- manifests/crd/federation/v1/federation.pingcap.com_volumebackupschedules.yaml
- manifests/crd/federation/v1/federation.pingcap.com_volumerestores.yaml
- manifests/crd/v1/pingcap.com_backups.yaml
- manifests/crd/v1/pingcap.com_backupschedules.yaml
- manifests/crd/v1/pingcap.com_dmclusters.yaml
- manifests/crd/v1/pingcap.com_restores.yaml
- manifests/crd/v1/pingcap.com_tidbclusterautoscalers.yaml
- manifests/crd/v1/pingcap.com_tidbclusters.yaml
- manifests/crd/v1/pingcap.com_tidbdashboards.yaml
- manifests/crd/v1/pingcap.com_tidbinitializers.yaml
- manifests/crd/v1/pingcap.com_tidbmonitors.yaml
- manifests/crd/v1/pingcap.com_tidbngmonitorings.yaml
- manifests/federation-crd.yaml
part of #5683
```release-note
```
> bump controller-gen to v0.15.0

- docs/api-references/docs.md
- manifests/crd.yaml
- manifests/crd/v1/pingcap.com_tidbclusters.yaml
- pkg/apis/pingcap/v1alpha1/openapi_generated.go
- pkg/apis/pingcap/v1alpha1/tidbcluster.go
- pkg/apis/pingcap/v1alpha1/types.go
- pkg/manager/member/startscript/v2/pd_start_script.go
- pkg/manager/member/startscript/v2/pd_start_script_with_wait_for_ip_match_test.go
> [PD] add option to wait a certain time before start pd

- cmd/http-service/Dockerfile
- images/br-federation-manager/Dockerfile
- images/br-federation-manager/Dockerfile.e2e
- images/tidb-backup-manager/Dockerfile
- images/tidb-backup-manager/Dockerfile.e2e
- images/tidb-operator/Dockerfile
- images/tidb-operator/Dockerfile.e2e
- use the latest secure base image
- use the official registry which the image will auto published to.
- use the detail tag to make it reproducible.
```release-note
```
> fix(deps): update docker image of pingcap base to v1.9.1

- examples/backup/backup-azblob.yaml
- examples/backup/backup-ebs-local.yaml
- examples/backup/backup-ebs-minio.yaml
- examples/backup/backup-local.yaml
- examples/backup/backup-nfs.yaml
- examples/backup/backup-schedule-azblob.yaml
- examples/backup/backup-schedule-nfs.yaml
- examples/backup/restore-azblob.yaml
- examples/backup/restore-ebs-minio.yaml
- examples/backup/restore-local.yaml
- examples/backup/restore-nfs.yaml
- manifests/backup/backup-aws-s3-br.yaml
- manifests/backup/backup-gcs-br.yaml
- manifests/backup/backup-s3-br.yaml
- manifests/backup/backup-schedule-aws-s3-br.yaml
- manifests/backup/backup-schedule-gcs-br.yaml
- manifests/backup/backup-schedule-s3-br.yaml
- manifests/backup/restore-aws-s3-br.yaml
- manifests/backup/restore-gcs-br.yaml
- manifests/backup/restore-s3-br.yaml
remove `spec.from` for BR backup and `.spec.to` for BR restore as they are not recommended to use for a long time.
ref https://github.com/pingcap/docs-tidb-operator/pull/2614
```release-note
```
> chore: remove spec.from for Backup and spec.to for Restore in example

- cmd/br-federation-manager/main.go
- cmd/controller-manager/main.go
- pkg/controller/autoscaler/tidbcluster_autoscaler_controller.go
- pkg/controller/backup/backup_controller.go
- pkg/controller/backupschedule/backup_schedule_controller.go
- pkg/controller/dmcluster/dm_cluster_controller.go
- pkg/controller/fedvolumebackup/fed_volume_backup_controller.go
- pkg/controller/fedvolumebackupschedule/fed_volume_backup_schedule_controller.go
- pkg/controller/fedvolumerestore/fed_volume_restore_controller.go
- pkg/controller/restore/restore_controller.go
- pkg/controller/tidbcluster/pod_control.go
- pkg/controller/tidbcluster/tidb_cluster_controller.go
- pkg/controller/tidbdashboard/tidb_dashboard_controller.go
- pkg/controller/tidbinitializer/tidb_initializer_controller.go
- pkg/controller/tidbmonitor/tidb_monitor_controller.go
- pkg/controller/tidbngmonitoring/tidb_ng_monitoring_controller.go
- pkg/metrics/metrics.go
closes #5737
```release-note
```
> chore: Add missing operator metrics

- ci/pull_e2e_kind.groovy
> ci: unset GOSUMDB for "Debug Info"

- ci/pull_e2e_kind.groovy
> ci: unset GOSUMDB for "Run"

- docs/api-references/docs.md
- manifests/crd/v1/pingcap.com_tidbclusters.yaml
- pkg/apis/pingcap/v1alpha1/openapi_generated.go
- pkg/apis/pingcap/v1alpha1/types.go
- pkg/manager/member/ticdc_member_manager.go
Reverts pingcap/tidb-operator#5778
> Revert "opt(ticdc): support to overwrite the default cluster TLS cert secret name"

- manifests/crd.yaml
- manifests/federation-crd.yaml
Regenerate manifest files
Run command `make generate crd api-references`
```release-note
```
> Regenerate CRD files

- manifests/backup/backup-aws-s3-br.yaml
- manifests/backup/backup-gcs-br.yaml
- manifests/backup/backup-s3-br.yaml
- manifests/backup/backup-schedule-aws-s3-br.yaml
- manifests/backup/backup-schedule-gcs-br.yaml
- manifests/backup/backup-schedule-s3-br.yaml
- manifests/backup/restore-aws-s3-br.yaml
- manifests/backup/restore-gcs-br.yaml
- manifests/backup/restore-s3-br.yaml
Fix typo in backup manifests.
```release-note
NONE
```
> fix typo in backup manifests

- .github/workflows/ci.yaml
- .github/workflows/e2e.yaml
> chore(ci): use GitHub hosted runner to run actions

- .github/workflows/ci-v2.yaml
- .github/workflows/ci.yaml
- Makefile
> chore: upload coverage to codecov

- pkg/image/image.go
- pkg/image/image_test.go
Improve ut coverage of `pkg/image`
> chore(image): add more ut cases and comments

- tests/images/kubekins-e2e/Dockerfile
> chore: install buildx for e2e image and bump Golang version

- .github/renovate.json
> chore: enable renovate for feature/v2

- examples/basic/pd-micro-service-cluster.yaml
> fix: remove namespace in PD MS example

- apis/core/v1alpha1/cluster_types.go
- apis/core/v1alpha1/pd_types.go
- manifests/crd/core.pingcap.com_clusters.yaml
- manifests/crd/core.pingcap.com_pdgroups.yaml
- pkg/controllers/pd/tasks/pod.go
- pkg/controllers/pd/tasks/pod_test.go
- tests/e2e/pd/pd.go
> opt: skip transfer leader if only one PD; update some CRD comments

- pkg/controllers/common/revision.go
- pkg/controllers/common/revision_test.go
- pkg/controllers/tidbgroup/tasks/state_test.go
- pkg/controllers/tiflashgroup/tasks/state_test.go
- pkg/utils/k8s/revision/controller_revision.go
- pkg/utils/k8s/revision/controller_revision_test.go
- third_party/kubernetes/pkg/controller/history/controller_history.go
- fix bug of https://github.com/pingcap/tidb-operator/pull/6045
> fix(group): fix missing component in controller revision name

- .github/workflows/auto-job-v2.yaml
> chore: add v2 Label and E2E trigger comment automatically

- .github/workflows/auto-job-v2.yaml
See https://github.com/actions/labeler?tab=readme-ov-file#recommended-permissions
> fix ci workflow

- pkg/utils/integer_test.go
> Fix: add missing license header

- cmd/operator/main.go
- pkg/client/client.go
- pkg/scheme/scheme.go
- pkg/utils/kubefeat/gates.go
- fix error when VolumeAttributeClass is not enabled
> fix(client): fix new client error if VolumeAttributeClass is not enabled

- pkg/apiutil/core/v1alpha1/group.go
- pkg/apiutil/core/v1alpha1/object.go
- pkg/controllers/common/resource_test.go
- pkg/controllers/common/task.go
- pkg/controllers/common/task_test.go
- pkg/controllers/pd/builder.go
- pkg/controllers/pd/tasks/state.go
- pkg/controllers/pd/tasks/state_test.go
- pkg/controllers/pdgroup/builder.go
- pkg/controllers/pdgroup/tasks/state.go
- pkg/controllers/pdgroup/tasks/state_test.go
- pkg/controllers/tidb/builder.go
- pkg/controllers/tidb/tasks/state.go
- pkg/controllers/tidb/tasks/state_test.go
- pkg/controllers/tidbgroup/builder.go
- pkg/controllers/tidbgroup/tasks/state.go
- pkg/controllers/tidbgroup/tasks/state_test.go
- pkg/controllers/tiflash/builder.go
- pkg/controllers/tiflash/tasks/state.go
- pkg/controllers/tiflash/tasks/state_test.go
- pkg/controllers/tiflashgroup/builder.go
- pkg/controllers/tiflashgroup/tasks/state.go
- pkg/controllers/tiflashgroup/tasks/state_test.go
- pkg/controllers/tikv/builder.go
- pkg/controllers/tikv/tasks/state.go
- pkg/controllers/tikv/tasks/state_test.go
- pkg/controllers/tikvgroup/builder.go
- pkg/controllers/tikvgroup/tasks/state.go
- pkg/controllers/tikvgroup/tasks/state_test.go
> refactor(tasks): simplify context cluster task

- Makefile
- cmd/prestop-checker/main.go
- examples/basic/01-pd.yaml
- examples/basic/02-tikv.yaml
- pkg/apicall/cluster.go
- pkg/apicall/group.go
- pkg/apicall/instance.go
- pkg/apiutil/core/v1alpha1/tikv.go
- pkg/configs/tikv/config.go
- pkg/controllers/common/task.go
- pkg/controllers/tikv/handler.go
- pkg/controllers/tikv/tasks/ctx.go
- pkg/controllers/tikv/tasks/pod.go
- pkg/controllers/tikv/tasks/pod_test.go
- pkg/runtime/scope/pd.go
- pkg/runtime/scope/scope.go
- pkg/runtime/scope/ticdc.go
- pkg/runtime/scope/tidb.go
- pkg/runtime/scope/tiflash.go
- pkg/runtime/scope/tikv.go
- tests/e2e/data/cluster.go
- tests/e2e/framework/framework.go
- tests/e2e/framework/tikv.go
- tests/e2e/framework/util.go
- tests/e2e/framework/workload.go
- tests/e2e/label/well_known.go
- tests/e2e/pd/pd.go
- tests/e2e/tikv/tikv.go
- tests/e2e/tikv/topology.go
- tests/e2e/utils/cert/cert.go
- fix prestop hook of tikv
- add e2e case of prestop hook
> fix(prestop): fix prestop hook of tikv

- api/core/v1alpha1/pd_types.go
- api/core/v1alpha1/ticdc_types.go
- api/core/v1alpha1/tidb_types.go
- api/core/v1alpha1/tiflash_types.go
- api/core/v1alpha1/tikv_types.go
- manifests/crd/core.pingcap.com_pdgroups.yaml
- manifests/crd/core.pingcap.com_pds.yaml
- manifests/crd/core.pingcap.com_ticdcgroups.yaml
- manifests/crd/core.pingcap.com_ticdcs.yaml
- manifests/crd/core.pingcap.com_tidbgroups.yaml
- manifests/crd/core.pingcap.com_tidbs.yaml
- manifests/crd/core.pingcap.com_tiflashes.yaml
- manifests/crd/core.pingcap.com_tiflashgroups.yaml
- manifests/crd/core.pingcap.com_tikvgroups.yaml
- manifests/crd/core.pingcap.com_tikvs.yaml
- support `kubectl get tc`
- support `kubectl get group`
- support `kubectl get instance`
- support `kubectl get pd kv flash db cdc`
- add more fields for crds
> feat(crd): optimize display of crds

- api/core/v1alpha1/pd_types.go
- api/core/v1alpha1/ticdc_types.go
- api/core/v1alpha1/tidb_types.go
- api/core/v1alpha1/tiflash_types.go
- api/core/v1alpha1/tikv_types.go
- manifests/crd/core.pingcap.com_pdgroups.yaml
- manifests/crd/core.pingcap.com_pds.yaml
- manifests/crd/core.pingcap.com_ticdcgroups.yaml
- manifests/crd/core.pingcap.com_ticdcs.yaml
- manifests/crd/core.pingcap.com_tidbgroups.yaml
- manifests/crd/core.pingcap.com_tidbs.yaml
- manifests/crd/core.pingcap.com_tiflashes.yaml
- manifests/crd/core.pingcap.com_tiflashgroups.yaml
- manifests/crd/core.pingcap.com_tikvgroups.yaml
- manifests/crd/core.pingcap.com_tikvs.yaml
- remove group+instance categories to avoid conflicts with instance name
- add shortNames for groups
> feat(crd): remove group+instance categories and add shortName for group

- pkg/ticdcapi/v1/client.go
- fix tls error of ticdc client
> fix(ticdc): fix tls bug

- Makefile
- api/core/v1alpha1/pd_types.go
- api/core/v1alpha1/ticdc_types.go
- api/core/v1alpha1/tidb_types.go
- api/core/v1alpha1/tiflash_types.go
- api/core/v1alpha1/tikv_types.go
- cmd/crd-modifier/main.go
- go.mod
- manifests/crd/core.pingcap.com_pdgroups.yaml
- manifests/crd/core.pingcap.com_pds.yaml
- manifests/crd/core.pingcap.com_ticdcgroups.yaml
- manifests/crd/core.pingcap.com_ticdcs.yaml
- manifests/crd/core.pingcap.com_tidbgroups.yaml
- manifests/crd/core.pingcap.com_tidbs.yaml
- manifests/crd/core.pingcap.com_tiflashes.yaml
- manifests/crd/core.pingcap.com_tiflashgroups.yaml
- manifests/crd/core.pingcap.com_tikvgroups.yaml
- manifests/crd/core.pingcap.com_tikvs.yaml
- tests/validation/crd/core.pingcap.com_pdgroups.yaml
- tests/validation/crd/core.pingcap.com_pds.yaml
- tests/validation/crd/core.pingcap.com_ticdcgroups.yaml
- tests/validation/crd/core.pingcap.com_ticdcs.yaml
- tests/validation/crd/core.pingcap.com_tidbgroups.yaml
- tests/validation/crd/core.pingcap.com_tidbs.yaml
- tests/validation/crd/core.pingcap.com_tiflashes.yaml
- tests/validation/crd/core.pingcap.com_tiflashgroups.yaml
- tests/validation/crd/core.pingcap.com_tikvgroups.yaml
- tests/validation/crd/core.pingcap.com_tikvs.yaml
- add a crd modifier tools to remove unused required constraints
- remove `+kubebuilder:validation:Schemaless`
- remove `+kubebuilder:pruning:PreserveUnknownFields`
> feat(crd): remove unused required constraints of overlay from crd

- cmd/operator/main.go
- pkg/client/client.go
- force apply unmanaged fields
- use same field manager for apply and update
> fix(client): use same field manager and force apply unmanaged fields

- pkg/controllers/ticdc/tasks/pod.go
> fix(cdc): retry when waiting for capture to be drained

- pkg/controllers/pd/tasks/pvc.go
- pkg/controllers/pd/tasks/pvc_test.go
- pkg/controllers/ticdc/tasks/pvc.go
- pkg/controllers/ticdc/tasks/pvc_test.go
- pkg/controllers/tidb/tasks/pvc.go
- pkg/controllers/tidb/tasks/pvc_test.go
- pkg/controllers/tiflash/tasks/pvc.go
- pkg/controllers/tiflash/tasks/pvc_test.go
- pkg/controllers/tikv/tasks/pvc.go
- pkg/controllers/tikv/tasks/pvc_test.go
- pkg/overlay/overlay.go
- pkg/reloadable/common.go
- support overlay pvc labels and annotations
> feat(pvc): support overlay pvc labels and annotations

- api/core/v1alpha1/tidb_types.go
- manifests/crd/core.pingcap.com_tidbgroups.yaml
- manifests/crd/core.pingcap.com_tidbs.yaml
- pkg/apiutil/core/v1alpha1/tidb.go
- pkg/configs/tidb/config_test.go
> feat(tidb): disable slowlog by default

- pkg/controllers/tidb/tasks/pod.go
- pkg/runtime/pd.go
- pkg/runtime/ticdc.go
- pkg/runtime/tidb.go
- pkg/runtime/tiflash.go
- pkg/runtime/tikv.go
- check generation when call `IsReady`
> fix(status): check generation when call IsReady

- pkg/client/client.go
- pkg/client/converter.go
- tests/e2e/cluster/cluster.go
- tests/e2e/data/tidb.go
- tests/e2e/label/well_known.go
- tests/e2e/tidb/tidb.go
- third_party/kube-openapi/pkg/util/proto/document_v3.go
- fix unexpected null creationTimestamp in spec when extracting
> fix(client): fix unexpected null creationTimestamp

- pkg/timanager/pd/pd.go
- pkg/timanager/poller.go
> fix(log): fix missing logger in timanager

- Makefile
- docs/CONTRIBUTING.md
- docs/arch/README.md
- docs/convention.md
- docs/rfcs/000000-template.md
- docs/rfcs/250424-pdms.md
- docs/why.md
- add rfc template
- add pdms design doc
- add `make doc` directive
> doc(pdms): add pdms design doc and rfc template

- pkg/controllers/common/cond.go
- pkg/controllers/common/cond_test.go
- pkg/controllers/scheduler/builder.go
- pkg/controllers/ticdc/builder.go
- pkg/controllers/tidb/builder.go
- pkg/controllers/tiflash/builder.go
- pkg/controllers/tikv/builder.go
- pkg/controllers/tso/builder.go
- PD addr in cluster status may be empty and instance controller may generate unexpected pod and cm.
> fix(instance): wait until pd addr is registered into cluster status

- pkg/controllers/tidbgroup/tasks/updater.go
- pkg/updater/actor.go
- pkg/updater/builder.go
- pkg/utils/topology/scheduler_test.go
- tests/e2e/framework/framework.go
- tests/e2e/framework/tidb.go
- tests/e2e/tidb/topology.go
- tests/e2e/utils/waiter/pod.go
- use scale in/out operations to replace update for TiDB
- update cannot resolve some cases of evenly spread AZs
Fixes https://github.com/pingcap/tidb-operator/issues/6136
> fix(updater): support scale in/out to replace update

- pkg/controllers/br/manager/backup/backup_cleaner.go
- pkg/controllers/br/manager/backup/backup_manager.go
- pkg/controllers/br/manager/constants/constants.go
- pkg/controllers/br/manager/restore/restore_manager.go
- pkg/controllers/br/manager/util/util.go
- fix gcs credentials issue of br 
Fix https://github.com/pingcap/tidb-operator/issues/6207
> fix(br): mount gcp credentials directly into br jobs

- pkg/controllers/pd/handler.go
- pkg/controllers/pd/tasks/ctx.go
- Log the health field for PD.
> feat(pd): add log for pd

- examples/advanced-statefulset/tidb-cluster.yaml
- examples/advanced/tidb-cluster.yaml
- examples/aks/tidb-cluster.yaml
- examples/aws/tidb-cluster.yaml
- examples/gcp/tidb-cluster.yaml
- examples/heterogeneous-tls/tidb-cluster.yaml
- examples/heterogeneous/tidb-cluster.yaml
- examples/tiflash/tidb-cluster.yaml
https://tidb.atlassian.net/jira/servicedesk/projects/APID/queues/custom/1/TCID-11636
guide customer configure tikv `max-days` and `max-backups`
```release-note
```
> add-tikv-config

- docs/api-references/docs.md
- manifests/crd.yaml
- manifests/crd/v1/pingcap.com_tidbngmonitorings.yaml
- manifests/federation-crd.yaml
- pkg/apis/pingcap/v1alpha1/openapi_generated.go
- pkg/apis/pingcap/v1alpha1/tidbngmonitoring_types.go
- pkg/manager/tidbngmonitoring/ng_monitoring_manager.go
- pkg/manager/tidbngmonitoring/start_script.go
- pkg/manager/tidbngmonitoring/start_script_test.go
Closes #6209 
Adds `RetentionPeriod` param to `TidbNGMonitoring`CR spec and plumbs it to the underlying ng-monitoring-server start script.
```release-note
```
> feat: support `--retention-period` arg for NGMonitoring

- Makefile
- cmd/testing-workload/import_data.go
- cmd/testing-workload/main.go
- hack/lib/e2e.sh
- pkg/controllers/common/interfaces.go
- pkg/controllers/tiflash/tasks/state.go
- pkg/controllers/tikv/tasks/ctx.go
- pkg/controllers/tikv/tasks/state.go
- tests/e2e/br/framework/framework.go
- tests/e2e/cluster/cluster.go
- tests/e2e/framework/framework.go
- tests/e2e/tikv/tikv.go
- tests/e2e/tikv/topology.go
- tests/e2e/utils/k8s/k8s.go
Fix #6222 
```release-note
```
> Fix(tikv): wait for leaders to transfer back during rolling restart

- .github/workflows/release-v2.yaml
- charts/tidb-operator/templates/_helpers.tpl
- charts/tidb-operator/templates/deployment.yaml
- charts/tidb-operator/values.yaml
- hack/release.sh
- support release charts to ghcr.io
> feat(charts): support release charts to ghcr.io

- docs/api-references/docs.md
- manifests/crd.yaml
- manifests/crd/federation/v1/federation.pingcap.com_volumebackups.yaml
- manifests/crd/federation/v1/federation.pingcap.com_volumebackupschedules.yaml
- manifests/crd/federation/v1/federation.pingcap.com_volumerestores.yaml
- manifests/crd/v1/pingcap.com_backups.yaml
- manifests/crd/v1/pingcap.com_backupschedules.yaml
- manifests/crd/v1/pingcap.com_compactbackups.yaml
- manifests/crd/v1/pingcap.com_restores.yaml
- manifests/federation-crd.yaml
- pkg/apis/pingcap/v1alpha1/openapi_generated.go
- pkg/apis/pingcap/v1alpha1/types.go
- pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
- pkg/backup/util/remote.go
- pkg/backup/util/remote_test.go
Closes https://github.com/pingcap/tidb-operator/issues/6246
```release-note
add forth path style parameter for backup
```
> s3: add forth path style parameter for fips backup

- pkg/backup/util/remote.go
Close https://github.com/pingcap/tidb-operator/issues/6246
Test backup could with below backup.yaml 
```
---
kind: Backup
metadata:
name: full03
namespace: backup-test
labels:
user: test-infra
spec:
backupType: full
serviceAccount: tidb-backup-manager
toolImage: gcr.io/pingcap-public/dbaas/br:v6.5.11-20250623-79aa077
br:
cluster: tc
clusterNamespace: hotfix-databricks-tps-7892647-1-33
sendCredToTikv: false
s3:
provider: aws
region: us-west-2
endpoint: https://s3-fips.us-west-2.amazonaws.com
forcePathStyle: false
bucket: s3endpoint-br-test
prefix: full-with-endpoint-with-brfix
```
and it works
```
full03   full   snapshot   Complete   s3://s3endpoint-br-test/full-with-endpoint-with-brfix   270 kB       458995394438234113                      6s          35m …
```
> br: support custom s3 endpoint for backup manager

- charts/tidb-operator/templates/webhook.yaml
- tests/e2e/data/data.go
- tests/e2e/data/tiproxy.go
- tests/e2e/e2e_test.go
- tests/e2e/webhook/webhook.go
#6172 
Add a ValidatingAdmissionPolicy, which ensures:
- Storage values must be greater than 0
- Storage values can only increase, never decrease (for UPDATE operations)
```release-note
```
> Opt: Add a ValidatingAdmissionPolicy for volume storage

- pkg/controllers/tiflash/tasks/ctx.go
- pkg/controllers/tiflash/tasks/finalizer.go
- pkg/controllers/tiflash/tasks/finalizer_test.go
- pkg/controllers/tikv/tasks/ctx.go
- pkg/controllers/tikv/tasks/finalizer.go
- pkg/controllers/tikv/tasks/finalizer_test.go
Do not use storeID to check whether the store exists.
> fix(store): fix deletion bug when del tikv or tiflash

- go.mod
- pkg/controllers/br/backup/controller.go
- pkg/controllers/br/restore/controller.go
- pkg/controllers/br/tibr/controller.go
- pkg/controllers/cluster/controller.go
- pkg/controllers/pd/controller.go
- pkg/controllers/pdgroup/controller.go
- pkg/controllers/scheduler/controller.go
- pkg/controllers/schedulergroup/controller.go
- pkg/controllers/ticdc/controller.go
- pkg/controllers/ticdcgroup/controller.go
- pkg/controllers/tidb/controller.go
- pkg/controllers/tidbgroup/controller.go
- pkg/controllers/tiflash/controller.go
- pkg/controllers/tiflashgroup/controller.go
- pkg/controllers/tikv/controller.go
- pkg/controllers/tikvgroup/controller.go
- pkg/controllers/tiproxy/controller.go
- pkg/controllers/tiproxygroup/controller.go
- pkg/controllers/tso/controller.go
- pkg/controllers/tsogroup/controller.go
- pkg/utils/task/v3/runner.go
- pkg/utils/task/v3/runner_test.go
- add id for report
- use logger from ctx
> feat(log): add id for report and use logger from ctx

- hack/lib/e2e.sh
- hack/lib/image.sh
- hack/lib/vars.sh
- pkg/image/image.go
- pkg/image/image_test.go
Change default prestop hook image to `tidb-operator-prestop-checker`
> fix(image): change default prestop hook image

- pkg/controllers/common/cond.go
- pkg/controllers/tiflash/builder.go
- pkg/controllers/tiflash/tasks/ctx.go
- pkg/controllers/tiflash/tasks/offline.go
- pkg/controllers/tiflash/tasks/pod.go
- pkg/controllers/tiflash/tasks/pod_test.go
- pkg/controllers/tiflash/tasks/pvc.go
- pkg/controllers/tiflash/tasks/pvc_test.go
- pkg/controllers/tiflash/tasks/status.go
- pkg/controllers/tiflash/tasks/status_test.go
- pkg/controllers/tiflash/tasks/store_labels.go
- pkg/controllers/tikv/builder.go
- pkg/controllers/tikv/tasks/ctx.go
- pkg/controllers/tikv/tasks/evict_leader.go
- pkg/controllers/tikv/tasks/offline.go
- pkg/controllers/tikv/tasks/pod.go
- pkg/controllers/tikv/tasks/pod_test.go
- pkg/controllers/tikv/tasks/pvc.go
- pkg/controllers/tikv/tasks/pvc_test.go
- pkg/controllers/tikv/tasks/status.go
- pkg/controllers/tikv/tasks/status_test.go
- pkg/controllers/tikv/tasks/store_labels.go
- for tikv and tiflash, fail if pd is not ready
- remove store id and use store.ID directly
> fix(store): fail if pd is not ready

- charts/br-federation/values.yaml
- charts/tidb-operator/values.yaml
- cmd/http-service/go.mod
- deploy/aliyun/variables.tf
- deploy/aws/variables.tf
- deploy/gcp/variables.tf
- examples/Runbooks/AKS/md-tidb-cluster.yaml
- examples/Runbooks/AKS/readme.md
- examples/Runbooks/EKS/readme.md
- examples/Runbooks/EKS/ssd-tidb-cluster.yaml
- examples/Runbooks/EKS/tidb-cluster.yaml
- examples/Runbooks/EKS/tidb-monitor.yaml
- examples/Runbooks/GKE/localdisk-tidb-cluster.yaml
- examples/Runbooks/GKE/pd-tidb-cluster.yaml
- examples/Runbooks/GKE/readme.md
- examples/Runbooks/GKE/tidb-monitor.yaml
- examples/Runbooks/K8s/readme.md
- examples/Runbooks/K8s/ssd-tidb-cluster.yaml
- examples/Runbooks/K8s/tidb-cluster.yaml
- examples/Runbooks/K8s/tidb-monitor.yaml
- go.mod
- hack/bump-version.sh
- pkg/client/go.mod
as the title
```release-note
```
> bump TiDB Operator to 1.6.3

- docs/api-references/docs.md
- manifests/crd.yaml
- manifests/crd/v1/pingcap.com_tidbclusters.yaml
- pkg/apis/pingcap/v1alpha1/openapi_generated.go
- pkg/apis/pingcap/v1alpha1/types.go
- pkg/manager/member/tidb_member_manager.go
- pkg/manager/member/tiflash_member_manager.go
- pkg/manager/member/tiflash_util.go
- pkg/manager/member/tikv_member_manager.go
- tail cannot handle the signal TERM when it's PID is 1
- use sidecar to avoid losing logs
> feat(log): support use sidecar to tail log

- pkg/controllers/pd/tasks/ctx.go
In `pkg/controllers/pd/tasks/ctx.go`, the `GetMemberReady` API was called directly without checking the `UsePDReadyAPI` feature gate. This is inconsistent with other parts of the codebase (e.g., `pod.go`) where the same API is properly protected by feature gates.
- Added `UsePDReadyAPI` feature gate check before calling `GetMemberReady`
- Added version compatibility check using `compatibility.Check()`
- Default `ready` to `true` for backward compatibility when feature gate is disabled
```release-note
```
> Fix(pd): add feature gate check before calling GetMemberReady

- cmd/testing-workload/main.go
- pkg/controllers/tiproxy/tasks/pod.go
- tests/e2e/data/data.go
- tests/e2e/data/tiproxy.go
- tests/e2e/framework/workload.go
- tests/e2e/pd/pd.go
- tests/e2e/ticdc/ticdc.go
- tests/e2e/tidb/tidb.go
- tests/e2e/tikv/tikv.go
- tests/e2e/tiproxy/tiproxy.go
- tests/e2e/utils/cert/cert.go
> Add tls e2e case for tiproxy

- pkg/controllers/scheduler/controller.go
- pkg/controllers/scheduler/handler.go
- pkg/controllers/tiflash/builder.go
- pkg/controllers/tiflash/handler.go
- pkg/controllers/tiflash/tasks/ctx.go
- pkg/controllers/tiflash/tasks/offline.go
- pkg/controllers/tiflash/tasks/store_labels.go
- pkg/controllers/tikv/builder.go
- pkg/controllers/tikv/handler.go
- pkg/controllers/tikv/tasks/ctx.go
- pkg/controllers/tikv/tasks/evict_leader.go
- pkg/controllers/tikv/tasks/offline.go
- pkg/controllers/tikv/tasks/store_labels.go
- pkg/controllers/tso/controller.go
- pkg/features/reload.go
- Fix a bug when enable PD ready api
- TiKV should not wait PD ready before creating pod
- Fix rolling update process
> fix(store): fix store when pd enable ready api

- .github/workflows/ci-v2.yaml
- run ci in release-2.0 branch
> fix(ci): also run ci in release-2.0 branch

- api/core/v1alpha1/common_types.go
- go.work.sum
- manifests/crd/br.pingcap.com_tibrs.yaml
- manifests/crd/core.pingcap.com_pdgroups.yaml
- manifests/crd/core.pingcap.com_pds.yaml
- manifests/crd/core.pingcap.com_schedulergroups.yaml
- manifests/crd/core.pingcap.com_schedulers.yaml
- manifests/crd/core.pingcap.com_ticdcgroups.yaml
- manifests/crd/core.pingcap.com_ticdcs.yaml
- manifests/crd/core.pingcap.com_tidbgroups.yaml
- manifests/crd/core.pingcap.com_tidbs.yaml
- manifests/crd/core.pingcap.com_tiflashes.yaml
- manifests/crd/core.pingcap.com_tiflashgroups.yaml
- manifests/crd/core.pingcap.com_tikvgroups.yaml
- manifests/crd/core.pingcap.com_tikvs.yaml
- manifests/crd/core.pingcap.com_tiproxies.yaml
- manifests/crd/core.pingcap.com_tiproxygroups.yaml
- manifests/crd/core.pingcap.com_tsogroups.yaml
- manifests/crd/core.pingcap.com_tsos.yaml
- tests/validation/common_test.go
- tests/validation/pd_test.go
- tests/validation/scheduler_test.go
- tests/validation/tiflash_test.go
- tests/validation/tikv_test.go
- tests/validation/tso_test.go
- tests/validation/validation.go
> Feat: add VolumeAttributesClassName validation rule

- charts/tidb-operator/values.yaml
- image/Dockerfile
> Fix(image): use fixed user id instead of username

- docs/api-references/docs.md
- manifests/crd.yaml
- manifests/crd/v1/pingcap.com_backupschedules.yaml
- manifests/federation-crd.yaml
- pkg/apis/pingcap/v1alpha1/openapi_generated.go
- pkg/apis/pingcap/v1alpha1/types.go
- pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
- pkg/backup/backupschedule/backup_schedule_manager.go
- pkg/backup/backupschedule/backup_schedule_manager_test.go
- pkg/controller/compactbackup/compact_backup_controller.go
- pkg/controller/generic_control_test.go
- pkg/monitor/monitor/util_test.go
- tests/e2e/br/br.go
Add a new field MinCompactStartTs, enable users customize compact start ts
```release-note
add new field `MinCompactStartTs` in `backupSchedule`, enable users customize compact start ts.
If the `logBackup.startTs` is less than customized `MinCompactStartTs`, compact will be forced to start from `MinCompactStartTs`.
```
> br: add new field `MinCompactStartTs` in `backupSchedule`, enable users customize compact start ts

- pkg/controllers/common/cond.go
- pkg/controllers/common/cond_test.go
- pkg/controllers/common/interfaces_test.go
- pkg/controllers/common/task.go
- pkg/controllers/pdgroup/builder.go
- pkg/controllers/replicationworkergroup/builder.go
- pkg/controllers/schedulergroup/builder.go
- pkg/controllers/ticdcgroup/builder.go
- pkg/controllers/tidbgroup/builder.go
- pkg/controllers/tiflashgroup/builder.go
- pkg/controllers/tikvgroup/builder.go
- pkg/controllers/tiproxygroup/builder.go
- pkg/controllers/tsogroup/builder.go
- wait cannot break the reconciliation
> fix(group): break if feature gates field is not synced

- cmd/runtime-gen/generators/scope.go
- pkg/apiutil/core/v1alpha1/instance.go
- pkg/runtime/scope/br.go
- pkg/runtime/scope/scope.go
- pkg/runtime/scope/zz_generated.scope.pd.go
- pkg/runtime/scope/zz_generated.scope.replicationworker.go
- pkg/runtime/scope/zz_generated.scope.scheduler.go
- pkg/runtime/scope/zz_generated.scope.ticdc.go
- pkg/runtime/scope/zz_generated.scope.tidb.go
- pkg/runtime/scope/zz_generated.scope.tiflash.go
- pkg/runtime/scope/zz_generated.scope.tikv.go
- pkg/runtime/scope/zz_generated.scope.tiproxy.go
- pkg/runtime/scope/zz_generated.scope.tso.go
- add gvk function for scope
- add `OwnerGroup` in apiutil for instance
> feat(runtime): add GVK function for runtime scope

- api/core/v1alpha1/tidb_types.go
- manifests/crd/core.pingcap.com_tidbgroups.yaml
- manifests/crd/core.pingcap.com_tidbs.yaml
- pkg/configs/tidb/config.go
- pkg/controllers/tidb/builder.go
- pkg/controllers/tidb/tasks/activate.go
- pkg/reloadable/tidb.go
- pkg/reloadable/tidb_test.go
- pkg/tidbapi/v1/client.go
- pkg/tidbapi/v1/client_test.go
- pkg/tidbapi/v1/types.go
- pkg/utils/http/error.go
- pkg/utils/http/error_test.go
- pkg/utils/http/http.go
- tests/validation/tidb_test.go
- support to activate standby tidb by modifying mode and keyspace
- fix issue that tidbgroup cannot modify mode and keyspace in template
> feat(tidb): support activate tidb from standby mode

- tests/e2e/utils/waiter/common.go
- tests/e2e/utils/waiter/pd.go
- tests/e2e/utils/waiter/scheduler.go
- tests/e2e/utils/waiter/ticdc.go
- tests/e2e/utils/waiter/tidb.go
- tests/e2e/utils/waiter/tiflash.go
- tests/e2e/utils/waiter/tikv.go
- tests/e2e/utils/waiter/tiproxy.go
- tests/e2e/utils/waiter/tso.go
> test(e2e): add more error infos if e2e failed

- pkg/controllers/tiflash/tasks/status.go
- pkg/controllers/tiflash/tasks/status_test.go
- if ready, tiflash store status has been Running
- if pod is ready but tiflash store status is not Running, should retry
> fix(tiflash): retry if tiflash is not running

- tests/e2e/framework/tikv.go
- tests/e2e/framework/util.go
- tests/e2e/ticdc/ticdc.go
- tests/e2e/tikv/tikv.go
- tests/e2e/tiproxy/tiproxy.go
enable some cases which are failed in legacy jenkins ci env
> fix(e2e): enable some disabled cases
