pingcap/tidb-operator

charts/tidb-cluster/templates/monitor-configmap.yaml
charts/tidb-cluster/templates/monitor-deployment.yaml
charts/tidb-cluster/templates/pd-configmap.yaml
charts/tidb-cluster/templates/privileged-tidb-configmap.yaml
charts/tidb-cluster/templates/tidb-configmap.yaml
charts/tidb-cluster/templates/tikv-configmap.yaml
charts/tidb-cluster/values.yaml
images/tidb-operator-e2e/tidb-cluster-values.yaml

This PR updates TiDB configuration to v2.0.4, and bumps monitor images version:
Prometheus: v2.0.0 -> v2.2.1
Grafana: 4.2.0 -> 4.6.3
tidb-dashboard-installer: v1.0.7 -> v2.0.0
PTAL @weekface @onlymellb

charts: update TiDB configuration and monitor versions

---

docs/google-kubernetes-tutorial.md

s/distribute MySQL database/distributed MySQL database/
Fixed name of cluster to "demo-tidb"
Clarified a few steps between TiDB Cluster and Kubernetes Cluster.
Changed project name to MY_NEW_PROJECT_NAME to make it clear the user is expected to change it (the name is unique and default name can not be used)

Minor Bug Fixes, readability.

---

README.md
docs/google-kubernetes-tutorial.md

Changed the flow to be 100% teachme - using integrations for account.
All commands work in sequence (can click directly) without error.
Moved the launch in Google Shell Button to README.md

Integrate fully with Google Cloud Shell tutorial framework

---

ROADMAP.md
docs/local-dind-tutorial.md
hack/dind-run-operators.sh
pkg/controller/pvc_control.go
pkg/controller/pvc_control_test.go
pkg/controller/tidbcluster/tidb_cluster_control_test.go
pkg/controller/tidbcluster/tidb_cluster_controller.go
pkg/controller/tidbcluster/tidb_cluster_controller_test.go
pkg/label/label.go
pkg/manager/member/pd_member_manager.go
pkg/manager/member/pd_scaler.go
pkg/manager/member/pd_scaler_test.go
pkg/manager/member/tidb_member_manager.go
pkg/manager/member/tidb_member_manager_test.go
pkg/manager/member/tikv_member_manager.go
pkg/manager/member/utils.go
tests/e2e/e2e_test.go
tests/e2e/upgrade.go

Now, when a pd cluster scales in, the related PVC will not be deleted, but the data were tombstoned. If we scale out again, the scaled pod will use the tombstoned data.
This pr try to delete the tombstoned PVC when scale out again.
@tennix @onlymellb @xiaojingchen @gregwebs PTAL

Safely scale out after a scale in operation for pd

---

.gitignore
checkout-pr-branch.sh
manifests/local-dind/dind-cluster-v1.10.sh
manifests/local-dind/kube-flannel.yaml
manifests/local-dind/kubernetes-dashboard.yaml
manifests/local-dind/local-volume-provisioner.yaml
manifests/local-dind/registry-proxy-deployment.yaml

The purpose of this PR is to unify the development environment of developers at home and abroad by setting environment variables `KUBE_REPO_PREFIX`. This script will do the following at startup.
- Launch a k8s v1.10 cluster with flannel network plugin
- Install a docker registry in DinD env, the defaults port of the registry is `5000`, which can be changed by setting the environment variable `REGISTRY_PORT`.
- Deploy tiller in k8s 
- Deploy local volume provisioner in k8s
- Create PV mount points on all Kube nodes except the master node, you can control the number of created PVS by setting the environment variable PV_NUMS. All PV directories will be mounted in the host's `YOU-TIDB-OPERATOR-DIR/data` directory.
- Create TidbCluster CRD object and e2e namespace `tidb-operator-e2e`
- Start …

chore(development env): unified the DinD development environment

---

README.md
ROADMAP.md
docs/google-kubernetes-tutorial.md

This small change to the button on `README.md` opens the tutorial file (not just the repo) in Cloud Shell.
I had to wait to make this change until the tutorial was pushed, as the Cloud Shell only checks out master -- and the tutorial file previously did not exist.
Tested manually, works as expected.

Directly open GKE tutorial

---

ci/pingcap_tidb_operator_build_dind.groovy
pkg/controller/controller_utils.go
pkg/manager/member/pd_member_manager.go
pkg/manager/member/tidb_member_manager.go
pkg/manager/member/tikv_member_manager.go
pkg/manager/member/utils.go

This pr rewrites the service comparison logic to avoid frequent update services causing the nodePort to always be changing

Fix service's nodePort will changing every 30s

---

pkg/util/util.go

Signed-off-by: huanwei <huan@harmonycloud.cn>
Fix [issue #52  Remove noise error log message](https://github.com/pingcap/tidb-operator/issues/52)

[ISSUE #52] Remove noise error log message

---

docs/CONTRIBUTING.md
docs/local-dind-tutorial.md
manifests/local-dind/dind-cluster-v1.10.sh

This PR updates DinD tutorial, to simplify DinD setup the script is also updated for `helm` and `kubectl` section. This makes both `helm` client and `kubectl` prerequisites.
PTAL @gregwebs @onlymellb @lilin90

*: update DinD script & tutorial to simplify DinD setup

---

pkg/controller/controller_utils.go

Signed-off-by: huanwei huan@harmonycloud.cn
This PR is derived from [ISSUE #52](https://github.com/pingcap/tidb-operator/issues/52) and  [PR #54 ](https://github.com/pingcap/tidb-operator/pull/54), to fix the noisy error messages problem on tikv storage capacity.

Fix the noisy error messages problem on storage

---

revive.toml

This setting defaulted to zero, which doesn't make sense.
Warnings are still zero.

linter: error means exit code 1

---

pkg/manager/member/tikv_member_manager.go

1. delete the useless variant called nodeName, fix #64

Fix issue-64: delete the useless variant called nodeName

---

pkg/controller/tidbcluster/tidb_cluster_control.go
pkg/controller/tidbcluster/tidb_cluster_control_test.go

1、Fix deepequal result in UpdateTidbCluster always false
2、Replace reflect.DeepEqual with apiequality.Semantic.DeepEqual
3、Add unit test to cover this situation
Fix issue #73

Fix deepequal result in UpdateTidbCluster always false

---

charts/tidb-cluster/templates/tidb-cluster.yaml
charts/tidb-cluster/values.yaml
pkg/controller/controller_utils.go

1. Add tikvpromgateway values in tidbcluster template
2. Fix function `controller.GetPushgatewayImage`
Fix issue: #82

fix tikvpromgateway not used in tidbcluster templates

---

charts/tidb-cluster/templates/monitor-configmap.yaml
charts/tidb-cluster/templates/monitor-deployment.yaml
charts/tidb-cluster/templates/privileged-tidb-configmap.yaml
charts/tidb-cluster/templates/privileged-tidb-deployment.yaml
charts/tidb-cluster/templates/privileged-tidb-service.yaml
charts/tidb-cluster/templates/tidb-cluster.yaml
charts/tidb-cluster/values.yaml
charts/tidb-operator/templates/controller-manager-deployment.yaml
charts/tidb-operator/values.yaml
images/tidb-operator/Dockerfile
pkg/apis/pingcap.com/v1alpha1/types.go
pkg/manager/member/pd_member_manager.go
pkg/manager/member/tidb_member_manager.go
pkg/manager/member/tikv_member_manager.go

This PR fixes #88. It also removes the mounting /etc/localtime solution for log timestamp.
With this PR the logs for pods will be in the same timezone with TiDB instead of with host machine. This may introduce confusion for users when using `kubectl logs` to view different pod logs in the same Kubernetes cluster, unfortunately this is unavoidable. But assuming there's a log collector, users should reference the collecting timestamp instead of timestamp in the log message.

*: Setting TZ env instead of mounting /etc/localtime

---

pkg/apis/pingcap.com/v1alpha1/tidbcluster.go
pkg/controller/tidb_control.go
pkg/controller/tidbcluster/tidb_cluster_control.go
pkg/controller/tidbcluster/tidb_cluster_controller.go
pkg/manager/member/pd_failover.go
pkg/manager/member/pd_failover_test.go
pkg/manager/member/pd_member_manager.go
pkg/manager/member/tidb_failover.go
pkg/manager/member/tidb_failover_test.go
pkg/manager/member/tidb_member_manager.go
pkg/manager/member/tikv_failover.go
pkg/manager/member/tikv_failover_test.go
pkg/manager/member/tikv_member_manager.go

This PR fixes #97 , the failover feature: 
- don't need to modify the `spec.PD.Replicas` to achieve the failover feature
- use `RequeueError` instead of update TidbCluster immediately
- adjust related unit tests
@tennix @onlymellb @xiaojingchen @gregwebs PTAL

Failover fix: no longer modify spec.Replicas

---

pkg/controller/pod_control.go
pkg/manager/member/tidb_member_manager.go
pkg/manager/member/utils.go

Currently, pd/tikv/tidb pods and pd/tidb statefulsets are updated all the time, even there's no update. This PR fixes this issue.

Remove unnecessary pod and statefulset update

---

charts/tidb-cluster/templates/privileged-tidb-configmap.yaml

Privileged TiDB can't started because of this typo:
```
start privileged-tidb-server ...
/usr/local/bin/privileged_tidb_start_script.sh: line 31: AGRS: parameter not set
```

fix wrong parameter AGRS to ARGS

---

docs/google-kubernetes-tutorial.md

The original placement didn't make sense in the context of the tutorial.

Modified placement of tidb_version

---

docs/CONTRIBUTING.md

remove redundant creation statement of namespace tidb-operator-e2e

---

docs/aws-eks-tutorial.md
manifests/gp2-storage.yaml

Hi there,
I would like to try to add a doc on how to provision a k8s on AWS via EKS and Terraform code.
Do you think it would be a good idea to add a doc like this here? 
And do you have any suggestion where to put the terraform code? 
In this repo as well or somewhere else? I am thinking about using some of the terraform code from here:
https://github.com/wardviaene/terraform-course/tree/master/eks-demo 
But not sure whether it will work out of the box or not.
Also I hope it is okay to open this work-in-progress PR, as I am in the hope someone else is trying the same and perhaps can help out with writing the doc as well :)

Add doc on how to provision kubernetes on aws

---

charts/tidb-cluster/templates/NOTES.txt
charts/tidb-cluster/templates/tidb-initializer-job.yaml
charts/tidb-cluster/templates/tidb-secret.yaml
charts/tidb-cluster/values.yaml
docs/aws-eks-tutorial.md
docs/google-kubernetes-tutorial.md
docs/local-dind-tutorial.md
images/tidb-operator-e2e/tidb-cluster-values.yaml
tests/e2e/create.go
tests/e2e/test_helper.go

This PR closes #167. It uses a `BatchJob` to set TiDB password when first deployed. When the job is completed, users can use the password to access TiDB.

Set password for TiDB when first deployed

---

docs/local-dind-tutorial.md

since Helm 2.9.0, --template flag supported. #170

DinD Helm prerequisites

---

charts/tidb-cluster/templates/config/_pd-config.tpl
charts/tidb-cluster/templates/config/_tidb-config.tpl
charts/tidb-cluster/templates/config/_tikv-config.tpl

if `log-level` is empty in tikv config file, starting tikv will fail.  
In this pr, if the `log-level` is empty,  it will be set to `info`. 
@tennix @weekface @xiaojingchen PTAL

add default value for tidb / tikv / pd log level

---

pkg/controller/controller_utils.go
pkg/controller/controller_utils_test.go
pkg/scheduler/predicates/test_helper.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go

- add unit tests to `pkg/scheduler/scheduler.go`, coverage from 0% to 96.7%
- add unit tests to  `pkg/controller_utils.go`, coverage from 3.8%  to 88%
- refine `Priority ` method
- remove some unuse codes

add unit tests to scheduler.go

---

charts/tidb-operator/templates/scheduler-deployment.yaml
charts/tidb-operator/templates/scheduler-policy-configmap.yaml
charts/tidb-operator/templates/scheduler-rbac.yaml

The scheduler can't use scheduler policy configmap correctly when you change the schedulerName in values.yaml. This PR fix it.

keep scheduler name consistent as defined in values.yml

---

pkg/controller/pd_control.go
pkg/controller/tidb_control.go

- just return an error if delete store failed
- use `GetEvictLeaderSchedulers` instead

fix pd_control: not rely on error text

---

pkg/controller/tidbcluster/tidb_cluster_control.go
pkg/controller/tidbcluster/tidb_cluster_control_test.go
pkg/controller/tidbcluster/tidb_cluster_controller.go
pkg/controller/tidbcluster/tidb_cluster_controller_test.go
pkg/label/label_test.go
pkg/manager/member/orphan_pods_cleaner.go
pkg/manager/member/orphan_pods_cleaner_test.go
pkg/manager/member/pd_failover.go
pkg/manager/member/pd_scaler.go
pkg/manager/member/scaler.go
pkg/manager/member/scaler_test.go
pkg/manager/member/tikv_scaler.go
tests/e2e/upgrade.go

- add orphan pods cleaner: delete the pod if its pvc is not exist
- add unit tests to orphan pods cleaner
- only delete one defer deleting pvc when scale out
- e2e: set upgrade timeout duration to 10 minutes(upgrading all 5 tikvs may need more than 5 minutes)

Orphan pods cleaner

---

pkg/manager/member/pd_scaler.go
pkg/manager/member/pd_scaler_test.go

fix pd-failover: scale out directly when failover occurs

---

charts/tidb-cluster/templates/tidb-initializer-job.yaml

the default timeout of mysql client is too long, cause the tidb-initializer-job spends much time to complete.
so need to set `connect-timeout`  for shortening the job's execution time
@tennix  @weekface PTAL

set connect timeout for set password sql 

---

ci/release_tidb_operator_binary_and_docker_dind.groovy

This PR do some things as follow:
* release tidb-operator and tidb-cluster charts separately
* keep the tidb-operator chart app version consistent with the release version

release tidb-operator and tidb-cluster charts separately

---

cmd/controller-manager/main.go

This pr is related the #154.
the Kubernetes client is not timeout by default, see: [https://github.com/kubernetes/client-go/blob/master/rest/config.go#L117](url). to set timeout may help to resolve the bug of #154, and it is more reasonable than always blocked
PTAL @weekface @tennix @gregwebs @onlymellb

set kube client timeout

---

charts/tidb-operator/templates/config/_scheduler-policy-json.tpl
charts/tidb-operator/templates/scheduler-deployment.yaml
charts/tidb-operator/values.yaml
docs/aws-eks-tutorial.md
docs/google-kubernetes-tutorial.md
docs/local-dind-tutorial.md
docs/setup.md

I had tested in kubernetes v1.10, v1.11 and v1.12
@tennix @onlymellb @xiaojingchen PTAL

fix scheduler policy issue

---

charts/tidb-operator/templates/scheduler-rbac.yaml
cmd/scheduler/main.go
pkg/scheduler/predicates/ha.go
pkg/scheduler/predicates/ha_test.go
pkg/scheduler/predicates/predicate_test.go
pkg/scheduler/predicates/test_helper.go
pkg/scheduler/scheduler.go
pkg/scheduler/server/mux.go

fixes #235 
@tennix @onlymellb @xiaojingchen PTAL

new algorithm for scheduler HA predicate

---

charts/tidb-operator/templates/scheduler-rbac.yaml
pkg/label/label.go
pkg/manager/meta/reclaim_policy_manager.go
pkg/manager/meta/reclaim_policy_manager_test.go
pkg/scheduler/predicates/ha.go
pkg/scheduler/predicates/ha_test.go

This pr fixes: #264, make sure only one pod can be scheduled at the same time.

Serial scheduling

---

charts/tidb-cluster/templates/scripts/_start_pd.sh.tpl

It means this pod have got the start args from `tidb-discovery` service when the `join` file exists. Start it directly

start directly when where is join file

---

charts/tidb-cluster/templates/NOTES.txt
charts/tidb-cluster/templates/tidb-initializer-job.yaml
charts/tidb-cluster/templates/tidb-secret.yaml
charts/tidb-cluster/values.yaml
docs/aws-eks-tutorial.md
docs/google-kubernetes-tutorial.md
docs/local-dind-tutorial.md
docs/operation-guide.md

Don't create
* a secret
* an initializer job
From my reading, random password initialization is broken: https://github.com/helm/helm/issues/3053
The user can manage users from the MySQL connection
As a benefit this allows users manage their password such that it is never stored in K8s. Or they can create their own init job, etc.
For both options:
* Perform output suggested in NOTES
* Verify whether secret/initializer are created

Don't initialize when there is no tidb.password

---

charts/tidb-cluster/templates/scripts/_start_pd.sh.tpl

If the data directory has a `join` file, start `pd-server` with `--join =`args([it can't be empty](https://github.com/pingcap/pd/blob/master/server/join.go#L77)), which is the contents of the `join` file, otherwise request the discovery service.
@tennix @xiaojingchen @onlymellb PTAL

fix join script

---

docs/CONTRIBUTING.md

close #287 
Signed-off-by: Yeh-lei Wu <rayingecho@gmail.com>

Document tool setup and e2e test detail in Contributing.md

---

images/tidb-operator-e2e/tidb-cluster-values.yaml
pkg/manager/member/tidb_member_manager.go
tests/e2e/create.go
tests/e2e/e2e_test.go
tests/e2e/scale.go
tests/e2e/test_helper.go
tests/e2e/upgrade.go

Ensure SLOW_LOG_FILE env variable is always set

---

docs/operation-guide.md
docs/setup.md

- fix a typo in operation-guide.md
- change ulimit to 1048576

fix setup document description

---

tests/cmd/fault-trigger/main.go
tests/pkg/fault-trigger/api/response.go
tests/pkg/fault-trigger/api/router.go
tests/pkg/fault-trigger/api/server.go
tests/pkg/fault-trigger/manager/etcd.go
tests/pkg/fault-trigger/manager/kubelet.go
tests/pkg/fault-trigger/manager/manager.go
tests/pkg/fault-trigger/manager/types.go
tests/pkg/fault-trigger/manager/vm.go
tests/pkg/fault-trigger/manager/vm_test.go

1. stop / start  virtual machine 
2. stop / start etcd 
3. stop / start kubelet  
@weekface @zyguan @xiaojingchen PTAL

stability: add fault-trigger server

---

tests/actions.go
tests/backup/backup.go
tests/backup/backupcase.go
tests/cmd/e2e/main.go

1.add create secret process
2.add bakcup process
3.add restore process
4.add some parameters via the values.yaml change.
5.use master branch to test
@weekface @zyguan @cwen0 @xiaojingchen PTAL

Yinliang/backup and  restore add adhoc backup and restore functison

---

tests/actions.go
tests/cluster_info.go
tests/cmd/e2e/main.go

I just implement two case functions for `OperationActions`, PTAL.

stability: add scale & upgrade case functions

---

tests/actions.go
tests/cmd/e2e/main.go
tests/log_dump.go
tests/manifests/e2e.yaml

@weekface @cwen0 @zyguan @shuijing198799 PTAL

log dump when test failed

---

tests/actions.go
tests/pkg/fault-trigger/api/response.go
tests/pkg/fault-trigger/api/router.go
tests/pkg/fault-trigger/client/client.go
tests/pkg/fault-trigger/client/client_test.go
tests/pkg/fault-trigger/manager/etcd.go
tests/pkg/fault-trigger/manager/kubelet.go
tests/pkg/fault-trigger/manager/types.go
tests/pkg/util/http.go

@weekface @zyguan @xiaojingchen PTAL

stability: add fault-trigger client

---

tests/actions.go
tests/cmd/e2e/main.go

@tennix @weekface @cwen0 @zyguan @shuijing198799 PTAL

monitor checker

---

tests/actions.go
tests/cmd/e2e/main.go
tests/pkg/blockWriter/blockWriter.go
tests/pkg/util/db.go
tests/pkg/util/string.go
tests/pkg/util/time.go

@weekface @zyguan @xiaojingchen @shuijing198799 PTAL

stability: add blockWriter case for inserting data 

---

pkg/scheduler/predicates/ha.go
pkg/scheduler/predicates/ha_test.go

This pr try to fix #350 
@tennix @xiaojingchen @onlymellb PTAL

fix ha when replcias is less than 3

---

manifests/crd.yaml

Testing result in my local 1.13 cluster:
```shell
kubectl get tidbcluster
NAME           PD                  STORAGE   READY   DESIRE   TIKV                  STORAGE   READY   DESIRE   TIDB                  READY   DESIRE
aylei-master   pingcap/pd:v2.1.0   1Gi       3       3        pingcap/tikv:v2.1.0   10Gi      5       5        pingcap/tidb:v2.1.0   4       4
```

Add additionalPrintColumns for TidbCluster CRD

---

README.md

Updated readme with information to engage with the community via different channels and an updated message on production readiness.

Updated Readme with New Info

---

Makefile
docs/CONTRIBUTING.md

close #374 
Fix tag build failure: https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/build_tidb_operator_tag/detail/build_tidb_operator_tag/5/pipeline/
@zhouqiang-cl @tennix @weekface PTAL

Separate and ensure setup before e2e-build

---

tests/cmd/stability/main.go
tests/fault.go
tests/pkg/fault-trigger/manager/static_pod_service.go

currently, stability test directly runs on k8s cluster without the test env check, this may cause invalid test and results. this pr add test env check and recover to ensure it is normal before the stability test cases start running; in the other hand if recover failed, the stability test will be failed,  need to recover  test environment manually.

ensure test env normal and completed before cases run

---

charts/tidb-cluster/templates/tidb-service.yaml
docs/setup.md

Update local-pv documentation

---

README.md

- job url: https://internal.pingcap.net/jenkins/job/build_tidb_operator_master -> https://internal.pingcap.net/idc-jenkins/job/build_tidb_operator_master
- badge image: https://internal.pingcap.net/jenkins/job/build_tidb_operator_master/badge/icon -> https://internal.pingcap.net/idc-jenkins/job/build_tidb_operator_master/badge/icon
I guess, we migrated to `https://internal.pingcap.net/idc-jenkins` now.

Update Jenkins links in README.md

---

Makefile
docs/CONTRIBUTING.md
tests/manifests/e2e/e2e.yaml

- use `[` instead of `[[` to be sh-compatible (more portable)
- fix e2e workflow in CONTRIBUTING.md
`make e2e-docker` builds e2e image from `tests/images/e2e` instead of `images/tidb-operator-e2e`, we should use new e2e yaml file `tests/manifests/e2e/e2e.yaml`.
xref: #346

Update e2e workflow in CONTRIBUTING.md

---

marketplace/gcp/tidb-operator/README.md
marketplace/gcp/tidb-operator/manifests/app-crd.yaml

document the service account
fix some issues with the manual install

marketplace update

---

charts/tidb-cluster/templates/scripts/_start_tidb.sh.tpl
charts/tidb-cluster/values.yaml

Support plugin start argument for tidb instance. The default value is disabled
Tests
- enable the plugin,  ARGS is appended as expected.
` ARGS="${ARGS}  --plugin-dir  /pulugins --plugin-load whitelist-1  "`
- disable the plugin, no plugin argument is added

Support plugin start argument for tidb instance

---

docs/setup.md

fixes https://github.com/pingcap/tidb-operator/issues/410
Operations on local volume setup are common in most environments, we can link to operation guides in `sig-storage-local-static-provisioner` project and maintain docs there. 
https://github.com/cofyc/tidb-operator/blob/fix410/docs/setup.md

Link to local volume operations guide in sig-storage-local-static-provisioner

---

Makefile
go.sum
tests/backup/backupcase.go
tests/pkg/blockwriter/blockwriter.go
tests/pkg/metrics/annotation_util.go

close #415 
@weekface @cofyc @tennix PTAL

Replace govet with official vet tool

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/question.md
.github/pull_request_template.md

GitHub allows a repository to [create issue templates and PR template under the `.github` directory](https://help.github.com/en/articles/about-issue-and-pull-request-templates). This PR adds some templates for issue reporting and PR. It should help users, contributors and ourselves to communicate more efficiently.

add GitHub templates for issue reporting and PR

---

tests/actions.go
tests/backup/backupcase.go
tests/cmd/stability/main.go
tests/failover.go
tests/pkg/blockwriter/blockwriter.go
tests/pkg/metrics/annotation_util.go

This PR fixes:
* sst truncate case
* block writer channel size to 100
* fix poll interval error
* fix pprof server port error
* fix backup issue
Tests 
- E2E test
Code changes
Side effects

fix stability issues

---

pkg/scheduler/predicates/ha.go
pkg/scheduler/predicates/ha_test.go
pkg/scheduler/scheduler.go
tests/cmd/stability/main.go

This pr:
* fix realAcquireLock bug: pvc must bound and its pod.spec.nodeName is not empty 
* emit event when scheduled failed
* more nice error message:
```
$ kubectl describe po -n tidb demo-pd-1
...
Events:
Type     Reason            Age                     From            Message
----     ------            ----                    ----            -------
Warning  FailedScheduling  2m25s (x1484 over 12m)  tidb-scheduler  Failed filter with extender at URL http://127.0.0.1:10262/scheduler/filter, code 500
Warning  FailedScheduling  2m21s (x1489 over 12m)  tidb-scheduler  can't scheduled to nodes: [172.16.4.159 172.16.4.160], because these pods had been scheduled to nodes: map[172.16.4.159:[demo-pd-0] 172.16.4.160:[demo-pd-2]]
```

a tidb-scheduler bug fix and emit event when scheduled failed

---

Makefile
ci/release_cli_binary_and_debug_image.groovy
pkg/tkctl/cmd/cmd.go
pkg/tkctl/cmd/completion/completion.go

add shell completion for the specified shell (bash or zsh)  for tkctl CLI
just add a completion subcommand without changing the existing logic，use it like any other command.
Tests 
- Manual test 
Code changes
Side effects
- No

Shell completion for tkctl

---

README.md

Simple change to README.me to fix broken TiDB Slack link.

Fix TiDB Slack link

---

pkg/scheduler/predicates/ha.go
pkg/scheduler/predicates/ha_test.go

this pr fixes #442 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects

fix scheduler ha bug

---

docs/google-kubernetes-tutorial.md

#404 
Adds instruction in the GKE tutorial to access Grafana dashboard
Tests 
- No code
Code changes
Side effects

Adds instructions to access Grafana in GKE tutorial

---

pkg/manager/member/pd_member_manager.go
pkg/manager/member/tidb_member_manager.go

remove set ClusterIP operation when syncing headless service
Tests 
- No code
Code changes
Side effects

no need to set ClusterIP when syncing headless service

---

README.md
docs/minikube-tutorial.md

fixes #447 
Check https://github.com/cofyc/tidb-operator/blob/fix447/docs/minikube-tutorial.md
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects

docs on how to deploy tidb cluster with tidb-operator in minikube

---

tests/actions.go
tests/backup/backupcase.go
tests/cmd/stability/main.go
tests/config.go
tests/failover.go
tests/fault.go
tests/manifests/stability/stability.yaml
tests/pkg/client/client.go
tests/pkg/metrics/annotation_util.go
tests/pkg/webhook/pods.go
tests/slack/slack.go
tests/util.go

solve the problem that stability test lack notify feature
this pr will notify the particular slack channel when stability test failed or complete
Tests 
Code changes
- Has stability test's yaml file change

add slack notify 

---

pkg/manager/member/pd_member_manager.go
pkg/manager/member/tidb_member_manager.go
pkg/manager/member/tikv_member_manager.go

Because the data in shareinformer is modified instead of using copy,，When the TiDB statefulset rolling upgrade process is interrupted, it will not be retried.
use copy data instead.
Tests 
- E2E test
Code changes
Side effects
- effect the TiDB rolling update process

Fix bug use shareinformer without copy

---

manifests/local-dind/local-volume-provisioner.yaml

To simplify administration, it would be helpful to be able to search PVs by node name.
e.g.
```
$ kubectl get pv -l kubernetes.io/hostname=kube-node-3
NAME                CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM   STORAGECLASS    REASON   AGE
local-pv-d20c2706   6Gi        RWO            Delete           Available           local-storage            5m4s
```
Configure `kubernetes.io/hostname` in `nodeLabelsForPV`, local-volume-provisioner will copy node labels to PVs it provisioned.
Note that local-volume-provisioner does not sync labels between node and PVs. It only applies to new PVs for now.
Tests 
- Unit test
- E2E test
1, Update local-volume-provisioner
```
kubectl apply -f …
```

Copy kubernetes.io/hostname label to PVs

---

docs/cli-manual.md

Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects

Fixed typo

---

docs/local-dind-tutorial.md
manifests/local-dind/dind-cluster-v1.10.sh
manifests/local-dind/dind-cluster-v1.12.sh

fixes https://github.com/pingcap/tidb-operator/issues/461
Tests 
Manual test (add detailed scripts or steps below)
configure http proxies in docker config.json
```
"proxies": {
"default": {
"httpProxy": "http://192.168.90.1:1087",
"httpsProxy": "http://192.168.90.1:1087",
"noProxy": ".svc,.local,127.0.0.1,0,1,2,3,4,5,6,7,8,9"
}   
}
```
propagate http proxies to dind containers
```
export DIND_PROPAGATE_HTTP_PROXY=true
manifests/local-dind/dind-cluster-v1.12.sh up
```

Update DinD image to make it possible to configure HTTP proxies

---

deploy/aliyun/README.md
deploy/aws/README.md
docs/aws-eks-tutorial.md

Testing current documentation of deploying TiDB Operator on AWS with Terraform and keep it up to date.
Tested all instructions in the AWS installation documentation on a VM with latest ArchLinux, updated them to fit testing results and added some detailed notes.
Tests 
- No code
Code changes
Side effects
- N/A
- N/A

docs/aws: update AWS deploy docs after testing

---

Makefile
pkg/discovery/server/mux.go
pkg/tkctl/config/config.go
pkg/tkctl/executor/executor.go
pkg/tkctl/readable/print_flags.go
pkg/tkctl/readable/printers.go
revive.toml
tests/actions.go
tests/cmd/e2e/main.go
tests/cmd/stability/main.go
tests/config.go
tests/failover.go
tests/pkg/metrics/annotation_util.go
tests/pkg/metrics/annotation_util_test.go
tests/pkg/ops/common.go
tests/pkg/ops/exec.go
tests/pkg/ops/tikv.go
tests/pkg/util/misc.go
tests/pkg/webhook/pods.go
tests/pkg/webhook/route.go
tests/slack/slack.go
tests/util.go

fixes #481 
Note that a lot of places violates `rule.var-naming`, it makes the PR too complicated to fix all. 
I decide to change the error level of it to "warning" temporarily. We can fix it in a separate PR.
Tests 
Unit test
```release-note
NONE
```

fix `make lint`

---

docs/minikube-tutorial.md

- updated some wording and note info as per the Queeny's test on Deploy TiDB in the minikube cluster
@AstroProfundis @lilin90 PTAL

tidb-operator: update wording and add note

---

deploy/aliyun/README-CN.md
deploy/aliyun/README.md
deploy/aliyun/data.tf
deploy/aliyun/main.tf
deploy/aliyun/outputs.tf
deploy/aliyun/templates/tidb-cluster-values.yaml.tpl
deploy/aliyun/variables.tf
deploy/aws/data.tf
deploy/aws/templates/tidb-cluster-values.yaml.tpl
deploy/aws/variables.tf

Improve the user experience of terraform deployment:
* Use tidb 2.1.8 by default for Aliyun
* Better defaults for Aliyun kubernetes cluster
* Disable Grafana anonymous user by default (both AWS and Aliyun expose Grafana to internet by default)
* Add an option to enable Grafana anonymous user
Terraform scripts changed, more options are exposed.
Tests 
```
$ terraform apply
```
@AstroProfundis @jlerche @tennix PTAL

Refine aliyun and aws cloud tidb configurations

---

docs/operation-guide.md
images/tidb-operator-e2e/tidb-cluster-values.yaml

close #487 
A warning about PD configuration change is documented.
Tests 
- No code
(This should be documented as **known issue** in the next release)
```known issue
Currently, the `scheduler` and `replication` configurations of PD can not be changed via ConfigMap rollout. You can use `pd-ctl` to change these values instead, see #487 for details.
```

Document about PD configuration management issue

---

charts/tidb-cluster/templates/tidb-cluster.yaml
charts/tidb-cluster/values.yaml
images/tidb-operator-e2e/tidb-cluster-values.yaml
pkg/apis/pingcap.com/v1alpha1/types.go
pkg/apis/pingcap.com/v1alpha1/zz_generated.deepcopy.go
pkg/manager/member/pd_member_manager.go
pkg/manager/member/tidb_member_manager.go
pkg/manager/member/tikv_member_manager.go
pkg/manager/member/utils.go

Support adding additional pod annotations for PD/TiKV/TiDB.
We could add pod annotation `fluentbit.io/parser: pingcap_log` for PD/TiKV/TiDB pod, so fluentbit knows that  the pod log should be processed using the pre-defined parser called `pingcap_log `.
refer: https://docs.fluentbit.io/manual/filter/kubernetes#kubernetes-annotations
At the server side, `Annotations` field was added in TidbClusterSpec's Pod Spec (PDSpec, TiKVSpec and TiDBSpec). If Annotations field is not empty, the PD/TiKV/TiDB statefulset will add the annotation to PodTemplateSpec's Annotations field.
At the client side, you could add additional annotations in Helm values file `charts/tidb-cluster/values.yaml`. 
Tests
- [] Unit test
- [] E2E test
The Unit and E2E test cases will be tracked in  issue …

Support adding additional pod annotations for PD/TiKV/TiDB

---

charts/tidb-backup/values.yaml

- add --namespace when create backup secret
Tests 
- No code
Code changes
Side effects
```release-note
NONE
```

add --namespace when create backup secret

---

charts/tidb-backup/templates/scripts/_start_restore.sh.tpl

this pr fixes:#509
Tests 
- E2E test [done]
- Stability test [WIP]
- Manual test [done]
Code changes
```release-note
None
```

fix restore script bug

---

tests/actions.go
tests/images/stability-test/Dockerfile

Modified the process in order to properly execute stability testing。
Modify stability test DockerFile and change the location to clean webhoook.yaml
Tests 
- E2E test
Code changes
```release-note
```
NONE

pause-upgrade stability test

---

tests/actions.go
tests/cmd/stability/main.go

1. reduce wait time
2. make stability test correct
change go code
Tests 
- E2E test
Code changes
```release-note
None
```

reduce wait time and fix stablity test

---

pkg/manager/member/tidb_member_manager.go

fix bug in reporting assigned nodes of tidb members
Code changes
```release-note
NONE
```

stable scheduling: fix bug in reporting assigned nodes of tidb members

---

deploy/aliyun/README-CN.md
deploy/aliyun/README.md
deploy/aliyun/variables.tf
deploy/aws/README.md
deploy/aws/variables.tf
deploy/gcp/README.md
deploy/gcp/variables.tf
docs/aws-eks-tutorial.md
docs/cli-manual.md
docs/local-dind-tutorial.md

The previous PR #520 didn't change tidb version in dind/aws/aliyun/gcp deployment. This is a supplement.
Bump the default tidb version in all platform deployment.
Tests 
- No code
Code changes
Side effects
- None
```release-note
Upgrade default TiDB version to v3.0.0-rc.1 in dind/aws/aliyun/gcp deployment.
```

upgrade tidb version in related documentations

---

tests/actions.go
tests/cmd/stability/main.go

fixes https://github.com/pingcap/tidb-operator/issues/498
Tests 
Code changes
```release-note
NONE
```

stability test: Add stable scheduling e2e test case

---

go.mod
manifests/create-cert.sh
manifests/webhook.yaml
tests/actions.go

Make webhook configurable
Use shell script to patch namespace to webhook.yaml 
Tests 
- E2E test
Code changes
- Has scripts change
```release-note
```
None

make webhook configurable

---

.gitignore
docs/cli-manual.md
pkg/tkctl/readable/printers.go

Tests 
- Manual test
@tennix @weekface @xiaojingchen PTAL
```release-note
`tkctl get` can show cpu usage correctly now.
```

Fix tkctl get cpu info rendering

---

tests/actions.go
tests/cmd/e2e/main.go
tests/cmd/stability/main.go

Check the pause upgrade feature only when upgrading cluster 2. 
Check the pause upgrade feature only once instead of every upgrade time
Tests 
- E2E test
Code changes
```release-note
NONE
```

Fix stability tidb pause case

---

charts/tidb-backup/templates/backup-job.yaml
charts/tidb-backup/templates/backup-pvc.yaml
charts/tidb-backup/values.yaml
charts/tidb-cluster/templates/scheduled-backup-pvc.yaml
docs/backup-restore.md
docs/operation-guide.md
docs/references/tidb-backup-configuration.md

More documentations!😆
Besides, for better user experience:
- the adhoc backup name is generated according to the date now.
- add the cluster name label for both adhoc-backup PVC and scheduled-backup PVC, in order to filter them easily.
- Manual Test 👌
Code changes
```release-note
Adhoc backup now appends the start time to the PVC name by default.
```
Preview: https://github.com/aylei/tidb-operator/blob/backup-doc/docs/backup-restore.md
@tennix @weekface @xiaojingchen @lilin90 PTAL

Refine backup and restore documentation

---

Makefile
tools.json

https://github.com/dominikh/go-tools/blob/5a4a2f4a438d01ba03c591f88ef312005a05063b/doc/2019.1.html
```
At the core of the 2019.1 release lies the grand restructuring of all of the staticcheck tools.
All of the individual checkers, as well as megacheck, have been merged into a single tool,
which is simply called staticcheck.
```
So we use `staticcheck` instead of `megacheck`.
This pr fixes: #546
Tests 
- No code
Code changes
Side effects
```release-note
NONE
```

use staticcheck instead of megacheck

---

tests/cmd/e2e/main.go
tests/cmd/stability/main.go
tests/util.go

change the affinity setting of restore cluster
Tests 
- E2E test [done]
- Stability test 
- Manual test [done]
- No code
Code changes
```release-note
NONE
```

fix the bug of stability test case of disaster tolerance

---

deploy/gcp/README.md
deploy/gcp/data.tf
deploy/gcp/main.tf
deploy/gcp/outputs.tf
deploy/gcp/variables.tf
deploy/gcp/versions.tf

This PR fixes #522 as well as upgrading the GCP terraform script to 0.12 compatibility. It will break backwards compatibility, but terraform will not run until upgraded
- Previously, bastion instance zone was hardcoded, script now checks `gcloud compute regions describe name-of-region` to see what zones are available in the region, and grabs the first one in the result
- Upgraded to be compatible with terraform 0.12
- Usability: Previously, when doing `terraform destroy` it would frequently abort because GCP does not allow deleting simultaneous node pools. The user would then have to re-run the command. This no longer happens, the downside is that `terraform apply` will run a little slower as the node pools are now created and destroyed sequentially.
Tests 
- Manual test (add detailed …

Gke terraform upgrade to 0.12 and fix bastion instance zone to be region agnostic

---

CHANGELOG.md
ROADMAP.md
charts/tidb-cluster/values.yaml
charts/tidb-operator/values.yaml
deploy/gcp/variables.tf
pkg/tkctl/cmd/upinfo/upinfo.go
tests/actions.go
tests/manifests/stability/stability.yaml

- Release TiDB Operator v1.0.0-beta.3
- adjust stability parameters
Tests 
- No code
Code changes
Side effects
```release-note
NONE
```

release v1.0.0-beta.3

---

deploy/aws/README.md
deploy/aws/data.tf
deploy/aws/main.tf
deploy/aws/variables.tf

This should close #514 
- Split `subnets` to `private_subnet_ids`and `public_subnet_ids`, to correctly put resources into different network.
- Add `cluster_name` to helm release name, making pod names unique
Tests 
Code changes
- Has Terraform change
Side effects
- It may cause error when using `terraform` with new code to manage an cluster deployed by old versions.
- N/A
```release-note
```

deploy/aws: split public and private subnets when using existing vpc

---

deploy/aws/README.md
deploy/gcp/README.md
docs/aws-eks-tutorial.md
docs/local-dind-tutorial.md
docs/minikube-tutorial.md
docs/setup.md

Fix #552 
`helm` v3.0.0+ are not supported yet.
Tests 
- No code
Code changes
Side effects
- N/A
- N/A
```release-note
```

docs: note helm versions in deployment docs

---

CHANGELOG.md
pkg/tkctl/debug/launcher.go

- fix gofmt
Tests 
Code changes
Side effects
```release-note
NONE
```

fix release

---

charts/tidb-cluster/templates/scripts/_start_scheduled_backup.sh.tpl

fix tidb user of scheduled backup script
Tests 
- E2E test
Code changes
Side effects
```release-note
fix tidb user of scheduled backup script
```

fix tidb user of scheduled backup script

---

Makefile

This makes the binaries significantly smaller
before:
30M     images/tidb-operator/bin/tidb-admission-controller
47M     images/tidb-operator/bin/tidb-controller-manager
42M     images/tidb-operator/bin/tidb-discovery
32M     images/tidb-operator/bin/tidb-scheduler
after:
30M     images/tidb-operator/bin/tidb-admission-controller
36M     images/tidb-operator/bin/tidb-controller-manager
32M     images/tidb-operator/bin/tidb-discovery
24M     images/tidb-operator/bin/tidb-scheduler
Note that stack traces still work, this information is just for the debugger. Set DEBUGGER=1 to build for debuggers. Eventually we may need to distribute both of these.
This issue came up when I was adding a new binary and it was initially 40M in size! After some changes I made, even after adding that binary the …

build without debugger symbols

---

pkg/manager/member/tikv_member_manager.go
pkg/manager/member/tikv_member_manager_test.go
pkg/manager/member/tikv_upgrader.go
pkg/manager/member/tikv_upgrader_test.go

this pr fixes #567 
- Unit test 
- E2E test 
Code changes

fix bug that tikv status is always upgrade

---

manifests/gke/local-ssd-optimize.yaml
manifests/gke/local-ssd-provision/local-ssd-provision.yaml

local SSD provision: use a single install command

---

charts/tidb-operator/values.yaml

Use scheduler image instead of hyperkube which is unnecessary and very large.
```
gcr.io/google-containers/hyperkube                               v1.12.2                      3e4497624dd0        7 months ago        635MB
gcr.io/google_containers/kube-scheduler                          v1.12.2                      d6d57c76136c        7 months ago        58.3MB
```
```release-note
Scheduler image is updated to use "k8s.gcr.io/kube-scheduler" which is much smaller than "gcr.io/google-containers/hyperkube". You must pre-pull the new scheduler image into your airgap environment before upgrading.
```

Use kube-scheduler image instead of hyperkube

---

tests/actions.go
tests/pkg/webhook/pods.go

Tests 
- E2E test
Code changes
Side effects
```release-note
NONE
```

pass TiKV upgrade case

---

pkg/label/label.go
pkg/manager/member/pd_member_manager.go
pkg/manager/member/pd_member_manager_test.go
pkg/manager/member/pd_upgrader.go
pkg/manager/member/pd_upgrader_test.go
pkg/manager/member/utils.go

close #609 
Support force upgrade if PD cluster is unavailable
Tests 
- Unit test
- E2E test
- PD cluster image pull backoff during the creation
- PD cluster pending due to affinity setting during the creation
- PD cluster is unavailable after creation
- PD cluster is running normally
- PD cluster only has 1 replica
Code changes
```
Support force upgrade when PD cluster is unavailable.
To enable force upgrade:
kubectl annotate --overwrite tc ${releaseName} -n ${namespace} tidb.pingcap.com/force-upgrade=true
To disable force upgrade:
kubectl annotate tc ${releaseName} -n ${namespace} tidb.pingcap.com/force-upgrade-
Note: Force …
```

support force upgrade when pd cluster is unavailable

---

pkg/manager/member/pd_member_manager.go
pkg/manager/member/tidb_member_manager.go
pkg/manager/member/tikv_member_manager.go

Improve the readability of the code for processing `LastTransitionTime`
Tests 
- Unit test
- E2E test
- No code
Code changes
```release-note
None
```

improving the readability of some code

---

deploy/aws/bastion.tf
deploy/aws/clusters.tf
deploy/aws/tidb-cluster/cluster.tf
deploy/aws/tidb-cluster/local.tf
deploy/aws/tidb-operator/main.tf
deploy/aws/versions.tf

- fix hard-code chart version, close #640 
- fix unreachable bastion, for #634 
- adjust tidb-cluster no-wait to avoid scheduled backup pvc blocking, close #633 
- add version check, a supplement for #636 
- disable pd node public_ip
Tests 
- Manual test
Code changes
- Has terraform scripts change
```release-note
Fix several usability problems for AWS terraform deployment
```
@tennix @gregwebs @weekface @DanielZhangQD PTAL

Several small fixes for terraform aws

---

charts/tidb-backup/templates/scripts/_start_backup.sh.tpl
charts/tidb-backup/templates/scripts/_start_restore.sh.tpl
charts/tidb-cluster/templates/scripts/_start_scheduled_backup.sh.tpl
tests/actions.go
tests/cmd/e2e/main.go

fixes: #643 
#634 
Tests 
- Unit test
- E2E test
Code changes
Side effects
```release-note
fix scheduled backup bug: segmentation fault when backup user's password is empty
```

bugfix: segmentation fault when backup user's password is empty

---

CHANGELOG.md
ROADMAP.md
charts/tidb-cluster/values.yaml
charts/tidb-operator/values.yaml
deploy/aws/README.md
deploy/aws/tidb-cluster/variables.tf
deploy/aws/tidb-operator/variables.tf
deploy/aws/variables.tf
deploy/gcp/variables.tf
tests/manifests/stability/stability.yaml

Tests 
- No code
Code changes
Side effects
```release-note
NONE
```

release v1.0.0-rc.1

---

charts/tidb-cluster/values.yaml

https://github.com/pingcap/tidb-operator/issues/656
values.yaml from TiDB cluster helm chart is updated
The default storage size for pump services is increased from 10GiB to 20GiB because pump introduced a new configuration `stop-write-at-available-space`, which comes with a default value of 10GiB. Deploying with the old default storage size, 10GiB, immediately results in `no available space` error in pump services.
Tests 
- Unit test
1. Deploy TiDB operator and cluster with the updated helm charts to AWS
Code changes
Side effects
- N/A
- N/A
```release-note
NONE
```

Increase the default storage size for pump from 10Gi to 20Gi

---

charts/tidb-cluster/values.yaml
deploy/aliyun/README-CN.md
deploy/aliyun/README.md
deploy/aliyun/variables.tf
deploy/aws/README.md
deploy/aws/clusters.tf
deploy/aws/variables.tf
deploy/gcp/README.md
deploy/gcp/variables.tf
deploy/modules/aws/tidb-cluster/variables.tf
deploy/modules/share/tidb-cluster-release/variables.tf
docs/aws-eks-tutorial.md
docs/cli-manual.md
docs/local-dind-tutorial.md
images/tidb-operator-e2e/tidb-cluster-values.yaml
tests/config.go
tests/manifests/e2e/e2e.yaml

upgrade default TiDB version to v3.0.1
Tests 
- Unit test
- E2E test
Code changes
```release-note
ACTION REQUIRED: upgrade default TiDB version to v3.0.1
```

Upgrade default TiDB version to v3.0.1

---

deploy/gcp/data.tf
deploy/gcp/main.tf
deploy/gcp/prod.tfvars
deploy/gcp/small.tfvars
deploy/gcp/variables.tf

Closes #615 
GKE master node is sized initially to expect 5 or fewer nodes when first provisioned, or the size of the default node pool. Previously, the initial node count for the default pool was 1 (3 total because one per availability zone), so when the rest of the node pools get provisioned, GKE would then upgrade the master node to accommodate the rest of the nodes. This change sets the initial node count of the default pool to be equal to the sum of the node counts for the other pools (pd, tikv, tidb, monitor). With this, the master node is correctly sized and does not upgrade shortly after creating the cluster, as it did previously.
Tests 
* `terraform apply` to GKE
* When all done, wait and see if master node auto upgrades
Code …

Sets node count for default pool equal to total desired node count to correctly size master

---

charts/tidb-operator/templates/controller-manager-deployment.yaml
charts/tidb-operator/values.yaml
cmd/controller-manager/main.go
images/tidb-operator-e2e/tidb-operator-values.yaml

Automatic failover has been verified by a large number of stability tests, so we should turn it on by default.
Tests 
- No code
Code changes
Side effects
```release-note
turn on automatic failover feature by default
```

turn on automatic failover

---

charts/tidb-cluster/templates/tidb-cluster.yaml
charts/tidb-cluster/values.yaml

Enable configmap rollout by default and quote configmap digest suffix
Tests 
- E2E test
Code changes
Side effects
- The tidb cluster will perform a rolling update when user upgrade chart from the prior versions.
```release-note
Configmap rollout is now enabled by default. 
```

Enable configmap rollout by default and quote configmap digest suffix 

---

docs/CONTRIBUTING.md

Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
```

meke -> make

---

docs/CONTRIBUTING.md

#689 
Tests 
- No code
Code changes
Side effects
NONE
NONE
NONE
```release-note
```

git remote add upstream using https

---

charts/tidb-cluster/values.yaml

TiKV metrics port cannot be accessed from Prometheus by default.
Also, we have to notice users to keep this configuration when they customize the `tikv.config`
Specify the tikv metrics listen address as `0.0.0.0`
Tests 
Code changes
Side effects
```release-note
Fix TiKV metrics monitoring in default setup.
```
@tennix @DanielZhangQD @weekface PTAL

Specify tikv status address to fix monitoring

---

CHANGELOG.md

This PR updates v1.0.0 changelog description, and fixes typos and format.
Only changelog
N/A
N/A

changelog: update wording and fix format for v1.0.0

---

deploy/gcp/main.tf

Closes #708 
This incorporates changes from @aylei's' commit https://github.com/aylei/tidb-operator/commit/47be0a7b388b5023f926571446b9a3390a98ff7c in his fork. This prevents node pools from being recreated.
In #673 the `initial_node_count` variable in the cluster resource was changed to depend on the tidb/monitor/tikv/pd count variables. Because of this, when a count variable is changed to scale out, the cluster resource is recreated by terraform. To get around this, a literal value of `5` is used. According to https://kubernetes.io/docs/setup/best-practices/cluster-large/#size-of-master-and-master-components this will cause a master node to be created that can accommodate up to 100 nodes.
Additional ordering in the resource creation to ensure that the tidb-cluster helm release is …

Terraform gke scale out fix

---

pkg/controller/service_control.go

Fix an incorrect condition judgment
The error handling for UpdateService is incorrect, this PR corrects it.
Tests 
- Unit test
- E2E test
Code changes
```release-note
Bug Fix: Fix error handling for UpdateService
```

pkg/controller: fix an incorrect condition judgment

---

pkg/scheduler/predicates/ha.go
pkg/scheduler/predicates/ha_test.go

cherry-pick https://github.com/pingcap/tidb-operator/pull/670 manually

cherry pick PR-670: document and improve HA algorithm

---

deploy/aliyun/README.md
deploy/aws/README.md
deploy/gcp/README.md

README.md had a number of outdated (404) links to pingcap.com/docs. This resolves that.

Update READMEs to point to correct docs URLs

---

cmd/controller-manager/main.go
pkg/controller/controller_utils.go
pkg/controller/pvc_control.go
pkg/manager/member/pd_scaler_test.go
pkg/manager/member/tikv_scaler.go
pkg/manager/member/tikv_scaler_test.go

This PR fixes #725 
Tests 
- Unit test
Code changes
Side effects
```release-note
Fix tikv scale in failure in some cases after tikv failover
```

Fix tikv scale in failure in some cases

---

charts/tidb-cluster/templates/drainer-statefulset.yaml
charts/tidb-cluster/templates/pump-statefulset.yaml
charts/tidb-cluster/values.yaml
tests/actions.go
tests/util.go

- add `affinity` to pump/drainer
- add e2e tests
- fix pump e2e test bug
Tests 
- E2E test
Code changes
Side effects
```release-note
add `affinity` to pump/drainer configration
```

add affinity to pump/drainer

---

tests/pkg/metrics/annotation_util.go

Signed-off-by: yeya24 <yb532204897@gmail.com>
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
```

some typo fix and comment cleanup

---

tests/actions.go

e2e:extend the wating time of CheckManualPauseTiDB process
Extends the wait time of the CheckManualPauseTiDB process to avoid test timeouts in extreme cases.
Tests 
- E2E test
Code changes

e2e:extend the wating time of CheckManualPauseTiDB process

---

charts/tidb-backup/templates/backup-job.yaml
charts/tidb-backup/values.yaml

#284
Add Tidb-backup helm chart job resource limits and requests.
Tests 
- E2E test
Code changes
Side effects
```release-note
NONE
```

Add tidb-backup job reource limits

---

tests/actions.go

v1.0.0 did't have [`affinity`](https://github.com/pingcap/tidb-operator/pull/746
) test case, we should't run the `affinity` case in v1.0.0
Tests 
- E2E test
Code changes
Side effects
```release-note
NONE
```

fix e2e test compatible with v1.0.0

---

deploy/gcp/manifests/local-ssd/overlays/terraform-local-ssd-provision.yaml

Remove duplicate key values.
```release-note
NONE
```

Remove duplicate key values

---

charts/tidb-cluster/templates/_helpers.tpl
charts/tidb-cluster/templates/drainer-configmap-rollout.yaml
charts/tidb-cluster/templates/drainer-statefulset.yaml
charts/tidb-cluster/templates/pump-configmap-rollout.yaml
charts/tidb-cluster/templates/pump-configmap.yaml
charts/tidb-cluster/templates/pump-statefulset.yaml
charts/tidb-cluster/templates/scripts/_start_drainer.sh.tpl
charts/tidb-cluster/templates/scripts/_start_pump.sh.tpl
charts/tidb-cluster/values.yaml
tests/actions.go
tests/cluster_info.go
tests/util.go

(cherry picked from commit a320e52236ba3ec4ad34b42afb800eb09e9f2305 manually)
auto-cherry-pick failed: https://github.com/pingcap/tidb-operator/pull/693#issuecomment-521077356

cherry pick PR-693: support `binlog.pump.config` configurations for pump and drainer

---

deploy/modules/gcp/tidb-cluster/main.tf
deploy/modules/gcp/tidb-cluster/variables.tf

Sometimes users may favor non-COS node images. This adds variables to configure image type for TiDB node pools.
Tests 
```release-note
terraform/gcp: Able to configure node image types for PD/TiDB/TiKV node pools.
```

terraform/gcp: Able to configure image type

---

charts/tidb-cluster/templates/scripts/_start_pump.sh.tpl

prevent pump progress from an exit with 0 if the pump become `offline`
, because it will be `online` again if the pod get restarted by `statefulset`.
Tests 
Code changes
Side effects
```release-note
prevent pump progress from an exit with 0 if the pump become `offline`
```

pump: prevent pump progress from an exit with 0 if the pump become `offline`

---

deploy/modules/gcp/tidb-cluster/main.tf

```hcl
length(data.google_compute_zones.available)
```
returns `5` for `us-west1`.
In `deploy/modules/gcp/tidb-cluster/main.tf` switches to 
```hcl
length(data.google_compute_zones.available.names)
```
which correctly reteurns `3`
Tests 
- Manual test (add detailed scripts or steps below):
- `terraform apply`
- When complete, note that number of pods is equal to the number of availability zones in the region (3 for us-west1).
- `terraform destroy`
Code changes
- Has Terraform changes
```release-note
NONE
```

Adds workaround for data.google_compute_zones.available weirdness

---

cmd/tkctl/main.go

fix #796 
Tests 
- Manual test
Code changes
Side effects
```release-note
fix tkctl log output exception
```

fix tkctl log output exception

---

deploy/modules/gcp/bastion/bastion.tf

Avoid name conflicts. Currently, when I try to deploy two GKE clusters, it will create two bastion instances with same firewall rule names.
```
Error: Error creating Firewall: googleapi: Error 409: The resource 'projects/smooth-tendril-207212/global/firewalls/allow-ssh-bastion' already exists, alreadyExists
on ../modules/gcp/bastion/bastion.tf line 1, in resource "google_compute_firewall" "allow_ssh_bastion":
1: resource "google_compute_firewall" "allow_ssh_bastion" {
Error: Error creating Firewall: googleapi: Error 409: The resource 'projects/smooth-tendril-207212/global/firewalls/allow-mysql-from-bastion' already exists, alreadyExists
on ../modules/gcp/bastion/bastion.tf line 15, in resource "google_compute_firewall" "allow_mysql_from_bastion":
15: resource "google_compute_firewall" …
```

deploy/gcp: Add prefix to avoid name conflicts

---

deploy/modules/gcp/tidb-cluster/data.tf
deploy/modules/gcp/tidb-cluster/main.tf

by default, the regional cluster will [choose 3 from all available zones]((https://cloud.google.com/kubernetes-engine/docs/concepts/regional-clusters#overview)). However, there are 4 zones in `us-central1` region.
Currently, we need to use `gcloud` command to retrieve the real number of node locations of the cluster.
See discussion: https://github.com/pingcap/tidb-operator/pull/788#issuecomment-523334689
Tests 
```release-note
NONE
```

deploy/gcp: Retrieve real number of node locations of the cluster

---

charts/tidb-drainer/values.yaml

https://github.com/pingcap/tidb-operator/issues/792
Default tidb-drainer config is adjusted to be compatible with the latest drainer config format.
To be more specific:
detect-interval is moved out from [syncer]
db-type value is changed from pb to file
compression is moved out from [syncer] and renamed to compressor
Tests 
1. Deploy tidb-drainer chart out-of-box to AWS
2. Drainer is successfully deployed and running
Code changes
Side effects
- N/A
```release-note
NONE
```

Fix default tidb-drainer config

---

charts/tidb-cluster/values.yaml

Tests 
- No code
Code changes
Side effects
```release-note
NONE
```

fix `extraLabels` description in `values.yaml`

---

charts/tidb-backup/templates/restore-job.yaml
charts/tidb-backup/values.yaml

Make tidb-backup to support  restore tidb clusters from a specified scheduled backup directory, while compatible with previous ad-hoc backup and restore method
Work as before
Tests 
- Manual test 
Code changes
Side effects
```release-note
support restore tidb cluster from a specified scheduled backup directory
```

support restore tidb cluster from a specified scheduled backup dir

---

charts/tidb-cluster/templates/scripts/_start_tikv.sh.tpl
charts/tidb-cluster/values.yaml

- add important parameters to tikv and tidb config
- add move `status-addr` to start script
Tests 
Code changes
Side effects
```release-note
NONE
```

chart: add important parameters to tikv and tidb config

---

charts/tidb-drainer/templates/drainer-configmap.yaml
charts/tidb-drainer/templates/drainer-service.yaml
charts/tidb-drainer/templates/drainer-statefulset.yaml

close #811 
Tests 
Code changes
No.

Keep the instance label of drainer same with the TiDB cluster in favor of monitoring

---

charts/tidb-cluster/templates/scripts/_start_pd.sh.tpl
charts/tidb-cluster/templates/scripts/_start_tikv.sh.tpl

See https://github.com/pingcap/tidb-operator/pull/774/files#r316750805.
Tests 
- E2E test
```release-note
NONE
```

chart/tidb-operator: Use HOSTNAME if POD_NAME is unset for backward compatibility.

---

deploy/modules/gcp/tidb-cluster/main.tf

GCP terraform was not creating tidb clusters when `tidb_version` was overriden with the right version number
Correctly passes tidb version through the modules
Tests 
Code changes
- Has terraform changes
Side effects
```release-note
NONE
```

Correctly uses tidb cluster version var when creating cluster

---

charts/tidb-cluster/templates/_helpers.tpl
charts/tidb-cluster/templates/tikv-importer-configmap.yaml
charts/tidb-cluster/templates/tikv-importer-service.yaml
charts/tidb-cluster/templates/tikv-importer-statefulset.yaml
charts/tidb-cluster/values.yaml
charts/tidb-lightning/.helmignore
charts/tidb-lightning/Chart.yaml
charts/tidb-lightning/secret.yaml
charts/tidb-lightning/templates/NOTES.txt
charts/tidb-lightning/templates/_helpers.tpl
charts/tidb-lightning/templates/configmap.yaml
charts/tidb-lightning/templates/job.yaml
charts/tidb-lightning/templates/persistentvolumeclaim.yaml
charts/tidb-lightning/templates/scripts/_start_data_retriever.sh.tpl
charts/tidb-lightning/templates/scripts/_start_lightning.sh.tpl
charts/tidb-lightning/templates/service.yaml
charts/tidb-lightning/values.yaml

Integrate tidb-lightning on k8s, this closes https://github.com/pingcap/tidb-operator/issues/347
Add tidb-lightning chart. The tikv-importer is inside the tidb-cluster chart and tidb-lightning is in a separate chart.
Tests 
Manual test (add detailed scripts or steps below)
Both the local and remote (S3) data sources are tested. The compressed sysbench dataset is 15GB, and the uncompressed dataset is 31GB. The restore time is `18m` while the sysbench prepare average time is `1h`
Code changes
Side effects
No
```release-note
Add tidb-lightning support
```

charts: Add tidb-lightning support

---

manifests/gke/local-ssd-provision/local-ssd-provision.yaml

- `defaults` includes `rw,data=ordered`
- `noatime` and `nodelalloc` are recommneded in https://pingcap.com/docs/v3.0/how-to/deploy/orchestrated/ansible/
- share mount options by using a variable
Tests 
```release-note
NONE
```

Update mount options in local volume provisioner

---

pkg/tkctl/cmd/cmd.go
pkg/tkctl/cmd/ctop/ctop.go
pkg/tkctl/cmd/debug/debug.go
pkg/tkctl/cmd/get/get.go
pkg/tkctl/cmd/info/info.go
pkg/tkctl/cmd/list/list.go
pkg/tkctl/cmd/upinfo/upinfo.go
pkg/tkctl/cmd/use/use.go
pkg/tkctl/readable/print_flags.go
pkg/tkctl/readable/printers.go

fix #821 and support for viewing details of a specific pod or PV
Tests 
- Manual test
1. Unify the output format of multiple clusters, remove the `NAMESPACE` column of PV. Change CLAIM colume of PV from `<pvc_name>` to `<namespace>/<pvc_name>`
```
$ tkctl get pd,tidb,volume -A
Cluster: test1/demo1
NAMESPACE   NAME         READY   STATUS    MEMORY          CPU             RESTARTS   AGE
test1       demo1-pd-0   1/1     Running   <none>/<none>   <none>/<none>   0          14d
test1       demo1-pd-1   1/1     Running   <none>/<none>   <none>/<none>   0          14d
test1       demo1-pd-2   1/1     Running   <none>/<none>   <none>/<none>   0          14d
NAMESPACE   NAME           READY   STATUS    MEMORY     CPU        RESTARTS   AGE
test1       demo1-tidb-0   2/2     Running   5Mi/50Mi …
```

improve tkctl get command output

---

charts/tidb-cluster/templates/scripts/_start_drainer.sh.tpl
charts/tidb-cluster/templates/scripts/_start_pump.sh.tpl
charts/tidb-drainer/templates/scripts/_start_drainer.sh.tpl

We allow users to specify a customized configuration file for `pump` and `drainer`, but if the user forget to configure the `data-dir` in config file or configure it wrongly, there are potential data loss risk.
This PR fix this problem.
Fix the `data-dir` via command line arguments.
Tests 
- E2E test
Code changes
```release-note
Fix the pump/drainer data dir to avoid potential data loss.
```

Fix the pump/drainer data dir to avoid data loss caused by bad configuration

---

deploy/gcp/tidbclusters.tf
deploy/modules/gcp/tidb-cluster/data.tf
deploy/modules/gcp/tidb-cluster/main.tf
deploy/modules/gcp/tidb-cluster/variables.tf
deploy/modules/gcp/tidb-operator/main.tf
deploy/modules/gcp/tidb-operator/outputs.tf

fixes #815 and other issues in refresh phrase.
For example, when `terraform apply` failed to create GKE cluster. In refreshing state, `jq` command will fail with this error:
```
Error: failed to execute "bash": jq: error (at <stdin>:1): Cannot iterate over null (null)
on ../modules/gcp/tidb-cluster/data.tf line 28, in data "external" "cluster_locations":
28: data "external" "cluster_locations" {
```
- module output variables are not available in refresh state, we can use them to set up dependencies or as creation arguments but should not use them as the ID of the resource or refreshing arguments (e.g. cluster name of node pool , kubeconfig file path of helm)
Tests 
```release-note
NONE
```

deploy/gcp: fix issues in refreshing state

---

charts/tidb-cluster/templates/config/_drainer-config.tpl
charts/tidb-cluster/values.yaml

https://github.com/pingcap/tidb-operator/issues/838
drainer config template from the tidb-cluster helm chart is changed to accept tidb and file as new drainer destDBType.
Tests 
1. Deploy drainer with `destDBType = "tidb"` -> replication is functional, and checkpoint table contains tso mapping
2. Deploy drainer with `destDBType = "mysql"` -> replication is functional, and checkpoint table doesn't contain tso mapping
3. Deploy drainer with `destDBType = "pb"` -> incremental backup is functional
4. Deploy drainer with `destDBType = "file"` -> incremental backup is functional
Code changes
Side effects
- N/A
- N/A
```release-note
NONE
```

Support file and tidb destDBType for drainer

---

charts/tidb-backup/templates/backup-job.yaml

ad-hoc backup will fail if use default backup name which is not rendered during helm install in backup-job.yaml.
Make helm render the backup name.
Tests 
- ad-hoc backup with the default name
- ad-hoc backup with the specified name
Code changes
```release-note
The ad-hoc backup will fail if use default backup name which is not rendered during helm install in backup-job.yaml.
```

fix ad-hoc full backup failure due to incorrect claimName

---

charts/tidb-backup/values.yaml
charts/tidb-cluster/values.yaml
tests/actions.go

add recommendations options to `mydumper`:
https://pingcap.com/docs/v3.0/how-to/maintain/backup-and-restore/#best-practices-of-full-backup-and-restoration-using-mydumper-loader
- `-t 16`: means 16 threads are used to export the data.
- `-F 64`: means a table is partitioned into chunks and one chunk is 64MB.
- `--skip-tz-utc`: the purpose of adding this parameter is to ignore the inconsistency of time zone setting between MySQL and the data exporting machine and to disable automatic conversion.
Tests 
Code changes
Side effects
```release-note
add recommendations options to mydumper: `-t 16 -F 64 --skip-tz-utc`
```

add recommendations options to mydumper

---

charts/tidb-backup/values.yaml
charts/tidb-cluster/values.yaml

Update image tag to pingcap/tidb-cloud-backup:20190828, in this version, rclone is introduced to upload and download the backup data https://github.com/pingcap/tidb-cloud-backup/pull/4
Tests 
- E2E test
Code changes
Side effects
```release-note
Update the default backup image to pingcap/tidb-cloud-backup:20190828
```

Update tidb-cloud-backup image tag

---

charts/tidb-lightning/templates/job.yaml
charts/tidb-lightning/templates/persistentvolumeclaim.yaml
charts/tidb-lightning/templates/scripts/_start_lightning.sh.tpl
charts/tidb-lightning/values.yaml

Allow ad-hoc data to be restored with tidb-lightning.
Add an option to support ad-hoc backup.
Tests 
Manual test with scheduled backup on AWS.
Code changes
Side effects
None
```release-note
Support add-hoc data source to be restored with tidb-lightning chart
```

charts/tidb-lightning: Add adhoc data source for lightning

---

charts/tidb-cluster/templates/drainer-statefulset.yaml
charts/tidb-cluster/templates/monitor-deployment.yaml
charts/tidb-cluster/templates/pump-statefulset.yaml
charts/tidb-cluster/templates/scheduled-backup-cronjob.yaml
charts/tidb-cluster/templates/tidb-initializer-job.yaml
charts/tidb-cluster/values.yaml

close #852 
Tests 
- E2E test
Code changes
Side effects
```release-note
Support configuring resources requests and limits for all containers of tidb cluster
```

Support configuring resources requests and limits for all containers of tidb cluster

---

charts/tidb-cluster/templates/config/_prometheus-config.tpl
charts/tidb-cluster/templates/monitor-rbac.yaml

Allow Prometheus to scrape cross namespace pods. The tidb-lightning chart may be deployed in the upstream tidb cluster to use the adhoc backup PVC. So Prometheus needs to scrape metrics cross namespace.
The rbac rule of Prometheus changed to use cluster role and cluster role binding in order scrape cross namespace.
Tests 
Manual test
Code changes
Side effects
None
- Need to cherry-pick to the release branch release-1.1
```release-note
None
```

charts: allow cross namespace metrics scraping

---

charts/tidb-operator/templates/controller-manager-deployment.yaml
charts/tidb-operator/templates/scheduler-deployment.yaml
charts/tidb-operator/values.yaml

Support tidb-operator to spec nodeSelector, affinity and tolerations.
tidb-operator Chart
Tests 
- No code
Code changes
Side effects
```release-note
Support tidb-operator to spec nodeSelector, affinity and tolerations.
```

Add tidb operator node selector

---

charts/tidb-operator/templates/controller-manager-deployment.yaml
charts/tidb-operator/values.yaml

Make the latest charts compatible with the old controller manager
Tests 
- Manual test
Code changes
Side effects
```release-note
make the latest  charts compatible with the old controller manager
```

compatible with the old controller manager

---

pkg/manager/member/pd_upgrader.go
pkg/manager/member/pd_upgrader_test.go
pkg/manager/member/tidb_upgrader.go
pkg/manager/member/tidb_upgrader_test.go
pkg/manager/member/tikv_upgrader.go
pkg/manager/member/tikv_upgrader_test.go

this PR fixes: #784
Add logic to prevent that TiDB operator setting partition before `statefulSet`'s `updateRevision` changed and sync to `TidbCluster`
Tests 
- Unit test
- E2E test
Code changes
```release-note
NONE
```

pkg/manager/member: Fix setting StatefulSet partition bug 

---

manifests/create-cert.sh
manifests/patch-ca.sh
pkg/label/label.go
pkg/tkctl/cmd/upinfo/upinfo.go
pkg/webhook/statefulset/statefulset.go

This PR resolve #866 
Tests 
- Manual test 
* I have tested this PR many times in IDC k8s,  and already have tikv's R&D used this feature in IDC k8s.
Code changes
Side effects
```release-note
support canary release for tikv component
```

support canary release for tikv

---

deploy/gcp/tidbclusters.tf
deploy/modules/gcp/tidb-operator/main.tf

fix #859 
we should not create the file again with its content. terraform will not
skip creation even if the content does not change. so terraform will
destroy the file and the new file cannot be created anymore
Tests 
Steps to test:
- terraform apply -var-file small.tfvars -state small.tfstate
- terraform apply -var-file small.tfvars -var 'tidb_version=v3.0.2' -state small.tfstate
- terraform refresh -var-file small.tfvars -var 'tidb_version=v3.0.2' -state small.tfstate
- terraform destroy -var-file small.tfvars -var 'tidb_version=v3.0.2' -state small.tfstate
```release-note
deploy/gcp: fix an issue that kubeconfig may be destroyed in apply phrase
```

deploy/gcp: fix apply issue and simplify terraform configuration

---

charts/tidb-operator/templates/controller-manager-deployment.yaml

This breaks CI and is fixed in later PR, so not necessary to keep in master
Fix broken CI on master after #750 is merged
The CI doesn't test TLS enabled cluster yet, so no need to keep that config in master
Tests 
- No code
Code changes
Side effects
- Manual added secret for TLS server won't work, but that doesn't matter as later PR fix it
- #750 
```release-note
```

tls: fix temp volume configs for controller-manager

---

Makefile

because our projects are using `go mod` now, we can safely make `GO111MODULE=on` by default, use `GO111MODULE=off` when necessary.
```release-note
NONE
```

make GO111MODULE=on by default

---

hack/cherry_pick_pull.sh

Easier to cherry-pick a PR into release branches.
Tests 
- Manual test
Example:
`GITHUB_USER=<name> ./hack/cherry_pick_pull.sh release-1.1 887`
https://github.com/pingcap/tidb-operator/pull/888 
```release-note
NONE
```

Add k8s cherry-pick script: hack/cherry_pick_pull.sh

---

pkg/discovery/discovery.go
pkg/discovery/discovery_test.go

Change port in the URL returned by discovery for `--join` parameters from `2380` to `2379`.
As per comment in [#1682](https://github.com/pingcap/pd/issues/1682), `2379` is the correct port for `--join`.
While `--init-cluster` uses `2380` as the port, and discovery reads member list from PD, which also uses port `2380`, the only change is to replace port `2380` with `2379` when building `--join` parameters for PD instances trying to join the cluster.
Tests 
Code changes
The current approach of using `2380` for `--join` works when PD instances use plain connections, but when enable TLS encrypted connections, it fails to start etcd server. See comments in …

discovery: use port 2379 for cmdline parameters

---

charts/tidb-cluster/templates/config/_prometheus-config.tpl
charts/tidb-cluster/templates/monitor-rbac.yaml
charts/tidb-cluster/values.yaml

Fixes #862. #854 enabled cross-namespace access in the tidb-cluster deployment. 
By default use the previous code. Add an option to use new code.
This maintains backwards compatibility with the previous chart.
Tests 
I deployed both versions to a local kind cluster
Code changes
This maintains backwards compatibility. Most users won't need to change this setting.
```release-note
Add an option to monitor across namespaces
```

by default, don't give montior any cross-namespace access

---

pkg/tkctl/alias/alias.go
pkg/tkctl/cmd/get/get.go
pkg/tkctl/readable/printers.go

https://github.com/pingcap/tidb-operator/issues/564
Adding one more column to show store state for each tikv by tkctl get and removing `printTikv` handler cause printing single tikv pod is not supported for tkctl now.
example:
```bash
$ ./tkctl get tikv -t tidb --namespace tidb
NAME          READY   STATUS    MEMORY          CPU             RESTARTS   AGE     STOREID   STORE STATE
tidb-tikv-0   1/1     Running   <none>/<none>   <none>/<none>   0          3d21h   4         Up
tidb-tikv-1   1/1     Running   <none>/<none>   <none>/<none>   0          3d21h   5         Up
tidb-tikv-2   1/1     Running   <none>/<none>   <none>/<none>   0          3d21h   1         Up
```
Moving the steps which printed the extra columns for tikv Into `printTikvList` function in `/pkg/tkctl/readable` from …

add store state for tkctl get tikv

---

charts/tidb-cluster/templates/scripts/_initialize_tidb_users.py.tpl
charts/tidb-cluster/templates/tidb-initializer-job.yaml

https://github.com/pingcap/tidb-operator/issues/921
For now, root password reset is not optional during sql intialization.
Editing the job template and python script for sql initialization.
Tests 
Code changes
Side effects
- N/A
- N/A
NONE

make rootpasswordreset optional

---

charts/tidb-cluster/templates/scripts/_initialize_tidb_users.py.tpl
charts/tidb-cluster/templates/tidb-initializer-job.yaml
charts/tidb-cluster/values.yaml

https://github.com/pingcap/tidb-operator/issues/899
It will be user-friendly if the sql of tidb initialization is supported to be read from configmap. and the previous way to init sql is still work.
Make initSql from configmap in `tidb-cluster` chart have a higher priority than iniSql in `values.yaml`
Tests 
Code changes
Side effects
- N/A
- N/A
NONE

add option to initSql from Configmap

---

charts/tidb-cluster/values.yaml
tests/actions.go

- fix drainer misconfiguration, fixes: #938 
from:
```
...
```
to:
```
...
```
Tests 
- E2E test
Code changes
Side effects
```release-note
fix drainer misconfiguration
```

Fix drainer misconfiguration

---

pkg/controller/controller_utils.go
pkg/controller/controller_utils_test.go
tests/cmd/e2e/main.go

fix bug in https://github.com/pingcap/tidb-operator/pull/942.
We should use GB/MB rather than GiB/MiB for backward compatibility with old TiKV versions.
Tests 
Unit test
E2E test
```release-note
```

Should use GB/MB rather than GiB/MiB for backward compatibility with old TiKV versions

---

deploy/modules/aliyun/tidb-cluster/values/default.yaml
deploy/modules/aws/tidb-cluster/values/default.yaml
deploy/modules/gcp/tidb-cluster/values/default.yaml

https://github.com/pingcap/tidb-operator/issues/879
The default externalTrafficPolicy is now set to be Local
Tests 
1. Deploy to AWS from /tidb-operator/deploy/aws out-of-box
2. Run `kubectl describe service my-cluster-tidb -n my-cluster` and verify the value of externalTrafficPolicy.
Code changes
Side effects
- N/A
```release-note
NONE
```

Set the default externalTrafficPolicy to be Local for TiDB service

---

deploy/aliyun/versions.tf
deploy/gcp/main.tf
deploy/gcp/tidbclusters.tf
deploy/gcp/variables.tf
deploy/gcp/versions.tf

Cherry pick of #959 on release-1.1.
#959: add provider version constraint for GCP and Aliyun

Automated cherry pick of #959: add provider version constraint for GCP and Aliyun

---

pkg/manager/member/pd_scaler_test.go
pkg/manager/member/pd_upgrader.go
pkg/manager/member/pd_upgrader_test.go
pkg/manager/member/tidb_upgrader.go
pkg/manager/member/tidb_upgrader_test.go
pkg/manager/member/tikv_scaler_test.go
pkg/manager/member/tikv_upgrader.go
pkg/manager/member/tikv_upgrader_test.go

Cherry pick of #912 on release-1.1.
#912: fix tidb-operator crash when user modify sts upgrade

Automated cherry pick of #912: fix tidb-operator crash when user modify sts upgrade

---

pkg/manager/member/tidb_failover.go
pkg/manager/member/tidb_failover_test.go
pkg/manager/member/tikv_failover.go
pkg/manager/member/tikv_failover_test.go

https://github.com/pingcap/tidb-operator/pull/965, added a `maxFailoverCount ` limit to TiKV, set it to `3` in `values.yaml`. But the old `TidbCluster` object is `0`, it can't failover after upgrade the tidb-operator.
To ensure compatibility, we should keep it no failover count limit if `maxFailoverCount` is `0`.
Tests 
- Unit test
Code changes
Side effects
```release-note
NONE
```

do not limit failover count when maxFailoverCount not greater than 0

---

deploy/aliyun/main.tf
deploy/aliyun/variables.tf

fix https://github.com/pingcap/tidb-operator/issues/970
Support values file customization for tidb-operator
Tests 
tidb-operator can be customized with specific values.yaml
Code changes
- Has terraform scripts change
```release-note
fix values file customization for tidb-operator on aliyun
```

fix values file customization for tidb-operator on aliyun

---

manifests/gke/local-ssd-provision/local-ssd-provision.yaml

`apiVersion: extensions/v1beta1` has marked DaemonSet as obsolete, switching to `apps/v1`
`apiVersion: extensions/v1beta1` has marked DaemonSet as obsolete
?
```release-note
NONE
```

fix apiVersion for DaemonSet

---

.github/workflows/ci.yaml

fixes https://github.com/pingcap/tidb-operator/issues/1004
Add a github actions job to run CI checks
Tests 
Unit test
E2E test
Code changes
```release-note
```

Add a github actions job to run CI checks

---

tests/cmd/e2e/main.go

because we share a machine to run e2e tests, if we don't free resources, a lot of processes will run in the machine even if no e2e tests are running.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
```

e2e: free resources on successful runs

---

tests/actions.go
tests/cmd/stability/main.go

close #1029 
Only expect upgrade complete when rollback bad conf.
Tests 
Side effects
- Need to cherry-pick to the release-1.0 branch
- Need to cherry-pick to the release-1.1 branch
```release-note
Stability: only expect upgrade complete when rollback bad configuration.
```

Stability: only expect upgrade complete when rollback bad conf

---

tests/actions.go
tests/cmd/stability/main.go

close #1035 
Tests 
- E2E test
```release-note
Enable ConfigMapRollout by default in stability test.
```

ConfigMapRollout should be enabled by default in stability test

---

deploy/modules/aliyun/tidb-operator/operator.tf
deploy/modules/gcp/tidb-cluster/main.tf
deploy/modules/share/tidb-cluster-release/data.tf
deploy/modules/share/tidb-cluster-release/main.tf

fix https://github.com/pingcap/tidb-operator/issues/1043
Wait for LB ready before computing output data
Tests 
- AWS test
Outputs:
bastion_ip = [
"54.184.41.97",
]
default-cluster_monitor-dns = aeb62d185f56d11e9aeb70ae67ff0b7e-1988083749.us-west-2.elb.amazonaws.com
default-cluster_tidb-dns = aeb748195f56d11e9aeb70ae67ff0b7e-25bbd4125f96646b.elb.us-west-2.amazonaws.com
eks_endpoint = https://3A07AB19D3A05BD1BF7B170A276FE317.yl4.us-west-2.eks.amazonaws.com
eks_version = 1.12
kubeconfig_filename = credentials/kubeconfig_dan-eks
region = us-west-2
- GKE test
Outputs:
how_to_connect_to_default_cluster_tidb_from_bastion = mysql -h 172.31.252.29 -P 4000 -u root
how_to_set_reclaim_policy_of_pv_for_default_tidb_cluster_to_delete = kubectl …

tidb loadbalancer output is empty after terraform apply

---

deploy/modules/aliyun/tidb-operator/operator.tf
deploy/modules/gcp/tidb-cluster/main.tf
deploy/modules/share/tidb-cluster-release/data.tf
deploy/modules/share/tidb-cluster-release/main.tf

Cherry pick of #1045 on release-1.0.
#1045: tidb lb is empty after terraform apply

Automated cherry pick of #1045: tidb lb is empty after terraform apply

---

.gitignore
pkg/tkctl/cmd/version/version.go

Cherry pick of #1065 on release-1.0.
#1065: Fix tkctl version does not work when the release name is

Automated cherry pick of #1065: Fix tkctl version does not work when the release name is

---

pkg/manager/member/pd_member_manager.go
pkg/manager/member/pd_member_manager_test.go
pkg/manager/member/tidb_member_manager.go
pkg/manager/member/tidb_member_manager_test.go
pkg/manager/member/tikv_member_manager.go
pkg/manager/member/tikv_member_manager_test.go
tests/cmd/e2e/main.go

fixes #1042 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
```

unit tests for hostnetwork and run e2e test conditionally

---

.github/workflows/ci.yaml
Makefile

Github action treats `go test` logs as errors.
Note that even if we disabled verbose logging, logs will be printed when the test fails.
Tests 
- Unit test
- E2E test
Code changes
```release-note
```

Disable verbose logging and coverage by default and enable -race in CI

---

CHANGELOG.md
charts/tidb-cluster/values.yaml
charts/tidb-operator/values.yaml
deploy/aliyun/variables.tf
deploy/aws/variables.tf
deploy/gcp/variables.tf
deploy/modules/aliyun/tidb-cluster/variable.tf
deploy/modules/aliyun/tidb-operator/variables.tf
deploy/modules/aws/tidb-cluster/variables.tf
deploy/modules/aws/tidb-operator/variables.tf
deploy/modules/gcp/tidb-cluster/variables.tf
deploy/modules/gcp/tidb-operator/variables.tf
deploy/modules/share/tidb-cluster-release/variables.tf
tests/manifests/stability/stability.yaml

Tests 
Code changes
Side effects
```release-note
NONE
```

release v1.0.2

---

charts/tidb-cluster/values.yaml
deploy/modules/aliyun/tidb-cluster/values/default.yaml
deploy/modules/gcp/tidb-cluster/values/default.yaml
pkg/controller/controller_utils.go
pkg/label/label.go
pkg/manager/member/tidb_member_manager.go
pkg/manager/member/tidb_member_manager_test.go
pkg/manager/member/tikv_member_manager.go
pkg/manager/member/tikv_member_manager_test.go

fix https://github.com/pingcap/tidb-operator/issues/880 for GCP  and Alibaba
Set net.ipv4.tcp_keepalive_time and net.core.somaxconn for tidb in init container
Set net.core.somaxconn for tikv in init container
Tests 
- Unit test
Code changes
```release-note
Support configuring net.ipv4.tcp_keepalive_time and net.core.somaxconn for TiDB and configuring net.core.somaxconn for TiKV.
```

set net.ipv4.tcp_keepalive_time and net.core.somaxconn for tidb and tikv in init container

---

charts/tidb-cluster/templates/drainer-statefulset.yaml
charts/tidb-cluster/templates/monitor-deployment.yaml
charts/tidb-cluster/templates/pump-statefulset.yaml
charts/tidb-cluster/templates/scheduled-backup-cronjob.yaml
charts/tidb-cluster/templates/tidb-initializer-job.yaml
charts/tidb-cluster/values.yaml

Cherry pick of #853 on release-1.0.
#853: Support confiugring resources requests and limits for all

Cherry pick of #853: configure resources for all containers

---

charts/tidb-backup/templates/backup-job.yaml
charts/tidb-backup/templates/restore-job.yaml
charts/tidb-backup/values.yaml
charts/tidb-cluster/templates/discovery-deployment.yaml
charts/tidb-cluster/templates/drainer-statefulset.yaml
charts/tidb-cluster/templates/monitor-deployment.yaml
charts/tidb-cluster/templates/pump-statefulset.yaml
charts/tidb-cluster/templates/scheduled-backup-cronjob.yaml
charts/tidb-cluster/templates/tidb-initializer-job.yaml
charts/tidb-cluster/templates/tikv-importer-statefulset.yaml
charts/tidb-drainer/templates/drainer-statefulset.yaml
charts/tidb-drainer/values.yaml
charts/tidb-lightning/templates/job.yaml
charts/tidb-lightning/values.yaml
charts/tidb-operator/templates/scheduler-deployment.yaml
charts/tidb-operator/values.yaml

This PR adds `timezone` support for [all charts](https://github.com/pingcap/tidb-operator/tree/master/charts), closes: #1123 
For the `tidb-cluster` chart, we already have the `timezone` option(default `UTC`). If the user does not change it to a different value(for example: `Aisa/Shanghai`), all pods will not be recreated.
If the user changes it to other value(for example: `Aisa/Shanghai`), all the related pods (add a `TZ` env) will be recreated(rolling update).
Regard other charts, we don't have a `timezone` option in their `values.yaml`. We add the `timezone` option in this PR. Whether the user uses the old `values.yaml` or the new `values.yaml`, all the related pods (add a `TZ` env) will not be recreated(rolling update).
The related pods include `pump`, `drainer`, `dicovery`, …

charts: add timezone support

---

hack/codegen.sh

We can only run this script correctly in the tidb-operator directory `./hack/codegen.sh`. If you run it in another directory, there will be problems.
run `./tidb-operator/hack/codegen.sh`
```
F1112 17:27:43.587879    7270 deepcopy.go:131] Failed loading boilerplate: open ./tidb-operator/hack/../hack/boilerplate.go.txt: no such file or directory
```
run `./codegen.sh`
```
bash: ../code-generator/generate-groups.sh: No such file or directory
```
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
- Need to update the …

make the script run anywhere correctly

---

Makefile
docs/CONTRIBUTING.md
go.mod
go.sum
tests/actions.go
tests/cmd/e2e/main.go

Cherry-pick #1129 to release-1.0 branch to upgrade the Go compiler to 1.13.

manually cherry-pick #1129 to upgrade Go compiler to 1.13

---

tests/actions.go
tests/cmd/stability/main.go

https://github.com/pingcap/tidb-operator/blob/3692c17bf18c8563e2426376ee865c2f0b18af5d/tests/actions.go#L2983-L3012
- EmitEvent sleeps 10 seconds, this slow down the e2e processes
- EmitEvent is used in stability test, no need to run in e2e tests. This is a quick fix to speed up e2e.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
```

skip emitting events for e2e tests

---

charts/tidb-drainer/templates/drainer-configmap.yaml
charts/tidb-drainer/templates/drainer-service.yaml
charts/tidb-drainer/templates/drainer-statefulset.yaml

Cherry pick of #812 on release-1.0.
#812: Keep the instance label of drainer same with the TiDB cluster

Automated cherry pick of #812: Keep the instance label of drainer same with the TiDB cluster

---

tests/actions.go
tests/cmd/e2e/main.go
tests/pkg/webhook/pods.go
tests/pkg/webhook/route.go
tests/pkg/webhook/webhook.go

fixes #1180
e2e webhook is used to verify pods in upgrading
however because we run e2e tests parallelly, the e2e webhook will reject pods in scaling in test
now, so we should update it to take effect for tidb clusters in ugprading only
Tests 
- Unit test
- E2E test
```release-note
```

register e2e webhook for tidb clusters in upgrading only

---

charts/tidb-cluster/templates/tidb-initializer-job.yaml

set timezone and tidb-init-job not work
fix helm chart template
Tests 
Code changes
Side effects
```release-note
NONE
```

Fix tidb-init-job chart templates timezone bug

---

charts/tidb-cluster/templates/tidb-cluster.yaml

Cherry pick of #1079 on release-1.0.
#1079: Set podSecuriyContext to nil by default in favor of backward

Automated cherry pick of #1079: Set podSecuriyContext to nil by default in favor of backward

---

tests/actions.go

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/operator_ghpr_e2e_test_kind/detail/operator_ghpr_e2e_test_kind/1033/
```
[2019-11-19T11:08:35.109Z] I1119 11:08:33.833151       1 actions.go:805] kubectl get pv -l app.kubernetes.io/managed-by=tidb-operator,app.kubernetes.io/namespace=e2e,app.kubernetes.io/instance=cluster1 | awk '{print $1}' | xargs -I {} kubectl patch pv {} -p '{"spec":{"persistentVolumeReclaimPolicy":"Delete"}}'
[2019-11-19T11:08:37.624Z] panic: failed to patch pv: exit status 123, Error from server (NotFound): persistentvolumes "NAME" not found
[2019-11-19T11:08:37.624Z] persistentvolume/local-pv-4ee4259 patched
[2019-11-19T11:08:37.624Z] persistentvolume/local-pv-644a88ec patched
[2019-11-19T11:08:37.624Z] persistentvolume/local-pv-9212c973 patched …
```

fix e2e: do not print headers in `kubectl get pv`

---

charts/tidb-cluster/templates/scripts/_start_drainer.sh.tpl
charts/tidb-cluster/templates/scripts/_start_pump.sh.tpl
charts/tidb-drainer/templates/scripts/_start_drainer.sh.tpl

Cherry pick of #826 on release-1.0.
#826: Fix the pump/drainer data dir to avoid data loss caused by

Automated cherry pick of #826: Fix the pump/drainer data dir to avoid data loss caused by

---

cmd/admission-controller/main.go
pkg/manager/member/scaler.go
pkg/webhook/pod/pods.go
pkg/webhook/webhook.go

Currently pod delete webhook would affect each delete request for pd/tikv pod. This requests limit the service account from admission request to avoid affecting other client requests ( like kubectl )
Tests 
Code changes
Side effects
- N/A
None

Limit the service accounts from pod request for webhook

---

deploy/modules/gcp/tidb-operator/versions.tf

This PR adds a workaround for #1205 
This PR restricts the Google Terraform provider to less than `2.19`.
Tests 
- Manual test
Code changes
None
Side effects
None
- Need to cherry-pick to the release-1.0 branch
```release-note
Fix google terraform module `use_ip_aliases` error.
```

Pin Terraform Google provider version to avoid use_ip_aliases error

---

ci/pingcap_tidb_operator_build_kind.groovy
hack/check-terraform.sh

* make check-terraform failed in Darwin OS
```shell
$ make check-terraform
./hack/check-terraform.sh
usage: dirname path
make: *** [check-terraform] Error 1
```
* fix build master job failed
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
```

Fix check terraform failed

---

ci/pingcap_tidb_operator_build_kind.groovy
tests/actions.go

* Fix e2e nil point dereference when get pod from apiserver failed.
https://internal.pingcap.net/idc-jenkins/view/tidb-operator/job/build_tidb_operator_master_kind/168/console
* Fix reclaim PV failed, this failed job come from PR #1210
https://internal.pingcap.net/idc-jenkins/view/tidb-operator/job/operator_ghpr_e2e_test_kind/1114/console
* Fix the judgment condition of ci script, make not upload build artifact when running PR
Tests 
- E2E test
Code changes
```release-note
None
```

fix e2e nil point dereference

---

charts/tidb-cluster/templates/scripts/_start_scheduled_backup.sh.tpl

fixes #1227 
Tests 
Code changes
Side effects
```release-note
get time string from current time instead of pod name
```

bugfix: get time string from current time instead of pod name

---

pkg/manager/member/pd_member_manager.go
pkg/manager/member/tikv_member_manager.go
tests/actions.go
tests/e2e/config/config.go
tests/e2e/tidbcluster/tidbcluster.go

fixes #1230 
- e2e: run hostNetwork test for Advanced Statefulset
- add POD_NAME env only if hostNetwork is enabled (backward
compatbility)
Tests 
- Unit test
- E2E test

some hostNetwork improvements

---

Makefile
hack/codegen.sh
hack/verify-codegen.sh

Tired of typing `./hack/codegen` and then `./hack/crd-groups generate`
Tests 
- Unit test
- E2E test
There is no user-facing change introduced in this PR.

Unify code-gen and verify-codegen to simplify local development

---

charts/tidb-operator/templates/controller-manager-rbac.yaml
pkg/controller/configmap_control.go
pkg/controller/configmap_control_test.go

This PR is separated from #1269 , in order to not blocking the development of #1192 #1264 #1263
```release-note
Add the privilege to operate configmap for tidb-controller-manager.
```
@tennix @weekface @cofyc @Yisaer PTAL

Add ConfigMapControlInterface and grant configmap privilege

---

charts/tidb-cluster/values.yaml

cherry-picked by https://github.com/pingcap/tidb-operator/pull/1251

manually cherry picked affinity for tidb and pump

---

charts/tidb-operator/templates/scheduler-rbac.yaml

fixes #1281
Tests 
- Unit test
- E2E test
```release-note
bugfix: fix tidb-scheduler RBAC permission in 1.16
```

Fix TiDB scheduler permission in 1.16

---

pkg/manager/member/pd_member_manager.go
pkg/manager/member/tidb_member_manager.go
pkg/manager/member/tikv_member_manager.go

Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
bugfix: don't set DNSPolicy if hostNetwork is not enabled to keep backward compatibility
```

[host network] keep backward compatibility in release-1.0

---

hack/e2e.sh

https://docs.docker.com/v17.12/registry/recipes/mirror/#configure-the-docker-daemon
Tests 
- Unit test
- E2E test

bugfix: registry mirrors is an array in daemon.json

---

cmd/controller-manager/main.go
pkg/controller/tidbcluster/tidb_cluster_control.go
pkg/controller/tidbcluster/tidb_cluster_control_test.go
pkg/controller/tidbcluster/tidb_cluster_controller.go
pkg/controller/tidbcluster/tidb_cluster_controller_test.go
pkg/label/label.go
pkg/manager/member/pod_restarter.go
pkg/util/util.go
tests/e2e/tidbcluster/tidbcluster.go

This request added a pod restarter controller. The controller would fetch all the pods of `tidbcluster` and restart them if they have specific annotations.
Add one controller into `tidbcluster` controller.
Code changes
Tests:
- e2e test

Add Pod Restarter Controller

---

cmd/controller-manager/main.go

informers are registered and started which is unnecessary. It consumes memory but does nothing in non-leader mode.
move initialization logic into leader election onStarted function
Tests 
- Unit test
- E2E test

bugfix: move initialization logic into leader election onStarted function

---

manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/tikv_config.go

Added some code-gen tag for tikv configuration
The schema will generate for tep swagger ui
Tests 
- E2E test
Code changes

config: add openapi-gen in tikv cofigurations

---

tests/actions.go
tests/cmd/stability/main.go
tests/dt.go
tests/e2e/config/config.go

- unable to change replicas of tidb-controller-mananger and tidb-scheduler
- LabelNodes is slow because it has unnecessary wait time
- able to configure replicas of tidb-controller-mananger and tidb-scheduler
- speed up LabelNodes
Tests 
- Unit test
- E2E test

e2e: able to configure replicas of tidb-controller-mananger and tidb-scheduler

---

charts/tidb-cluster/values.yaml

Cannot start tikv-importer using the default config
```
thread 'main' panicked at 'invalid auto generated configuration file /etc/tikv-importer/tikv-importer.toml, err unknown field `metrics`, expected one of `log-level`, `log-file`, `log-rotation-timespan`, `storage`, `server`, `metric`, `rocksdb`, `security`, `import`', src/import/config.rs:134:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
Reference: https://github.com/tikv/importer/blob/master/etc/tikv-importer.toml
A typo is fixed
Tests 
- Unit test
- E2E test
```release-note
Fix the default tikv-importer configuration
```

fix error importer config

---

charts/tidb-operator/templates/scheduler-rbac.yaml
ci/pingcap_tidb_operator_build_kind.groovy
hack/e2e.sh

fixes: #1313 and closes: #1413
Tests 
Code changes
Side effects
```release-note
NONE
```

ci: add k8s v1.17 support

---

pkg/apis/pingcap/v1alpha1/tidbcluster.go
pkg/manager/member/orphan_pods_cleaner.go
pkg/manager/member/orphan_pods_cleaner_test.go
pkg/manager/member/pd_member_manager.go
pkg/manager/member/pd_member_manager_test.go
pkg/manager/member/pump_member_manager.go
pkg/manager/member/pump_member_manager_test.go
pkg/manager/member/pvc_cleaner.go
pkg/manager/member/pvc_cleaner_test.go
pkg/manager/member/tidb_discovery_manager.go
pkg/manager/member/tidb_member_manager.go
pkg/manager/member/tidb_member_manager_test.go
pkg/manager/member/tikv_member_manager.go
pkg/manager/member/tikv_member_manager_test.go
pkg/manager/meta/meta_manager.go
pkg/manager/meta/meta_manager_test.go
pkg/manager/meta/reclaim_policy_manager.go

close #1418 
Tests 
- Unit test
- E2E test
```release-note
The instance label key of resources owned by `tidbcluster` is default to the cluster name now. 
```

make controller logic independable with certain tidbcluster label

---

go.mod
pkg/httputil/httputil.go
pkg/manager/member/pd_member_manager.go
pkg/manager/member/tidb_member_manager.go
pkg/pdapi/pdapi.go
tests/actions.go
tests/e2e/tidbcluster/tidbcluster.go
tests/e2e/util/proxiedpdclient/proxiedpdclient.go
tests/e2e/util/proxiedtidbclient/proxiedtidbclient.go

fixes #1450 
- fix pd client tls bug
- use table driven tests to cover tls case (more extensible)
Tests 
- Unit test
- E2E test

fix pd client tls and use table driven tests to cover tls case

---

pkg/manager/member/pd_member_manager.go
pkg/manager/member/pump_member_manager.go
pkg/manager/member/tidb_member_manager.go
pkg/manager/member/tikv_member_manager.go
pkg/manager/member/utils.go

close #1475 
Now the `last-applied-config` annotation of statefulset's PodTemplate will be retained during update to keep the backward-compatibility.
In addition, we need #1440 to help us prevent such issues.
Tests 
- Unit test
- E2E test
```release-note
Retain last-applied-config of StatefulSet's `PodTemplate` during updates to keep backward compatibility.
```

Retain last applied pod template to keep backward-compatibility

---

ci/pingcap_tidb_operator_build_kind.groovy
hack/e2e.sh
hack/run-e2e.sh
tests/actions.go
tests/e2e/e2e.go
tests/e2e/tidbcluster/serial.go
tests/e2e/tidbcluster/tidbcluster.go
tests/e2e/util/image/image.go
tests/e2e/util/image/image_test.go

disable docker registry mirrors temporarily (except docker.io)

---

charts/tidb-operator/templates/admission/admission-webhook-deployment.yaml

fixes #1503 
As suggested by @aylei , we should add `readinessProbe` for admission webhook.
without `readinessProbe`, the pod is in Ready state when the process is started. However, the HTTP server may not be ready. 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

add readinessProbe/livenessProbe for admission webhook

---

ci/pingcap_tidb_operator_build_kind.groovy
hack/e2e.sh
hack/lib.sh

regular upgrade
https://github.com/kubernetes-sigs/kind/releases/tag/v0.7.0
- upgrade to use kind 0.7.0
- upgrade to use k8s 1.16.4
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

upgrade to use kind 0.7.0

---

docs/CONTRIBUTING.md
hack/e2e.sh

Add bash version requirements note in doc.
fix #1560
Check bash version in e2e test script.
It add bash version requirements note in doc.
`e2e.sh` and `CONTRIBUTIN.md`.
In `e2e.sh` , we check the `$BASH_VERSION` and make sure it >= 4 before really execute anything.
```release-note
NONE
```

Check bash version for hack/e2e.sh

---

.github/pull_request_template.md

The "Release Notes Language Style Guide" url in the `pull_request_template.md` is "not found" now, change it back to the right one.
It should be [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md)
The only change is the "Release Notes Language Style Guide" url in `pull_request_template.md`.
```release-note
NONE
```

fix the "Release Notes Language Style Guide" url in pull request template

---

pkg/upgrader/upgrader.go

Fixes #1595
Skip to revert when there isn't any resources of `apps.pingcap.com/statefulsets`
```release-note
NONE
```

Fix upgrader error when advanced statefulset disabled 

---

pkg/controller/pv_control.go
pkg/controller/tidbmonitor/tidb_monitor_controller.go
pkg/monitor/monitor/monitor_manager.go
tests/e2e/tidbcluster/tidbcluster.go
tests/pkg/fixture/fixture.go

Ref #1586
In this request, `TidbMonitor` controller would sync its pv to update the label just like other `tidbcluster` components.
This request is only for `TidbMonitor`, 
```release-note
Add labels for `TidbMonitor`'s `PersistentVolume`
```

Sync labels for Monitor's PersistentVolume

---

tests/e2e/tidbcluster/serial.go
tests/e2e/tidbcluster/tidbcluster.go

pd 2 sometimes fails to scale-out and we don't need to use tidb 2 anymore [except the backward compatibility test](https://github.com/pingcap/tidb-operator/blob/c45c031667dbebc1d2c56d27ee2cbe73e0184a25/tests/e2e/tidbcluster/tidbcluster.go#L137-L143)
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/operator_ghpr_e2e_test_kind/detail/operator_ghpr_e2e_test_kind/2455/pipeline
Fixes https://github.com/pingcap/tidb-operator/issues/1592
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
- Need to cherry-pick to …

e2e: don't use TiDB 2 version except backward compatibility test

---

pkg/manager/member/tikv_member_manager.go
pkg/manager/member/tikv_member_manager_test.go

Fixes https://github.com/pingcap/tidb-operator/issues/1582
Currently, `tikv-manager` would sync all the store info in the `tikv status`, which is not suitable if we add `tiflash` in the future. In this request, the `tikv-manager` would check the store owner by comparing the address of each store. 
Tests 
Code changes
```release-note
NONE
```

Check store owner for tikv manager

---

pkg/manager/member/pd_scaler.go
tests/e2e/tidbcluster/serial.go

fix scaling pd with Advanced StatefulSet
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

fix scaling pd with Advanced StatefulSet

---

ci/pingcap_tidb_operator_build_kind.groovy

it's very unstable when more than 1 jobs running on the same node, so we must not limit nodes to run.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

WIP: don't limit nodes and reduce parallel nodes

---

ci/pingcap_tidb_operator_build_kind.groovy
hack/check-terraform.sh
tests/e2e/tidbcluster/tidbcluster.go

On these nodes, we configured 'cgroup.memory=nokmem' to avoid issues in
CentOS 7.6.
https://github.com/pingcap/tidb-operator/issues/1603#issuecomment-583263692
it also fixes https://github.com/pingcap/tidb-operator/issues/1539
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

CI: Running on TiDB Operator Nodes.

---

charts/tidb-operator/templates/controller-manager-deployment.yaml
pkg/manager/member/pd_upgrader.go
pkg/manager/member/tidb_upgrader.go
tests/actions.go
tests/e2e/tidbcluster/serial.go
tests/e2e/tidbcluster/tidbcluster.go
tests/e2e/util/image/image.go
tests/e2e/util/statefulset/statefulset.go

fixes #1590 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

[Advanced StatefulSet] e2e case: upgrade cluster while pods are not consecutive

---

hack/e2e.sh

using with `REUSE_CLUSTER=y`, we don't want to restart docker every time.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

skip restarting docker if already configured

---

charts/tidb-operator/templates/controller-manager-deployment.yaml
pkg/manager/member/pd_upgrader.go
pkg/manager/member/tidb_upgrader.go
tests/actions.go
tests/e2e/tidbcluster/serial.go
tests/e2e/tidbcluster/tidbcluster.go
tests/e2e/util/image/image.go
tests/e2e/util/statefulset/statefulset.go

Cherry pick of #1628 on release-1.1.
#1628: upgrade cluster while pods are not consecutive

Automated cherry pick of #1628: upgrade cluster while pods are not consecutive

---

charts/tidb-lightning/templates/job.yaml
charts/tidb-lightning/templates/rclone-conf.yaml
charts/tidb-lightning/templates/scripts/_start_lightning.sh.tpl
charts/tidb-lightning/values.yaml

fix https://github.com/pingcap/tidb-operator/issues/1566
Tests 
Manual test (add detailed scripts or steps below)
Test restore with lightning with below config in values.yaml:
- Set jobName
- Set targetTidbCluster.secretName
- Set targetTidbCluster.secretUserKey
-  Set targetTidbCluster.secretPwdKey
-  Do not set targetTidbCluster.secretPwdKey
- Do not set targetTidbCluster.secretUserKey
- Set targetTidbCluster.secretPwdKey
- Do not set targetTidbCluster.secretPwdKey
- Do not set targetTidbCluster.secretName
- Set dataSource.remote.rcloneConfig
- Do not set dataSource.remote.rcloneConfig
- local
Code changes
- Has Helm scripts change
- Need to cherry-pick to the release-1.1
```release-note
- Support customizing job name in tidb-lightning chart.
- Support setting rclone …
```

Add authorization configuration for lighting

---

.github/workflows/ci.yaml
ci/pingcap_tidb_operator_build_kind.groovy

- run checks via Github Actions
- don't run checks in Jenkins job (this speeds up the job)
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

Move some checks from Jenkins job to Github Actions

---

charts/tidb-cluster/templates/tidb-cluster.yaml
charts/tidb-cluster/values.yaml
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
pkg/manager/member/tidb_member_manager.go

This PR fixes: #1699 , add more SANs to tidb server certificate.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
add more SANs to tidb server certificate
```

add more SANs to tidb server certificate

---

charts/tidb-backup/templates/backup-pvc.yaml
charts/tidb-backup/templates/restore-job.yaml
charts/tidb-backup/values.yaml

It looks like for ad-hoc backup and restore (at least in the failing test), the helm chart expects the same pvc from the backup to be kept around and used for the subsequent restore. This only works if the source and target clusters are in the same namespace.
I would like to restore to a cluster without any local backups, running on a different Kubernetes cluster in a different region, via S3.
This is split from https://github.com/pingcap/tidb-operator/pull/1705
This adds a `restoreUsingExistingVolume` defaulting to `true`. If set to `false`, then a new volume in the `restore` mode to hold data loaded from s3, gcp, ceph, etc.
This option has the same effect as simply setting the mode to `scheduled-restore`, but I didn't really understand what `scheduled-restore` meant.

tidb-backup: add restoreUsingExistingVolume option

---

charts/tidb-backup/templates/backup-job.yaml
charts/tidb-backup/templates/restore-job.yaml
charts/tidb-backup/values.yaml

* Makes the templates for the restore job respect `resources` and `imagePullPolicy` from the `values.yaml`, making it mirror the backup job better.
* Add `nodeSelector` to both backup and restore.
* ~Fixes: the restore job expects a PVC, but doesn't attempt to create the PVC in
restore mode.~ Removed from PR

tidb-backup: restore respects resources, imagePullPolicy, nodeSelector

---

pkg/manager/member/template.go

close db connect after set privilege in tidb initializer
Tests 
- E2E test
Code changes

tidb-initializer:close connection after set privilege

---

manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/tidbclusterautoscaler_types.go

Fix an Auto-scaler api json property name
```release-note
NONE
```

fix autoscaler api

---

go.sum
hack/e2e.sh
hack/lib.sh
hack/prepare-e2e.sh
hack/run-e2e.sh
tests/e2e/e2e.go

- use kubetest2 to run e2e
- support GKE provider
xref: https://github.com/pingcap/tidb-operator/issues/1697
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

use kubetest2 to run e2e and support GKE provider

---

cmd/controller-manager/main.go
pkg/autoscaler/autoscaler/autoscaler_manager.go
pkg/autoscaler/autoscaler/tidb_autoscaler.go
pkg/autoscaler/autoscaler/tikv_autoscaler.go
pkg/autoscaler/autoscaler/util.go
pkg/controller/autoscaler/tidbcluster_autoscaler_control.go
pkg/controller/autoscaler/tidbcluster_autoscaler_controller.go

ref #1651 
Finish the rest logic of auto-scaler controller to update the `tidbcluster` and `tidbclusterAutoScaler` .
I test the auto-scaling locally with cpu load by sysbench, and it works well.
And I also find some bugs and fix it.
```release-note
Support TidbCluster Auto-scaling feature based by CPU averageUtilization load.
```

Manually cp #1731

---

pkg/monitor/monitor/template.go
pkg/monitor/monitor/template_test.go

* Fix TidbMonitor template error, manually cp #1745 
```release-note
Fix the template error which would cause TidbMonitor can't srape tikv metrics
```

Fix TidbMonitor template error (#1745)

---

charts/tidb-backup/templates/backup-job.yaml
charts/tidb-backup/templates/restore-job.yaml
charts/tidb-backup/values.yaml
charts/tidb-cluster/templates/scheduled-backup-cronjob.yaml
charts/tidb-cluster/values.yaml
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
pkg/backup/backup/backup_manager.go
pkg/backup/restore/restore_manager.go

Fixes the issue https://github.com/pingcap/tidb-operator/issues/1535
Being able to set the affinity and tolerations in order to schedule backups or restores
```release-note
Allow users to configure affinity and tolerations for `Backup` and `Restore`
```

Allow to configure Affinity or Tolerations for Backups and Restores

---

.github/workflows/ci.yaml

update actions/checkout to v2, in this version it can fetch the HEAD commit of PR only and we don't need to specify `fetch-depth`.
https://github.com/actions/checkout#checkout-v2
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

actions: update actions/checkout to v2

---

deploy/modules/aws/bastion/data.tf

Fixes #1774 
Adds a filter on marketplace Product Code (in addition to existing filters) to make sure the correct product is chosen.
Tests 
I simply tested `terraform apply` after applying this change and the correct AMI was chosen (whereas the *incorrect* AMI was being chosen before applying the change).
Code changes
```release-note
NONE
```

Added marketplace product code filter for bastion to avoid selecting AMI from wrong vendor

---

manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/tikv_config.go
pkg/manager/member/pd_member_manager.go
pkg/manager/member/tikv_member_manager.go

this pr fixes: #1771 
Tests 
Code changes
Side effects
```release-note
Fix cluster TLS while using CR to create cluster
```

tls: fix cluster TLS while using CR to create cluster

---

.gitignore
tests/e2e/tidbcluster/serial.go

fixes #1540 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

use TidbCluster CRD to simplify the test and increase wait timeout

---

CHANGELOG-1.1.md
charts/tidb-cluster/values.yaml
charts/tidb-operator/values.yaml
docs/release-note-guide.md
tests/manifests/stability/stability.yaml

fixes #1760 
release notes are generated via the following command:
```
go get k8s.io/release/cmd/release-notes@v0.2.0
release-notes --start-rev v1.1.0-beta.1 --end-rev release-1.1 --branch release-1.1 --github-org pingcap --github-repo tidb-operator --output note.md --debug --format markdown -requiredAuthor ''
```
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

release v1.1.0-beta.2

---

ci/pingcap_tidb_operator_build_kind.groovy

Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

fix master ci

---

charts/tidb-operator/values.yaml
ci/deploy_tidb_operator_staging.groovy
pkg/apis/pingcap/v1alpha1/defaulting/tidbcluster.go

Enable tidbcluster webhook defaulting both in idc configuration and operat chart values.
```release-note
Enable TidbCluster defaulting mutation by default which is recommended when admission webhook is used
```

Enable defaulting for tidbcluster

---

cmd/admission-webhook/main.go
cmd/controller-manager/main.go
cmd/discovery/main.go
cmd/scheduler/main.go

this is useful in debugging. in addition to component version, we can know CLI flags from logs.
example logs of tidb-controller-manager:
```
I0227 17:36:49.969981   88390 version.go:38] Welcome to TiDB Operator.
I0227 17:36:49.970745   88390 version.go:39] TiDB Operator Version: version.Info{GitVersion:"v1.1.0-beta.1.97+89e0c38525404a", GitCommit:"89e0c38525404aea9c085a64848ad36bcbcd8bf1", GitTreeState:"clean", BuildDate:"2020-02-27T09:36:35Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
I0227 17:36:49.970794   88390 main.go:97] FLAG: --V="false"
I0227 17:36:49.970805   88390 main.go:97] FLAG: --add_dir_header="false"
I0227 17:36:49.970809   88390 main.go:97] FLAG: --alsologtostderr="false"
I0227 17:36:49.970814   88390 main.go:97] FLAG: --auto-failover="true"
I0227 …
```

show cli flags in logs

---

charts/tidb-operator/templates/admission/admission-webhook-registration.yaml
charts/tidb-operator/templates/admission/pre-delete-job.yaml
charts/tidb-operator/templates/controller-manager-deployment.yaml
charts/tidb-operator/values.yaml
ci/deploy_tidb_operator_staging.groovy
tests/actions.go

Current Admission Webhook templates is complex (which means hard to maintain) and the values setting is misleading and difficult to understand.
This request is to simplify the admission templates and make admission values setting easier to understand.
```release-note
ACTION REQUIRED:
1. Change the setting from the previous admission.hookEnabled.pods to the admission.validation.pods.
2. Change the setting from the previous admission.hookEnabled.statefulSets to the admission.validation.statefulSets
3. Change the setting from the previous admission.hookEnabled.validating to the admission.validation.pingcapResources.
4. Change the setting from the previous admission.hookEnabled.defaulting to the admission.mutation.pingcapResources. …
```

Refactor Admission Webhook templates and values

---

hack/lib.sh

fixes #1812
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

support kubetest2 on non-linux platforms

---

pkg/apis/pingcap/v1alpha1/defaulting/tidbcluster.go

We only add default base image when the necessary version property is defined.
```release-note
NONE
```

Fix defaulting bug

---

pkg/monitor/monitor/monitor_manager.go

When TidbMonitor's targetRef namespace is not set, it is supposed to be the tidbmonitor's namespace instead
Fixes https://github.com/pingcap/tidb-operator/issues/1825
```release-note
TidbMonitor would use its namespace for the targetRef if it is not defined.
```

Default TidbMonitor targetRef Namespace

---

pkg/upgrader/upgrader.go
pkg/upgrader/upgrader_test.go

We should not check this, otherwise the controller-manager with advanced statefulset cannot be restarted when some clusters have delete slot annotations set.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

disable current delete slot annotations check in Advanced Statefulset upgrader

---

.github/workflows/ci.yaml
Makefile
examples/basic/tidb-cluster.yaml
hack/e2e-examples.sh
hack/local-up-operator.sh
tests/examples/001-basic.sh

xref: #1814
fixes https://github.com/pingcap/tidb-operator/issues/1111
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

add hack/local-up-operator.sh to run tidb-operator locally and test examples

---

charts/tidb-backup/templates/scripts/_start_backup.sh.tpl
charts/tidb-backup/values.yaml
charts/tidb-cluster/templates/scheduled-backup-cronjob.yaml
charts/tidb-cluster/templates/scripts/_start_scheduled_backup.sh.tpl
charts/tidb-cluster/values.yaml

This is required if you use EKS ServiceAccount -> IAM role authentication using OIDC.
```release-note
Support no secret for s3/ceph when using OIDC authentication
```

Support no secret for s3/ceph

---

cmd/backup-manager/app/backup/backup.go
cmd/backup-manager/app/constants/constants.go
cmd/backup-manager/app/restore/restore.go
cmd/backup-manager/app/util/util.go
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/backup/backup/backup_manager.go
pkg/backup/backupschedule/backup_schedule_manager.go
pkg/backup/constants/constants.go
pkg/backup/restore/restore_manager.go
pkg/backup/util/util.go

use BR as the backup tool in an TLS cluster
use client certification for BR communicate with TiKV and PD
Tests 
use operator and backup manager with this PR
```
helm install --values values.yaml --name operator --namespace tidb-admin . --set-string -operatorImage=hub.pingcap.net/yinliang/pingcap/tidb-operator:latest,tidbBackupManagerImage=hub.pingcap.net/yinliang/pingcap/tidb-backup-manager:latest
```
create backup and restore cluster
```
helm install --values values.yaml --name cluster --namespace cluster . --set-string enableTLSCluster=true,tidb.image=pingcap/tidb:latest,tikv.image=pingcap/tikv:latest,pd.image=pingcap/pd:latest
helm install --values values.yaml --name cluster1 --namespace cluster . --set-string …
```

Backup: support TLS for br component

---

charts/tidb-cluster/templates/scripts/_start_tidb.sh.tpl
charts/tidb-cluster/values.yaml
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/tidbcluster.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
pkg/manager/member/template.go
pkg/manager/member/tidb_member_manager.go

Closes https://github.com/pingcap/tidb-operator/issues/1439
v2.1.0 and later versions have this argument:
https://github.com/pingcap/tidb/blob/v2.1.0/config/config.go#L48
start tidb-server with `-advertise-address` parameter, refer to https://github.com/pingcap/tidb/pull/7078.
Tests 
- Unit test
- E2E test
When `EnableAdvertiseAddress` is set to false:
```
/ # ps
PID   USER     TIME  COMMAND
1 root      0:00 /tidb-server --store=tikv --host=0.0.0.0 --path=db-pd:2379 --config=/etc/tidb/tidb.toml --log-slow-query=/var/log/tidb/slowlog
```
When `EnableAdvertiseAddress` is set to true:
```
/ # ps
PID   USER     TIME  COMMAND
1 root      0:01 /tidb-server --store=tikv --advertise-address=db-tidb-0.db-tidb-peer.tidb10.svc …
```

support starting tidb-server with `-advertise-address` parameter

---

charts/tidb-cluster/templates/scripts/_start_tikv.sh.tpl
charts/tidb-cluster/values.yaml
charts/tidb-operator/templates/admission/admission-webhook-rbac.yaml
charts/tidb-operator/templates/admission/admission-webhook-registration.yaml
charts/tidb-operator/values.yaml
pkg/controller/tidbcluster/tidb_cluster_controller.go
pkg/manager/member/scaler.go
pkg/manager/member/template.go
pkg/manager/member/tikv_member_manager.go
pkg/manager/member/tikv_scaler.go
pkg/manager/member/utils.go
pkg/webhook/admission_hooks.go
pkg/webhook/pod/pod_mutater.go
pkg/webhook/pod/pods.go
pkg/webhook/pod/util.go

When tikv is scaled-out by auto-scaler, It should be added special hot region label by starting configuration instead of pdapi after started.
This request use mutation pod webhook to add env for the tikv created by auto scaler, which would inject special label durint it starting.
```release-note
The TiKV created by the Auto-scaler would only schedule the hot region if `admission.mutation.pods` is enabled.
```

Fix hot region label setting for tikv auto-scaling

---

charts/tidb-lightning/values.yaml

The pingcap/tidb-cloud-backup image has the most recent rclone version which supports EKS OIDC IAM authentication

Change the lightning restore image

---

pkg/webhook/pod/pod_mutater.go

Currently the tikv Configmap wouldn't be fetched when we only using TidbCluster CR with `configUpdateStrategy: RollingUpdate`. This request get the configmap from the volume template from the coming tikv pod.
I haven tested all four situations( helm/cr, RollingUpdate/Inplace), all situtations work well
Fix the problem which would let the
```release-note
NONE
```

Fix wrong method to get tikv configmap in mutation webhook

---

hack/kind-cluster-build.sh

no need to set up for e2e testing anymore
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

cleanup hack/kind-cluster-build.sh

---

manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/tikv_config.go
pkg/apis/pingcap/v1alpha1/tikv_config_test.go

close #1780 
Fix the toml key
Tests 
- Unit test
- E2E test
Code changes
```release-note
Fix some TiKV configuration keys in toml
```

Fix tikv configuration key in toml and add an ut case

---

pkg/manager/member/utils.go

Fix the nil error check for `updateStatefulSet` which would cause controller-manager crash.
```release-note
NONE
```

Fix nil error for update statefulset util

---

docs/CONTRIBUTING.md
hack/local-up-operator.sh

fixes #1814
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

docs about manual testing in development

---

images/tidb-backup-manager/Dockerfile
images/tidb-backup-manager/entrypoint.sh
manifests/backup/backup-aws-s3-br.yaml
manifests/backup/backup-s3-br.yaml
manifests/backup/backup-schedule-aws-s3-br.yaml
manifests/backup/backup-schedule-s3-br.yaml
manifests/backup/restore-aws-s3-br.yaml
manifests/backup/restore-s3-br.yaml
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/backup/backup/backup_cleaner.go
pkg/backup/backup/backup_manager.go
pkg/backup/constants/constants.go
pkg/backup/restore/restore_manager.go
pkg/backup/util/util.go

support kms decryption secret in tidb-operator
add KMS field in backup CRD, it should set to be true if the secret has been encrypted by KMS
Tests 
Code changes
```release-note
Add `spec.useKMS` field in `Backup`, `Restore` and `BackupSchedule` custom resources. Set it to `true` if you want to decrypt the secrets encrypted with KMS.
```

backup: support kms decryption secret

---

pkg/apis/pingcap/v1alpha1/tidbcluster.go
pkg/manager/member/tikv_member_manager.go

fix #1932 
Defaulting tikv container privileged field to false if not set.
Tests 
Upgrade tidb-operator from v1.0 to v1.1 and no rolling update for PD/TiDB/TiKV.
Code changes
```release-note
NONE
```

defaulting tikv container privileged field

---

docs/api-references/docs.html
images/tidb-backup-manager/entrypoint.sh
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/manager/member/tikv_member_manager.go

support tikv specify a serviceAccount name and make rclone can use iam in cloud env
support tikv specify a serviceAccount name and make rclone can use iam in cloud env
Tests 
modify tc and then verify serviceaccount is changed in tikv pod
use rclone in cloud env without set secretkey and accesskey
Code changes
Add `spec.tikv.serviceAccount` field in `TiDBCluster` custom resources. To specify a service account name for tikv pods.
```

Backup: make tikv support add serviceaccount and switch rclone env_auth to true

---

charts/tidb-lightning/templates/job.yaml
charts/tidb-lightning/templates/scripts/_start_data_retriever.sh.tpl
charts/tidb-lightning/templates/scripts/_start_lightning.sh.tpl
charts/tidb-lightning/values.yaml

manually cherry pick #1629 
```release-note
support using a remote directory as data source for tidb-lightning.
```

Cherry-pick: Support sync bucket in lightning (#1629)

---

pkg/upgrader/upgrader.go
pkg/upgrader/upgrader_test.go

- revert #1851 
- fix the root issue in #1851 by checking tidb clusters which own builtin StatefulSets only 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

check tidb clusters which own builtin StatefulSets only in upgrading

---

docs/api-references/docs.html
hack/e2e.sh
hack/run-e2e.sh
images/tidb-backup-manager/Dockerfile
images/tidb-backup-manager/entrypoint.sh
manifests/backup/backup-aws-s3-br.yaml
manifests/backup/backup-s3-br.yaml
manifests/backup/backup-schedule-aws-s3-br.yaml
manifests/backup/backup-schedule-s3-br.yaml
manifests/backup/restore-aws-s3-br.yaml
manifests/backup/restore-s3-br.yaml
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/backup/backup/backup_cleaner.go
pkg/backup/backup/backup_manager.go
pkg/backup/backupschedule/backup_schedule_manager.go
pkg/backup/constants/constants.go
pkg/backup/restore/restore_manager.go
pkg/backup/util/util.go
pkg/manager/member/tikv_member_manager.go

- #1749
- #1861
- #1908
- #1930
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

cherry pick missing PRs into release-1.1

---

charts/tidb-drainer/templates/_helpers.tpl

Drainer installation failed when `drainerName` is set:
```
Error: YAML parse error on tidb-drainer/templates/drainer-statefulset.yaml: error converting YAML to JSON: yaml: line 5: could not find expected ':'
```
The `drainerName` is in separate line:
```
metadata:
name: 
dan10-drainer
labels:
```
Remove the newline character. 
Tests 
tidb-drainer can be installed successfully with below cases:
-    Set `drainerName`
-    Do not set `drainerName`
Code changes
- Has Helm scripts change
```release-note
Fix the drainer installation error when `drainerName` is set
```

fix drainer installation error

---

hack/e2e-examples.sh

- fix `$((cnt++))`
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

fix bug in e2e-examples script

---

charts/tidb-operator/templates/controller-manager-rbac.yaml
manifests/monitor/tidb-monitor.yaml

1. After upgrade TiDB Operator from v1.0 to v1.1, then create TiDB Monitor CR, tidb-controller-manager reports below error:
```
Event(v1.ObjectReference{Kind:"TidbMonitor", Namespace:"dan10", Name:"dan10", UID:"c8b9b9ed-67f9-11ea-8886-8a678ff421f7", APIVersion:"pingcap.com/v1alpha1", ResourceVersion:"68470646", FieldPath:""}): type: 'Warning' reason: 'FailedSync' Sync TidbMonitor[dan10/dan10] Deployment failed,err:secrets "dan10-monitor" is forbidden: User "system:serviceaccount:tidb-admin:tidb-controller-manager" cannot update resource "secrets" in API group "" in the namespace "dan10"
```
2. No full example for TiDB Monitor.
update permission for tidb-controller-manager and add example for tidb-monitor
Tests 
TiDB Monitor CR can be …

update permission for tidb-controller-manager and add example for tidb-monitor

---

cmd/backup-manager/app/export/export.go

mask visual tables when dumper 
add ignore policy when dumper
Tests 
dumper with backup yaml 
```
---
kind: Backup
metadata:
name: export-backup-s3
namespace: tidb4
annotations:
iam.amazonaws.com/role: "arn:aws:iam::123456789012:role/user"
spec:
backupType: full
useKMS: true
tikvGCLifeTime: 100h
storageClassName: gp2
storageSize: 1Gi
from:
host: 172.30.2.6
secretName: mysql-pwd-1584498036384022997
port: 4000
user: root
s3:
provider: aws
region: us-west-2
bucket: my-backup-bucket
```
Code changes

backup: mask visual tables when dumper 

---

tests/actions.go
tests/cmd/stability/main.go
tests/e2e/tidbcluster/serial.go
tests/e2e/tidbcluster/tidbcluster.go

we should not test stable scheduling in parallel. this is because another pod may occupy the position then the pod can not be scheduled back.
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-e2e-eks-ci-master/detail/tidb-operator-e2e-eks-ci-master/17/tests
this test does not fail in kind because kind nodes resources are very large (share with the host).
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

add a serial test for stable scheduling

---

hack/lib.sh
hack/run-e2e.sh
tests/images/test-apiserver/Dockerfile

- skip master node in image loading (speed up e2e process)
- remove unused Dockefile
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

some cleanups in e2e

---

ci/e2e_eks.groovy
ci/e2e_gke.groovy

Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

configure default parameters via envs in Jenkins job

---

ci/aws-clean-eks.sh

Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

fix clean-eks script bug

---

hack/run-e2e.sh
tests/images/e2e/Dockerfile
tests/images/e2e/entrypoint.sh

fixes https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-e2e-gke-ci-master/detail/tidb-operator-e2e-gke-ci-master/62/pipeline
```
[2020-03-19T19:01:24.731Z] [5] E0319 19:01:24.307547      15 actions.go:907] failed to get tidbcluster: tidb-cluster-4946/basic-v2, Get https://104.155.180.0/apis/pingcap.com/v1alpha1/namespaces/tidb-cluster-4946/tidbclusters/basic-v2: error executing access token command "/google-cloud-sdk/bin/gcloud config config-helper --format=json": err=fork/exec /google-cloud-sdk/bin/gcloud: no such file or directory output= stderr=
```
e2e image needs to run `/google-cloud-sdk/bin/gcloud config config-helper` to refresh the auth token when it expired.
Tests 
- Unit test
- E2E test
- Manual test (add detailed scripts or …

Mount google-cloud-sdk into e2e image

---

ci/e2e_kind.groovy
ci/pingcap_tidb_operator_build_kind.groovy
hack/lib.sh
tests/e2e/e2e.go
tests/e2e/tidbcluster/serial.go
tests/e2e/tidbcluster/stability.go
tests/e2e/util/pod/pod.go
tests/e2e/util/tidb/tidb.go

fixes #1584 
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-e2e-kind-ci-master-stability/detail/tidb-operator-e2e-kind-ci-master-stability/12/pipeline
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

add stability e2e group and a basic case

---

deploy/modules/aliyun/tidb-operator/versions.tf

CI failed due to the latest version of alicloud terraform module removed some fields.
Pin the alicloud terraform module version.
Tests 
`terraform ini` and `terraform apply` work normally.
Code changes
```release-note
NONE
```

pin alicloud version to fix ci errors

---

hack/run-e2e.sh
tests/e2e/e2e_test.go

- fix arg passing in run-e2e.sh
- log args
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-e2e-gke-ci-master/detail/tidb-operator-e2e-gke-ci-master/65/artifacts
report-dir is not passed into e2e, no test results are reported. 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

fix args passing in run-e2e.sh

---

pkg/apis/pingcap/v1alpha1/tidbcluster.go

The default value of separateSlowLog is set to the incorrect value.
Set it to the correct value.
Tests 
- Unit test
- E2E test
Code changes
```release-note
NONE
```

fix default value of separateSlowLog

---

ci/pingcap_tidb_operator_build_kind.groovy

#1438 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

don't run on k8s-node for PR jobs

---

docs/api-references/docs.html
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/types.go
pkg/manager/member/pd_member_manager.go
pkg/manager/member/tidb_member_manager.go
pkg/manager/member/tikv_member_manager.go
pkg/manager/member/utils.go
pkg/util/crdutil.go

Close https://github.com/pingcap/tidb-operator/issues/1623
Adding the new property in `status` as `image` for each tidbcluster component. And changing the CRD column defination.
```release-note
Fix the error that `kubectl get tc` cannot show correct images 
```

Fix the error that `kubectl get tc` cannot show correct images 

---

charts/tidb-cluster/templates/scripts/_start_tidb.sh.tpl
charts/tidb-cluster/values.yaml
docs/api-references/docs.html
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/tidbcluster.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
pkg/manager/member/template.go
pkg/manager/member/tidb_member_manager.go

After https://github.com/pingcap/tidb-operator/pull/2013, users can set `spec.paused` to `true` if they want to avoid `tidb-server` rolling upgrade in tidb-operator upgrading. Note that users should set it back to `false` when it's ok to upgrade `tidb-server`. 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
ACTION REQUIRED: `--advertise-address` will be configured for `tidb-server` which will trigger rolling-upgrade for `tidb-server` component, you can set `spec.paused` to …
```

remove enableAdvertiseAddress field, --advertise-address should be always configured

---

cmd/backup-manager/app/backup/backup.go
cmd/backup-manager/app/restore/restore.go

fixes #1657
create a stdout pipe from the exec process, and read the pipe message in a for loop, If the output meesage with ERROR, add to the backup status message information
Tests 
It seems the log will output intime and the backup status messsage is 
```
status:
backupPath: ""
backupSize: 0
commitTs: ""
conditions:
- lastTransitionTime: "2020-03-30T12:14:02Z"
message: ""
reason: ""
status: "True"
type: Scheduled
- lastTransitionTime: "2020-03-30T12:14:03Z"
message: ""
reason: ""
status: "True"
type: Running
- lastTransitionTime: "2020-03-30T12:14:36Z"
message: "cluster cluster/sa-backup-s3, wait pipe message failed, errMsg [2020/03/30
12:14:36.196 +00:00] [ERROR] [push.go:106] [\"backup occur unknown error\"]
[error=\"Io(Custom { …
```

backup: fix issue 1657

---

pkg/manager/member/pd_member_manager.go
pkg/manager/member/pd_member_manager_test.go
pkg/manager/member/pump_member_manager.go
pkg/manager/member/tidb_member_manager.go
pkg/manager/member/tikv_member_manager.go
pkg/util/util.go
pkg/util/utils_test.go

merged envs should not be sorted in #2052. this is unnecessary and will trigger a rolling update of statefulset.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

should not change relative order of envs

---

CHANGELOG-1.1.md
charts/tidb-cluster/values.yaml
charts/tidb-operator/values.yaml
deploy/gcp/variables.tf
tests/manifests/stability/stability.yaml

fixes #2067 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

release v1.1.0-rc.1

---

Makefile
go.sum
hack/e2e.sh
hack/run-e2e.sh
tests/actions.go
tests/config.go
tests/e2e/config/config.go
tests/e2e/tidbcluster/tidbcluster.go
tests/e2e/util/image/image.go
tests/e2e/util/tidb/tidb.go
tests/pkg/fixture/fixture.go

add auto e2e test for BR backup and restore
add whole auto e2e test for BR backup and restore and check correct in AWS.
Tests 
- E2E test
run e2e on eks env, and skip e2e in PR triggered e2e test
Code changes

BR e2e test in AWS

---

pkg/controller/periodicity/periodicity_controller.go
pkg/upgrader/upgrader.go
pkg/upgrader/upgrader_test.go
pkg/util/util.go

If a instance label is set in `TidbCluster` CR, its value will be used to keep backward compatibility.
https://github.com/pingcap/tidb-operator/blob/50a517b5e4dd7b2e6de032483503b7504ebc3d04/pkg/apis/pingcap/v1alpha1/tidbcluster.go#L372-L381
We should not use this label to find the tidb cluster owner in our controller.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

Find tidb cluster owner via owner references

---

tests/examples/002-selfsigned-tls.sh

Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

upgrade cert-manager to v0.14.1 in example tests

---

pkg/autoscaler/autoscaler/calculate/calculate_test.go
pkg/autoscaler/autoscaler/calculate/cpu_test.go
pkg/autoscaler/autoscaler/util_test.go

Add unit test for auto-scaling util
```release-note
NONE
```

Add unit test for Auto-scaling Util

---

hack/e2e.sh
hack/run-e2e.sh
manifests/gke/local-ssd-provision/local-ssd-provision.yaml
manifests/local-dind/local-volume-provisioner.yaml
pkg/pdapi/pdapi.go
tests/actions.go
tests/e2e/e2e.go
tests/e2e/tidbcluster/stability.go
tests/e2e/util/node/node.go
tests/e2e/util/tikv/tikv.go

fixes #1546 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

add a recovery test on node deletion for eks/gke

---

ci/pingcap_tidb_operator_build_kind.groovy
tests/config.go
tests/e2e/config/config.go
tests/e2e/e2e.go
tests/e2e/util/operator/operator.go

fixes #2043
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

kill tidb-operator pods randomly in e2e

---

deploy/modules/aws/tidb-operator/main.tf

Fix #2144 
Do not make kubeconfig file as resources so that it will not be removed at the beginning phase of terraform destroy.
Tests 
- Run `terraform apply` and then `terraform destroy`, the cluster is destroyed successfully.
Code changes
```release-note
Fix the failure that Helm cannot load the kubeconfig file when deleting the tidb-operator release during `terraform destroy`
```

fix terraform destroy failure on aws

---

charts/tidb-cluster/templates/monitor-rbac.yaml
charts/tidb-operator/templates/admission/admission-webhook-deployment.yaml
charts/tidb-operator/templates/admission/admission-webhook-service.yaml
charts/tidb-operator/templates/controller-manager-rbac.yaml
ci/run-in-vm.sh
ci/vm.groovy
hack/e2e-openshift.sh
hack/run-e2e.sh
hack/run-in-container.sh
pkg/monitor/monitor/monitor_manager.go
pkg/monitor/monitor/util.go
tests/actions.go
tests/e2e/e2e.go
tests/e2e/e2e_test.go

fixes #2087 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

scripts to run e2e against OpenShift 4

---

cmd/to-crdgen/main.go
manifests/crd.yaml
pkg/util/crdutil.go

Add the `AGE` column to show creation timestamp for all CRDs. This is convenient for users to know when the object was created. By the way, almost all Kubernetes built-in objects have this column too. `AGE` column is the default column in Kubernetes if `additionalPrinterColumns` is empty.
example:
```
$ kubectl  get tc
NAME    PD                  STORAGE   READY   DESIRE   TIKV                  STORAGE   READY   DESIRE   TIDB                  READY   DESIRE   AGE
basic   pingcap/pd:v3.0.8   1Gi       3       3        pingcap/tikv:v3.0.8   1Gi       3       3        pingcap/tidb:v3.0.8   2       2        5h8m
```
Tests 
- Unit test
- E2E test
- No code
Code changes
- …

add AGE column for all CRDs

---

.github/workflows/ci.yaml
misc/images/tidb-control/Dockerfile

`tidb-latest-linux-amd64.tar.gz` contains `tidb-v3.0.12-linux-amd64` directory not `tidb-latest-linux-amd64` now.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

fix debug docker

---

.github/workflows/ci.yaml
Makefile

We use fixed names for CI jobs, then we don't need to update branch protection rules when we modified the command we run in CI jobs.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

use fixed names for CI jobs

---

docs/api-references/docs.md
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/defaulting/tidbcluster.go
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
pkg/manager/member/pd_failover.go
pkg/manager/member/pd_failover_test.go
pkg/manager/member/pd_member_manager.go
tests/e2e/tidbcluster/stability.go

fixes #2116 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
Add `spec.pd.maxFailoverCount` field to limit max failover replicas for PD
```

Add spec.pd.maxFailoverCount to limit max failover replicas for PD

---

ci/run-in-vm.sh

We should fetch `refs/heads/*` into `refs/*`, then `master` and `release-1.1` can be parsed by `git rev-parse`.
`--depth 1` is added to avoid fetching unnecessary objects.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

fix openshift job

---

cmd/backup-manager/app/backup/backup.go
cmd/backup-manager/app/cmd/backup.go
cmd/backup-manager/app/cmd/restore.go
cmd/backup-manager/app/restore/restore.go
cmd/backup-manager/app/util/generic.go
cmd/backup-manager/app/util/util.go
go.mod
go.sum
images/tidb-backup-manager/Dockerfile
pkg/backup/backup/backup_manager.go
pkg/backup/restore/restore_manager.go

…anager image
- The stderr logs from BR are missed
- The backup-manager cannot backup or restore v3.1 TiDB Cluster
- Add the stderr logs from BR
- Include both 3.1 and 4.0 br in the tidb-backup-manager image
- Backup controller gets the tikv version from tc and passes it to backup-manager
- backup-manager chooses the correct BR version to do backup and restore according to the tikv version
Tests 
- Backup and Restore for TiDB Cluster v3.1.0-rc
- Backup and Restore for TiDB Cluster v4.0.0-rc
- Backup and Restore for TiDB Cluster nightly
Code changes
```release-note
Add stderr logs from BR to the backup-manager logs
```

fix br log issue and include both 3.1 and 4.0 br in the tidb-backup-manager image

---

Makefile
hack/e2e.sh

See examples:
```
DOCKER_REPO=hub.pingcap.net/fuyecheng make docker
docker push hub.pingcap.net/fuyecheng/tidb-backup-manager:latest
```
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

add `DOCKER_REPO` to specify full image repository

---

tests/images/e2e/Dockerfile

```
error executing access token command "/google-cloud-sdk/bin/gcloud config config-helper --format=json": err=exit status 127 output= stderr=/google-cloud-sdk/bin/gcloud: 191: exec: python: not found
```
https://internal.pingcap.net/idc-jenkins/view/tidb-operator/job/tidb-operator-e2e-gke-ci-master-serial/19/console
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

install python for gcloud CLI in e2e image

---

misc/images/tidb-debug/Dockerfile

```
...
tidb-v3.0.12-linux-amd64/
tidb-v3.0.12-linux-amd64/bin/
tidb-v3.0.12-linux-amd64/bin/pd-server
tidb-v3.0.12-linux-amd64/bin/tidb-ctl
tidb-v3.0.12-linux-amd64/bin/reparo
tidb-v3.0.12-linux-amd64/bin/tikv-ctl
tidb-v3.0.12-linux-amd64/bin/drainer
tidb-v3.0.12-linux-amd64/bin/binlogctl
tidb-v3.0.12-linux-amd64/bin/arbiter
tidb-v3.0.12-linux-amd64/bin/etcdctl
tidb-v3.0.12-linux-amd64/bin/pd-ctl
tidb-v3.0.12-linux-amd64/bin/tikv-server
tidb-v3.0.12-linux-amd64/bin/tidb-server
tidb-v3.0.12-linux-amd64/bin/pd-recover
tidb-v3.0.12-linux-amd64/bin/pump
```
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
- Breaking backward …

fix tidb-debug docker build

---

pkg/backup/backup/backup_manager.go
pkg/backup/restore/restore_manager.go
pkg/backup/util/util.go
pkg/backup/util/utils_test.go

The original way to get the image tag did not consider the "127.0.0.1:30002/pingcap/tidb-operator:v3.1.0" case.
Update the function to get the image tag.
Tests 
- Backup and Restore with v3.1.0-rc
- Backup and Restore with nightly
Code changes
```release-note
NONE
```

update the function to get the image tag

---

pkg/controller/tidbcluster/tidb_cluster_controller.go
pkg/manager/member/tidb_member_manager.go
pkg/manager/member/tidb_member_manager_test.go

When TLS for mysql client is enabled, if `tls.crt` key's value in `tlsClientSecret` is empty, tidb will start successfully, and TLS is disabled. When certificate is ready, We need to restart tidb pod to let TLS cert take effect.
If we're going to apply certificate from Letsencrypt, we need to wait for the service LB to be successfully created before applying for a certificate. When certificate is ready, then create TiDB StatefulSet.
Tests 
- Unit test
- E2E test
```
mysql> \s;
--------------
mysql  Ver 14.14 Distrib 5.7.29, for Linux (x86_64) using  EditLine wrapper
Connection id:		72
Current database:
Current user:		root@10.250.27.122
SSL:			Cipher in use is ECDHE-RSA-AES128-GCM-SHA256
Current pager:		stdout
Using …
```

check TLS certificate for mysql client before creating TiDB StatefulSet

---

docs/CONTRIBUTING.md

This fix the wrong script name in `CONTRIBUTING.md`,  which mentioned in #2264 .
Just change the `install-up-operator.sh` into `local-up-operator.sh`.
```release-note
NONE
```

fix the wrong script name in `CONTRIBUTING.md`

---

CHANGELOG-1.1.md

#1836 introduces changes to backup and restore custom resources but not included in the release notes.
Update the release notes.
Tests 
- No code
```release-note
NONE
```

update release notes for v1.1.0-rc.1

---

pkg/controller/tidb_control.go
pkg/pdapi/pdapi.go

fixes: https://github.com/pingcap/tidb-operator/issues/2253
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
Fix pdapi cache issue while cluster TLS is enabled
```

Fix pdapi cache when cluster TLS enabled

---

pkg/autoscaler/autoscaler/autoscaler_manager.go

Fix the error when syncing tidbclusterautoscaler status, add check whether the target sts is existed.
```release-note
Fix the error in syncing tidbclusterautoscaler status would cause panic when target tidbcluster is not existed.
```

Fix auto scaler status syncing error

---

ci/e2e_kind.groovy

e.g. https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-e2e-kind-ci-master-1.17/detail/tidb-operator-e2e-kind-ci-master-1.17/19/pipeline
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

require more ephemeral storage in periodical KIND jobs

---

pkg/webhook/statefulset/statefulset.go

Fix the error which would cause panic for sts webhook when sts updated strategy is not rolling updated.
```release-note
Fix a bug which would cause panic in statefulset webhook when update strategy of `StatefulSet` is not `RollingUpdate`
```

Fix sts webhook error

---

tests/e2e/tidbcluster/tls.go

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-e2e-gke-ci-master/detail/tidb-operator-e2e-gke-ci-master/102/tests
If namespace controller responds quickly, the resources under `cert-manager` may be deleted by it before kube-apiserver. So we should ignore NotFound error.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

Ignore NotFound error because resources may be deleted by namespace controller first

---

pkg/manager/member/pd_member_manager.go
pkg/manager/member/tidb_member_manager.go
pkg/manager/member/tiflash_member_manager.go
pkg/manager/member/tikv_member_manager.go

Fix https://github.com/pingcap/tidb-operator/pull/2284#issuecomment-619485792
And also the `last-applied-configuration` annotation is not set correctly during update for headless services.
Set the `last-applied-configuration` annotation correctly for services.
Tests 
- `kubectl get svc -A --watch` confirms that services are not updated without any change to service spec.
- check the log of tidb-controller-manager that no service update log without any change to service spec.
Code changes
```release-note
Fix the issue that services are updated during each sync even if no changes to the service configuration
```

services are updated during every each sync

---

hack/e2e.sh
hack/run-e2e.sh
pkg/apis/pingcap/v1alpha1/tidbcluster.go
pkg/label/label.go
pkg/manager/member/pd_failover.go
pkg/manager/member/pd_member_manager.go
pkg/manager/member/pd_member_manager_test.go
tests/e2e/tidbcluster/stability.go
tests/e2e/util/cloud/cloud.go

fixes #2161 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

PD: auto-created failover pods should be deleted when failed members are recovered

---

ci/pingcap_tidb_operator_build_kind.groovy
tests/e2e/util/operator/operator.go

https://github.com/pingcap/tidb-operator/pull/2308#discussion_r416372286
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

Improve operator killer and enable it in Advanced StatefulSet job

---

pkg/manager/member/utils.go

statefulsets are updated during each sync even if no changes to the config
Fix the equality check logic
Tests 
- Check tidb-controller-manager logs that statefulsets are not updated without changes to the config
Code changes
```release-note
Fix the issue that statefulsets are updated during each sync even if no changes to the config
```

statefulsets are updated during each sync even if no changes to the config

---

pkg/manager/member/pd_member_manager.go
pkg/manager/member/tiflash_member_manager.go
pkg/pdapi/pdapi.go

Fix #2219 
If users enable TiFlash for the existing TiDB Cluster, enable placement rules automatically with pdapi.
Tests 
- Enable TiFlash for the existing TiDB Cluster, enable-placement-rules is set automatically and PD cluster will not be rolling updated.
- Create cluster with enable-placement-rules set, tiflash will start successfully and the operator will not update the enable-placement-rules config.
Code changes
```release-note
Set `enable-placement-rules` to `true` for PD if TiFlash is enabled in the cluster
```

do not enable placement rules automatically

---

images/tidb-backup-manager/entrypoint.sh

do not print rclone conf file in the entrypoint
do not print rclone conf file in the entrypoint
Tests 
Code changes
Side effects
```release-note
Do not print rclone config in the Pod logs
```

do not print rclone conf file

---

tests/e2e/e2e_test.go

fixes #2339
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

e2e: fix namespace creation conflict

---

deploy/aliyun/main.tf
deploy/aliyun/variables.tf
deploy/modules/aliyun/tidb-cluster/local.tf
deploy/modules/aliyun/tidb-cluster/variables.tf
deploy/modules/aliyun/tidb-operator/operator.tf

fix https://github.com/pingcap/tidb-operator/issues/2378
Support creating node pools for tiflash and cdc on ack.
Tests 
- Deploy ACK with the following config, node pools for tiflash and cdc are created successfully and tiflash Pods can be scheduled to the tiflash nodes.
```
cdc_count = 1
tiflash_count = 1
cdc_instance_type = "ecs.c5.large"
tiflash_instance_type = "ecs.i2.xlarge"
#create_cdc_node_pool = true
#create_tiflash_node_pool = true
```
- Deploy ACK with the following config, node pools for tiflash and cdc will not be created.
```
cdc_count = 1
tiflash_count = 1
cdc_instance_type = "ecs.c5.large"
tiflash_instance_type = "ecs.i2.xlarge"
#create_cdc_node_pool = true
#create_tiflash_node_pool = true
```
Code changes
- Has Terraform …

support creating node pools for tiflash and cdc on ack

---

images/tidb-backup-manager/Dockerfile

https://github.com/pingcap/br/issues/241 is fixed in v3.1.1, so we have to update the BR version.
update br to v3.1.1
Tests 
- Backup and restore with the new tidb-backup-manager image for v3.1.1 TiDB Cluster
```release-note
Update BR to v3.1.1 in the tidb-backup-manager image
```

update br to v3.1.1

---

examples/prometheus-operator/tikv-serviceMonitor.yaml

Signed-off-by: yeya24 <yb532204897@gmail.com>
The current tikv service monitor example doesn't work with prometheus operator because tikv doesn't open 20180 explicitly.
This example works for me. Verification

Update prometheus operator tikv example

---

pkg/manager/member/pd_member_manager.go
pkg/manager/member/tidb_member_manager.go
pkg/manager/member/utils.go

Close https://github.com/pingcap/tidb-operator/issues/2455
```release-note
Fix the bug that the service annotations would be exposed in `Tidbcluster` speciafication.
```

Fix the bug that service annotations exposed in tidbcluster

---

ci/pingcap_tidb_operator_build_kind.groovy
tests/e2e/util/image/image.go
tests/e2e/util/util.go

upgrade 4.0 upgrade version from `nightly` to `4.0.0-rc.2` in e2e and make wait timeout for installing operator from 3min to 10min.
```release-note
NONE
```

Upgrade e2e 4.0 version and fix 1.12 env error

---

ci/pingcap_tidb_operator_build_kind.groovy
tests/actions.go

Fix the helm install params error which would cause `ValidatingWebhookConfiguration` and `MutatingWebhookConfiguration` installed in an unwanted env.
```release-note
NONE
```

Fix Helm install setting params

---

tests/e2e/tidbcluster/tidbcluster.go
tests/e2e/tidbcluster/tls.go

fixes: https://github.com/pingcap/tidb-operator/issues/2405
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

e2e: separate client certificates for BR

---

pkg/controller/tidb_control.go
pkg/controller/tidb_control_test.go

Now, all controllers use this single tidbConrol instance, this pr remove the mutex to improve performance.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
Improve performance by removing TidbControl's lock.
```

Improve performance by removing TidbControl's lock

---

docs/api-references/docs.md
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/tikv_config.go
pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
tests/pkg/fixture/fixture.go
tests/util.go

fixes #2509 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

Set `reserve-space = 0MB` for TiKV 4.0+ in e2e tests

---

pkg/manager/member/tiflash_member_manager.go
pkg/manager/member/tiflash_member_manager_test.go
pkg/manager/member/tikv_member_manager.go

fix #2458 
Separate the tikv and tiflash tombstone stores
Tests 
- Delete some tikv and tiflash stores, check the tidbcluster status that status.tikv.tombstoneStores only includes tikv tombstone stores and status.tiflash.tombstoneStores only includes tiflash tombstone stores
```
tiflash:
image: pingcap/tiflash:v3.1.0-rc
phase: Normal
statefulSet:
collisionCount: 0
currentReplicas: 5
currentRevision: test310-tiflash-64684cfbdb
observedGeneration: 9
readyReplicas: 5
replicas: 5
updateRevision: test310-tiflash-64684cfbdb
updatedReplicas: 5
stores:
"157":
id: "157"
ip: test310-tiflash-1.test310-tiflash-peer.test310.svc
lastHeartbeatTime: "2020-05-14T13:04:07Z"
lastTransitionTime: "2020-05-14T11:11:40Z"
leaderCount: 0
podName: …
```

separate tikv and tiflash tombstone stores

---

charts/tidb-operator/templates/config/_scheduler-policy-json.tpl
hack/local-up-operator.sh
pkg/scheduler/predicates/fake.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go
pkg/scheduler/server/mux.go

fixes #1968 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
Support preemption in `tidb-scheduler`
```

tidb-scheduler: implement kube-scheduler extender preempt verb

---

tests/e2e/util/image/image.go

Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

e2e/bugfix: preload tidb 3 upgrade version image

---

hack/e2e-openshift.sh

this works around the bug in docker CLI: https://github.com/docker/cli/issues/2533
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

e2e/openshift: pin the same version for docker-ce and docker-ce-cli

---

docs/api-references/docs.md
go.mod
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/tidbclusterautoscaler_types.go
pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
pkg/autoscaler/autoscaler/autoscaler_manager.go
pkg/autoscaler/autoscaler/tikv_autoscaler.go
pkg/autoscaler/autoscaler/util.go
pkg/autoscaler/autoscaler/util_test.go
pkg/label/label.go
tests/e2e/tidbcluster/serial.go

UCP #2241 
Add Phrase for `TidbClusterAutoScaler`, it has three optional values: Normal, ReadyToScaleOut, ReadyToScaleIn.
Add user defined autoscale threshold.
use tidb as an example, tikv should be the same.
1. check phase
after autoscaler calculate the target replica, if target replica equals to current replica, set auto scaler phase to normal and return, otherwise check if the phase equal to scaleOut or scaleIn, if not, update the phase and record timestamp. go to 2.
2. check timestamp threshold
check the record timestamp remains longer than threshold which user defined. If not, return, otherwise go to 3.
3. do autoscale
set phase to normal and do normal autoscale.
**Design for e2e tests:**
After mock response from Prometheus, without noise reduction, it will start auto scaling after …

[UCP] Noise reduction support when cluster auto scaling

---

ci/e2e_eks.groovy
ci/e2e_gke.groovy

Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

e2e: clean eks/gke if job is unsuccessful

---

manifests/dm/master/dm-master.yaml
manifests/dm/worker/base/dm-worker.yaml

This PR bumps dm version to latest HA version: v2.0.0-beta.1
DM image version is bumped.
Tests 
- No code
Code changes
- DM manifests
- Need to cherry-pick to the release branch: release-1.1
```release-note
Bump dm version to v2.0.0-beta.1
```

Bump dm version to v2.0.0-beta.1

---

tests/e2e/tidbcluster/tidbcluster.go
tests/e2e/util/image/image.go

images tagged with `nightly` change very day
better we don't use it in e2e tests
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

use v4.0.0 in CDC e2e

---

docs/api-references/docs.md
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/apis/pingcap/v1alpha1/validation/validation.go
pkg/apis/pingcap/v1alpha1/validation/validation_test.go
pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
pkg/manager/member/tidb_member_manager.go
pkg/manager/member/tidb_member_manager_test.go
pkg/monitor/monitor/util.go
pkg/monitor/monitor/util_test.go

UCP: #2586 
Close: #2586 
Resolve: #2564
1. Add `loadBalancerSourceRanges` to `service spec`.
2. Expose it on the `TiDB Service` and `Monitor Service`.
3. Add some unit tests for setting `LoadBalancerSourceRanges` on the `TiDB Service` and `Monitor Service`.
Tests 
- Unit test
- E2E test
Code changes
Side effects
```release-note
Support LoadBalancerSourceRanges in the ServiceSpec for the TidbCluster and TidbMonitor.
```

UCP:Support Service LoadBalancerSourceRanges

---

tests/e2e/tidbcluster/tidbcluster.go

Revise Tidbmonitor e2e case by using crd directly and fix some checking error.
ref https://github.com/pingcap/tidb-operator/issues/2513
```release-note
NONE
```

Revise Tidbmonitor e2e case

---

pkg/scheduler/predicates/ha.go
pkg/scheduler/predicates/ha_test.go
pkg/scheduler/predicates/test_helper.go

fix: #2638
When scheduling a pod based on zone, firstly, gets all the nodes that have scheduled the pod by traversing pods, and then, gets all zones that have scheduled pods by querying node information from `kubecli`, finally, computes available zones.
Tests 
- Unit test
Code changes
Side effects
- None
```release-note
NONE
```

Fixed scheduling errors when based on zone scheduling

---

ci/e2e_kind.groovy
ci/pingcap_tidb_operator_build_kind.groovy
hack/e2e.sh

fix #2619 
Add an option environment `ETCD_STORAGE_TYPE` , default is `disk`, if set it as `memory` will
running etcd use memory storage.
Reference:
https://github.com/kubernetes-sigs/kind/issues/845#issuecomment-529154066
Tests 
Code changes
Side effects
```release-note
None
```

E2e CI job use memory storage for etcd

---

cmd/backup-manager/app/util/util.go

close https://github.com/pingcap/tidb-operator/issues/2505
As each backup job's target tidbcluster have already been set in its spec. We don't need to expose its datasource connection info in the log.
```release-note
Make datasource information hidden in log for `Backup` and `Restore` job
```

Hide datasource information for backup job

---

tests/e2e/tidbcluster/serial.go

Add some useful logs in auto-scaling e2e case to help us know what happended during e2e test.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

revise log for auto-scaling e2e case

---

cmd/backup-manager/app/backup/backup.go
cmd/backup-manager/app/backup/manager.go
cmd/backup-manager/app/util/remote.go
cmd/backup-manager/app/util/util.go
pkg/apis/pingcap/v1alpha1/types.go

issues: fix https://github.com/pingcap/tidb-operator/issues/2660
If backup job failed, remote file will not clean if delete the backup CRD.
add remote path at the begining of backup 
Tests 
- E2E test
the step just as issue 
Code changes

Backup: fix remote file not clean when job is failed

---

charts/tidb-drainer/templates/drainer-statefulset.yaml
charts/tidb-drainer/values.yaml
charts/tidb-lightning/templates/job.yaml
charts/tidb-lightning/values.yaml
charts/tidb-operator/templates/admission/admission-webhook-deployment.yaml
charts/tidb-operator/templates/admission/pre-delete-job.yaml
charts/tidb-operator/templates/advanced-statefulset-deployment.yaml
charts/tidb-operator/templates/apiserver-deployment.yaml
charts/tidb-operator/templates/controller-manager-deployment.yaml
charts/tidb-operator/templates/scheduler-deployment.yaml
charts/tidb-operator/values.yaml
charts/tikv-importer/templates/tikv-importer-statefulset.yaml
charts/tikv-importer/values.yaml
docs/api-references/docs.md
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/tidbcluster_component.go
pkg/apis/pingcap/v1alpha1/tidbinitializer_types.go
pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
pkg/backup/backup/backup_cleaner.go
pkg/backup/backup/backup_manager.go
pkg/backup/backupschedule/backup_schedule_manager.go
pkg/backup/restore/restore_manager.go
pkg/manager/member/tidb_discovery_manager.go
pkg/manager/member/tidb_init_manager.go
pkg/monitor/monitor/util.go

fixes: https://github.com/pingcap/tidb-operator/issues/2418
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
Add imagePullSecrets attribute to all components
```

Add imagePullSecrets attribute to all components

---

charts/tidb-cluster/templates/discovery-deployment.yaml
pkg/manager/member/tidb_discovery_manager.go

fixes: https://github.com/pingcap/tidb-operator/issues/2693
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
Change tidb-discovery strategy type to `Recreate`
```

Change tidb-discovery strategy type to `Recreate`

---

pkg/controller/pv_control.go
pkg/manager/meta/reclaim_policy_manager.go

The label selector logic is wrong in `reclaimPolicyManager`'s `sync` function which would cause TidbMonitor covered TidbCluster's reclaimPolicy, this request fix it.
fix https://github.com/pingcap/tidb-operator/issues/2697
```release-note
Fix the pv syncing error when `TidbMonitor` and `TidbCluster` have different value in `reclaimPolicy`
```

Fix labelselector error in reclaimPolicyManager

---

docs/api-references/docs.md
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
pkg/manager/member/pd_member_manager.go

Close https://github.com/pingcap/tidb-operator/issues/2650
Add `enableDashboardInternalProxy` to control whether enable `internal-proxy` for pd dashboard.  This would let user directly visit dashboard by discovery-service:10262. 
After this pr finished, we need to update the document about `access dashboard`.
```release-note
Add `EnableDashboardInternalProxy` in `PDSpec` to let user directly visit PD Dashboard.
```

Add switch to control the Dashboard Proxy

---

tests/monitor.go

When checking grafana functionality, we should use wait function instead of throwing error directly.
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/operator_ghpr_e2e_test_kind/detail/operator_ghpr_e2e_test_kind/6675/pipeline
```release-note
NONE
```

Fix TidbMonitor e2e check error

---

manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/pd_config.go

The Dashboard configuration's openapi comment is forgotten to be added, this request fix this.
```release-note
NONE
```

Fix missing openapi configuration

---

pkg/controller/tidbcluster/tidb_cluster_control.go
pkg/manager/member/orphan_pods_cleaner.go
pkg/manager/member/orphan_pods_cleaner_test.go
pkg/manager/member/pvc_cleaner.go

fixes #2699 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
Fix an issue that pods may be stuck in pending for a long time in scale-out after a scale-in
```

use the latest version object in deletion request

---

pkg/label/label.go
pkg/manager/member/pd_member_manager.go
pkg/manager/member/pd_member_manager_test.go
pkg/manager/member/tidb_member_manager.go
pkg/manager/member/tidb_member_manager_test.go
pkg/manager/member/tiflash_member_manager_test.go
pkg/manager/member/tikv_member_manager.go
pkg/manager/member/tikv_member_manager_test.go
pkg/monitor/monitor/util.go
pkg/monitor/monitor/util_test.go

Fixes https://github.com/pingcap/tidb-operator/issues/2622
Tests 
- Unit test
```bash
➜  tidb-operator git:(add-labels-for-service) ✗ kubectl get svc -n pingcap-dev
NAME                     TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)              AGE
basic-discovery          ClusterIP   10.107.212.188   <none>        10261/TCP            2m3s
basic-grafana            ClusterIP   10.111.254.210   <none>        3000/TCP             2m2s
basic-monitor-reloader   ClusterIP   10.97.149.92     <none>        9089/TCP             2m2s
basic-pd                 ClusterIP   10.110.120.114   <none>        2379/TCP             2m2s
basic-pd-peer            ClusterIP   None             <none>        2380/TCP             2m2s
basic-prometheus …
```

add label to identify individual services
