charts/tidb-cluster/templates/monitor-deployment.yaml
charts/tidb-cluster/values.yaml

Part of: https://github.com/pingcap/tidb-operator/issues/2710
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
Fix alert rules lost after rolling upgrade
```

Fix alert rules lost after rolling upgrade

---

manifests/crd.yaml
pkg/util/crdutil.go

Fix https://github.com/pingcap/tidb-operator/issues/2659
previous: 
```
➜  ~ kubectl get bk -o wide
NAME              BACKUPPATH   BACKUPSIZE   COMMITTS   STARTED   COMPLETED   AGE
demo1-backup-s3                0                       14m       14m         14m
```
now:
```
➜  ~ kubectl get bk -o wide
NAME              BACKUPPATH   BACKUPSIZE   COMMITTS   STARTED                COMPLETED              AGE
demo1-backup-s3                0                       2020-06-16T10:20:28Z   2020-06-16T10:20:28Z   9m51s
```
Tests 
Code changes
Side effects
```release-note
NONE
```

fix backup and restore time column

---

tests/backup.go
tests/e2e/tidbcluster/tidbcluster.go

The backup and restore e2e case failed somtimes due to unconcurrency of the target database and source database. This request ensured that we will stop insert data to target database before we started to back up data.
```release-note
NONE
```

Revise e2e backup restore case

---

docs/api-references/docs.md
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
pkg/monitor/monitor/util.go

fixes: https://github.com/pingcap/tidb-operator/issues/2710
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
Add alertMangerAlertVersion option to TidbMonitor
```

Add alertMangerAlertVersion option to TidbMonitor

---

tests/actions.go
tests/backup.go
tests/cmd/stability/main.go
tests/crd_test_util.go
tests/e2e/tidbcluster/serial.go
tests/e2e/tidbcluster/tidbcluster.go
tests/failover.go
tests/pkg/fixture/fixture.go
tests/pkg/ops/tikv.go

These request let tidbcluster deployed by CR and fix some stability bugs.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

Use crd to manage tidbcluster in stability

---

tests/e2e/util/image/image.go

ref: https://github.com/pingcap/tidb-operator/issues/2761
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

revert tidb v3 version change

---

pkg/apis/pingcap/v1alpha1/tidbcluster.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/manager/member/pd_member_manager.go
pkg/manager/member/pd_member_manager_test.go
pkg/manager/member/pd_upgrader.go
pkg/manager/member/pd_upgrader_test.go
pkg/manager/member/tikv_member_manager.go
pkg/manager/member/tikv_member_manager_test.go
pkg/manager/member/tikv_scaler.go
pkg/manager/member/tikv_scaler_test.go
pkg/manager/member/tikv_upgrader.go
pkg/manager/member/tikv_upgrader_test.go

Fix https://github.com/pingcap/tidb-operator/issues/2631
Cross-check during upgrading and scaling and make sure that upgrading and scaling for tikv do not occur at the same time.
Tests 
- Unit test
- E2E test
- Scale out TiKV and then upgrade TiKV
- Scale in TiKV and then upgrade TiKV
- Scale in and upgrade TiKV at the same time
- Upgrade TidbCluster to newer version and scale in TiKV at the same time
Code changes
```release-note
Do not scale or upgrade tikv at the same time
```

do not scale or upgrade tikv at the same time

---

pkg/pdapi/pdapi.go
pkg/webhook/pod/tikv_creater.go
tests/e2e/util/image/image.go

Move `filterLeaderEvictScheduler` into pdapi function to make `GetEvictLeaderSchedulers` function common used both for PD 3.0.x and 4.0.x
fixes https://github.com/pingcap/tidb-operator/issues/2761
```release-note
NONE
```

Move compatible filterLeaderEvictScheduler in pdapi

---

cmd/backup-manager/app/backup/manager.go
cmd/backup-manager/app/export/manager.go
docs/api-references/docs.md
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/types.go
pkg/util/crdutil.go

Fixes https://github.com/pingcap/tidb-operator/issues/2634
Tests 
Code changes
Side effects
```release-note
NONE
```

add humanreadable backup size

---

pkg/pdapi/pd_config.go
pkg/pdapi/pdapi.go

fixes #2805 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
ACTION REQUIRED: PD v4.0.2 introduced a breaking change in config API, please upgrade tidb-operator tor v1.1.2 when deploying the TiDB after v4.0.2
```

update PD config API schema and use evictSchedulerLeader config API

---

pkg/controller/pod_control.go
pkg/controller/pvc_control.go
pkg/controller/service_control.go
pkg/controller/stateful_set_control.go

use `runtime.Object` instead of `TidbCluster` for the native api controller interface so that other controller could use these methods directly.
```release-note
NONE
```

Revise interface for the native api in the controller package

---

tests/e2e/tidbcluster/serial.go

Skip the e2e case `upgrading tidb-operator in the same minor series should not trigger rolling-update` as it have already been covered by the `[Verify: Upgrading Operator from 1.1.0]`
```release-note
NONE
```

Skip duplicated e2e case

---

docs/api-references/docs.md
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/pd_config.go
pkg/apis/pingcap/v1alpha1/tidb_config.go
pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go

Fix #2808
update pd/tidb/tikv config to v4.0.2
Tests 
- Unit test
- E2E test
- Create TiDB cluster with the default configuration and telemetry is enabled for both the TiDB and Dashboard
- Create TiDB cluster with the telemetry configuration disabled and telemetry is disabled for both the TiDB and Dashboard
Code changes
Side effects
```release-note
Update PD/TiDB/TiKV config to v4.0.2
```

update pd/tidb/tikv config to v4.0.2

---

pkg/backup/backup/backup_cleaner.go
pkg/backup/backup/backup_manager.go
pkg/backup/restore/restore_manager.go
pkg/controller/backupschedule/backup_schedule_controller_test.go
pkg/controller/controller_utils.go
pkg/controller/generic_control_test.go
pkg/manager/member/pd_member_manager.go
pkg/manager/member/pd_scaler_test.go
pkg/manager/member/pd_upgrader_test.go
pkg/manager/member/scaler_test.go
pkg/manager/member/ticdc_member_manager.go
pkg/manager/member/tidb_discovery_manager.go
pkg/manager/member/tidb_init_manager.go
pkg/manager/member/tidb_member_manager.go
pkg/manager/member/tidb_upgrader_test.go
pkg/manager/member/tiflash_member_manager.go
pkg/manager/member/tikv_group_member_manager.go
pkg/manager/member/tikv_member_manager.go
pkg/manager/member/tikv_scaler_test.go
pkg/manager/member/tikv_upgrader_test.go

Resolve #2836 
Replace controller.Int32Ptr with k8s.io/utils/pointer.Int32Ptr
Tests 
- Unit test
- E2E test
```release-note
NONE
```

Replace controller.Int32Ptr with k8s.io/utils/pointer.Int32Ptr

---

CHANGELOG-1.1.md
charts/tidb-cluster/values.yaml
charts/tidb-operator/values.yaml
deploy/aliyun/variables.tf
deploy/aws/variables.tf
deploy/gcp/variables.tf

Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

add v1.1.2 release notes

---

examples/basic-cn/tidb-cluster.yaml
examples/basic/tidb-cluster.yaml

this is because the `tikv-server` creates a 2GB file in its data directory to reserve space since TiKV 4.0.0-beta. we should disable this feature in our basic examples which are expected to work in minimal environments, e.g. minikube, kind.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

disable reserve-space in basic examples

---

pkg/controller/tidbcluster/tidb_cluster_controller.go

it has high frequency and normally not useful in debugging (not human readable), e.g.
```
I0701 03:04:59.820980       1 tidb_cluster_controller.go:384] StatefulSet default/basic-tidb updated, {Replicas:0xc0017e7638 Selector:&LabelSelector{MatchLabels:map[string]string{app.kubernetes.io/component: tidb,app.kubernetes.io/instance: basic,app.kubernetes.io/managed-by: tidb-operator,app.kubernetes.io/name: tidb-cluster,},MatchExpressions:[]LabelSelectorRequirement{},} Template:{ObjectMeta:{Name: GenerateName: Namespace: SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[app.kubernetes.io/component:tidb app.kubernetes.io/instance:basic app.kubernetes.io/managed-by:tidb-operator …
```

don't dump StatefulSet spec on update event

---

charts/tidb-cluster/templates/monitor-secret.yaml

Fixes a deployment error. (#2867)
```
<(.Values.monitor.create) and (.Values.monitor.grafana.create)>: can't give argument to non-function .Values.monitor.create
```
I have confirmed that both helm2 and helm3 work.
https://v2.helm.sh/docs/chart_template_guide/#operators-are-functions
https://helm.sh/docs/chart_template_guide/function_list/#and
Fixed syntax.
Tests 
I used a v1.16 series k8s cluster.
The following command is used to check the operation.
```bash
kubectl create ns tidb-admin
helm repo add pingcap https://charts.pingcap.org/
kubectl apply -f https://raw.githubusercontent.com/pingcap/tidb-operator/master/manifests/crd.yaml
helm upgrade tidb-operator pingcap/tidb-operator -i --wait -n tidb-admin
helm upgrade tidb-cluster …
```

Fixed syntax for "and" conditions

---

manifests/local-dind/kubernetes-dashboard.yaml

`gcr.io/google_containers` is deprecated, see https://github.com/kubernetes/release/issues/270
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

Use k8s.gcr.io vanity domain

---

charts/tidb-cluster/values.yaml
deploy/aliyun/manifests/db-monitor.yaml.example
deploy/aws/manifests/db-monitor.yaml.example
deploy/gcp/manifests/db-monitor.yaml.example
examples/auto-scale/tidb-monitor.yaml
examples/basic-cn/tidb-monitor.yaml
examples/basic/tidb-monitor.yaml
examples/monitor-with-externalConfigMap/tidb-monitor.yaml
examples/monitor-with-thanos/tidb-monitor.yaml
examples/tiflash/tidb-monitor.yaml
manifests/monitor/tidb-monitor.yaml
tests/e2e/util/image/image.go

fix https://github.com/pingcap/tidb-operator/issues/2797
replace grafana version from v6.0.1 to v6.1.6
Tests 
- Unit test
- E2E test
```release-note
Update used grafana version from v6.0.1 to v6.1.6
```

update grafana version to v6.1.6

---

docs/api-references/config.json
docs/api-references/docs.md

The doc link to the kubernetes v1.13 is not available any more, so we need to update the link.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

fix link error for kubernetes reference

---

charts/tidb-drainer/templates/_helpers.tpl
charts/tidb-drainer/templates/drainer-statefulset.yaml
charts/tidb-drainer/values.yaml

resolve https://github.com/pingcap/tidb-operator/issues/2969
add tls support between drainer and downstream database server.
add tls syncer part for drainer.
Tests 
- Unit test
- E2E test
* Write to downstream database without tls.
* Write to downstream database with only downstream tls specified.
* Write to downstream but checkpoint to another database with/without tls enabled.
```release-note
Add TLS support between drainer and downstream database server
```

add tls support between drainer and downstream database server

---

CHANGELOG-1.1.md
charts/tidb-cluster/values.yaml
charts/tidb-operator/values.yaml
deploy/aliyun/variables.tf
deploy/aws/variables.tf
deploy/gcp/variables.tf

Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

v1.1.3 release notes

---

docs/api-references/docs.md
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/tidb_config.go

deprecate auto_random config
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

deprecate auto_random config

---

charts/tidb-operator/templates/admission/admission-webhook-deployment.yaml
charts/tidb-operator/templates/advanced-statefulset-deployment.yaml
charts/tidb-operator/values.yaml
pkg/backup/backup/backup_cleaner.go
pkg/backup/backup/backup_manager.go
pkg/backup/restore/restore_manager.go
pkg/util/util.go
pkg/util/utils_test.go

fixes #2944 
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
Configure TZ environment for admission webhook and advanced statefulset controller deployed in tidb-operator chart
```

set TZ environment for webhook and advanced statefulset

---

hack/run-e2e.sh

Under mac system,I cannot run e2e test  normally.
command：
`
./output/bin/helm init --service-account tiller --output yaml             | sed 's@apiVersion: extensions/v1beta1@apiVersion: apps/v1@'             | sed 's@  replicas: 1@  replicas: 1\n  selector: {"matchLabels": {"app": "helm", "name": "tiller"}}@'             | kubectl  apply -f -
`
error:
`
error: error parsing STDIN: error converting YAML to JSON: yaml: line 11: mapping values are not allowed in this context
`
I find `\n` nextline character not work in mac , so we can replace with `\'$'\n`.
Tests 
- E2E test
Code changes

fix  helm install question included in e2e shell under mac system

---

charts/tidb-operator/Chart.yaml
ci/release_tidb_operator_binary_and_image.groovy

This is necessary to publish via rancher charts.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

chart/tidb-operator: add appVersion & maintainers fields

---

charts/tidb-operator/templates/admission/admission-webhook-registration.yaml
cmd/admission-webhook/main.go
pkg/webhook/admission_hooks.go
pkg/webhook/strategy/webhook.go
pkg/webhook/strategy/webhook_test.go

https://github.com/pingcap/tidb-operator/issues/3046
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

webhook: Register Strategy AdmissionHook at a separate API endpoint

---

pkg/apis/pingcap/v1alpha1/tiflash_config.go
pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
pkg/manager/member/tiflash_util.go
pkg/manager/member/tiflash_util_test.go

Add advertise status address for TiFlash
Tests 
- Unit test
- E2E test
- Deploy TiFlash with TLS enabled
- Deploy TiFlash with TLS disabled
Code changes
```release-note
NONE
```

add advertise status address for tiflash

---

pkg/autoscaler/autoscaler/query/external.go
pkg/controller/http_client.go
pkg/controller/tidb_control.go
pkg/pdapi/pdapi.go

Fix #3079 
Disable keepalive for TLS connections, more detail refer to https://github.com/elastic/cloud-on-k8s/issues/854#issuecomment-491773323
Tests 
- Unit test
- E2E test
- Deploy, upgrade, scaling TiDB Cluster with TLS enabled (find one bug with upgrading #3078)
- Deploy, upgrade, scaling TiDB Cluster with TLS disabled
Code changes
```release-note
Fix goroutine leak when TLS enabled
```

fix goroutine leak when tls enabled

---

pkg/autoscaler/autoscaler/autoscaler_manager.go
pkg/autoscaler/autoscaler/util.go

Signed-off-by: Lonng <heng@lonng.org>
1. Use `tcLister` to retrieve the TidbCluster instance instead of fetching it from apiserver directly.
2. Simplify some code in `pkg/autoscaler`, I think nested `if` statement will make the code not straightforward.
Tests 
- Unit test
- E2E test
```release-note
NONE
```

Simplify some code in pkg/autoscaler

---

docs/api-references/docs.md
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/tidb_config.go
pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go

Fixes https://github.com/pingcap/tidb-operator/issues/3075
Add max-index-length to TidbCluster and TiDBGroup in manifests/crd.yaml, and add MaxIndexLength to tidb_config.go.
Tests 
I was able to successfully add max-index-length to the config in TidbCluster and have it applied to nodes in the cluster.
Code changes
Side effects
n/a
```release-note
Add support for the `max-index-length` (https://docs.pingcap.com/tidb/stable/tidb-configuration-file#max-index-length) TiDB config option to the TidbCluster CRD
```

Add support for max-index-length to TidbCluster CRD

---

pkg/backup/backup/backup_manager.go
pkg/backup/restore/restore_manager.go

None
Unified use of public method  `TidbCluster.IsTLSClusterEnabled`.

Unified use of public method TidbCluster.IsTLSClusterEnabled.

---

docs/api-references/docs.md
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/tiflash_config.go
pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
pkg/manager/member/tiflash_util.go
pkg/manager/member/tiflash_util_test.go

Support cert-allowed-cn for TiFlash
Tests 
- Unit test
- E2E test
- Deploy TiDB Cluster with TiFlash and TLS enabled
Code changes
```release-note
Support cert-allowed-cn for TiFlash
```

support cert-allowed-cn for tiflash

---

cmd/backup-manager/app/cmd/export.go
cmd/backup-manager/app/cmd/import.go
cmd/backup-manager/app/export/export.go
cmd/backup-manager/app/export/manager.go
cmd/backup-manager/app/import/import.go
cmd/backup-manager/app/import/manager.go
pkg/backup/backup/backup_manager.go
pkg/backup/restore/restore_manager.go

resolve https://github.com/pingcap/tidb-operator/issues/3094
dumpling and lightning have already supported tls but tidb-operator don't use the configs.
Add tls configs for lightning&dumpling in tidb-operator.
Tests 
- Unit test
- E2E test
Manually test dumpling&lightning for tidb cluster.
Code changes
```release-note
Support TLS for Backup&Restore with dumpling&lightning.
```

backup: TLS Support for Backup&Restore with dumpling&lightning

---

docs/design-proposals/2020-08-03-deploy-tidb-cluster-across-mulitple-kubernetes-clusters.md

After more discussion with community members, we agreed that we can reuse the `spec.cluster` added in the heterogeneous design and update the discovery component to get PD members from the PD cluster of `spec.cluster`, if it's unavailable, get PD members from its own PD service, which makes the TiDB Clusters more equipotent and no "master" cluster concept anymore, one cluster can be down without affecting the other clusters.
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE …
```

update design for across kubernetes deploy

---

charts/tidb-operator/templates/controller-manager-rbac.yaml
pkg/controller/tidbcluster/tidb_cluster_control.go
pkg/controller/tidbcluster/tidb_cluster_control_test.go
pkg/controller/tidbcluster/tidb_cluster_controller.go
pkg/manager/member/pvc_resizer.go
pkg/manager/member/pvc_resizer_test.go
pkg/util/util.go

fixes https://github.com/pingcap/tidb-operator/issues/3004
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
Support patching PVCs when the storage request is increased. Due to the limitation of the current statefulset, new PVCs will be created with the old storage request and resized later
```

Patch PVCs when storage request is increased

---

pkg/manager/meta/reclaim_policy_manager.go

Signed-off-by: Lonng <heng@lonng.org>
The previous implementation contains a BUG that wrongly treats `TiKVGroup.GetName()` as `namespace`.
This PR fixes the bug described above and refactor some code to simply the codebase.
Tests 
- Unit test
- E2E test
```release-note
NONE
```

Refactor the reclaim_policy_manager and fix TiKVGroup.GetName()

---

pkg/manager/member/pvc_resizer.go

With the current implementation, there will be too many noisy logs even if there is no change to the `storage` if the sc does not support expansion:
```
W0820 11:06:53.210573       1 pvc_resizer.go:170] Storage Class "local-storage" used by PVC ns1/tikv-ns1-tikv-1 does not support volume expansion, skipped
W0820 11:06:53.210581       1 pvc_resizer.go:170] Storage Class "local-storage" used by PVC ns1/tikv-ns1-tikv-4 does not support volume expansion, skipped
W0820 11:06:53.210590       1 pvc_resizer.go:170] Storage Class "local-storage" used by PVC ns1/tikv-ns1-tikv-3 does not support volume expansion, skipped
```
Check if expansion is supported only when we need to patch the PVC.
Tests 
- Unit test
- E2E test
Deploy …

optimize pvc resizer logic

---

CHANGELOG-1.1.md
charts/tidb-cluster/values.yaml
charts/tidb-operator/values.yaml
deploy/aliyun/variables.tf
deploy/aws/variables.tf
deploy/gcp/variables.tf

https://github.com/pingcap/tidb-operator/issues/3140
Tests 
- Unit test
- E2E test
- No code
Code changes
```release-note
NONE
```

add release notes for v1.1.4 and update operator versions

---

examples/heterogeneous/tidb-monitor.yaml
pkg/monitor/monitor/util.go

#3062 
Prometheus configuration relabel_configs regex use multiple cluster name join.
Tests 
- Unit test
- E2E test
Code changes
Side effects
- None

Support tidbmonitor monitor multiple cluster.

---

charts/tidb-operator/templates/admission/pre-delete-job.yaml

Fails to install or uninstall tidb-operator again if last `helm uninstall` was interrupted by `ctrl + c`. 
Related issue: [https://github.com/helm/helm/issues/8640](https://github.com/helm/helm/issues/8640)
Add the default `before-hook-creation` to `helm.sh/hook-delete-policy`. This configuration delete the previous resource before a new hook is launched.
Tests 
1. Stop `helm uninstall` abruptly by `ctrl + c`.
2. Successfully execute `helm uninstall` again.
Code changes
```release-note
NONE
```

fix tidb-operator helm hook-delete-policy.

---

ci/pull_e2e_kind.groovy

Close: #3136 
Upload images and charts if the `GIT_REF` of the build matches `release-*` branch.
Tests 
- No code
Code changes
Side effects
None
None
```release-note
NONE
```

ci: upload images and charts if the build is on release-* branch

---

docs/api-references/docs.md
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/manager/member/failover.go
pkg/manager/member/pd_failover.go
pkg/manager/member/tidb_failover.go
pkg/manager/member/tiflash_failover.go
pkg/manager/member/tiflash_member_manager.go
pkg/manager/member/tikv_failover.go
pkg/manager/member/tikv_member_manager.go
pkg/manager/member/utils.go
pkg/manager/member/utils_test.go

Fix #3177
Add `recoverFailover` field to the spec of TiKV and TiFlash, when users set it to `true`, TiDB Operator will try to recover the failure stores for TiKV and TiFlash.
Tests 
- Unit test
- E2E test
- Failover TiKV manually, after the failed Pods is recovered, the newly created Pods will not be removed, update TidbCluster to set `recoverFailover: true`, the newly created Pods will be removed
- Failover TiFlash manually, after the failed Pods is recovered, the newly created Pods will not be removed, update TidbCluster to set `recoverFailover: true`, the newly created Pods will be removed
Code changes …

Support recover from failover for tiflash and tikv

---

docs/api-references/docs.md
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/manager/member/pd_member_manager.go
pkg/manager/member/pump_member_manager.go
pkg/manager/member/ticdc_member_manager.go
pkg/manager/member/tidb_member_manager.go
pkg/manager/member/tiflash_member_manager.go
pkg/manager/member/tikv_member_manager.go

fix #3244 
Tests 
deploy a cluster using the origin master branch operator, after upgrade the operator to this branch the origin cluster will not rolling update.
deploy a cluster using: 
```yaml
metadata:
name: account
spec:
version: v4.0.4
serviceAccount: gacc
timezone: UTC
pvReclaimPolicy: Delete
discovery: {}
pd:
serviceAccount: pdacc
replicas: 1
requests:
storage: "1Gi"
config: {}
tikv:
baseImage: pingcap/tikv
replicas: 1
requests:
storage: "1Gi"
config:
storage:
reserve-space: "0MB"
tidb:
serviceAccount: tidbacc
baseImage: pingcap/tidb
replicas: 1
service:
type: ClusterIP
config: {}
pump:
baseImage: pingcap/tidb-binlog
serviceAccount: "pumpaccount"
replicas: 3 …
```

Add servicsAccount for pump/pd/tidb/tidbcluster

---

ci/pull_e2e_kind.groovy

Define a `RELEASE_VER` parameter for Jenkins job, to make the released version configurable via CI.
Tests 
- E2E test
- No code
Code changes
```release-note
NONE
```

ci: make release version configurable via jenkins parameter

---

pkg/apis/pingcap/v1alpha1/tidbcluster.go

Fix https://github.com/pingcap/tidb-operator/issues/3050
Tests 
- Unit test
- E2E test
- Configure baseImage for PD/TiDB/TiKV/TiFlash/Pump/TiCDC with image tag and set `spec.version: ""`, `spec.<component>.spec: ""`
Code changes
```release-note
NONE
```

fix empty version issue

---

pkg/apis/pingcap/v1alpha1/pd_config.go
pkg/apis/pingcap/v1alpha1/tidb_config.go

In https://github.com/pingcap/tidb-operator/pull/3180 we added three new configurations but we forget to label them as `omitempty`.
Add `omitempty` fro these configurations.
Tests 
- Unit test
- E2E test
Code changes
```release-note
NONE
```

add omitempty for newly added tidb&pd configurations

---

docs/api-references/docs.md
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/tidbclusterautoscaler_types.go
pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
pkg/autoscaler/autoscaler/autoscaler_manager.go
pkg/autoscaler/autoscaler/util.go
pkg/autoscaler/autoscaler/util_test.go

Signed-off-by: Howard Lau <howardlau1999@hotmail.com>
https://github.com/pingcap/tidb-operator/issues/3159 Task#2
Construct pd strategy according to autoscaler spec
Tests 
- Unit test
Code changes
```release-note
NONE
```

autoscaler: construct pd strategy request according to autoscaler spec

---

docs/api-references/docs.md
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
pkg/manager/member/pd_member_manager.go
pkg/manager/member/tikv_member_manager.go

Tests 
- Unit test
- E2E test
- Set `mountClusterClientSecret` for PD and TiKV and cluster client TLS secret can be mounted to the container
Code changes
```release-note
Add `mountClusterClientSecret` for PD and TiKV, if set it to `true`, TiDB Operator will mount the `${cluster_name}-cluster-client-secret` to the PD or TiKV containers
```

add switch for cluster client tls mounting

---

pkg/backup/backupschedule/backup_schedule_manager.go

close https://github.com/pingcap/tidb-operator/issues/3333
Update prefix with timestamp, like we did for s3 storage.
Tests 
- Unit test
- E2E test
Test create scheduled backup to GCS. bks can backup to GCS successfully.
Code changes
```release-note
Add timestamp to the prefix of scheduled backup on GCS
```

use timestamp to update gcs prefix for scheduled backup

---

pkg/apis/pingcap/v1alpha1/pd_config_wraper.go
pkg/apis/pingcap/v1alpha1/pd_config_wraper_test.go
pkg/apis/pingcap/v1alpha1/tidb_config_wraper.go
pkg/apis/pingcap/v1alpha1/tidb_config_wraper_test.go
pkg/apis/pingcap/v1alpha1/tikv_config_wraper.go
pkg/apis/pingcap/v1alpha1/tikv_config_wraper_test.go

https://github.com/pingcap/tidb-operator/pull/3342/commits/6a23edae1b6a901bda60bb7418cc51e4c9d3e97f in #3342 
introduce an issue.
we pass `&x` (type *interface{}) to `json.Unmarshal`
so type of x will be `map[string]interface{}` after it.
will fail the add test `TestUnmarshlJSON` in this pr.
pass origin `x` interface and improve test.
Tests 
- Unit test
```release-note
NONE
```

Fix pass *interface{} to json.Unmarshal

---

cmd/backup-manager/app/backup/backup.go
cmd/backup-manager/app/import/import.go
cmd/backup-manager/app/restore/restore.go
cmd/controller-manager/main.go
pkg/backup/backupschedule/backup_schedule_manager.go
pkg/controller/periodicity/periodicity_controller.go
pkg/manager/member/scaler.go
pkg/version/version.go
pkg/webhook/statefulset/statefulset.go
tests/failover.go
tests/fault.go
tests/slack/slack.go

Some BR logs are printed incorrectly. (For example, `%!](MISSING)`)
```log
I1012 09:45:55.314821       1 backup.go:91] [2020/10/12 09:45:55.314 +00:00] [INFO] [progress.go:114] [progress] [step="Full backup"] [progress=100.00%!](MISSING) [count="1 / 1"] [speed="? p/s"] [elapsed=1s] [remaining=1s]
```
replace `Errorf` with `Error` and `Infof` with `Info`.
Tests 
- Unit test
- E2E test
Test Backup with new operator:
```log
I1012 09:50:47.385423       1 backup.go:91] [2020/10/12 09:50:47.385 +00:00] [INFO] [progress.go:114] [progress] [step="Full backup"] [progress=100.00%] [count="1 / 1"] [speed="? p/s"] [elapsed=0s] [remaining=0s]
```
Code changes
- Need to cherry-pick to the release …

replace Errorf with Error and Infof with Info

---

cmd/backup-manager/app/backup/backup.go
cmd/backup-manager/app/backup/manager.go
cmd/backup-manager/app/util/util.go
go.mod
go.sum

close https://github.com/pingcap/tidb-operator/issues/3330 close https://github.com/pingcap/tidb-operator/issues/3259
Use br metadata to get total physical bytes
Tests 
- Unit test
- E2E test
```bash
NAME    BACKUPPATH             BACKUPSIZE   COMMITTS             AGE
basic   ***   5.4 kB       420129971367575553   9m15s
```
The result matches the actual size.
Code changes
```release-note
Use br metadata to get total backup size
```

backup: use br metadata to get total physical bytes

---

pkg/monitor/monitor/util.go
pkg/monitor/monitor/util_test.go

`prometheus.spec.config.commandOptions` has surprising behavior. Setting it overrides flags essential to correct operation, and other config options on the `spec`.
```
- --web.enable-admin-api	
- --web.enable-lifecycle	
- --config.file=/etc/prometheus/prometheus.yml	
- --storage.tsdb.path=/data/prometheus	
- --storage.tsdb.retention=12d
```
while merging with with `--log-level`.
Now, `commandOptions` will only append to the existing set of flags. Prometheus will error on startup if a flag is duplicated.
Note that this is a breaking change. I'm assuming that `commandOptions` is a rarely used advanced option and anyone who uses it will be able to apply a fix pretty easily.
A non-breaking alternative is to add an `extraCommandOptions` flag, but that seems a bit overboard.
Tests
- Unit test …

monitor: fix surprising prometheus commandOptions behavior

---

pkg/util/config/config_test.go
pkg/util/crypto/certs.go
pkg/util/crypto/certs_test.go
pkg/util/dmcluster/dmcluster_test.go
pkg/util/http/httputil.go
pkg/util/http/httputil_test.go
pkg/util/tidbcluster/tidbcluster_test.go
pkg/util/util.go
pkg/util/utils_test.go

fix #3396 
after this pr:
➜  util git:(util_test) ✗ go test ./... -cover
ok      github.com/pingcap/tidb-operator/pkg/util       0.041s  coverage: 73.1% of statements
ok      github.com/pingcap/tidb-operator/pkg/util/config        0.013s  coverage: 76.2% of statements
ok      github.com/pingcap/tidb-operator/pkg/util/crypto        0.394s  coverage: 78.6% of statements
ok      github.com/pingcap/tidb-operator/pkg/util/discovery     0.019s  coverage: 85.0% of statements
ok      github.com/pingcap/tidb-operator/pkg/util/dmcluster     0.031s  coverage: 90.0% of statements
ok      github.com/pingcap/tidb-operator/pkg/util/http  0.023s  coverage: 83.3% of statements
ok      github.com/pingcap/tidb-operator/pkg/util/tidbcluster   0.035s  coverage: 90.0% of statements
ok …

Improve unit test for pkg/util

---

docs/api-references/docs.md
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/backup.go
pkg/apis/pingcap/v1alpha1/restore.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/util/crdutil.go

Signed-off-by: gongmengnan <gong.mengnan@ninjavan.co>
Fix https://github.com/pingcap/tidb-operator/issues/1658.
`phase` is added in `BackupStatus` and `RestoreStatus`, it will be in sync with the latest condition type and shown when doing `kubectl get`.
Tests 
- Manual test
Code changes
Side effects
N/A
N/A
```release-note
NONE
```

add phase for backup and restore status

---

hack/split-crd.py

Add a script to split `manifests/crd.yaml` to seperate files, it is useful when submitting new releases to OperatorHub.
Added a script in `hack`.
Tests 
- No code
Code changes
- None
Side effects
- None
- None
```release-note
NONE
```

hack: add script to seperate CRD files

---

pkg/webhook/pod/pd_deleter.go
pkg/webhook/pod/pd_deleter_test.go
pkg/webhook/pod/pods.go
pkg/webhook/pod/tikv_creater.go
pkg/webhook/pod/tikv_creater_test.go
pkg/webhook/pod/tikv_deleter.go
pkg/webhook/pod/tikv_util.go
pkg/webhook/pod/util_test.go
pkg/webhook/util/util.go
pkg/webhook/util/util_test.go

after this pr:
github.com/pingcap/tidb-operator/pkg/webhook/pod        2.815s  coverage: 64.0% of statements
ok      github.com/pingcap/tidb-operator/pkg/webhook/statefulset        0.063s  coverage: 80.0% of statements
ok      github.com/pingcap/tidb-operator/pkg/webhook/strategy   0.053s  coverage: 81.7% of statements
ok      github.com/pingcap/tidb-operator/pkg/webhook/util       0.020s  coverage: 85.7% of statements
fix #2938 
```release-note
NONE
```

Improve pkg/webhook test

---

pkg/scheduler/predicates/ha.go
pkg/scheduler/predicates/ha_test.go

https://github.com/pingcap/tidb-operator/issues/3407
Tests 
- Unit test
- E2E test
- No code
Code changes
Side effects
```release-note
NONE
```

support HA scheduling when failover happen

---

pkg/controller/dependences.go
pkg/manager/member/config.go

1. The configmap in controller manger log is too long.
2. set `resyncDuration` back to 30s which is mistakenly changed in https://github.com/pingcap/tidb-operator/pull/3306/files
<details><summary>An example when debugging current operator.</summary>
```log
I1023 10:11:01.740253       1 config.go:42] compare demo/basic-pd-6130373 
--and-- 
true
I1023 10:11:01.740309       1 config.go:86] old: &ConfigMap{ObjectMeta:{basic-pd-6130373  demo /api/v1/namespaces/demo/configmaps/basic-pd-6130373 20c06010-3f35-459f-82d7-317322ef12a9 8864164 0 2020-10-23 09:13:47 +0000 UTC <nil> <nil> map[app.kubernetes.io/component:pd app.kubernetes.io/instance:basic app.kubernetes.io/managed-by:tidb-operator app.kubernetes.io/name:tidb-cluster] map[] [{pingcap.com/v1alpha1 TidbCluster basic …
```

delete log, set default resyncDuration to 30s

---

pkg/manager/member/dm_master_member_manager.go
pkg/manager/member/dm_master_member_manager_test.go
pkg/manager/member/pd_member_manager.go
pkg/manager/member/pd_member_manager_test.go

Currently, force upgrade won't take effect if we fail at scaling.
Let force upgrade happen before scaling.
Tests 
- Unit test
- E2E test
Code changes
```release-note
NONE
```

let force upgrade happen before scale

---

pkg/controller/pd_control.go
pkg/manager/member/pd_scaler.go

- Fix PD member name error when the multi-cluster feature is enabled and the cluster is scaling out.
- Provide the right PD client when the multi-cluster feature is enabled.
Add logic to ScaleOut and GetPDClient.
Tests 
The cluster goes normally when deploying new controller-manager. The cluster can scale out normally without admission webhook enabled.
Code changes
Side effects
```release-note
NONE
```

Fix PD member name error for multi cluster

---

pkg/manager/member/pd_scaler.go
pkg/manager/member/pd_scaler_test.go

fix #3452 
basically revert pr #2793 
Tests 
- Unit test
Code changes
- Manual test
1. deploy a `tidbCluster` named `tidb-old`, setup a `tidbMonitor` watching both `tidb-old` and `tidb-new`
2. start `sysbench` with `oltp_read_only` workload against `tidb-old`
3. deploy a `tidbCluster` named `tidb-new`, with `spec.pdAddresses` contains all pd peer urls from `tidb-old`
4. follow [migrate-tidb-to-kubernetes](https://docs.pingcap.com/zh/tidb-in-kubernetes/dev/migrate-tidb-to-kubernetes) to migrate `tidb-old` to `tidb-new`, while monitor grafana dashboard to make sure everything is fine.
5. PD/TiDB/TiKV pods in `tidb-old` are all scaled to 0
Side effects
None
```release-note
Fix the issue that PD cannot scale in …
```

Fix pd scale in to 0

---

docs/api-references/docs.md
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/backup/backup/backup_cleaner.go
pkg/backup/backup/backup_manager.go
pkg/backup/backup/backup_test.go
pkg/backup/backupschedule/backup_schedule_manager.go
pkg/backup/backupschedule/backup_schedule_manager_test.go
pkg/backup/restore/restore_manager.go
pkg/backup/restore/restore_manager_test.go
pkg/controller/dependences.go
pkg/controller/dependences_test.go

close #2920 
Imporve test of pkg/backup
Add test for all pkg under pkg/backup/
?       github.com/pingcap/tidb-operator/pkg/backup     [no test files]
ok      github.com/pingcap/tidb-operator/pkg/backup/backup      6.446s  coverage: 75.3% of statements
ok      github.com/pingcap/tidb-operator/pkg/backup/backupschedule      2.318s  coverage: 79.3% of statements
?       github.com/pingcap/tidb-operator/pkg/backup/constants   [no test files]
ok      github.com/pingcap/tidb-operator/pkg/backup/restore     6.462s  coverage: 75.0% of statements
ok      github.com/pingcap/tidb-operator/pkg/backup/util        0.044s  coverage: 94.7% of statements
Tests 
- Unit test
Code changes
Side effects
```release-note
NONE
```

Imporve test of pkg/backup

---

ci/release-nightly.groovy

Add a dedicated Jenkins pipeline for building nightly releases.
E2E test is not necessary for nightly builds as every commits should be tested before merge, and it's never gangrened for nightly builds to be stable.
Tests 
- No code
Code changes
```release-note
NONE
```

ci: add a dedicated pipeline for nightly build

---

cmd/backup-manager/app/backup/backup.go
cmd/backup-manager/app/restore/restore.go
docs/api-references/docs.md
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/backup/backup/backup_manager.go
pkg/backup/restore/restore_manager.go
pkg/util/util.go

Signed-off-by: gongmengnan <gong.mengnan@ninjavan.co>
Fix https://github.com/pingcap/tidb-operator/issues/3441. 
Added an `image` field in the `spec.br` of Backup and Restore CR as init container. The BR executable file will be provided by the specified image.
Tests 
Code changes
Side effects
N/A.
```release-note
NONE
```

add init container for BR backup/restore to supply the BR bin

---

cmd/backup-manager/app/backup/backup.go
cmd/backup-manager/app/restore/restore.go
docs/api-references/docs.md
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/backup/backup/backup_manager.go
pkg/backup/restore/restore_manager.go
pkg/util/util.go

Cherry pick of #3471 on release-1.1.
#3471: add init container for BR backup/restore to supply the BR

Automated cherry pick of #3471: add init container for BR backup/restore to supply the BR

---

pkg/monitor/monitor/util.go

fix #3460 
To avoid the situation that, in some Kubernetes platforms, the default user is not 0, setting `RunAsUsr: 0` may cause Grafana container to fail to start. More info see [issue](https://github.com/pingcap/tidb-operator/issues/3460). 
Remove `SecurityContext` for the initializer container of the monitor deployment.
When remove `SecurityContext`，the security policy is `runAsUser: rule: 'RunAsAny' `.
https://kubernetes.io/docs/concepts/policy/pod-security-policy/#example-policies
Tests 
- Unit test  
successed
- E2E test  
do not run
- Stability test 
do not run
initializer container start successfully, yaml config as below. We can see that `securityContext` is empty. 
```
image: pingcap/tidb-monitor-initializer:v4.0.7 …
```

remove RUNAsUser when init monitor pod

---

ci/pull_e2e_kind.groovy
ci/release-nightly.groovy

change UCLOUD_UFILE_PROXY_HOST=pingcap-dev.hk.ufileos.com
ucloud proxy url has changed
Tests 
- No code
Code changes
Side effects
None
```release-note
NONE
```

fix UCLOUD_UFILE_PROXY_HOST

---

ci/release-nightly.groovy

The pipeline for nightly build was not correct and was using cached pod for E2E tests.
Properly create and manage pod for nightly builds themselves.
This does not affect any real codes and testing CI jobs, should be safe to merge.
Tests 
- No code
Code changes
```release-note
NONE
```

ci: fix ngihtly build

---

pkg/controller/pod_control.go
pkg/controller/pod_control_test.go

Fix some codes related to PD,TiKV,TiFlash in UpdateMetainfo. When the multi-cluster feature enabled, it may select the wrong members and stores from PD when tidbcluster names conflicts.
Get info from tc.Status.
Tests 
- Unit test
Code changes
Side effects
```release-note
NONE
```

Fix logic in UpdateMetainfo for update info to pvc when multi-clustesr enabled

---

examples/basic-cn/tidb-cluster.yaml
examples/basic/tidb-cluster.yaml

run basic examples in some K8s cluster may got `the maximum number of open file descriptors is too small, got 1024, expect greater or equal to 82920` for TiKV.
add `max-open-files: 256` config item for `rocksdb` and `raftdb`.
Tests 
- No code
Code changes
- None
Side effects
- None
- None
```release-note
NONE
```

Refine basic examples about "max-open-files" for TiKV

---

pkg/manager/member/template.go

https://github.com/pingcap/tidb-operator/issues/3568 
The non-ASCII characters in the password will lead the init script broken down.
Add encoding params in tidbInitializer scripts.
Tests 
Create the root secret
```bash
kubectl create secret generic tidb-secret --from-literal=root=おはよう
```
Modify the examples/initialize/tidb-initializer.yaml and apply, the job is finished
```output
basic-tidb-initializer-gz7tw               0/1     Completed   0          68s
```
Check if the password works
```bash
[root@handlerww-multi-cluster init]# mysql -h 127.0.0.1 -u root -P 4000 
ERROR 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: NO)
[root@handlerww-multi-cluster init]# mysql -h 127.0.0.1 -u root -P 4000 -p
Enter …
```

Fix codecs error for non-ASCII char in tidbInitializer job passwordSecret

---

pkg/apis/pingcap/v1alpha1/validation/validation.go
pkg/manager/member/tidb_init_manager.go

Fix the bug that tikv storageVolumes validate bug.
Closes #3583 
```release-note
Fix the issue that TiDB cluster fails to deploy if `spec.tikv.storageVolumes` is configured
```

fix storageVolumes validate bug 

---

docs/api-references/docs.md
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
pkg/manager/member/tidb_member_manager.go

Closes #3596 
Add spec for additional ports
```yaml
metadata:
name: basic
spec:
version: v4.0.8
timezone: UTC
pvReclaimPolicy: Retain
enableDynamicConfiguration: true
configUpdateStrategy: RollingUpdate
discovery: {}
pd:
baseImage: registry.cn-beijing.aliyuncs.com/tidb/pd
replicas: 1
requests:
storage: "1Gi"
config: {}
tikv:
baseImage: registry.cn-beijing.aliyuncs.com/tidb/tikv
replicas: 1
requests:
storage: "1Gi"
config: {}
tidb:
baseImage: registry.cn-beijing.aliyuncs.com/tidb/tidb
replicas: 1
service:
type: NodePort
externalTrafficPolicy: Local
additionalPorts: 
- name: "health-checker"
nodePort: 32402
port: 8080
protocol: "TCP"
targetPort: 8080
config: {}
```
The new TiDB service shows as the feature request:
```yaml
spec:
clusterIP: …
```

Add additional port support to extend TiDB service

---

manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/backup/util/util.go
pkg/backup/util/utils_test.go

#3557. 
Allow empty secret when backup/restore to/from gcs in BR.
Change `GcsStorageProvider.SecretName` to`omitempty`, add UT.
- Backup to gcs with BR configuring SecretName
1. Create a kind cluster and deployment tidb cluster
```shell
kind create cluster
./hack/local-up-operator.sh
kubectl apply -f example/basic/tidb-cluster.yaml
```
2. [Backup to gcs with BR](https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/backup-to-gcs-using-br)
```yaml
curl https://raw.githubusercontent.com/pingcap/tidb-operator/master/manifests/backup/backup-rbac.yaml
kubectl apply -f backup-rbac.yaml -n test1
kubectl create secret generic gcs-secret --from-file=credentials=gcs-credentials.json
kubectl create secret generic backup-demo1-tidb-secret --from-literal=password=${password}
```
backup-gcs.yaml …

allow empty secret in gcs BR

---

cmd/backup-manager/app/clean/clean.go
cmd/backup-manager/app/export/export.go
cmd/backup-manager/app/import/import.go
cmd/backup-manager/app/util/util.go
cmd/backup-manager/app/util/util_test.go

Fix #3561 , user can configure logging options for rclone  in yaml file, example as below.
- Code chages
Add options in LocalStorageProvider and GcsStorageProvider
- How does it work
User can configure rclone options in yaml file when starting backup/restore jobs like below. We set `-v` flag as default for rclone command to output [logging info](https://rclone.org/docs/#logging). If user set logging flags such as `-q` , `-v=4` , user defined flags will take precedence.
Tests 
- Unit test
- E2E test
- Backup&Restore using aws s3 AWS-KMS enabled
1. Create a kind cluster and generate test data with go-tpc
```shell
kind create cluster
./hack/local-up-operator.sh
kubectl apply -f example/basic/tidb-cluster.yaml
go-tpc -H …
```

add options for local and gcs provider in backup

---

pkg/monitor/monitor/monitor_manager.go
pkg/monitor/monitor/template.go
pkg/monitor/monitor/template_test.go

Fix multiple cluster monitor.
Closes #xxx (issue number)
```release-note
ACTION REQUIRED:
If TidbMonitor CRs are deployed, after upgrading TiDB Operator to this version, please update the `spec.initializer.version` to `v4.0.9`, otherwise, some metrics will not be shown correctly in the Grafana dashboards.
Scrape job names are changed from `${component}` to `${namespace}-${TidbCluster Name}-${component}`
```

support multiple cluster

---

cmd/backup-manager/app/export/export.go
cmd/backup-manager/app/import/import.go
cmd/backup-manager/app/import/manager.go
docs/api-references/docs.md
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/backup/backup/backup_manager.go
pkg/backup/restore/restore_manager.go
pkg/util/util.go

Support setting `spec.toolImage` for backup with dumpling and restore with lightning.
Close #3619
If `spec.toolImage` is configured when using dumpling/lightning, add initContainers to copy binary file `dumpling`/`tidb-lightning` from toolImage and run this binary file to backup/restore.
1. Backup using dumpling when configuring `spec.toolImage`
Prepare tidb cluster. 
```shell
kind create cluster
./hack/local-up-operator.sh
kubectl apply -f example/basic/tidb-cluster
```
Backup to gcs suing dumpling according to [docs](https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/backup-to-gcs), configuration is as follows.
```yaml
---
kind: Backup
metadata:
name: demo1-backup-gcs
namespace: default
spec:
toolImage: pingcap/dumpling:v4.0.8
from:
host: …
```

support toolimage when backup/restore using dumpling/lightning

---

cmd/backup-manager/app/util/remote.go
cmd/backup-manager/app/util/util.go
cmd/backup-manager/app/util/util_test.go

in release v1.1.8, after #3517, the gcs path for BR backup&restore is not backward-compatible with tidb 4.0.8
add trailing slash `/` back for gcs paths.
ref https://docs.google.com/document/d/1kqw4moTM7HRnXhncdcWOrr23v7MBQNENm8pA_PsQOWE/edit
- incompatible with 1.1.8
- should mention that operator v1.1.8 has this issue, so that users should skip this version
```release-note
Fix compatibility issue for using BR to backup/restore from/to gcs
```

fix gcs br backup&restore path

---

charts/tidb-cluster/values.yaml
charts/tidb-operator/values.yaml
deploy/aliyun/variables.tf
deploy/aws/variables.tf
deploy/gcp/variables.tf
examples/advanced/tidb-cluster.yaml
examples/dm/dm-monitor.yaml
hack/bump-version.sh

Bump operator to v1.1.9 and tidb components to v4.0.9
ref #3613
run script `hack/bump-version.sh`, and correct some comments by hand.
```release-note
NONE
```

Bump operator to v1.1.9 and tidb components to v4.0.9

---

cmd/backup-manager/app/backup/manager.go
cmd/backup-manager/app/clean/manager.go
cmd/backup-manager/app/export/manager.go
cmd/backup-manager/app/import/manager.go
cmd/backup-manager/app/restore/manager.go
pkg/backup/backup/backup_cleaner.go
pkg/backup/backup/backup_manager.go
pkg/backup/restore/restore_manager.go
pkg/controller/backup_status_updater.go
pkg/controller/backup_status_updater_test.go
pkg/controller/restore_status_updater.go
pkg/controller/restore_status_updater_test.go

Fix the issue that in some cases some fields, e.g. BACKUPPATH, BACKUPSIZE, COMMITTS, etc. in the status of Backup CR or Restore CR are missed even if the backup or restore job succeed.
Fix #3635
Root cause:
Take the Backup CR for example, and the Restore CR has a similar logic.
Currently, two controllers will update the status of Backup CR, one is the backup controller in the tidb-controller-manager Pod, which only updates the conditions slice in the status. The other is the controller in the backup-manager Pod which is the real backup job and will update all the fields in the status.
With the current status update logic, if something wrong with the update API call, the status updater will retrieve the latest Backup resource from the lister and replace the `status` field totally with the …

status missed even if backup job succeeds

---

examples/advanced/tidb-cluster.yaml

Fix tidb config level values needs to be enclosed by quotes, or tidb-controller-manager will report following error and won't create k8s work load stuff ( such as statefulset, pod, svc ):
```log
E1229 11:40:12.437553       1 reflector.go:123] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: Failed to list *v1alpha1.TidbCluster: v1alpha1.TidbClusterList.Items: []v1alpha1.TidbCluster: v1alpha1.TidbCluster.Spec: v1alpha1.TidbClusterSpec.TiDB: v1alpha1.TiDBSpec.ComponentSpec: NodeSelector: Config: unmarshalerDecoder: Near line 1 (last key parsed 'level'): expected value but found "info" instead, error found in #10 byte of ...| = true\n","nodeSele|..., bigger context ...|"config":"level = info\nenable-timestamp = true\n","nodeSelector":{"app.kubernetes.io/component":"ti|...
```
Just …

Fix tidb config level value enclose

---

examples/advanced/tidb-cluster.yaml

fix #3677
add `requests.storage` for PD and TiKV
- apply the changed yaml, and the desired TidbCluster show up
```release-note
NONE
```

fix advanced TidbCluster example

---

ci/pull_e2e_kind.groovy

preserve long logs in test output
add `keepLongStdio: true` params to junit plugin
- jenkins job https://internal.pingcap.net/idc-jenkins/job/tidb-operator-pull-e2e-kind/3703/
```release-note
NONE
```

add keepLongStdio: true in ci junit params

---

ci/pull_e2e_kind.groovy

adjust e2e pod resources to avoid eviction during job run.
adjust ephemeral-storage/cpu/memory of e2e pods
```release-note
NONE
```

adjust e2e pod resources

---

go.mod
pkg/controller/autoscaler/tidbcluster_autoscaler_controller.go
pkg/controller/backup/backup_controller.go
pkg/controller/backupschedule/backup_schedule_controller.go
pkg/controller/dmcluster/dm_cluster_controller.go
pkg/controller/rate_limiter.go
pkg/controller/restore/restore_controller.go
pkg/controller/tidbcluster/tidb_cluster_controller.go
pkg/controller/tidbinitializer/tidb_initializer_controller.go
pkg/controller/tidbmonitor/tidb_monitor_controller.go

The current workqueue ratelimiter for controllers are using the default combination of `ItemExponentialFailureRateLimiter` and `BucketRateLimiter`. However the `ItemExponentialFailureRateLimiter` has a `baseDelay` of 5ms and `maxDelay` of 1000s, which is unrealistic.
add a new controller rate limiter function, and default to `baseDelay=1s` and `maxDelay=100s`
```release-note
Optimize CR syncing intervals
```

add customizable controller rate limiter

---

charts/tidb-cluster/values.yaml
charts/tidb-operator/values.yaml
deploy/aliyun/variables.tf
deploy/aws/variables.tf
deploy/gcp/variables.tf
hack/bump-version.sh

bump chart version to v1.2.0-alpha.1
write and run this script
```shell
OPERATOR_OLD="v1\.1\.9"
OPERATOR_NEW="v1\.2\.0-alpha\.1"
TIDB_OLD="v4\.0\.9"
TIDB_NEW="v4\.0\.9"
find ./deploy -name "*\.tf"| xargs $SED_BIN -i "s/$OPERATOR_OLD/$OPERATOR_NEW/g"
find ./charts -name "*\.yaml"| xargs $SED_BIN -i "s/$OPERATOR_OLD/$OPERATOR_NEW/g"
find ./deploy -name "*\.yaml.example"| xargs $SED_BIN -i "s/$TIDB_OLD/$TIDB_NEW/g"
find ./examples -name "*\.yaml"| xargs $SED_BIN -i "s/$TIDB_OLD/$TIDB_NEW/g"
find ./deploy -name "*\.tf"| xargs $SED_BIN -i "s/$TIDB_OLD/$TIDB_NEW/g"
find ./charts -name "*\.yaml"| xargs $SED_BIN -i "s/$TIDB_OLD/$TIDB_NEW/g"
$SED_BIN -i "s/$TIDB_OLD/$TIDB_NEW/g" images/tidb-backup-manager/Dockerfile
```
```release-note
NONE
```

bump chart version to v1.2.0-alpha.1

---

pkg/backup/backup/backup_manager.go
pkg/backup/restore/restore_manager.go

Fix #3681 
- Fix `secret "${cluster_name}-tidb-client-secret" not found` when Backup with BR with TiDB v4.0.9 without configuring `spec.from`, and TLS is enabled. 
- Fix nilptr panic when Restore with BR with TiDB v4.0.9 without configuring `spec.to`, and TLS is enabled.
Change the condition to mount tidb client secret when Backup/Restore with BR with TiDB v4.0.9 without configuring  `spec.from` or`spec.to` . Actually, when BR set gc life time itself (without configuring  `spec.from` or`spec.to`), operator do not need "${cluster_name}-tidb-client-secret".
1. Backup&Restore when tls disabled.
Backup and restore successfully.
2. Backup&Restore when tls enabled.
Generate certs.
```
./hack/gen-tls-certs.sh
```
tidb-cluster.yaml
```yaml …
```

Fix backup & restore panic when tls enabled

---

ci/pull_e2e_kind.groovy
docs/api-references/docs.md
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/tidbcluster_component.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
pkg/manager/member/pd_member_manager.go
pkg/manager/member/pump_member_manager.go
pkg/manager/member/ticdc_member_manager.go
pkg/manager/member/tidb_member_manager.go
pkg/manager/member/tiflash_member_manager.go
pkg/manager/member/tikv_member_manager.go

Closes #3695 
Add the spec below to TiDB/TiKV/TiFlash/PD spec:
```yaml
annotations:
tidb.pingcap.com/sysctl-init: "true"
podSecurityContext:
sysctls:
- name: net.ipv4.tcp_keepalive_time
value: "300"
- name: net.ipv4.tcp_keepalive_intvl
value: "75"
- name: net.core.somaxconn
value: "32768"
initContainers:
- command:
- /bin/sh
image: busybox
imagePullPolicy: IfNotPresent
name: inittest
```
We can see TiKV init with 2 pods, shows the inject of init containers succeed.
```output
cluster1-discovery-7d8dc88cbb-mdc6l        1/1     Running    0          19s
cluster1-pd-0                              1/1     Running    0          19s
cluster1-pump-0                            1/1     Running    0          8s
cluster1-tikv-0                            0/1     Init:0/2   0          8s …
```

Support configuring init containers for components in TiDB cluster

---

ci/pull_e2e_kind.groovy

e2e pods are evicted due to storage exceeded.
change ephemeral-storage to 150Gi
```release-note
NONE
```

change ephemeral-storage to 150Gi

---

ci/pull_e2e_kind.groovy
cmd/backup-manager/app/backup/backup.go
cmd/backup-manager/app/backup/manager.go
cmd/backup-manager/app/clean/clean.go
cmd/backup-manager/app/clean/manager.go
cmd/backup-manager/app/export/export.go
cmd/backup-manager/app/export/manager.go
cmd/backup-manager/app/import/import.go
cmd/backup-manager/app/import/manager.go
cmd/backup-manager/app/restore/manager.go
cmd/backup-manager/app/restore/restore.go
cmd/backup-manager/app/util/generic.go
cmd/backup-manager/app/util/util.go
pkg/apis/pingcap/v1alpha1/backup.go
pkg/apis/pingcap/v1alpha1/restore.go
pkg/backup/backup.go
pkg/backup/backup/backup_manager.go
pkg/backup/restore/restore_manager.go
pkg/controller/backup/backup_control.go
pkg/controller/backup/backup_controller.go
pkg/controller/backup/backup_controller_test.go
pkg/controller/restore/restore_control.go
pkg/controller/restore/restore_controller.go
pkg/controller/restore/restore_controller_test.go

support cancel backup and restore jobs via signal.
fix #3675 
receive signal via `signal.Notify` and then cancel context for backup/restore processing.
**NOTE**: 
- Archive/Unarchive backuped data can still be blocked and killed, because no context supported yet.
- It seems that the job controller will re-create a new pod when the old one is evicted, ref https://github.com/kubernetes/kubernetes/issues/96363#issuecomment-745433925
- test for cancel signal
1. modify the code to inject waiting operations via `time.Sleep` or `<-ctx.Done()`
2. `exec` into the backup/restore pod and send a signal via `kill -15 1`
3. observe the status of the backup/restore job, somethings like bellow should be found.
```
NAME           STATUS   BACKUPPATH   BACKUPSIZE   COMMITTS   AGE
basic-backup   Failed …
```

Support cancel backup and restore jobs via signal and update status with failed pod

---

tests/e2e/tidbcluster/tidbcluster.go
tests/pkg/fixture/fixture.go

Set E2E default pvReclaimPolicy set to Delete

---

pkg/monitor/monitor/template.go
pkg/monitor/monitor/template_test.go

Tidbmonitor add `tidb_cluster `target label to support multiple cluster monitor.
```release-note
Add `tidb_cluster` label for the scrape jobs in TidbMonitor to support multiple clusters monitoring
```

Tidbmonitor add `tidb_cluster `target label .

---

charts/tidb-cluster/values.yaml
charts/tidb-operator/values.yaml
deploy/aliyun/variables.tf
deploy/aws/variables.tf
deploy/gcp/variables.tf
hack/bump-version.sh

Bump operator to v1.1.10 and tidb components to v4.0.10.
This PR dump operator, tidb components are dumped in PR #3757
ref #3657
run script `hack/bump-version.sh`  bump TiDB Operator from v1.1.9 to v1.1.10.
```release-note
NONE
```

Bump operator to v1.1.10

---

tests/e2e/tidbcluster/serial.go
tests/e2e/tidbcluster/stability-asts.go
tests/e2e/tidbcluster/stability-br.go
tests/e2e/tidbcluster/stability.go
tests/e2e/tidbcluster/tidbcluster.go
tests/e2e/util/image/image.go
tests/pkg/fixture/fixture.go

deployed tidb versions in e2e test cases are outdated
update tidb versions to the latest v4.
simplify version const variable names.
```release-note
None
```

e2e: refactor tidb version

---

pkg/manager/member/tikv_upgrader.go
pkg/manager/member/tikv_upgrader_test.go

During TiKV upgrade, when we determine if one Pod has been upgraded, we check if the Pod phase is `Running` or not, however, it's better to check if the Pod is `Ready` or not.
Check whether the Pod is `Ready` during the TiKV upgrade.
```release-note
NONE
```

check pod ready during tikv upgrade

---

Makefile
docs/api-references/docs.md
examples/advanced/tidb-cluster.yaml
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/tidbcluster.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
pkg/manager/member/tikv_member_manager.go
pkg/manager/member/tikv_member_manager_test.go
tests/e2e/tidbcluster/tidbcluster.go

Currently, we can't query RocksDB log and Raft log in the grafana, because they are not collected by loki.
This PR is designed to support collect them by loki and can be queried in the grafana.
Similar to how we collect TiDB slow log, we use sidecar containers to mount RocksDB and Raft log files and print them in the stdout of the individual container.
Related doc which added in this PR: https://github.com/tidbcloud/infra/pull/621
```release-note
- Print RocksDB and Raft log to stdout to support them be collected and queried in the grafana
```
---
Manual Test Steps:
1. Deploy a default basic cluster
```
> kubectl apply -f …
```

support print rocksdb log and raft log to stdout

---

charts/tidb-operator/templates/controller-manager-deployment.yaml
charts/tidb-operator/values.yaml
cmd/controller-manager/main.go
pkg/controller/dependences.go

For some maybe performance issues due to the cluster, it may be slow to respond for acquiring or renew the lease.
like this, it takes roughly 4s to acquire the lock
```
30 I0218 10:45:15.603307       1 leaderelection.go:241] attempting to acquire leader lease  tidb-operator/tidb-controller-manager...
31 I0218 10:45:19.553068       1 leaderelection.go:251] successfully acquired lease tidb-operator/tidb-controller-manager
```
And we are setting `RenewDeadline` as the only 5s, so it will easy fail to acquire or renew the lock.
change the values to  defaults as the core client(enlarge `RenewDeadline` from 5s to 10s)
also support user configuration
build a image to use myself
change the added items as some value and use the custom image
run `helm install tidb-operator charts/tidb-operator …

tune and suppport configuration about LeaderElection

---

docs/api-references/docs.md
go.mod
go.sum
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/tidbcluster.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/controller/dependences.go
pkg/controller/tikv_control.go
pkg/manager/member/tikv_upgrader.go
pkg/manager/member/tikv_upgrader_test.go
pkg/tikvapi/fake_tikvapi.go
pkg/tikvapi/tikv_control.go
pkg/tikvapi/tikvapi.go
tests/actions.go
tests/pkg/fixture/fixture.go

Fix #3781
Root cause:
Currently, we retrieve the region count leader from PD to determine whether the leaders of one TiKV have been transferred to the other ones, however, if one PD is restarted and then becomes the leader in 1 minute, it may not have all the region leader info for each TiKV, so we have to change the logic to retrieve the region leader from each TiKV directly.
- Deploy a TidbCluster with 3 PDs and 3 TiKVs, do not enable TLS, run sysbench to the cluster, upgrade PD and TiKV, check that the QPS does not drop obviously during the TiKV upgrade.
```
[ 140s ] thds: 16 tps: 179.20 qps: 3574.92 (r/w/o: 2500.91/715.60/358.40) lat (ms,95%): 125.52 err/s: 0.00 reconn/s: 0.00
[ 150s ] thds: 16 tps: 174.70 qps: 3503.41 (r/w/o: 2453.31/700.60/349.50) lat (ms,95%): 130.13 err/s: 0.10 …
```

retrieve region leader from tikv

---

pkg/manager/member/tiflash_member_manager.go
pkg/manager/member/tiflash_upgrader.go
pkg/manager/member/tiflash_upgrader_test.go
pkg/manager/member/utils.go

Fixes #3786
Add rolling upgrade logic for TiFlash component.
1. Create a cluster with TiFlash
> Note: The replicas of TiKV should be more than TiFlash.
```yaml
tikv:
baseImage: registry.cn-beijing.aliyuncs.com/tidb/tikv
version: v4.0.8
replicas: 3
requests:
storage: "5Gi"
config: {}
tiflash:
baseImage: registry.cn-beijing.aliyuncs.com/tidb/tiflash
version: v4.0.8
maxFailoverCount: 3
annotations:
tidb.pingcap.com/sysctl-init: "true"
replicas: 2
storageClaims:
- resources:
requests:
storage: 1Gi
```
3. Use go-tpc tpch to generate data into the TiFlash
```bash
go-tpc tpch -H 10.96.138.6 --tiflash --sf=50 prepare 
```
Modify the TiFlash replicas of the tables in SQL.
```sql
ALTER TABLE `test`.`nation` SET TIFLASH REPLICA 2;
ALTER TABLE `test`.`region` SET TIFLASH REPLICA 2;
ALTER TABLE …
```

Add TiFlash rolling upgrade logic

---

images/tidb-backup-manager/entrypoint.sh

Fixes #3807
Create a backup CR to backup data from TiDB to minio. The job output shows:
```log
Create rclone.conf file.
/tidb-backup-manager backup --namespace=pingcap --backupName=demo1-backup-s3 --tikvVersion=v4.0.8
I0225 04:12:56.658268      11 backup.go:71] start to process backup pingcap/demo1-backup-s3
I0225 04:12:56.677715      11 backup_status_updater.go:84] Backup: [pingcap/demo1-backup-s3] updated successfully
...
I0225 04:12:56.834287      11 backup.go:93] [2021/02/25 04:12:56.834 +00:00] [INFO] [client.go:205] ["save backup meta"] [path=s3://my-bucket/my-folder] [size=16]
I0225 04:12:56.846596      11 backup.go:93] [2021/02/25 04:12:56.846 +00:00] [INFO] [ddl.go:391] ["[ddl] DDL closed"] [ID=8646920c-ccaa-42fa-9050-2f9a3ad90e82] ["take time"=514.268µs]
I0225 04:12:56.846608 …
```

Fix backup manager scripts to competite with some shell 

---

charts/tidb-cluster/values.yaml
charts/tidb-operator/values.yaml
deploy/aliyun/variables.tf
deploy/aws/variables.tf
deploy/gcp/variables.tf
hack/bump-version.sh

Bump operator to v1.1.11
ref #3756
run script `hack/bump-version.sh` to bump TiDB Operator from v1.1.10 to v1.1.11.
```release-note
NONE
```

Bump operator version to v1.1.11

---

docs/api-references/docs.md
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
pkg/manager/member/tikv_member_manager.go

Fix https://github.com/pingcap/tidb-operator/issues/3783
```release-note
Support setting customized store labels according to the node labels
```

add store labels

---

misc/images/tidb-debug/Dockerfile

Currently tidb-debug image only  includes `gdb` for debugging. It's not convenient as `delve`. This PR burns `delve` into the image so that developer also can debug tidb through delve.
This PR just add a single line to build delve into the image.

Add delve into tidb-debug

---

pkg/tkctl/debug/launcher.go

Many kernel debugging tools are based on debugfs.  Those tools, specifically the [linux tracing system](https://jvns.ca/blog/2017/07/05/linux-tracing-systems),  are quite useful to understand the system behavior as well as user-level behavior of tidb processes.  This PR shares host debugfs, kernel modules and kernel sources path to containers for kernel/user-space debugging.
Below example shows how to trace the latency distribution on tikv's `crocksdb_write_multi_batch` function.
```
$ tkctl debug tidb-cluster-tikv-0 --launcher-image 'mzhou/debug-launcher:latest' --image 'quay.io/iovisor/bpftrace:latest' --privileged
@ns[apply-0]:
[64K, 128K)           33 |@@@                                                 |
[128K, 256K)         425 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@        | …
```

Share host debugfs, kernel modules and kernel sources path to container

---

tests/e2e/tidbcluster/tidbcluster.go
tests/e2e/util/tidbcluster/tidbcluster.go

Signed-off-by: Li Yilong <liyilongko@gmail.com>
Add e2e case: delete resources controlled by tc.
```release-note
None
```

add test case: delete resources controlled by tc

---

charts/tidb-operator/templates/controller-manager-deployment.yaml
charts/tidb-operator/templates/controller-manager-rbac.yaml
charts/tidb-operator/templates/scheduler-deployment.yaml
charts/tidb-operator/templates/scheduler-rbac.yaml

Fix the following issue:
1. Deploy TiDB Operator
2. Deploy another TiDB Operator in the same namespace with `appendReleaseSuffix: true`
3. Delete the TiDB Operator deployed in step 1
Then the TiDB Operator deployed in step 2 cannot work because the service accounts it uses have been deleted in step 3.
Use new service account when release suffix is appended.
1. Deploy TiDB Operator
2. Deploy another TiDB Operator in the same namespace with `appendReleaseSuffix: true`
3. Delete the TiDB Operator deployed in step 1 and check that the TiDB Operator deployed in step 2 still work normally
4. Deploy TiDB Operator as in step 1
5. Delete the TiDB Operator deployed in step 2 and check that the TiDB Operator deployed in step 4 still work normally
Please refer to [Release Notes Language Style …

use new serviceaccount when release suffix is appended

---

pkg/manager/member/pd_failover_test.go
pkg/manager/member/pd_scaler_test.go
pkg/manager/member/scaler.go
pkg/manager/member/tikv_scaler.go
pkg/manager/member/tikv_scaler_test.go
pkg/manager/member/utils.go
pkg/util/util.go
tests/e2e/tidbcluster/tidbcluster.go

ref: #3802
Change tikv related code to support multiple pvc from pod spec, instead of constructing a single pvc name from tc name and ordinal.
Also refactored related util functions for brevity.
1. deploy a tc
```yaml
metadata:
name: basic
spec:
version: v4.0.10
timezone: UTC
pvReclaimPolicy: Delete
configUpdateStrategy: RollingUpdate
discovery: {}
pd:
replicas: 3
requests:
storage: "1Gi"
config: {}
tikv:
baseImage: pingcap/tikv
replicas: 4
requests:
storage: "1Gi"
storageVolumes:
- name: additional
storageSize: "1Gi"
mountPath: /mnt
config: {}
tidb:
baseImage: pingcap/tidb
replicas: 1
config: {}
```
2. check pvc with `kubectl get pvc`
```
NAME                           STATUS   VOLUME …
```

Fix support for multiple pvc for tikv

---

ci/pull_e2e_kind.groovy

revert docker hub to `hub.pingcap.net`.
revert from `hub-dev.pingcap.net` to `hub.pingcap.net` (ref #3732)
```release-note
None
```

revert to hub.pingcap.net

---

pkg/manager/member/pd_member_manager.go

Fixes #3846
check before dereference `tc.Spec.TiDB`.
1. deploy a tc without `tidb` field, and find out that the tc is deployed successfully. Before the fix, if there's no tc.Spec.TiDB, tidb-controller-manager will go panic.
```yaml
metadata:
name: basic
spec:
version: v4.0.10
timezone: UTC
pvReclaimPolicy: Delete
configUpdateStrategy: RollingUpdate
discovery: {}
pd:
replicas: 3
requests:
storage: "1Gi"
config: {}
tikv:
baseImage: pingcap/tikv
replicas: 1
requests:
storage: "1Gi"
config: {}
```
```release-note
Fix the issue that when TidbCluster's …
```

fix tc.spec.tidb nil pointer dereference

---

ci/pull_e2e_kind.groovy

when the CI triggered after a PR merged, the `GIT_COMMIT` is not valid, then the E2E coverage report can't be uploaded.
always set `GIT_COMMIT` as the head SHA.
```release-note
None
```

try to fix GIT_COMMIT env after PR merged in CI

---

docs/api-references/docs.md
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
pkg/monitor/monitor/util.go

Add additional volume and volumeMount configuration.
```release-note
TidbMonitor add additional volume and volumeMount configurations.
```

tidbmonitor add additional volume configuration

---

examples/monitor-with-thanos/tidb-monitor-with-additional-volumes.yaml
pkg/manager/member/template.go

Sometimes when DNS service is not stable, in-pod DNS lookup requests will fail. We need to add the retry logic for the related exception.
Manual test:
1. Deploy a basic TiDB cluster
2. Create TidbInitializer.
```yaml 
kind: TidbInitializer
metadata:
name: initialize-demo
spec:
image: tnir/mysqlclient
imagePullPolicy: IfNotPresent
cluster:
name: initialize-demo
initSql: "create database hello;"
```
3. The initialization succeeded.
```output
cluster1-tidb-initializer-tpq5h            0/1     Completed   0          13mcluster1-tidb-initializer-tpq5h            0/1     Completed   0          13m
```
4. The startup script in configMap shows as below:
```python
import os, sys, time, MySQLdb
host = 'cluster1-tidb'
permit_host = '%'
port = 4000
retry_count = 0
for …
```

Add retry for DNS lookup failure exception in TiDBInitializer

---

cmd/controller-manager/main.go
cmd/discovery/main.go
cmd/scheduler/main.go

fix #3850 
- do not retry after leader election lost (remove `wait.Forever`)
- shutdown the HTTP server after leader election lost
```release-note
```

shutdown controll-manager if leader election lost

---

pkg/manager/member/pvc_resizer.go
pkg/manager/member/pvc_resizer_test.go

Closes #3851
Fix unresolved issues in #3858
1. deploy tc and dm-cluster
```yaml
metadata:
name: basic
spec:
configUpdateStrategy: RollingUpdate
discovery: {}
enablePVReclaim: false
imagePullPolicy: IfNotPresent
pd:
affinity: {}
config:
dashboard:
internal-proxy: true
replication:
location-labels:
- region
- zone
- rack
- host
log:
file:
filename: /var/log/pdlog/pd.log
level: "warn"
schedule:
enable-cross-table-merge: true
storageVolumes:
- name: log
storageSize: "2Gi"
mountPath: "/var/log/pdlog"
imagePullPolicy: IfNotPresent
maxFailoverCount: 3
replicas: 1
requests:
storage: 1Gi
pvReclaimPolicy: Delete
schedulerName: default-scheduler
services:
- name: pd
type: ClusterIP
ticdc:
baseImage: pingcap/ticdc
replicas: 1 …
```

Fix pvc resize support for tidb

---

charts/tidb-cluster/values.yaml
charts/tidb-operator/values.yaml
deploy/aliyun/variables.tf
deploy/aws/variables.tf
deploy/gcp/variables.tf
hack/bump-version.sh

Bump operator to v1.2.0-beta.1
ref #3897
run script `hack/bump-version.sh` to bump TiDB Operator from v1.2.0-alpha.1 to v1.2.0-beta.1
```release-note
NONE
```

Bump operator version to v1.2.0-beta.1

---

cmd/backup-manager/app/backup/manager.go
cmd/backup-manager/app/export/export.go
cmd/backup-manager/app/export/manager.go

Closes #3904
```release-note
```

fix backup stage order

---

charts/tidb-operator/templates/admission/admission-webhook-deployment.yaml
charts/tidb-operator/templates/advanced-statefulset-deployment.yaml
charts/tidb-operator/templates/controller-manager-deployment.yaml
charts/tidb-operator/templates/scheduler-deployment.yaml
charts/tidb-operator/values.yaml
docs/api-references/docs.md
manifests/crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/tidbcluster_component.go
pkg/apis/pingcap/v1alpha1/tidbinitializer_types.go
pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
pkg/backup/backup/backup_cleaner.go
pkg/backup/backup/backup_manager.go
pkg/backup/restore/restore_manager.go
pkg/manager/member/pump_member_manager.go
pkg/manager/member/tidb_discovery_manager.go
pkg/manager/member/tidb_init_manager.go
pkg/monitor/monitor/util.go
tests/e2e/tidbcluster/stability-asts.go
tests/e2e/tidbcluster/tidbcluster.go
tests/pkg/fixture/fixture.go

Add support of PodSecurityContext for all ti-components.
Closes #3874 
```release-note
Support pod security context for all components
```
```yaml
kind: DMCluster
metadata:
name: basic
spec:
podSecurityContext:
runAsUser: 1000
runAsGroup: 2000
fsGroup: 2000
version: v2.0.0
pvReclaimPolicy: Retain
discovery:
address: "http://basic-discovery.default:10261"
master:
baseImage: pingcap/dm
replicas: 1
storageSize: "1Gi"
requests: {}
config: {}
worker:
baseImage: pingcap/dm
replicas: 1
storageSize: "1Gi"
requests: {}
config: {}
```
Both master and worker are set `securityContext`
```yaml
apiVersion: …
```

add support of pod security context for all ti-components

---

tests/e2e/e2e.go
tests/e2e/tidbcluster/tidbcluster.go
tests/log_dump.go

kubetest2 can only dump logs for living pods, but in order to get test coverage for tidb-operator, we need to uninstall them (to trigger the process exit)
dump tidb-operator's log before uninstall tidb-operator
```release-note
None
```

e2e: dump tidb-operator's log before uninstall tidb-operator

---

pkg/manager/member/pd_member_manager.go

fix #3952
update unjoined pd base on the current pods
see #3952 but make sure the unjoined pd disappear
```release-note
```

update unjoined pd base on the current pods

---

pkg/manager/member/template.go
tests/dm.go
tests/e2e/dmcluster/dmcluster.go

- fix #3971
- add scale out/in E2E tests cases, part of #2868
fix `--join` arg for DM-master
```release-note
Fix the issue that DM-master may restart failed
```

Fix dm-master restarted failed; add scale E2E cases

---

cmd/backup-manager/app/export/export.go

This masks the password in the logging of a backup.
example from a dumpling backup:
```
I0518 12:12:42.930173       1 export.go:87] The dump process is ready, command "/dumpling --output=/backup/dvaneeden-test-s3/backup-2021-05-18T12:12:42Z --host=10.100.144.207 --port=4000 --user=tidb-backup --password=af73fa3sFud0 --filter *.* --filter !/^(mysql|test|INFORMATION_SCHEMA|PERFORMANCE_SCHEMA|METRICS_SCHEMA|INSPECTION_SCHEMA)$/.* --threads=16 --rows=10000"
```
It iterates over `args` and creates `args_redacted` where it replaced the arg with `--password=******` if it starts with `--password=` and uses this for log message.
Create a dumpling backup and inspect the logging of the pod.
Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/ …

backup-manager: avoid logging the database password

---

tests/e2e/tidbcluster/stability.go
tests/e2e/tidbcluster/tidbcluster.go

- fix some It args in `for` loop
- replace `local-storage` sc with default sc for PD/TiKV scale cases
```release-note
None
```

e2e: fix some It args; replace local-storage sc for PD scale case

---

charts/tidb-operator/templates/controller-manager-deployment.yaml

Fix #3799 
```release-note
TiDB Operator add liveness readiness probe.
```

Operator add liveness readiness probe

---

hack/e2e.sh

add mirror for `k8s.gcr.io`
```
containerdConfigPatches:
- |-
[plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
endpoint = ["http://registry-mirror.pingcap.net"]
[plugins."io.containerd.grpc.v1.cri".registry.mirrors."gcr.io"]
endpoint = ["https://gcr-mirror.pingcap.net"]
[plugins."io.containerd.grpc.v1.cri".registry.mirrors."k8s.gcr.io"]
endpoint = ["https://k8s-gcr-mirror.pingcap.net"]
[plugins."io.containerd.grpc.v1.cri".registry.mirrors."quay.io"]
endpoint = ["https://quay-mirror.pingcap.net"]
```
```release-note
None
```

e2e: add mirror for k8s.gcr.io

---

pkg/controller/tidbcluster/tidb_cluster_controller.go
pkg/manager/member/tidb_member_manager.go
pkg/manager/member/tidb_member_manager_test.go
pkg/manager/member/tidb_scaler.go
pkg/manager/member/tidb_scaler_test.go
pkg/manager/meta/meta_manager.go
pkg/manager/meta/meta_manager_test.go
tests/e2e/tidbcluster/tidbcluster.go

close #3997
Handle the PVC during scaling of TiDB
```release-note
Support to handle PVC during scaling of TiDB
```

Handle the PVC during scaling of TiDB

---

pkg/manager/member/tikv_upgrader.go

Unable to upgrade tikv when unable to get the leader count of tikv.
Judge whether eviting leader is timeout before get leader count of tikv.
```release-note
```

optimize tikv upgrade process

---

pkg/manager/meta/meta_manager.go
pkg/util/util.go

Fix the bug that main synchronization is blocked when *TiDB* don't use PVC.
delpoy a tidb-cluster and watch the log of *controller manager*.
```release-note
```

Fix blocked main synchronization when TiDB don't use PVC

---

images/tidb-backup-manager/Dockerfile
images/tidb-backup-manager/Dockerfile.e2e

Use 'centos:8' image as the base image of tidb-backup-manager.
Use new *Dockerfile* to build images, and try to deploy tidb-backup-manager.
```release-note
```

Use 'centos:8' image as the base image of tidb-backup-manager

---

pkg/controller/tidbcluster/tidb_cluster_controller.go
pkg/manager/member/pd_failover.go
pkg/manager/member/scaler.go
pkg/manager/member/tidb_member_manager.go
pkg/manager/member/tidb_member_manager_test.go
pkg/manager/member/tidb_scaler.go
pkg/manager/member/tidb_scaler_test.go
pkg/manager/member/utils.go
pkg/manager/meta/meta_manager.go
pkg/manager/meta/meta_manager_test.go
pkg/util/util.go
tests/e2e/tidbcluster/tidbcluster.go

- manually cherry-pick #4033
- fix E2E
---
close #3997
Handle the PVC during scaling of TiDB
```release-note
Support to handle PVC during scaling of TiDB
```

Handle the PVC during scaling of TiDB (#4033)

---

examples/advanced/tidb-cluster.yaml

Update the 'schedulerName' field of pump to 'default-scheduler'.
```release-note
```

Update the 'schedulerName' field of pump to 'default-scheduler'

---

pkg/apis/pingcap/v1alpha1/tidbcluster.go
pkg/apis/pingcap/v1alpha1/tidbcluster_component.go
pkg/apis/pingcap/v1alpha1/validation/validation.go
pkg/backup/backup/backup_manager.go
pkg/backup/restore/restore_manager.go
pkg/controller/tidbcluster/tidb_cluster_condition_updater.go
pkg/manager/member/ticdc_member_manager.go
pkg/tkctl/cmd/info/info.go
tests/e2e/br/br.go

Fix #4051
Fixed potential nil pointer issues.
* Test upgrade
1. Upgrade `TiDB-Opertaor` and check the cluster is normal.
* Test depolyment
* Deploy new cluster and monitor, then check function.
* Deploy  new cluster without `PD` ,  then check pods and watch logs of `TiDB-Operator`.
```shell
NAME                                READY   STATUS    RESTARTS   AGE
my-tidb-cluster-dev-pump-0          0/1     Running   1          114s
my-tidb-cluster-dev-ticdc-0         1/1     Running   0          114s
my-tidb-cluster-dev-ticdc-1         1/1     Running   0          114s
my-tidb-cluster-dev-ticdc-2         1/1     Running   0          114s
my-tidb-cluster-dev-tiflash-0       4/4     Running   0          114s
my-tidb-cluster-dev-tikv-0          3/3     Running   0          114s …
```

Fixed potential nil pointer issues

---

pkg/apis/pingcap/v1alpha1/tidbcluster.go
pkg/manager/member/tikv_upgrader_test.go

Set the leader eviction default timeout of TiKV to 1500 min.
```release-note
Set the default region leader eviction timeout of TiKV to 1500 min
```

Set the leader eviction default timeout of TiKV to 1500 min

---

examples/advanced/tidb-cluster.yaml

correct `imagePullSecrets` usage of example.
Ref: https://kubernetes.io/docs/concepts/containers/images/#referring-to-an-imagepullsecrets-on-a-pod
```release-note
```

correct `imagePullSecrets` usage of example

---

pkg/controller/tidbcluster/tidb_cluster_control.go
pkg/manager/member/pd_upgrader.go
pkg/manager/member/pd_upgrader_test.go
pkg/manager/member/tiflash_upgrader.go
pkg/manager/member/tiflash_upgrader_test.go

Fix https://github.com/pingcap/tidb-operator/issues/4096
Sync TiFlash after pd
- Deploy TidbCluster with CDC, PD, TiKV, TiFlash, Pump, TiDB, waiting for Pods ready, upgrade the tc, check that the upgrade order is CDC, PD, TiFlash, TiKV, Pump, TiDB
```release-note
```

upgrade tiflash after pd

---

examples/basic/README.md
examples/tiflash/README.md
marketplace/gcp/tidb-operator/README.md

To stop the MySQL client from stripping TiDB specific comments (`/*T! ... */`) we need to add `--comments`
```release-note
NONE
```

Add `--comments` to READMEs

---

charts/tidb-cluster/values.yaml
charts/tidb-operator/values.yaml
deploy/aliyun/variables.tf
deploy/aws/variables.tf
deploy/gcp/variables.tf
hack/bump-version.sh

ref #4057.
run script `hack/bump-version.sh`, and correct some comments by hand.
```release-note
None
```

Bump operator to v1.2.0

---

.github/workflows/ci.yaml

Only open ssh session when the job is 'e2e-examples'.
```release-note
```

Only open ssh session when job is 'e2e-examples'

---

pkg/apis/pingcap/v1alpha1/tidbcluster_component.go
pkg/manager/member/pd_member_manager_test.go
tests/e2e/tidbcluster/tidbcluster.go

After https://github.com/pingcap/tidb-operator/pull/3909, hostNetwork is available for Discovery, however, the dnsPolicy is not updated accordingly.
After a further check, TiCDC has a similar issue.
Update dnsPolicy accordingly to match with the hostNetwork config.
- Deploy a TidbCluster with PD/TiDB/TiKV/TiFlash/Pump/TiCDC and set `spec.hostNetwork: true`, check that the cluster is created successfully, and hostNetwork and dnsPolicy configurations are as below:
```
t6-discovery-78ccf7fb5f-chx8n   1/1     Running     0          103s
t6-pd-0                         1/1     Running     0          3h2m
t6-pump-0                       1/1     Running     0          3h2m
t6-ticdc-0                      1/1     Running     0          83s
t6-tidb-0                       2/2     Running     0 …
```

support hostnetwork for all components

---

hack/tools/Makefile
hack/tools/README.md
hack/tools/go.mod
hack/tools/tools.go
hack/update-goimports.sh
hack/verify-boilerplate.sh
hack/verify-lint.sh
hack/verify-spelling.sh

Build tools and output to repo's dir instead of GOBIN. In order not to override global cmd.
```release-note
```

Build tools and output to repo's dir instead of GOBIN

---

pkg/apis/label/label.go
pkg/manager/member/dm_master_scaler.go
pkg/manager/member/dm_worker_scaler.go
pkg/manager/member/pd_scaler.go
pkg/manager/member/pump_scaler.go
pkg/manager/member/scaler.go
pkg/manager/member/ticdc_scaler.go
pkg/manager/member/tidb_scaler.go
pkg/manager/member/tiflash_scaler.go
pkg/manager/member/tikv_scaler.go
pkg/util/util.go
pkg/util/utils_test.go
pkg/webhook/pod/pod_mutater.go

Close #3736 
```release-note
remove unused func SyncAutoScalerAnn
```

remove: SyncAutoScalerAnn

---

pkg/manager/member/config.go
pkg/manager/member/config_test.go
tests/e2e/br/br.go
tests/e2e/tidbcluster/tidbcluster.go

Check startup script when check if configmap has beed updated
Upgrade operator v1.1.7 to v1.2.4:
* If set `clusterDomain` in TidbCluster, `PD`,`TiKV` and `TiDB` roll update. Because of PR #4123
* If don't set `clusterDomain` in TidbCluster, `PD`,`TiKV` and `TiDB` don't roll update.
```release-note
Roll update `PD`, `TiKV`, `TiDB` if set `clusterDomain`.
```

Check startup script when check if configmap has beed updated

---

pkg/apis/pingcap/v1alpha1/tidbcluster.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/manager/member/tidb_member_manager.go

Fix `PD` scale in failed when deploying cluster across multi Kubernetes
```release-note
```

Fix `PD` scale in failed when deploying cluster across multi Kubernetes

---

tests/e2e/br/br.go
tests/e2e/tidbcluster/tidbcluster.go
tests/e2e/util/ginkgo/ginkgo_util.go

Fix issue run unexpected e2e case

---

Makefile

revert #592
```release-note
None
```

add build debugger symbols back

---

docs/api-references/docs.md
pkg/apis/pingcap/v1alpha1/defaulting/tidb_ng_monitoring.go
pkg/apis/pingcap/v1alpha1/defaulting/tidb_ng_monitoring_test.go
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/tidbmonitor_types.go
pkg/controller/tidbngmonitoring/tidb_ng_monitoring_control.go

Default ns of target cluster to be same as TidbNGMonitoring
```release-note
```

Defaulting ns of target cluster to be same as TidbNGMonitoring

---

pkg/controller/backup_status_updater.go
pkg/controller/restore_status_updater.go

fix #4334 
FYI, I've test it with creating a backup and then add firewall that simply drop the packets to the apiserver after br succeed, here are the retry logs( focus on "Failed to update backup ..."). After retrying 3 times, I remove the firewall and it succeeds.
```
I1231 05:29:43.876251       8 manager.go:321] Get cluster tidb-operator-test/basic2-backup-s3 commitTs 430159582415028225 success
E1231 05:30:27.684019       8 backup_status_updater.go:89] Failed to update backup [tidb-operator-test/basic2-backup-s3], error: Put "https://10.0.0.1:443/apis/pingcap.com/v1alpha1/namespaces/tidb-operator-test/backups/basic2-backup-s3": http2: client connection lost
W1231 05:30:27.684049       8 reflector.go:424] …
```

feat(restore): retry updating restore status when restore job succeeded

---

hack/version.sh

Fix version script

---

tests/e2e/br/br.go
tests/e2e/tidbcluster/across-kubernetes.go

Address e2e problem in #4368 by adding timeout for checkClusterDomainstatus
```release-note
None
```

refine e2e check cluster domain status

---

pkg/manager/member/scaler.go

Closes #4332 
Print logs when trying to delete pvcs without defer-deleting annotation exists.
```release-note
None
```

log optimization when deleting pvc

---

docs/api-references/docs.md
manifests/crd.yaml
manifests/crd/v1/pingcap.com_tidbclusters.yaml
manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
manifests/crd_v1beta1.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/manager/member/pd_member_manager.go
pkg/manager/member/template.go

for version >= v.5.0.5, the nslookup version is changed in the image.
if nameserver in `/etc/resolv.conf` contains not only coredns cluster ip, PD pod will fail to start since the startup script use nslookup and the behavior of nslookup is different from general resolver.
ref: https://serverfault.com/a/398854
https://github.com/coredns/coredns/issues/3835#issuecomment-616715938
https://github.com/isc-projects/bind9/blob/808d0b07b00244de735be68ce85b2652e4e0efec/bin/dig/dighost.c#L4128-L4162
```
if ((msg->rcode == dns_rcode_servfail && !l->servfail_stops) ||
(check_ra && (msg->flags & DNS_MESSAGEFLAG_RA) == 0 && l->recurse))
```
we will hit the `check_ra&&。。` condition here, and nslookup will try the next nameserver, and the next nameserver will return NXDOMAIN(since it is not the coredns) …

Add startUpScriptVersion for pd spec

---

go.mod
pkg/binlog/binlog.go
pkg/manager/member/pump_member_manager.go
tests/e2e/tidbcluster/across-kubernetes.go

Closes #4361 
For the 2 problems mentioned in #4361 :
1. add all peermembers to endpoints when initializing etcd client. 
2. Instead of timedout every context in pumpclient, I just making the clientv3.New() to return error when underlying endpoints are not available(see https://github.com/etcd-io/etcd/issues/9877), thus to avoid the following client call get stucked indefinitely.
```release-note
Fixed the problem where sync pump would get stuck when the PDs of one Kubernetes cluster are all down in across Kubernetes deployment.
```

Fixed the problem where pump would get stuck when local pds are down

---

charts/tidb-operator/templates/config/_scheduler-config-yaml.tpl
charts/tidb-operator/templates/scheduler-deployment.yaml

Closes #4383 
refer to [k8s v1.23 changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md#deprecation)
```release-note
adjust KubeSchedulerConfiguration api changes in k8s v1.23
```

adjust KubeSchedulerConfiguration api changes in k8s v1.23

---

pkg/manager/member/pd_upgrader.go
pkg/manager/member/pd_upgrader_test.go

Close #1235
Ref: #3944
Deploy tc with pd's replicas is 5
* Upgrade pd when the leader is pd-4, and check transfer leader to pd-0.
* Upgrade pd when the leader is pd-4 and pd-0 is unhealthy, and check transfer leader to pd-1.
* Upgrade pd when the leader is pd-0 and check transfer leader to pd-4.
```release-note
```

Choose a healthy pd to transfer leader when upgrade pd

---

pkg/manager/member/tiflash_util.go
pkg/manager/member/tiflash_util_test.go

* Deploy cluster-1 and cluster-2, cluster-2 don't contain TiDB, check `tidb_status_addr`
```release-note
```

Use headless tidb service when deploy across k8s and local tidb isn't exist

---

pkg/util/discovery/discovery.go

Optimize IsAPIGroupVersionResourceSupported method comment.
```release-note
```

Optimize IsAPIGroupVersionResourceSupported method comment

---

charts/tidb-cluster/values.yaml
charts/tidb-operator/values.yaml
deploy/aliyun/variables.tf
deploy/aws/variables.tf
deploy/gcp/variables.tf
hack/bump-version.sh

bump operator to v1.2.7
```release-note
None
```

bump operator to v1.2.7

---

pkg/controller/pd_control.go
pkg/controller/pod_control.go
pkg/manager/member/tikv_upgrader.go
tests/failover.go

- fixes #4412
- Using `GetPDClient` to get pd client, and make `getPDClientFromService` private
```release-note
Fix tikv ugprade process when local pd are down
```

Fix tikv ugprade process when local pd are down

---

pkg/manager/member/tiflash_util.go
pkg/manager/member/tiflash_util_test.go

Close #4434 
Close #4435
```release-note
Fix the issue about creating TiFlash replicas for tables
```

Fix tiflash config after v5.4.0

---

examples/istio/README.md
examples/istio/disable-mtls.yaml
examples/istio/tidb-cluster.yaml
examples/istio/tidb-monitor.yaml
pkg/manager/member/pd_member_manager.go
pkg/manager/member/pd_member_manager_test.go

Run TiDB on istio enabled k8s cluster
Closes: https://github.com/pingcap/tidb-operator/issues/4150
For TiDB to work on Istio enabled k8s cluster below are the configuration changes needed
1. Disable MTLS
```
---
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
name: "ns-disable-mtls-pa"
namespace: "<namespace>"
spec:
mtls:
mode: DISABLE
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
name: "ns-disable-mtls-dr"
spec:
host: "*.<namespace>.svc.cluster.local"
trafficPolicy:
tls:
mode: DISABLE
```
2. Prefix protocol name to peer port or in Kubernetes 1.18+ by the appProtocol 
3. Add port 2379 to PD peer service to create listeners for pod DNS with this port as we have noticed that other components of TiDB communicate to a particular …

Changes required to run TiDB on Istio enabled k8s cluster

---

pkg/manager/member/tiflash_member_manager.go

Reslove #3184
TiFlash add metrics port.
```release-note
```

TiFlash add metrics port

---

pkg/manager/member/tidb_member_manager.go
pkg/manager/member/tidb_member_manager_test.go

Closed #4489.
validate password not contain '\' character.
```release-note
```

fix random password conatin illegal character

---

cmd/backup-manager/app/clean/clean.go
pkg/controller/backup/backup_control.go

* Return error when deleted objects are less than input.
* Only log count for deleted objects and failed objects.
* Add log when removing backup's finalizer.
```release-note
```

optimize clean pod log

---

pkg/manager/member/pvc_resizer.go
pkg/manager/member/pvc_resizer_test.go

1. Deploy tc and tikv have three volumes
2. Scale up three volumes
3. Check the resize is pod by pod
```release-note
Resize PVCs pod by pod 
```

Resize PVCs pod by pod

---

pkg/manager/member/pvc_resizer.go
pkg/manager/member/pvc_resizer_test.go

Close #4616
```release-note
Fix the issue that can not upgrade tikv when using local storage
```

Fix the issue than can not upgrade tikv when using local storage

---

pkg/apis/pingcap/v1alpha1/validation/validation.go
pkg/apis/pingcap/v1alpha1/validation/validation_test.go

This PR solves the problem that when validating PD spec, `Service` is not validated. This causes the invalid IP in `Spec.PD.Service.LoadBalancerSourceRanges` being silently rejected. However, according to the [source code](https://github.com/pingcap/tidb-operator/blob/346a330c71e2f50e98b0f5394660f9713821cf3a/pkg/apis/pingcap/v1alpha1/validation/validation.go#L632) of this operator, the function `validateService` is used to validate the field `LoadBalancerSourceRanges`, and the operator is supposed to throw an error message for the invalid IP in `LoadBalancerSourceRanges`  . 
Details of this problem can be found at https://github.com/pingcap/tidb-operator/issues/4637.
We added a sanity check in the function `validatePDSpec` by calling the function `validateService`. This change ensures …

add: validation for service in pd

---

pkg/manager/member/pvc_resizer.go

not recreate sts when storage scale-in

---

pkg/apis/pingcap/v1alpha1/tidbcluster.go
pkg/apis/pingcap/v1alpha1/tidbcluster_test.go
pkg/controller/ticdc_control.go
pkg/controller/ticdc_control_test.go
pkg/manager/member/ticdc_member_manager_test.go
pkg/manager/member/ticdc_scaler.go
pkg/manager/member/ticdc_scaler_test.go
pkg/manager/member/ticdc_upgrader.go
pkg/manager/member/ticdc_upgrader_test.go
pkg/util/cmpver/cmpver_test.go

Close #4664
Wait TiCDC cluster becomes healthy after resigning owner, otherwise there may be latency spike.
| master branch | this PR |
| -- | -- |
| <img width="918" alt="image" src="https://user-images.githubusercontent.com/2150711/182792275-db702588-bbde-4a19-a867-7bb8376c45cb.png"> | <img width="919" alt="image" src="https://user-images.githubusercontent.com/2150711/182790823-e443da77-3849-45b1-9fd1-67c31cea261a.png"> |
```release-note
None
```

ticdc: wait TiCDC cluster becomes healthy after resigning owner

---

pkg/manager/member/tidb_upgrader.go
pkg/manager/member/tidb_upgrader_test.go
pkg/manager/member/tiflash_upgrader.go
pkg/manager/member/tiflash_upgrader_test.go
pkg/manager/member/tikv_upgrader.go
pkg/manager/member/tikv_upgrader_test.go

feat(minReadySeconds): support minReadySeconds in TC annotation

---

pkg/manager/suspender/suspender.go
pkg/manager/suspender/suspender_test.go

```release-note
Fix the issue cluster sync stuck caused by suspending cluster when scaling
```

Fix the issue cluster sync stuck caused by suspending cluster when scaling

---

pkg/apis/pingcap/v1alpha1/validation/validation.go

Signed-off-by: mahjonp <junpeng.man@gmail.com>
Closes #4690
The root cause is on `acrossK8s` scenario, pd spec could be nil, this PR checks the nil of pdSpec before access it's sub-fields.
```release-note
```

fix the panic on validating a nil pd spec

---

docs/api-references/docs.md
manifests/crd.yaml
manifests/crd/v1/pingcap.com_tidbclusters.yaml
manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
manifests/crd_v1beta1.yaml
pkg/apis/label/label.go
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/tidbcluster.go
pkg/apis/pingcap/v1alpha1/tidbcluster_test.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
pkg/controller/ticdc_control.go
pkg/controller/ticdc_control_test.go
pkg/controller/tidbcluster/tidb_cluster_condition_updater.go
pkg/controller/tidbcluster/tidb_cluster_condition_updater_test.go
pkg/controller/tidbcluster/tidb_cluster_control.go
pkg/manager/member/ticdc_member_manager.go
pkg/manager/member/ticdc_member_manager_test.go
pkg/manager/member/ticdc_scaler.go
pkg/manager/member/ticdc_scaler_test.go
pkg/manager/member/ticdc_upgrader.go
pkg/manager/member/ticdc_upgrader_test.go
pkg/util/cmpver/cmpver_test.go
pkg/util/tidbcluster/tidbcluster.go

```release-note
Support graceful upgrade TiCDC (>=6.3.0) pods
```

Support graceful upgrade TiCDC (>=6.3.0) pods

---

pkg/manager/member/tidb_member_manager.go
pkg/manager/member/tidb_member_manager_test.go

The least version that tidb support set server labels via HTTP is v6.3.0, so we should skip set labels before this version.
```release-note
None
```

tidb: set tidb support set label min version to v6.3.0

---

cmd/backup-manager/app/util/util.go

Signed-off-by: WangLe1321 <wangle1321@163.com>
Sometimes we got 403 error when request S3, and when we retry manually later, the S3 request can be successful. The reason is when we add policy and attach it to role in AWS server, the authority need spend some seconds to take effect.
Closes #4742
Add retry when get backup meta data. 
```release-note
```

br: add retry when get backup meta data

---

pkg/backup/backupschedule/backup_schedule_manager.go

Closes #4731 
set Azure prefix like S3 or Gcs.
```release-note
fix backup schedule set no Azure prefix 
```

BR: fix backup schedule set no Azure prefix 

---

cmd/backup-manager/app/backup/backup.go
cmd/backup-manager/app/clean/clean.go
cmd/backup-manager/app/clean/clean_test.go
cmd/backup-manager/app/restore/restore.go
cmd/backup-manager/app/util/util.go
images/tidb-operator/Dockerfile
pkg/backup/backup/backup_manager.go
pkg/backup/constants/constants.go
pkg/backup/restore/restore_manager.go
pkg/backup/restore/restore_manager_test.go
pkg/backup/snapshotter/snapshotter.go
pkg/backup/snapshotter/snapshotter_aws.go
pkg/backup/snapshotter/snapshotter_gcp.go
pkg/backup/snapshotter/snapshotter_none.go
pkg/backup/snapshotter/snapshotter_test.go
pkg/backup/util/remote.go
pkg/backup/util/remote_test.go
pkg/backup/util/util.go

Closes #4781
using the remote storage to pass info between backup manager and controller
50+ EKS node with tidb cluster has 50 tikv nodes, backup works and completed
restore
```release-note
```

fix backup failure on tidb cluster has massive tikv nodes (40+)

---

pkg/backup/snapshotter/snapshotter.go

it caused failure when the volume snapshot restores to the same eks cluster with the backup cluster.
always create PV when volume restores completed. if PV already existed, skip it, if not always create a new one.
```release-note
```

fix: restore the cluster to the same eks with diff namespace

---

pkg/util/cmpver/cmpver.go
pkg/util/cmpver/cmpver_test.go

Signed-off-by: lobshunter <pengyu@pingcap.com>
This PR adds `master` to latest version list, so images with that tag can be used(mainly used in testing).
```release-note
Treat "master" as latest version of TiDB components too
```

feat(controller): treat "master" as latest version

---

pkg/manager/volumes/phase.go
pkg/manager/volumes/phase_test.go

Fixes the issue where the operator panics by manually injecting extra volumes in asts.
Fixes #4817
Fixed a nil ptr reference issue.
```release-note
```

Check desired volume during validation

---

charts/tidb-operator/templates/controller-manager-deployment.yaml
charts/tidb-operator/values.yaml
cmd/controller-manager/main.go
pkg/controller/dependences.go

Close #4829.
Add two config `kubeClientQPS` and `kubeClientBurst`, they will be passed to kube `client-go` config.
```release-note
Support for configuring kube-client QPS and Burst: `kubeClientQPS`/`kubeClientBurst`
```

Add config to increase kube-client qps limit

---

pkg/manager/volumes/delegation/aws/ebs_modifier.go
pkg/manager/volumes/delegation/interface.go
pkg/manager/volumes/pod_vol_modifier.go

fix #4797
NOTE, in this case, some volume statuses will not be updated
```
volumes:
tikv:
boundCount: 1
currentCapacity: 1Gi
currentCount: 1
currentStorageClass: standard
modifiedCapacity: 1Gi
modifiedCount: 0
modifiedStorageClass: test
name: tikv
resizedCapacity: 1Gi
resizedCount: 0
```
```release-note
Fix the issue that TiDB Operator panics if without PV permission
```

fix panic without PV permission

---

pkg/manager/member/tiflash_member_manager.go

fix #4843 
1. create a TiFlash with 1 replica and 110G storage and `m6g.xlarge` instance in AWS EKS
2. scale TiFlash to 0
3. scale TiFlash to 1 with 100G storage
4. TiFlash becomes ready and tc synced, TiFlash volume status with `modifiedCapacity: 100Gi` and `modifiedCount: 1`
5. scale TiFlash to 0
6. scale TiFlash to 1 with `t4g.medium` instance
7. TiFlash becomes ready and tc synced
```release-note
```

tc: delete tiflash sts before scale from 0

---

pkg/manager/member/tiflash_member_manager.go
pkg/manager/member/tikv_member_manager.go

fix #4854
- Scale in TiKV/TiFlash, check `LastTransitionTime` is set for `tombstoneStores `
```release-note
Fix the issue that LastTransitionTime is not set for TiKV and TiFlash tombstone stores 
```

fix: set LastTransitionTime for tombstoneStores status

---

pkg/manager/member/tiflash_util.go

```release-note
Fix the issue that tiflash listen on IPv4 addr when `preferIPv6` is enabled
```

Fix the issue that tiflash listen on IPv4 addr when `preferIPv6` is enabled

---

ci/e2e_eks.groovy
ci/e2e_gke.groovy
ci/e2e_kind.groovy
ci/pull_e2e_kind.groovy
ci/pull_e2e_release.groovy
ci/vm.groovy
hack/run-in-container.sh

update go version to 1.19.5 for e2e

---

cmd/controller-manager/main.go

Originally the pprof routes are not working.
Closes #4873
Added default http route back.
```release-note
Fix the issue that pprof endpoint is not reachable because the route conflicts with the metrics endpoint
```
---
Here's the manual test, you can see that now both `/metrics` and `/debug/pprof` endpoints are working:
```console
➜  tidb-operator git:(fix/pprof-route-conflict) curl -s localhost:6060/metrics | head -n 5                                 
go_gc_duration_seconds{quantile="0"} 2.4544e-05
go_gc_duration_seconds{quantile="0.25"} 7.0549e-05
go_gc_duration_seconds{quantile="0.5"} 9.0915e-05
➜  tidb-operator …
```

Add http route for pprof

---

pkg/manager/volumes/delegation/aws/ebs_modifier.go

fix(ebs): fix missing param in sc when modify ebs

---

cmd/controller-manager/main.go
pkg/controller/autoscaler/tidbcluster_autoscaler_controller.go
pkg/controller/backup/backup_controller.go
pkg/controller/backupschedule/backup_schedule_controller.go
pkg/controller/dmcluster/dm_cluster_controller.go
pkg/controller/restore/restore_controller.go
pkg/controller/tidbcluster/pod_control.go
pkg/controller/tidbcluster/tidb_cluster_controller.go
pkg/controller/tidbdashboard/tidb_dashboard_controller.go
pkg/controller/tidbinitializer/tidb_initializer_controller.go
pkg/controller/tidbmonitor/tidb_monitor_controller.go
pkg/controller/tidbngmonitoring/tidb_ng_monitoring_controller.go
pkg/metrics/metrics.go
pkg/metrics/workerqueue.go

Add workerqueue and reconcile related metrics.
Closes #4872
```release-note
Add the metrics for the reconciler and worker queue to improve observability
```
---
Here're the metrics after introducing this change:
```console
➜  ~ curl localhost:6060/metrics
controller_runtime_active_workers{controller="backup"} 10
controller_runtime_active_workers{controller="dmcluster"} 5
controller_runtime_active_workers{controller="restore"} 5
controller_runtime_active_workers{controller="tidb-dashboard"} 5
controller_runtime_active_workers{controller="tidb-ng-monitoring"} 5
controller_runtime_active_workers{controller="tidbcluster"} 5 …
```

Add controller runtime related metrics

---

pkg/manager/member/tiflash_util.go

Fix the issue tiflash metric server listen on incorrect addr when ipv6 enabled

---

pkg/backup/snapshotter/snapshotter.go
pkg/backup/snapshotter/snapshotter_test.go
pkg/backup/testutils/br.go

Closes #4884
precondition.
according to https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/advanced-statefulset, upgrade tide-operator with asts.
case#1
- create a cluster with 6 nodes
- scale out the cluster to 9 nodes
- scale in the cluster to 6 nodes, and set delete-slots [3,4,5]
- keep released existing pv/pvcs and then do the backup
- restore the backup
case#2
- create a cluster with 6 nodes
- scale out the cluster to 9 nodes
- scale in the cluster to 6 nodes, and set delete-slots [3,4,5]
- remove released existing pv/pvcs and then do the backup
- restore the backup
```release-note
```

br: ensure pvc names sequential for ebs restore

---

pkg/apis/pingcap/v1alpha1/types.go
pkg/controller/tidbcluster/pod_control.go
pkg/controller/tidbcluster/pod_control_test.go

Closes: https://github.com/pingcap/tidb-operator/issues/4758
```release-note
```

Add PD graceful restart

---

cmd/backup-manager/app/backup/backup.go
cmd/backup-manager/app/import/import.go
cmd/backup-manager/app/restore/restore.go
pkg/autoscaler/autoscaler/query/external.go
pkg/binlog/binlog.go
pkg/controller/ticdc_control.go
pkg/controller/tidb_control.go
pkg/controller/tidb_control_test.go
pkg/discovery/server/proxy_test.go
pkg/discovery/server/server_test.go
pkg/pdapi/pdapi.go
pkg/pdapi/pdapi_test.go
pkg/util/http/httputil.go
pkg/util/http/httputil_test.go
tests/actions.go
tests/crd_test_util.go
tests/e2e/tidbdashboard/dashboard.go
tests/e2e/util/pd/pd.go
tests/e2e/util/proxiedtidbclient/proxiedtidbclient.go
tests/e2e/util/tngm/ng_monitoring_client.go
tests/monitor.go
tests/pkg/fault-trigger/client/client.go
tests/pkg/metrics/annotation_util.go
tests/pkg/mock/monitor.go
tests/pkg/mock/util.go
tests/pkg/webhook/route.go

Replace the ioutil package with the io package, ioutil.ReadAll() has been deprecated in go 1.16 (https://golang.google.cn/pkg/io/ioutil/)
```release-note
```

chore: ioutil has been deprecated in go 1.16

---

CHANGELOG.md
charts/tidb-operator/values.yaml
manifests/local-dind/kubernetes-dashboard.yaml
tests/e2e/config/config.go
tests/e2e/tidbcluster/serial.go
tests/e2e/tidbcluster/stability-asts.go

On April 3, 2023, the old regiestry `k8s.gcr.io` will be frozen, and images of kubernetes and its related sub-projects will no longer be pushed to this old regiestry. 
use `registry.k8s.io` repository to replaces the old one.
Ref:  https://kubernetes.io/zh-cn/blog/2023/02/06/k8s-gcr-io-freeze-announcement/
```release-note
```

chore:  update k8s.gcr.io -> registry.k8s.io

---

docs/api-references/docs.md
manifests/crd.yaml
manifests/crd/v1/pingcap.com_dmclusters.yaml
manifests/crd/v1beta1/pingcap.com_dmclusters.yaml
manifests/crd_v1beta1.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/manager/member/dm_master_member_manager.go
pkg/manager/member/startscript/v1/template.go
pkg/manager/member/startscript/v1/template_test.go

Originally in the startup script, it's only checking against `A` record which is `IPv4` only and cannot handle `AAAA` record which is for `IPv6`. Fixed the domain check to make it work for `AAAA`-only records during startup.
Fixed the startup script to check against both `A` and `AAAA` records.
```release-note
Introduce `startUpScriptVersion` field for DM master to specify startup script version
```
---
The existing DM clusters won't be affected. After applying the change, the start script in config will be updated, but DM pods won't be affected.
```console
ubuntu@ip-172-31-71-58:~/tidb-operator$ kubectl get cm …
```

Add startUpScriptVersion for dm-master spec

---

pkg/controller/equality.go
pkg/controller/service_control.go
pkg/controller/service_control_test.go
pkg/manager/member/dm_master_member_manager.go
pkg/manager/member/dm_worker_member_manager.go
pkg/manager/member/pd_member_manager.go
pkg/manager/member/tiflash_member_manager.go
pkg/manager/member/tikv_member_manager.go
pkg/manager/member/tiproxy_member_manager.go

close https://github.com/pingcap/tidb-operator/issues/4972
```release-note
```

Check service annotation and labels

---

pkg/backup/backup/backup_manager.go

If cluster metadata file already exists, fail the backup job immediately.
With this patch, meta data file existing error will be skipped without repeating retrying as before.
```release-note
```

Fix cluster meta data existing

---

pkg/manager/member/pd_member_manager.go

in #4973, we refactored the logic of PD service update, after that the PD peer service is updated repeatly.
```
I0519 09:53:29.198719       1 service_control.go:91] update Service: [default/tc-1-pd-peer] successfully, kind: TidbCluster, name: tc-1
I0519 09:54:29.199537       1 service_control.go:91] update Service: [default/tc-1-pd-peer] successfully, kind: TidbCluster, name: tc-1
I0519 09:55:29.220976       1 service_control.go:91] update Service: [default/tc-1-pd-peer] successfully, kind: TidbCluster, name: tc-1
```
This is because the service get from the cache may lack the `pingcap.com/last-applied-configuration` annotation as it is deleted by a previous reconcile. also see #462
https://github.com/pingcap/tidb-operator/blob/e97423ed992efdddfcab449d7cdf9472b4199176/pkg/controller/servic …

fix PD peer svc update repeatly

---

cmd/backup-manager/app/backup/manager.go
cmd/backup-manager/app/clean/manager.go
cmd/backup-manager/app/util/backup_size.go
pkg/backup/util/remote.go

1. Backup  size attribute of a backup CR is now the expected size after restore instead of the delta.
2. Backup size will be reported for both successful and failed ebs backup job
3. No need to recalculate backupsize at clean time
```release-note
```

ebs: calc full snapshot size and report backup size for failed backup

---

cmd/backup-manager/app/cmd/restore.go
cmd/backup-manager/app/restore/restore.go
cmd/backup-manager/app/util/util.go
docs/api-references/docs.md
manifests/crd.yaml
manifests/crd/v1/pingcap.com_restores.yaml
manifests/crd/v1beta1/pingcap.com_restores.yaml
manifests/crd_v1beta1.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/restore.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/backup/backup/backup_manager.go
pkg/backup/backup/backup_test.go
pkg/backup/constants/constants.go
pkg/backup/restore/restore_manager.go
pkg/backup/restore/restore_manager_test.go
pkg/backup/snapshotter/snapshotter.go
pkg/backup/snapshotter/snapshotter_aws.go
pkg/backup/snapshotter/snapshotter_gcp.go
pkg/backup/snapshotter/snapshotter_none.go
pkg/backup/testutils/helpers.go
pkg/backup/util/util.go
pkg/backup/util/utils_test.go
pkg/controller/restore/restore_controller.go

Refactor restore controller to support across k8s volume restore
Closes #5009
Divide volume snapshot backup into 3 phases: `restore-volume`, `restore-data` and `restore-finish`
for `restore-volume` phase, restore all the tikv volumes from volume snapshots, then start all the tikv instances. After all the tikv instances are up, the restore enters `TikvComplete` status.
for `restore-data` phase, execute volume restore data command to restore the data of tikv to min-resolved ts. After it is complete, the restore enters `DataComplete` status.
for `restore-finish` phase, restart tikv instances and set `tc.spec.recoveryMode` to `false` to start tidb. Then the restore enters `Complete` status.
Please refer to [Release Notes Language Style …

br: refactor restore controller to support across k8s

---

ci/pull_e2e_kind.groovy

update E2E Pod resources

---

pkg/manager/member/startscript/v2/pd_start_script.go

follow #5005
```release-note
```

fix custom port for PD startScriptVersion v2

---

pkg/manager/tidbdashboard/manager.go
pkg/manager/tidbdashboard/manager_test.go

Fix wrong baseImage version adapt for image tag while the repo has specified a unique port with ':'.
Fix the bug that  baseImage auto version adapt can be executed unexpected while the repo has specified a unique port with ':'.
e.g. 
If baseImage = example.registry.com:30000/foo/pingcap/tidb-dashboard:vx.y.z,  the final image will be "example.registry.com:vx.y.z".
Judge whether there were '\' after the last ':'.  If there is one, it is not a ':' for the image tag.
```release-note
Fix TidbDashboard baseImage parsing fault.
```

Fix TidbDashboard baseImage parsing fault

---

Makefile
tests/drainer.go

fix drainer E2E for custom port

---

pkg/controller/ticdc_control.go
pkg/controller/ticdc_control_test.go
pkg/controller/tidb_control_test.go

When deploying TiCDC cluster containing capture servers managed by different tidb cluster CRs across multiple Kubernetes clusters. In this case, the existing tidb operator won't be able to pick the right capture to drain, as two caputre servers may share similar advertise address prefix. 
Consider cluster domain when draining capture servers across multiple kubernetes clusters
```release-note
`None`
```

Consider cluster domain when draining capture servers across multiple kubernetes clusters

---

docs/api-references/docs.md
manifests/crd.yaml
manifests/crd/v1/pingcap.com_tidbinitializers.yaml
manifests/crd/v1beta1/pingcap.com_tidbinitializers.yaml
manifests/crd_v1beta1.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/tidbinitializer_types.go
pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
pkg/manager/member/tidb_init_manager.go

add tolerations support for TidbInitializer, so that it can be scheduled to some special nodes with taints
```release-note
Support setting tolerations for TidbInitializer
```

add tolerations support for TidbInitializer

---

pkg/controller/ticdc_control.go

fix bug introduced in #5040
```
W0609 09:40:30.451678       1 ticdc_member_manager.go:268] Failed to get status for Pod tc-1-ticdc-0 of [ns-1/tc-1], error: Get "http://tc-1-ticdc-0.tc-1-ticdc-peer.ns-1.cluster.local:8301/status": dial tcp: lookup tc-1-ticdc-0.tc-1-ticdc-peer.ns-1.cluster.local on 10.234.0.10:53: no such host
```
```release-note
```

fix TiCDC across K8s address

---

pkg/manager/member/tiflash_util.go
pkg/manager/member/tiflash_util_test.go

The tcp_port and http_port are deprecated in tiflash since v7.1.0.
Remove those two ports for the corresponding versions.
```release-note
```

Remove tcp and http ports for tiflash >= 7.1.0

---

docs/api-references/docs.md
manifests/crd.yaml
manifests/crd/v1/pingcap.com_tidbclusters.yaml
manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
manifests/crd_v1beta1.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/manager/member/tiproxy_member_manager.go

tiproxy: revert enable SSL by default

---

docs/api-references/docs.md
manifests/crd.yaml
manifests/crd/v1/pingcap.com_tidbclusters.yaml
manifests/crd/v1beta1/pingcap.com_tidbclusters.yaml
manifests/crd_v1beta1.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/manager/member/startscript/v1/render_script.go
pkg/manager/member/startscript/v1/template.go
pkg/manager/member/startscript/v1/template_test.go
pkg/manager/member/startscript/v2/pd_start_script.go
pkg/manager/member/startscript/v2/pd_start_script_test.go

make pd start timeout configurable
Update pd start timeout value to make it configurable 
```release-note
```

make pd start timeout configurable

---

pkg/apis/pingcap/v1alpha1/tidbcluster.go
pkg/manager/member/startscript/v1/render_script.go
pkg/manager/member/startscript/v1/template_test.go
pkg/manager/member/startscript/v2/pd_start_script.go
pkg/manager/member/startscript/v2/pd_start_script_test.go

in #5071, a new `startTimeout` field for PD spec is introduced, and it's default value is set via CRD.
If a user upgrades the TiDB-Operator image before updating the CRD, this new field will become `0` and PD will be rolling restarted.
- ensure no rolling restart for PD after updated the image to this PD's version.
```release-note
```

fix PD StartTimeout if no CRD updated

---

Makefile

add `make help` command. result:
```release-note
```

chore: add make help cmd

---

docs/api-references/docs.md
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go

update the bootstrap SQL supported version
```release-note
```

Chore: update the bootstrap SQL supported version

---

cmd/backup-manager/app/clean/clean.go
pkg/backup/restore/restore_manager.go
pkg/backup/snapshotter/snapshotter.go
pkg/backup/snapshotter/snapshotter_aws.go
pkg/backup/snapshotter/snapshotter_gcp.go
pkg/backup/snapshotter/snapshotter_none.go
pkg/backup/util/aws_ebs.go

Close #5103 
Add 2 more tags for the restored aws ebs volume, like
'CSIVolumeName=<pvc_name> ex: pvc-daff-ddfasdfs-dafdsaf-dafsdf-asdfa
[kubernetes.io/created-for/pvc/name=<tikv_pod_name>](http://kubernetes.io/created-for/pvc/name=%3Ctikv_pod_name%3E) Ex: tikv-mussel-prod-tikv-10'
```release-note
```

pkg: add 2 operator related tags to restored ebs volume

---

examples/initialize/tidb-initializer.yaml

in #5047, we added `tolerations` support for `TidbInitializer`, we should update the example too.
```release-note
```

Add TidbInitializer tolerations example

---

pkg/backup/backup/backup_test.go
pkg/backup/backupschedule/backup_schedule_manager.go
pkg/backup/backupschedule/backup_schedule_manager_test.go
pkg/backup/restore/restore_manager.go
pkg/backup/restore/restore_manager_test.go
pkg/backup/testutils/br.go
pkg/backup/testutils/helpers.go

Close #5147 #4992 #5129
This PR addresses 3 problems
1. Make sure backup schedule will GC completed and failed backups when they are expired.
2. Precheck tikv replicas in restore tc with the backup metadata for EBS restore
3. Make sure recovery mode is on when doing EBS across k8s restore
```release-note
```

br: GC by MaxReservedTime works on completed or failed backups

---

charts/br-federation/templates/controller-manager-rbac.yaml
docs/api-references/federation-docs.md
pkg/apis/federation/pingcap/v1alpha1/types.go

br: add permission of events to br federation manager

---

pkg/backup/util/aws_ebs.go

Fix the bug that always miss one restore volume tag
Closes #5161
The root cause is that the `tag` variable in the `for` loop is always covered, so after the for loop, the `tag` value is the last key. We reference the pointer of `tag` in the `for` loop, so all the objects that reference the pointer of `tag` all get the last key finally.
So we use a local variable to replace the `tag`
```release-note
```

br: fix missing restore volume tag

---

pkg/apis/pingcap/v1alpha1/component_spec.go

fix: add missing tiproxy label

---

pkg/controller/tidbcluster/tidb_cluster_control.go
pkg/features/features.go
pkg/manager/member/tikv_upgrader.go
pkg/manager/volumes/pod_vol_modifier.go

Change the scope of feature `VolumeModifying`.
Now even if we disable the feature `VolumeModifying`, volume resizing will also be worked.
```release-note
```

feat: change scope of feat VolumeModifying

---

ci/pull_e2e_kind.groovy
ci/pull_e2e_release.groovy

fix jenkins groovy

---

pkg/controller/ticdc_control.go
pkg/manager/member/ticdc_scaler.go
pkg/manager/member/ticdc_scaler_test.go

Close #4912
- upgrade TiCDC to a version with improper constraint image tag
```release-note
```

try to Graceful Drain TiCDC for improper constraint image tag

---

docs/api-references/docs.md
manifests/crd.yaml
manifests/crd/v1/pingcap.com_backupschedules.yaml
manifests/crd/v1beta1/pingcap.com_backupschedules.yaml
manifests/crd_v1beta1.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go

ref https://github.com/pingcap/tidb-operator/issues/4955
as title, this already fixed in https://github.com/pingcap/tidb-operator/pull/5137 for master, so we just need fix this for release-1.4 branch
make BackupScheduleSpec.LogBackupTemplate optional on release-1.4
```release-note
none
```

backup: make LogBackupTemplate optional

---

pkg/backup/constants/constants.go
pkg/backup/restore/restore_manager_test.go
pkg/backup/util/aws_ebs.go

Close #5185 
Pass the region name for EBS volume delete and addtag operation.
```release-note
```

ebs br: pass region name for aws EBS volume operation

---

images/br-federation-manager/Dockerfile
images/br-federation-manager/Dockerfile.e2e
images/tidb-backup-manager/Dockerfile
images/tidb-backup-manager/Dockerfile.e2e
images/tidb-operator/Dockerfile
images/tidb-operator/Dockerfile.e2e

The current base image lack matainence and may contains security problem.
Use pingcap unify base image maintained by EE and security team
```release-note
```

feat: use pingcap base image

---

examples/advanced/tidb-monitor.yaml
manifests/monitor/tidb-monitor.yaml

Close #4845 
The tag of Grafna has no `v` prefix, like https://hub.docker.com/layers/grafana/grafana/7.5.11/images/sha256-c6d621725df5a179bb19f8fd3c8c7bd10fee915edc98a4418d0a21011e104f9b?context=explore
```release-note
```

example: fix and update grafana version

---

cmd/backup-manager/app/backup/manager.go
cmd/backup-manager/app/util/backup_size.go
docs/api-references/docs.md
docs/api-references/federation-docs.md
manifests/crd.yaml
manifests/crd/federation/v1/federation.pingcap.com_volumebackups.yaml
manifests/crd/federation/v1/federation.pingcap.com_volumebackupschedules.yaml
manifests/crd/v1/pingcap.com_backups.yaml
manifests/crd/v1/pingcap.com_backupschedules.yaml
manifests/federation-crd.yaml
pkg/apis/federation/pingcap/v1alpha1/openapi_generated.go
pkg/apis/federation/pingcap/v1alpha1/types.go
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/backup/snapshotter/snapshotter_test.go

Close #5201 
Close #5212 
This pr introduced an option 'calcSizeLevel' in backup spec to claim if calculate backup snapshot size or not, and calculate which part of snapshot sizes. 
- 'all' (default) : calculate both full and incremental size; ''
- 'full' : calculate full size
-  'incremental': calculate incremental size
-  'disabled': skip size calculation
```yaml
kind: Backup
metadata:
name: zm-dataplane-a
namespace: backup-a
spec:
backoffRetryPolicy:
maxRetryTimes: 2
minRetryDuration: 300s
retryTimeout: 30m
backupMode: volume-snapshot
backupType: full
br:
cluster: db-a
clusterNamespace: backup-a
sendCredToTikv: false
cleanPolicy: Delete
calcSizeLevel: disabled | full | incremental | all
resources: {}
s3:
bucket: wangle-ebs-test-us-west-2
prefix: …
```

ebs br: make snapshot size calculation optional

---

pkg/backup/backup/backup_manager.go
pkg/backup/backup/backup_manifests.go
pkg/backup/backup/backup_manifests_test.go
pkg/backup/constants/constants.go
pkg/controller/controller_utils.go

backup manifests related to tidb cluster in EBS backup
Closes #5116 
retrieve the objects of `TidbMonitor`, `TidbDashboard`, `TidbClusterAutoScaler`, `TidbInitializer`, `TidbNgMonitoring`, filter them by check if their `Cluster` is equal to `tc`. Then upload them with `tc` to the remote storage. The storage path of the manifests `{backup-path}/manifests/{namespace}/{kind}/{name}.yaml`
```release-note
Support backup manifests related to tidb cluster in EBS backup
```

br: backup manifests related to tidb cluster in EBS backup

---

charts/br-federation/values.yaml
charts/tidb-cluster/values.yaml
charts/tidb-operator/values.yaml
deploy/aliyun/variables.tf
deploy/aws/variables.tf
deploy/gcp/variables.tf
go.mod
hack/bump-version.sh
pkg/client/go.mod

bump to v1.6.0-alpha.4

---

pkg/apis/label/label.go
pkg/apis/pingcap/v1alpha1/tidbcluster.go
pkg/manager/member/tiflash_util.go

in #5075, we removed tcp and http ports for tiflash >= 7.1.0.
In this PR, add a `tidb.pingcap.com/tiflash-710-keep-ports` annotation to avoid restarting when upgrading TiDB Operator for existing TiFlash (>= 7.1.0)
- deploy operator without #5075
- create a >=v7.1.0 cluster with TiFlash
- add annotation `tidb.pingcap.com/tiflash-710-keep-ports`  in tc
- upgrade operator to this PR version
- observe no TiFlash upgrade
- remove the annotation
- observe TiFlash upgrade
```release-note
```

opt: keep ports config for TiFlash 7.1.0+ to avoid restarting

---

charts/br-federation/values.yaml
charts/tidb-cluster/values.yaml
charts/tidb-operator/values.yaml
deploy/aliyun/variables.tf
deploy/aws/variables.tf
deploy/gcp/variables.tf
go.mod
hack/bump-version.sh
pkg/client/go.mod

bump to v1.6.0-alpha.5

---

pkg/apis/pingcap/v1alpha1/component_spec.go

fix: revert 'add missing tiproxy label'

---

pkg/fedvolumebackup/backup/backup_manager.go
pkg/fedvolumebackup/restore/restore_manager.go

iam role cannot be used during backup process
allow porting labels when initiating backup/restore member
```release-note
```
Reviewers: @WangLe1321 @BornChanger

allow porting labels when initiating backup/restore member

---

docs/api-references/docs.md
docs/api-references/federation-docs.md
manifests/crd.yaml
manifests/crd/federation/v1/federation.pingcap.com_volumerestores.yaml
manifests/crd/v1/pingcap.com_restores.yaml
manifests/federation-crd.yaml
pkg/apis/federation/pingcap/v1alpha1/openapi_generated.go
pkg/apis/federation/pingcap/v1alpha1/types.go
pkg/apis/federation/pingcap/v1alpha1/volume_restore.go
pkg/apis/label/label.go
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/restore.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/backup/restore/restore_manager.go
pkg/controller/fedvolumerestore/fed_volume_restore_controller.go
pkg/controller/restore/restore_controller.go
pkg/fedvolumebackup/restore/restore_manager.go
pkg/fedvolumebackup/restore/restore_test.go

Closes #5228
Closes #5200 
Closes #5160 
Closes #5235 
```release-note
```

br: add warmup process to volume snapshot restore

---

cmd/backup-manager/app/restore/manager.go
pkg/backup/restore/restore_manager.go

Make sure time complete is valid for restore with volume-snapshot mode.
Closes #5239 
Before this change, the timeStarted and timeCompleted in restore status is the time of data restore phase. We change timeStarted to start time of volume restore phase and timeCompleted to the time of restore complete.
```release-note
```

br: modify time complete of restore status

---

charts/br-federation/values.yaml
charts/tidb-cluster/values.yaml
charts/tidb-operator/values.yaml
deploy/aliyun/variables.tf
deploy/aws/variables.tf
deploy/gcp/variables.tf
go.mod
hack/bump-version.sh
pkg/client/go.mod
pkg/manager/utils/statefulset.go
pkg/util/util.go

in #5273, we hacked the volume mode if the pod template is equal. but if the annotation of the asts is changed, we didn't hacked it. when scaling a replica with `delete-slots` used, then the remain pods restarted unexcepted.
- scaling in TiDB created with v1.5.0-alpha.8 and v1.6.0-alpha.6
```release-note
```

fix anno check and bump operator to v1.6.0-alpha.8

---

cmd/backup-manager/app/backup/backup.go
cmd/backup-manager/app/restore/restore.go
cmd/backup-manager/app/util/util.go
docs/api-references/docs.md
images/tidb-backup-manager/entrypoint.sh
manifests/crd.yaml
manifests/crd/v1/pingcap.com_backups.yaml
manifests/crd/v1/pingcap.com_backupschedules.yaml
pkg/apis/federation/pingcap/v1alpha1/types.go
pkg/apis/federation/pingcap/v1alpha1/volume_backup.go
pkg/apis/pingcap/v1alpha1/backup.go
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/backup/backup/backup_manager.go
pkg/fedvolumebackup/backup/backup_manager.go
pkg/fedvolumebackup/backup/backup_test.go

1. resume gc and pd scheduler when all the volume snapshots are created
Closes #5256
2. send `SIGTERM` to the BR process when tidb-backup-manager receives `SIGTERM`
3. read stderr async in case that the pipe of stderr is full and blocks the BR process
Closes #5281 
4. The EBS backup task may cause the import task to fail 
Closes #5282 
**data plane:**
1. check if the `backupmeta` file is existed when the backup enter `execute` phase. if it is existed, modify backup status `VolumeBackupSnapshotsCreated`
**control plane:**
2. if all the backups in data plane has status `VolumeBackupSnapshotsCreated`, modify `resumeGcSchedule` field `true` in the backup that is responsible to pause gc and pd schduler.
**data plane:**
3. if `resumeGcSchedule` field is `true`, delete the initialize pod and …

ebs br: resume gc and scheduler when volume snapshots created

---

pkg/controller/tidbcluster/pod_control.go
pkg/manager/volumes/pvc_modifier.go

Fixes a small issue that can occur when using Volume Replacement feature added in https://github.com/pingcap/tidb-operator/pull/5150
While a disk replacement is ongoing, if we apply a `tidb.pingcap.com/evict-leader="none"` annotation to the tikv at the same time. It can result in a deadlock.
* replacement feature will delete store and eventually store becomes tombstone.
* However since eviction code runs first, it will error forever saying cannot find store for this tikv, and get stuck permanently.
The place where it gets stuck is when calling `member.TiKVStoreIDFromStatus` here: https://github.com/pingcap/tidb-operator/blob/master/pkg/controller/tidbcluster/pod_control.go#L421C26-L421C47
Since store is tombstone this will fail forever, and will prevent replacement code from continuing to …

Fix issue in VolumeReplace feature that may conflict with TiKV eviction annotation.

---

pkg/manager/volumes/pvc_modifier.go

pvc_modifier keeps throwing errors even if a manual TiKV region leader eviction is requested by annotating the pod per the documentation here:
https://docs.pingcap.com/tidb-in-kubernetes/stable/maintain-a-kubernetes-node#evict-tikv-region-leader
This happens even if no volume modification is actually requested.
Do not keep checking if eviction has ended during pvc_modifier sync.
If an annotation does exist for resize, delete it and throw an error once alone to give pod_control.go a chance to stop the eviction. But do not block forever until it is removed as this may have been requested by user manually and should not throw errors.
Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release …

Do not error in pvc_modifier, when a manual TiKV eviction is requested.

---

pkg/backup/restore/restore_manager.go
pkg/backup/restore/restore_manager_test.go
pkg/backup/testutils/br.go
pkg/backup/testutils/helpers.go

Close #5287 
We will check if restore TC has the same volume number as the upstream cluster.
```release-note
```

pkg: validate volume number for ebs snapshot restore

---

cmd/http-service/Dockerfile
cmd/http-service/Makefile
cmd/http-service/README.md
cmd/http-service/deploy.yaml

support to deploy the http-serivce for Kubernetes
```release-note
```

http-service: k8s deploy support

---

examples/selfsigned-tls/tidb-cluster.yaml

fix tls example in CI
```release-note
```

ci: fix e2e-examples in GitHub Action

---

pkg/manager/member/dm_master_upgrader.go
pkg/manager/member/dm_master_upgrader_test.go
pkg/manager/member/pd_upgrader.go
pkg/manager/member/pd_upgrader_test.go
pkg/manager/member/ticdc_upgrader.go
pkg/manager/member/tidb_upgrader.go
pkg/manager/member/tiflash_upgrader.go
pkg/manager/member/tikv_upgrader.go
pkg/manager/member/tiproxy_upgrader.go

Fix operator so it properly rollbacks pods when a partial upgrade is rolled back.
Issue described in https://github.com/pingcap/tidb-operator/issues/5204
(Previous PR attempt: https://github.com/pingcap/tidb-operator/pull/5291)
Remove the early return when updateRevision and currentRevision match.
This was purely for optimization, and instead now let the operator check each individual pod matches
before confirming that the Upgrade() function can return as completed.
```release-note
Fix an issue that prevents rollback of partially in-flight updates to pods
```

Remove early return during upgrade that might block rollbacks

---

cmd/http-service/server/cluster.go

```
[2023/10/19 10:17:14.916 +00:00] [WARN] [cluster.go:525] ["TidbMonitor not found"] [request=GetCluster] [k8sID=] [clusterID=tidb-clsuter-002] [error="[tidbmonitors.pingcap.com](http://tidbmonitors.pingcap.com/) \"tidb-monitor\" not found"]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1208754]
goroutine 123 [running]:
[github.com/pingcap/tidb-operator/http-service/server.convertToClusterInfo](http://github.com/pingcap/tidb-operator/http-service/server.convertToClusterInfo)(0x1a41e40?, {0x1a6db78, 0x4000221080}, 0x4000d4c000, 0x4000e93b00)
/home/sean/code/src/[github.com/pingcap/tidb-operator/cmd/http-service/server/cluster.go:669](http://github.com/pingcap/tidb-operator/cmd/http-service/server/clus …
```

http-service: fix get prometheus config panic

---

cmd/backup-manager/app/cmd/restore.go
cmd/backup-manager/app/restore/restore.go
cmd/backup-manager/app/util/util.go
images/ebs-warmup/warmup-steps.sh
manifests/crd.yaml
manifests/federation-crd.yaml
pkg/backup/restore/restore_manager.go
pkg/backup/restore/restore_manager_test.go

Close #5300 
Turn on FSR warmup option, and run EBS snapshot restore. Verify that tikv volumes are warmed up by BR kernel side after EBS volumes are created.
```release-note
```

Fsr warmup support

---

cmd/backup-manager/app/cmd/restore.go
cmd/backup-manager/app/restore/restore.go
cmd/backup-manager/app/util/util.go
images/ebs-warmup/warmup-steps.sh
manifests/crd.yaml
manifests/crd_v1beta1.yaml
manifests/federation-crd.yaml
manifests/federation-crd_v1beta1.yaml
pkg/backup/restore/restore_manager.go
pkg/backup/restore/restore_manager_test.go

Close #5300 
A cherry-pick of https://github.com/pingcap/tidb-operator/pull/5338
```release-note
```

Fsr warmup support (#5338)

---

cmd/http-service/server/cluster.go

delete all PVCs when call delete TidbCluster api
```release-note
```

delete all pvc in tidbcluster ns

---

pkg/manager/volumes/pvc_replacer.go

Fix an issue with Volume Replacement feature that can cause it to be blocked when user requests a metadata / annotation change, clubbed with a disk replacement.
Remove check in pvc_replacer that checks if sts is upgrading before recreating sts.
If a disk change is clubbed with pod spec changes (but not metadata changes), it gets reverted here: https://github.com/pingcap/tidb-operator/blob/6de4871569b4e556436b35ba87cad753c3c72b62/pkg/manager/member/tikv_member_manager.go#L276
So the statefulset would not show any changes (and would not fail upgrade check, so issue doesn't happen).
However metadata changes like (annotation change), do not get reverted, and will be applied to the sts, but since volume replace marks the update strategy to be OnDelete : …

Fix issue in VolumeReplace feature that may block replacement when combined with an annotation change

---

pkg/controller/pod_control.go
pkg/controller/tidbcluster/pod_control.go
pkg/controller/tidbcluster/tidb_cluster_control.go
pkg/manager/member/tikv_scaler.go
pkg/manager/member/tikv_scaler_test.go

Fix an issue Introduced in https://github.com/pingcap/tidb-operator/pull/5150 by running metaManager.Sync() once before the member syncs status.
Specifically in rare cases (AFAIK only when using volume replace) there can be a race condition.
`controller/pod_control.go` can run right after a pd member is deleted + pod is deleted + new pod comes back all before pd member manager has had a chance to run it's `syncTidbClusterStatus` function
This leaves `tc.Status.PD.Members` in an old state without removing the member that was deleted.
This can cause controller/pod_control.go to run with an out of date stale tc.Status.PD.Members and use the wrong member id to apply as pod label for PD.
Consequently causing more bugs when that pd pod is restarted (leader eviction missed), or disk replaced …

Fix issue when using VolumeReplace feature that may mark wrong PD member ID labels.

---

pkg/manager/volumes/vol_compare_utils.go

Tiproxy needs no volume, remove warning:
```
Reconciliation is blocked due to : unsupported change in number of volumes 0 -> 1 for cluster tidb1379661944646195934/db:tiproxy, requeuing
```
```release-note
```

tiproxy: no need for volume

---

charts/br-federation/templates/controller-manager-deployment.yaml
charts/br-federation/templates/controller-manager-rbac.yaml
charts/br-federation/values.yaml
cmd/br-federation-manager/main.go
pkg/controller/br_fed_config.go
pkg/controller/br_fed_dependences.go

Our infra setup deploys a given TiDB cluster across multiple k8s clusters, so we use federation to manage br resources across these k8s clusters. Additionally, we deploy multiple of these TiDB clusters in a single k8s cluster across different namespaces -- for ease of deployment/upgrade and least-access, we want to deploy the br-federation-manager control plane independently for each of these TiDB clusters to manage volume backups/restores in separate namespaces.
This PR applies two sets of changes that enable br-federation-manager (bfm) to run in a namespace-scoped way.
1. Support `clusterScoped` in helm charts. When `clusterScoped=false`, charts generate manifests for `Role`s and `RoleBinding`s in the specified namespace rather than `ClusterRole`s and `ClusterRoleBinding`s.
2. Support …

Support br-federation-manager managing resources in specific-namespace tidb clusters

---

images/ebs-warmup/warmup-steps.sh
images/tidb-backup-manager/e2e-entrypoint.sh
images/tidb-backup-manager/entrypoint.sh

Closes #5430
Create a path when the main container exits, the sidecar can check the path once it shows up it can exit. 
```release-note
```

Add trap to create a path when BR container exit

---

charts/tidb-operator/templates/advanced-statefulset-deployment.yaml
charts/tidb-operator/templates/advanced-statefulset-rbac.yaml
charts/tidb-operator/values.yaml

ref:
- https://github.com/kubernetes/kubernetes/pull/106852
- https://github.com/pingcap/advanced-statefulset/pull/104
see log of advanced-statefulset deploy with this chart `--set advancedStatefulset.resourceLock=leases`
```
I1207 08:24:39.220976       1 flags.go:33] FLAG: --add-dir-header="false"
I1207 08:24:39.221003       1 flags.go:33] FLAG: --alsologtostderr="false"
I1207 08:24:39.221007       1 flags.go:33] FLAG: --controller-start-interval="0s"
I1207 08:24:39.221012       1 flags.go:33] FLAG: --help="false"
I1207 08:24:39.221016       1 flags.go:33] FLAG: --kube-api-burst="30"
I1207 08:24:39.221020       1 flags.go:33] FLAG: --kube-api-content-type="application/vnd.kubernetes.protobuf"
I1207 08:24:39.221024       1 flags.go:33] FLAG: --kube-api-qps="20"
I1207 08:24:39.221028 …
```

chart: set leader-elect-resource-lock when deploying asts controller

---

charts/tidb-operator/values.yaml
tests/pkg/fixture/fixture.go

for k8s > v1.19, we often don't need to deploy tidb-scheduler. ref https://docs.pingcap.com/tidb-in-kubernetes/stable/tidb-scheduler
and some users became confused when deploying tidb-scheduler (e.g #5462), so we disable it by default from v1.6.
```release-note
```

chart: do not deploy tidb-scheduler by default

---

pkg/backup/snapshotter/snapshotter.go
pkg/backup/snapshotter/snapshotter_test.go

Fix the bug that if there are redundant pvc or pv of backup tidb cluster, the backup can succeed but the restore can fail.
The redundant pvc or pv means:
- redundant pvc: there are labels in the pvc indicating that the pvc belongs to the backup tidb cluster but there is no tikv pod using it
- redundant pv: there are labels in the pv indicating that the pv belongs to the backup tidb cluster but there is no tikv pvc using it.
Closes #5459 
At first we retrieve all the pvcs and pvs that may belong to the backup tidb cluster. Then we filter pvc by the tikv pod and filter pv by the pvc.
```release-note
```

br: fix redundant pvc and pv in metadata

---

pkg/fedvolumebackup/backup/backup_manager.go

Make sure the VolumeBackup is failed after backup initialize failed.
Closes #5499
```release-note
```

br: set volume backup failed if one data plane failed

---

pkg/fips/fips.go
pkg/version/version.go

Adjust version suffix, so that it does not display double fips suffixes (`v1.5.1-fips-fips`) for tags end with `fips`.
Ref #5396
```
➜ git tag v1.5.1-fips                             
➜ make                                            
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags '-X 'github.com/pingcap/tidb-operator/pkg/version.buildDate=2024-01-12T06:57:32Z' -X 'github.com/pingcap/tidb-operator/pkg/version.gitCommit=ea9d440b225831e85d3eababbb1a69df868ceb95' -X 'github.com/pingcap/tidb-operator/pkg/version.gitTreeState=clean' -X 'github.com/pingcap/tidb-operator/pkg/version.gitVersion=v1.5.1-fips'' -o images/tidb-operator/bin/amd64/tidb-controller-manager cmd/controller-manager/main.go
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags '-X …
```

fips: adjust version suffix (#5512)

---

pkg/fips/fips.go
pkg/version/version.go

Adjust version suffix, so that it does not display double fips suffixes (`v1.5.1-fips-fips`) for tags end with `fips`.
Ref #5396
```
➜ git tag v1.5.1-fips                             
➜ make                                            
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags '-X 'github.com/pingcap/tidb-operator/pkg/version.buildDate=2024-01-12T06:57:32Z' -X 'github.com/pingcap/tidb-operator/pkg/version.gitCommit=ea9d440b225831e85d3eababbb1a69df868ceb95' -X 'github.com/pingcap/tidb-operator/pkg/version.gitTreeState=clean' -X 'github.com/pingcap/tidb-operator/pkg/version.gitVersion=v1.5.1-fips'' -o images/tidb-operator/bin/amd64/tidb-controller-manager cmd/controller-manager/main.go
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags '-X …
```

fips: adjust version suffix

---

cmd/backup-manager/app/clean/clean.go
docs/api-references/docs.md
docs/api-references/federation-docs.md
go.mod
manifests/crd.yaml
manifests/crd/federation/v1/federation.pingcap.com_volumebackups.yaml
manifests/crd/federation/v1/federation.pingcap.com_volumebackupschedules.yaml
manifests/crd/v1/pingcap.com_backups.yaml
manifests/crd/v1/pingcap.com_backupschedules.yaml
manifests/federation-crd.yaml
pkg/apis/federation/pingcap/v1alpha1/openapi_generated.go
pkg/apis/federation/pingcap/v1alpha1/types.go
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/backup/snapshotter/snapshotter_aws.go
pkg/backup/util/aws_ebs.go
pkg/fedvolumebackup/backup/backup_manager.go
pkg/fedvolumebackup/backupschedule/backup_schedule_manager.go

Closes #5493 
Closes #5503
1. Provide backoff for snapshots deletion in data plane cleanup and provide a simple local flow control on snapshot deletion at no more than one per second. What's more a new option is provided to backup schedule CRD as `spec.template.snapshotsDeleteRatio`. It controls the expected ratio for snapshots deletion at individual data plane.
2. Let volumebackup succeed in the scenario where meta file is not created in some data plane.
When use the default ratio (1.0)
When set to 0.5
```release-note
```

ebs br: backoff support for snapshots deletion

---

cmd/backup-manager/app/clean/clean.go
pkg/backup/restore/restore_manager.go
pkg/backup/snapshotter/snapshotter.go
pkg/backup/snapshotter/snapshotter_aws.go
pkg/backup/snapshotter/snapshotter_test.go

Closes #5505 
1. Add tags to valid PVs in the cluster
2. Add tag of name of namespace
```release-note
```

Fixing volume tagging

---

pkg/fedvolumebackup/backupschedule/backup_schedule_manager.go
pkg/fedvolumebackup/backupschedule/backup_schedule_manager_test.go

Closes #5517 
When GC expired volumebackup, we need to use creationtimestamp instead of commitTS, since commitTS is empty for failed backup.
```release-note
```

Use CreationTimestamp of volumebackup for gc check

---

pkg/backup/snapshotter/snapshotter_aws.go

Closes #5506 
Add pvc name as tag of restored volume
```release-note
```

ebs: adjust volume tagging

---

docs/api-references/docs.md
examples/basic/pd-micro-service-cluster.yaml
manifests/crd.yaml
manifests/crd/v1/pingcap.com_tidbclusters.yaml
pkg/apis/pingcap/v1alpha1/component_status.go
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/apis/pingcap/v1alpha1/validation/validation.go
pkg/apis/pingcap/v1alpha1/validation/validation_test.go
pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
pkg/controller/tidbcluster/tidb_cluster_controller.go
pkg/manager/member/constants/constants.go
pkg/manager/member/pd_ms_member_manager.go
pkg/manager/member/pd_ms_member_manager_test.go
pkg/manager/member/pvc_resizer.go
pkg/manager/member/startscript/v1/render_script.go
pkg/manager/member/startscript/v1/template.go
pkg/manager/member/startscript/v2/pd_start_script.go
pkg/manager/volumes/vol_compare_utils.go
pkg/util/utils_test.go

ref https://github.com/tikv/pd/issues/7519
yaml like
```
pdms:
- name: "tso"
version: nightly
replicas: 2
requests:
storage: 1Gi
storageVolumes:
- name: log
storageClassName: standard
storageSize: 1Gi
mountPath: /var/lib/pd/tso
config:
log:
file: 
filename: "/var/lib/pd/tso/tso.log"
- name: "scheduling"
version: nightly
replicas: 1
```
will get 
```
$ kubectl describe pod basic-pdms-tso-0 -n tidb
...
Volumes:
pdms-tso:
Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
ClaimName:  pdms-tso-basic-pdms-tso-0
ReadOnly:   false
pdms-tso-log:
Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
ClaimName:  pdms-tso-log-basic-pdms-tso-0
ReadOnly:   false
...
``` …

pdms: support pv for log

---

pkg/manager/member/pd_ms_member_manager.go
pkg/pdapi/pd_control.go

ref https://github.com/tikv/pd/issues/7519
need to update pd-server.json
```bash
$ cat pd-server.json
{
"CN": "TiDB",
"hosts": [
"127.0.0.1",
"::1",
"basic-pd",
"basic-pd.pingcap",
"basic-pd.pingcap.svc",
"basic-pd-peer",
"basic-pd-peer.pingcap",
"basic-pd-peer.pingcap.svc",
"*.basic-pd-peer",
"*.basic-pd-peer.pingcap",
"*.basic-pd-peer.pingcap.svc",
"basic-pdms-scheduling",
"basic-pdms-scheduling.pingcap",
"basic-pdms-scheduling.pingcap.svc",
"basic-pdms-scheduling-peer",
"basic-pdms-scheduling-peer.pingcap",
"basic-pdms-scheduling-peer.pingcap.svc",
"*.basic-pdms-scheduling-peer",
"*.basic-pdms-scheduling-peer.pingcap",
"*.basic-pdms-scheduling-peer.pingcap.svc",
"basic-pdms-tso",
"basic-pdms-tso.pingcap",
"basic-pdms-tso.pingcap.svc",
"basic-pdms-tso-peer", …
```

pdms: make pdms tls reusing pd tls

---

pkg/manager/member/pd_ms_member_manager.go
pkg/manager/member/pd_ms_member_manager_test.go

Ref https://github.com/tikv/pd/issues/7519
fix config panic when enable tls
```release-note
```

pdms: fix tls config is nil

---

cmd/backup-manager/app/clean/manager.go
pkg/apis/federation/pingcap/v1alpha1/types.go
pkg/apis/federation/pingcap/v1alpha1/volume_backup.go
pkg/apis/pingcap/v1alpha1/backup.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/controller/fedvolumebackup/fed_volume_backup_control.go
pkg/fedmetrics/metrics.go
pkg/fedvolumebackup/backup/backup_manager.go
pkg/metrics/brfederation.go

Add metrics for br federation manager
Closes #5533
Add metrics about volume backup status, volume backup total time, volume backup total size, volume backup cleanup status and volume backup cleanup total time.
For volume backup cleanup, there is no status to indicate cleanup failed. So I also add a `CleanFailed` status to backup and volume backup. If backup cleanup is failed, the backup CR will become `CleanFailed` status. If one of backup cleanup in data plane is failed, the volume backup CR will become `CleanFailed` status.
```release-note
```

br: add metrics for volume backup

---

pkg/pdapi/pdapi.go

ref https://github.com/tikv/pd/pull/7819
```release-note
```

pdms: change get ms members return value

---

pkg/manager/member/tikv_upgrader.go

Closes #5501 
Check whether the last TiKV pod is available before end evict leader.
1. Modify the basic tidb-cluster, set `replicas` for TiKV to `2`, and add annotation `tidb.pingcap.com/tikv-min-ready-seconds: "300"`.
2. Deploy the operator and the modified basic tidb-cluster.
3. Once all things ready, trigger an upgrade for TiKV.
```
I0207 05:57:42.942954       1 tidb_cluster_controller.go:142] TidbCluster: default/basic, still need sync: tidbcluster: [default/basic]'s upgraded tikv pod: [basic-tikv-1] is not available, last transition time is 2024-02-07 05:57:42 +0000 UTC, requeuing
...
I0207 06:02:38.460404       1 tidb_cluster_controller.go:142] TidbCluster: default/basic, still need sync: tidbcluster: [default/basic]'s upgraded tikv pod: [basic-tikv-1] is not available, last …
```

fix: minreadyseconds for last TiKV

---

pkg/manager/member/tiproxy_member_manager.go

Before, tiproxy will use TLS certs from TiDB to serve both SQL and HTTP ports. When only `tlsCluster` is enabled, there will be errors(others will try to use HTTPS to access tiproxy).
Since now we have dedicated `server-http-tls` options, we can now specify certs for tiproxy when only `tlsCluster` is enabled.
For backward compatibility, it is also enabled on only `tlsTiDB`, which is wrong. But it is kept for now.
```release-note
```

tiproxy: fix http tls when only tls cluster is enabled

---

pkg/manager/member/pd_ms_member_manager.go
pkg/manager/member/pd_ms_member_manager_test.go
pkg/manager/member/pd_ms_scaler.go
pkg/manager/member/pd_ms_scaler_test.go
pkg/manager/member/pd_ms_upgrader.go
pkg/manager/member/pd_ms_upgrader_test.go
pkg/manager/member/pd_upgrader_test.go

Fix the bug that modifing tso config did not take effect
Closes #5553, related https://github.com/tikv/pd/issues/7519
```release-note
```

pdms: remove shutdown component and add test for scaler&upgrader

---

pkg/apis/label/label.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/controller/controller_utils.go
pkg/manager/member/pd_ms_member_manager_test.go
pkg/manager/volumes/selector_test.go
pkg/monitor/monitor/template.go
pkg/monitor/monitor/template_test.go
pkg/pdapi/pd_control.go

ref https://github.com/tikv/pd/issues/7519
rename `pdms-tso` to `tso`
before 
after
```release-note
```

pdms: rename pdms-`service` to `service`

---

pkg/apis/label/label.go
pkg/apis/pingcap/v1alpha1/tidbcluster.go
pkg/manager/member/startscript/v1/render_script.go
pkg/manager/member/startscript/v1/template.go
pkg/manager/member/startscript/v1/template_test.go
pkg/manager/member/startscript/v2/tiflash_start_script.go
pkg/manager/member/startscript/v2/tiflash_start_script_test.go
pkg/manager/member/tiflash_member_manager.go
pkg/manager/member/tiflash_util.go
pkg/manager/member/tiflash_util_test.go
tests/e2e/tidbcluster/tidbcluster.go

Add an annotation `tiflash.tidb.pingcap.com/mount-cm-in-tiflash-container` to tc.spec.tiflash.annotations to supports run tiflash pod without init container and directly mount ConfigMap in tiflash container.  This change enable tiflash supports config hot-reload when the tc.spec.configUpdateStrategy is set to InPlace.
When this annotation is annotated, the tiflash container will directly mount config ConfigMap and use new start script to launch tiflash without the initContainer did ever that use sed to modify ConfigMap and then generate a new config files into /data0 directory. 
* create a TC with tiflash enabled
* edit TC to add `tiflash.tidb.pingcap.com/mount-cm-in-tiflash-container: "true"` into tc.spec.tiflash.annotations
* old tiflash pod will be terminated and new tiflash pod …

support run tiflash pod with ConfigMap mounted in tiflash container

---

pkg/apis/pingcap/v1alpha1/validation/validation.go
pkg/apis/pingcap/v1alpha1/validation/validation_test.go
pkg/backup/backup/backup_tracker.go
pkg/controller/pd_control.go
pkg/controller/tidb_control.go
pkg/controller/tidbcluster/pod_control.go
pkg/discovery/discovery.go
pkg/manager/member/pump_member_manager.go
pkg/manager/member/startscript/v2/ticdc_start_script.go
pkg/manager/member/startscript/v2/ticdc_start_script_test.go
pkg/manager/member/tidbcluster_status_manager.go
pkg/manager/member/tiflash_util.go
pkg/manager/member/tiflash_util_test.go
pkg/manager/member/tikv_upgrader.go
pkg/monitor/monitor/monitor_manager.go
pkg/pdapi/pd_control.go
pkg/tikvapi/tikv_control.go

ref #5375
before this PR, TiDB Operator may not append the cluster domain (for local K8s) in the URL when creating clients.
this often works well, but if TLS enabled and the cert can only be issued for the cluster domain, the clients may not work as #5375
- append cluster domain for PD/TiKV/TiDB/etcd clients
- add preferred PD address support for TiFlash/TiCDC, which introduced in #5400
1. modify CoreDNS config with `mydomain.internal` cluster domain support
2. add certs for components
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
name: basic-pd-cluster-secret
namespace: tls
spec:
secretName: basic-pd-cluster-secret
duration: 8760h # 365d
renewBefore: 360h # 15d
subject:
organizations:
- PingCAP
commonName: "TiDB"
usages:
- server auth
- client auth
dnsNames:
- …
```

fix: append cluster domain for PD/TiKV/TiDB/etcd URL; prefer PD address for TiFlash/TiCDC

---

examples/basic/pd-micro-service-cluster.yaml
pkg/controller/tidbcluster/tidb_cluster_control.go
pkg/manager/member/pd_member_manager.go
pkg/manager/member/pd_ms_member_manager.go
pkg/manager/member/startscript/v1/render_script.go
pkg/manager/member/startscript/v2/pd_start_script.go
pkg/manager/member/tikv_member_manager.go
tests/actions.go
tests/e2e/tidbcluster/tidbcluster.go
tests/e2e/util/image/image.go
tests/pkg/fixture/fixture.go

Ref https://github.com/tikv/pd/issues/7519
run e2e in local machine
test log in ci
https://ci.pingcap.net/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/5325/pipeline/65
```release-note
```

pdms: randomly run pdms in e2e test

---

pkg/backup/restore/restore_manager.go
pkg/backup/restore/restore_manager_test.go

Currently restore only checks if all warmup jobs completed (success or fail) before continuing w/ later steps of restore. Instead, if any warmup jobs fail, we should fail the restore.
Observed behavior:
* Failed warmup job conditions:
```yaml
...
conditions:
- lastProbeTime: "2024-03-10T21:05:24Z"
lastTransitionTime: "2024-03-10T21:05:24Z"
message: Job has reached the specified backoff limit
reason: BackoffLimitExceeded
status: "True"
type: Failed
failed: 5
ready: 0
startTime: "2024-03-10T20:53:09Z"
uncountedTerminatedPods: {}
```
* Results in `WarmUpComplete` in restore
```yaml
commitTs: "448239596192667254"
conditions:
- lastTransitionTime: "2024-03-10T20:51:49Z"
status: "True"
type: Scheduled
- lastTransitionTime: "2024-03-10T20:51:57Z"
status: "True"
type: Running
- …
```

Fail restore if any warmup job failed for volume-snapshot restores

---

docs/api-references/docs.md
manifests/crd.yaml
manifests/crd/v1/pingcap.com_restores.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/tidbcluster.go
pkg/apis/pingcap/v1alpha1/tidbcluster_test.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/backup/restore/restore_manager.go

This PR provides the resilience to a single TiKV crash due to wal corruption at restore
Add a new attribute `spec.tolerateSingleTiKVOutage` to restore CR. When it's set to true, restore to the tc can tolerate a single TiKV outage due to wal log corruption issue.
```release-note
```

ebs br: add resilience to single TiKV crash

---

manifests/crd.yaml
manifests/federation-crd.yaml
pkg/apis/pingcap/v1alpha1/types.go
pkg/backup/restore/restore_manager.go
pkg/fedvolumebackup/restore/restore_manager.go
pkg/fedvolumebackup/restore/restore_test.go

This PR provide restore capability to check wal corruption only during restore by specifying the warmup strategy of volumerestore to `check-wal-only`
cc #5582
```release-note
```

ebs br: add check wal warmup option

---

pkg/controller/backup/backup_controller.go

ref https://github.com/pingcap/tidb-operator/issues/5584
Fix tidb operator panic becuase of empty backup.Status.BackoffRetryStatus in multiple operators' case.
```release-note
```

fix: avoid tidb operator panic becuase of empty backup.Status.BackoffRetryStatus

---

images/ebs-warmup/warmup-steps.sh

During EBS snapshot warmup, only check WALs up to the last one for corruption. We expect some corruptions in the last WAL due to race between fsync and EBS snapshot, and we can recover from these scenarios.
Also updates WAL log file pattern since logs can contain variable length log nos.
Executed warmup w/ these changes and observe warmup progress normally w/out checking the last WAL
```release-note
```

Skip corruption check on last WAL

---

images/ebs-warmup/warmup-steps.sh

Add sleep before exiting the warmup container. This is needed to give time to sidecar containers to upload logs/metrics before warmup completes.
Ran EBS snapshot restore w/ updated warmup pod and observe restore functions as expected.
```release-note
```

Add 10s sleep prior to warmup exit for sidecars to upload logs

---

pkg/manager/member/startscript/v2/tiproxy_start_script.go
pkg/manager/member/startscript/v2/tiproxy_start_script_test.go
pkg/manager/member/tiproxy_member_manager.go

Fix the bug that TiDB connects to TiProxy with IP but the SAN in TiProxy certificate is DNS.
Closes https://github.com/pingcap/tiproxy/issues/494
Add an `advertise-addr` arg to TiProxy so that TiDB connects to TiProxy by DNS.
In the TiProxy container logs:
```
starting: tiproxy --config=/etc/proxy/proxy.toml --advertise-addr=basic-tiproxy-0.basic-tiproxy-peer.tidb-cluster.svc
```
Query the TiProxy config:
```
curl http://127.1:3080/api/admin/config/ | grep advertise
advertise-addr = 'basic-tiproxy-0.basic-tiproxy-peer.tidb-cluster.svc'
```
```release-note
- Pass argument `advertise-addr` to TiProxy binary.
```

Add `advertise-addr` arg to tiproxy start script

---

pkg/apis/pingcap/v1alpha1/tidbcluster.go
pkg/manager/member/tikv_upgrader.go
tests/e2e/tidbcluster/across-kubernetes.go

close #5614
In some cases when upgrading TiKV, the evict-leader-scheduler may not be added or missing in PD, but the `evictLeaderBeginTime` annotation of the TiKV pod is added. As TiDB Operator will not call PD API to add evict-leader-scheduler again, then the upgrade operation is blocked.
In this PR, we check whether the evict-leader-scheduler exists if a timeout (10m) is reached, and try to add evict-leader-again if it's missing.
1. hack TiDB Operator code to remove the `controller.GetPDClient(u.deps.PDControl, tc).BeginEvictLeader(storeID)` call in `beginEvictLeader`
2. upgrade TiKV
3. check whether the upgrade operation is blocked (`wait for evictition to complete`), and check the `evictLeaderBeginTime` annotation existing
4. revert the hack in step.1 and re-deploy TiDB-Operator
5. …

retry evict leader when upgrading TiKV if needed

---

pkg/backup/snapshotter/snapshotter_aws.go

""kubernetes.io/created-for/pv/name" tag is a common ebs tag added by CSI driver, current restore EBS vol does not have it 
. Added in this PR. 
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/pkg/driver/controller_test.go#L1551
```release-note
```

[BR] add pv name in restore EBS vol

---

docs/api-references/docs.md
manifests/crd.yaml
manifests/crd/v1/pingcap.com_tidbclusters.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
pkg/manager/member/startscript/v1/render_script.go
pkg/manager/member/startscript/v1/template.go
pkg/manager/member/startscript/v1/template_test.go

close #5625
- create a new TidbCluster
1. apply a TidbCluster CR with `.spec.tidb.arguments` set
2. check the generate ConfigMap and the startup log of TiDB to check the extral arguments is used
- update arguments for a existing TidbCluster
1. update the TidbCluster CR with `.spec.tidb.arguments` set
2. check a new ConfigMap is generated and TiDB Pods restart with the new config
```release-note
support setting extra command line arguments for TiDB
```

support setting extra command line arguments for TiDB

---

images/ebs-warmup/warmup-steps.sh
pkg/backup/restore/restore_manager.go
pkg/backup/restore/restore_manager_test.go

Currently warmup script exits w/ error when it encounters corruption. Similar to #5621, this behavior makes sense for checking viability of backups, but conflicts w/ desire to perform a full restore and recover.
When we perform a full restore, if restore encounters corruption, warmup will fail and will cancel the actual warmup of the volumes. Desired behavior is to log the corruption but continue the warmup operation, so that, when complete, if there is only a single corrupt TiKV, we can attempt to recover using functionality added in #5585.
Change updates warmup script to only exit/cancel warmup when encountering corruption when explicitly enabled. This is only enabled for `check-wal-only` strategy. Otherwise, we only log the corruption but continue with normal warmup.
Please refer to …

Make warmup failure/skip on corruption configurable

---

pkg/backup/restore/restore_manager.go
pkg/backup/restore/restore_manager_test.go

#5569 updates volume-snapshot restore process to fail the entire restore if any warmup job failed. We use this to quickly check the viability of restores and terminate restore processing early if a corruption is detected.
#5572 updates volume-snapshot restore process to enable recovery from a corruption in a single TiKV through manual cluster operations. We use this in a full restore in case we encounter a corruption during this process.
These features are in conflict w/ each other. If we want to perform a full restore and use single TiKV recovery in the event of corruption, we cannot fail the restore during warmup and instead need to complete warmup stage and progress to restarting TiKVs. If we only want to check the viability of a restore, we are ok w/ failing the restore and not …

Fail restore if warmup fails only during `check-wal-only` strategy

---

pkg/apis/pingcap/v1alpha1/restore.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/backup/restore/restore_manager.go
pkg/backup/snapshotter/snapshotter.go
pkg/backup/snapshotter/snapshotter_aws.go
pkg/backup/snapshotter/snapshotter_gcp.go
pkg/backup/snapshotter/snapshotter_none.go
pkg/backup/util/aws_ebs.go
pkg/controller/restore/restore_controller.go

Add cleaning volumes function when restore volume failed. Then we can avoid volume leak
Closes #5638
manual test steps:
1. create a cluster
2. create a volume backup
3. create a restore cluster
4. create a volume restore using the volume backup in step 2. in this step, restore volume is successful and the tikv pods are started
5. edit the restore CR, modify its status from `VolumeComplete` to `Failed` to mock restore volume failed scenario
6. edit the tc CR, remove the annotation `tidb.pingcap.com/tikv-volumes-ready` to block tikv creation, then delete the tikv statefulset to detach the EBS volumes
7. wait for the volumes detached and deleted by tidb-operator
Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md …

br: clean volumes when restore volume failed

---

pkg/apis/label/label.go
pkg/manager/utils/statefulset.go

Currently, we have no ability to check whether the STS is already updated with the latest TC.spec.{component}. But for some scenarios, we want to know whether is a STS successfully updated. Therefore, this PR introduces a new annotation `tidb.pingcap.com/owner-generation` to store the generation of its owner into STS's annotation.
* create a cluster with old tidb-operator
* deploy new tidb-operator, components of this cluster shouldn't restart and all STSs shouldn't be annotated with that annotation
* scale tidb out, that annotation should be annotated into STS db-tidb and the old tidb pod shouldn't be restarted.
* scale tidb in, that annotation should be annotated into STS db-tidb and the another one tidb pod shouldn't be restarted.
```bash
k get tc -oyaml | grep generation
generation: …
```

Record owner's generation into STS's annotation

---

pkg/apis/label/label.go
pkg/backup/backupschedule/backup_schedule_manager.go
pkg/backup/backupschedule/backup_schedule_manager_test.go
pkg/fedvolumebackup/backupschedule/backup_schedule_manager.go
pkg/fedvolumebackup/backupschedule/backup_schedule_manager_test.go

Close #5632 
In order to support multiple active schedulers, we need to co-ordinate the scheduling to make sure there is only one active backup within the same namespace.
A new label is introduced in this PR, whose key is `tidb.pingcap.com/backup-schedule-group`.  Backup schedule CRD can be assigned such a label, and the value is not empty,  if it's in a multiple schedule group, otherwise, the schedule is independent.  At backup schedule check time, all schedules in the same group need to be checked.
Here is a sample volume backup schedule CRD with the label specified `tidb.pingcap.com/backup-schedule-group: ebs-backup-schedule-group1`.
``` shell
apiVersion: federation.pingcap.com/v1alpha1
kind: VolumeBackupSchedule
metadata:
name: sche-rolling
namespace: bc-fed-admin
labels: …
```

backup: support multiple schedules

---

cmd/backup-manager/app/restore/restore.go
docs/api-references/docs.md
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/backup/util/util.go

This PR is addressing the issue [issue-5657](https://github.com/pingcap/tidb-operator/issues/5657)
Adding support for the **logRestoreStartTs** option in the PITR restore spec.
With this update, the Point-in-Time Recovery (PITR) restore mode allows users to apply PITR logs within a specified time range. Specifically, users can define the **start** and **end** timestamps using the **logRestoreStartTs**(start timestamp) and **pitrRestoredTs**(end timestamp) options in the restore spec, respectively. This enhancement enables more precise control over the restoration process, allowing users to restore data to an exact point in time by specifying the interval of PITR logs to be applied.
After this change the user can use a combination of **pitrFullBackupStorageProvider** and …

Adding support for logRestoreStartTs option in PITR restore spec

---

docs/api-references/docs.md
manifests/crd.yaml
manifests/crd/v1/pingcap.com_tidbclusters.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/tidbcluster.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
pkg/controller/tidbcluster/tidb_cluster_control.go
pkg/manager/volumes/pvc_replacer.go

https://github.com/pingcap/tidb-operator/blob/9ef26f88bf75338cef427b44aa6303237ddcdbd6/pkg/features/features.go#L55C9-L57C44
PVC replace feature is currently enabled / disabled at tidb-operator level, which might not be comforting situation as a single tidb-operator can be handling multiple tidbclusters, so this PR enables tidbcluster level flag to enable / disable this feature. This is similar to another similar feature `enablePVReclaim` flag
Added a new flag in CRD `enablePVCReplace` with a false as default value. If this flag is enabled then only tidb-operator would perform the PVC replacement process.
```release-note …
```

tc level flag to enablePVCReplace feature

---

docs/api-references/docs.md
manifests/crd.yaml
manifests/crd/v1/pingcap.com_tidbclusters.yaml
pkg/apis/pingcap/v1alpha1/defaulting/tidbcluster.go
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/tidbcluster.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
pkg/manager/member/tikv_member_manager_test.go

Currently the VolumeReplace feature assumes a default spare replica of 1 for PD & TiKV.
Sometimes it is useful to change this number. Setting a larger spare replica number helps for faster tikv region transfer
In multi-az setups, it is possible to get zone skewness with only a single replica, which will cause issues during scale down of spare replica.
Example multi-az senario:
3 zones , 6 replicas, initial zones per replica: 1,2,3,1,2,3
After adding 1 spare replica: 1,2,3,1,2,3,1
Now replace will start replacing from start, but now the new disks can get different zones, example:
after replacing first disk it could now become 2,2,3,1,2,3,1
After this if we scale down the spare replica (last one), it will become 2,2,3,1,2,3 which is zone-skewed and can be blocked depending on configured …

Add support to customize spare replicas during VolumeReplace

---

pkg/manager/tidbdashboard/manager.go
pkg/manager/tidbdashboard/manager_test.go

Currently, tidb-dashboard ignores the PortName specified in the service configuration and always uses the default `tidb-dashboard`. 
If a PortName is specified in the service configuration, tidb-dashboard uses that port name instead. If no PortName is specified, it uses the default `tidb-dashboard`. 
```release-note
NONE
```

[tidb-dashboard] use portName for service

---

docs/CONTRIBUTING.md
manifests/crd.yaml
manifests/crd/v1/pingcap.com_tidbclusters.yaml
pkg/apis/pingcap/v1alpha1/component_status.go
pkg/apis/pingcap/v1alpha1/tidbcluster.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/controller/tidbcluster/pod_control.go
pkg/controller/tidbcluster/pod_control_test.go
pkg/controller/tidbcluster/tidb_cluster_controller_test.go
pkg/manager/member/utils.go

Adds volume replace support for TiFlash component
There is an existing reconciliation for replacing PVC of TiDB components. However, TiFlash component reconciliation was not written. This PR adds support for TiFlash volume replace as well. It works almost similar to TiKV except for leader eviction which is not required for TiFlash as all the regions are learner regions only.
```release-note
Volume Replace is not supported for TiFlash component
```

Add pvc volume replace for TiFlash component

---

ci/e2e_eks.groovy
ci/e2e_gke.groovy
ci/e2e_kind.groovy
ci/pull_e2e_kind.groovy
ci/pull_e2e_release.groovy
ci/vm.groovy

This is a part of #5683.
We will bump CI first, and then update code until CD bumpped
```release-note
```

CI: bump runner Golang to v1.22.5

---

ci/pull_e2e_kind.groovy

Go 1.22 may not work before this PR in CI
```release-note
```

fix CI: unset GOSUMDB

---

pkg/controller/pd_control.go
pkg/manager/member/pd_ms_upgrader.go
pkg/manager/member/pd_ms_upgrader_test.go
pkg/manager/member/utils.go
pkg/pdapi/fake_pdapi.go
pkg/pdapi/pd_control.go
pkg/pdapi/pdapi.go
pkg/pdapi/pdms_api.go

Ref #1235, Ref https://github.com/tikv/pd/pull/8157
Let's assume there are three tso nodes scheduling-0, scheduling-1, scheduling-2.
tidb-operator will upgrade them in the order 2->0.
If `scheduling-1` is primary, it is possible that when upgrading `scheduling-1`, the primary will be transferred to `scheduling-0`, and then the primary will be transferred again when upgrading `scheduling-0`.
- This pr ensures that when `scheduling-1` is upgraded, the primary is transferred to `scheduling-2`, reducing the number of transfers.
When I created 3 scheduling pods with `8.3.0` PD version
```bash
$ kubectl exec -it basic-pd-0 -n pingcap sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
sh-5.1# curl --location …
```

pdms: Choose a suitable pdms to transfer primary when upgrade

---

cmd/backup-manager/app/backup/manager.go
cmd/backup-manager/app/export/manager.go
cmd/backup-manager/app/import/manager.go
cmd/backup-manager/app/restore/manager.go

Add some log to record the CR we are processing, so that even the CR is deleted in K8s, we can still get this information from our log.
Backup **with** `.spec.from`
```
I0823 04:07:07.095130      15 backup.go:77] start to process backup default/bk-after-restart
I0823 04:07:07.096848      15 manager.go:103] start to process backup: {"kind":"Backup","apiVersion":"pingcap.com/v1alpha1","metadata":{"name":"bk-after-restart","namespace":"default","uid":"b0c40f67-71c9-48dd-9f6d-00cd16185fbb","resourceVersion":"6697723","generation":2,"creationTimestamp":"2024-08-23T04:07:05Z","annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"pingcap.com/v1alpha1\",\"kind\":\"Backup\",\"metadata\":{\"annotations\":{},\"name\":\"bk-after-restart\",\"namespace\":\"default\"},\"spe …
```

br: add some log to record the CR we are processing

---

pkg/monitor/monitor/util.go

Monitor can be created with duplicate environment variable TZ. This is both theoretically a bad thing to do but also practically can trigger some [bugs in k8s](https://github.com/kubernetes/kubernetes/pull/121103) when it comes to pod GC. 
Don't add TZ twice in monitor util
```release-note
```

Remove duplicate env var TZ from monitor spec

---

docs/api-references/docs.md
manifests/crd.yaml
manifests/crd/federation/v1/federation.pingcap.com_volumebackups.yaml
manifests/crd/federation/v1/federation.pingcap.com_volumebackupschedules.yaml
manifests/crd/federation/v1/federation.pingcap.com_volumerestores.yaml
manifests/crd/v1/pingcap.com_backups.yaml
manifests/crd/v1/pingcap.com_backupschedules.yaml
manifests/crd/v1/pingcap.com_restores.yaml
manifests/federation-crd.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/backup/util/remote.go
pkg/backup/util/util.go
pkg/backup/util/utils_test.go

Previously, tidb-operator only supports access key and AAD authentication for Azure blob storage. The [SAS (Shared Access Signature)](https://learn.microsoft.com/en-us/azure/storage/common/storage-sas-overview) token is also commonly used, especially for cross Azure tenant scenario. The BR kernel already supports SAS token authentication. This PR adds SAS token support in tidb-operator.
On Azure, the storage account is a namespace for Azure storage. In this respect, it's similar to S3 and GCS bucket. Though Azure blob storage has another hierarchy `container`. So the storage account should also be in the `Backup` CR spec. The BR kernel should also re-organize the storage account as normal argument.
I add two new fields (`StorageAccount`, `SasToken`) in `AzblobStorageProvider` and …

BR: support Azure blob storage sas token

---

hack/local-up-by-k3s.sh
hack/local-up-by-kind.sh
hack/local-up-operator.sh

Add a new script to use k3s as k8s cluster provider and install tidb-operator
Add a new script to route between kind and k3s
Add a new script to use k3s as k8s cluster provider and install tidb-operator
Add a new script to route between kind and k3s
```release-note
Add a new script to use k3s as k8s cluster provider and install tidb-operator
Add a new script to route between kind and k3s
```

hack: support k3s as provider for local-up

---

ci/e2e_eks.groovy
ci/e2e_gke.groovy
ci/e2e_kind.groovy
ci/pull_e2e_kind.groovy
ci/pull_e2e_release.groovy
ci/vm.groovy

CI: bump runner Golang to v1.23.1

---

pkg/autoscaler/autoscaler/pdplan_autoscaler.go

The intention here should be to initialize a slice with a capacity of  `len(components)`  rather than initializing the length of this slice. 
The online demo: https://go.dev/play/p/q1BcVCmvidW
```release-note
fix slice init length
```

fix: fix slice init length

---

ci/pull_e2e_kind.groovy

the coverage files merge tool can't work in Golang v1.21 now, so we choose to disable it in release-1.5
```
✗ make gocovmerge
GOBIN=/home/ubuntu/go/src/github.com/pingcap/tidb-operator/bin/ GOOS=linux GOARCH=arm64 go install github.com/zhouqiang-cl/gocovmerge@latest
go: downloading github.com/zhouqiang-cl/gocovmerge v0.0.0-20190125174600-5256314471af
go: finding module for package golang.org/x/tools/cover
go: downloading golang.org/x/tools v0.26.0
go: toolchain upgrade needed to resolve golang.org/x/tools/cover
go: golang.org/x/tools@v0.26.0 requires go >= 1.22.0 (running go 1.21.3)
make: *** [Makefile:180: gocovmerge] Error 1
```
Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release …

e2e: disable coverage upload

---

cmd/backup-manager/app/backup/backup.go
cmd/backup-manager/app/backup/manager.go
docs/api-references/docs.md
hack/local-up-operator.sh
manifests/crd.yaml
manifests/crd/v1/pingcap.com_backups.yaml
manifests/crd/v1/pingcap.com_backupschedules.yaml
manifests/federation-crd.yaml
pkg/apis/pingcap/v1alpha1/backup.go
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/backup/backup/backup_manager.go
pkg/controller/backup/backup_controller.go
pkg/controller/backup_status_updater.go
tests/e2e/br/br.go

Closes #5699 
1. Use a more straight forward operator interface to replace the old one.
2. support pause and resume pitr task
Now, the crd to control log backup would loops like
```spec:
backupMode: log
logSubcommand: log-start/log-stop/log-pause
logTruncateUntil: "xxxxxxxxx"
```
(If no subcommand is provided, the default value is `log-start`)
If the task is not created before:
It could transfer to `running` state using `log-start`
If the task is running:
It could transfer to `paused` state using `log-pause`
It could transfer to `stop` state using `log-stop`
If the task is paused:
It could transfer to `running` state using `log-start`
It could transfer to `stop` state using `log-stop`
If the task is stopped:
This is the end state and can't transfer state again
As long as the task is …

br: a more straight forward operator interface

---

pkg/fedvolumebackup/backup/backup_manager.go
pkg/fedvolumebackup/backup/backup_test.go

Closes #5725 
only set volume backup is done (failed or complete) after all data planes are done at waiting snapshot creation time whose during is long.
```release-note
```

br: modify vbk failed when all backups are complete or failed

---

hack/lib.sh

ci: use kubetest2 hosted in pingcap/tidb-operator

---

docs/api-references/docs.md
manifests/crd/v1/pingcap.com_tidbclusters.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/manager/member/ticdc_member_manager.go

This PR introduces a new field `clusterTLSSecretName` in `tc.spec.ticdc` that support overwriting the default cluster TLS secret name. This is useful sharing the same mTLS cert secret for multiple ticdc clusters connecting to the same upstream tidb cluster.
* Create a TC with ticdc enabled
* The ticdc pod should mount '{TC_NAME}-ticdc-cluster-secret' as the `ticdc-tls`
```yaml
- name: ticdc-tls
secret:
defaultMode: 420
secretName: db-ticdc-cluster-secret
```
* Set 'tc.spec.ticdc.clusterTLSSecretName' to 'db-cluster-client-secret', the ticdc pod should be recreated and mount the secret 'db-cluster-client-secret' as the `ticdc-tls`
```yaml
- name: ticdc-tls
secret:
defaultMode: 420
secretName: db-cluster-client-secret
```
```
db-ticdc-0                               1/1     Terminating   0 …
```

opt(ticdc): support to overwrite the default cluster TLS cert secret name

---

pkg/manager/volumes/vol_compare_utils.go

evict leader for TiKV may take a long time, and the performance drop without leader-eviction is very low.
So we decide to disable this leader-eviction behavior for TiKV EBS modification.
**NOTE**: do not upgrade TiDB Operator when some leader-eviction (with EBS modification, but do not include EBS size modification, ref #5101) is happening as after this PR no "remove evict-leader-scheduler" will be performed then some evict-leader-scheduler may be kept.
```release-note
disable leader-eviction for TiKV EBS modification
```

TidbCluster: disable evict leader for TiKV EBS modification

---

pkg/manager/member/pd_upgrader.go
pkg/manager/member/pd_upgrader_test.go

ref https://github.com/pingcap/tiup/issues/2461
closes #5764
also ref #4675
The better method is to check whether if PD is ready via an API from PD (in later versions)
```
basic-pd-0                         1/1     Running   1 (66m ago)   66m
basic-pd-1                         1/1     Running   1 (70m ago)   70m
basic-pd-2                         1/1     Running   1 (74m ago)   74m
```
```release-note
```

feat(minReadySeconds): support minReadySeconds for PD

---

docs/api-references/docs.md
manifests/crd/v1/pingcap.com_tidbclusters.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/manager/member/tiproxy_member_manager.go

This PR introduces a new spec field for tiproxy: `certLayout`. It determines how tidb-operator mounts certificate related k8s secrets and how to configure TLS related configuration for tiproxy.
For compatibility, the old certLayout is kept as legacy (the default value), the newly added one is the `v1`. So that upgrading tidb-operator to new version is safe and change nothing.
* After deploy the new tidb-operator, the existing TCs having tiproxy enabled shouldn't have any pod restarts.
* Set `certLayout` to `v1 for this tc, the tiproxy pods should be restarted
```yaml
tiproxy:
certLayout: v1
```
** the tiproxy pods have been restarted
```
db-tiproxy-0                                          0/1     Terminating   0          6m6s
db-tiproxy-0                                          0/1 …
```

New certificate layout for tiproxy

---

pkg/apis/label/label.go
pkg/controller/generic_control.go
pkg/monitor/monitor/monitor_manager.go
pkg/monitor/monitor/monitor_manager_test.go
pkg/monitor/monitor/util.go

fixes #5299
- check no error log
- check ClusterRole/ClusterRoleBinding is deleted after TidbMonitor is deleted
```release-note
fix TidbMonitor can't update ClusterRole/ClusterRoleBinding when clusterScoped is set
```

fix(TidbMonitor): do not set OwnerReferences for ClusterRole and ClusterRoleBinding

---

docs/api-references/docs.md
manifests/crd.yaml
manifests/crd/v1/pingcap.com_dmclusters.yaml
manifests/crd/v1/pingcap.com_tidbclusters.yaml
manifests/crd/v1/pingcap.com_tidbdashboards.yaml
manifests/crd/v1/pingcap.com_tidbmonitors.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
pkg/manager/member/dm_master_member_manager.go
pkg/manager/member/tidb_member_manager.go
pkg/manager/member/tidb_member_manager_test.go

closes #5543
1. set `.service.type: LoadBalancer` and `.service.loadBalancerClass: service.k8s.aws/nlb` for TiDB in TidbCluster CR
2. apply the TidbCluster CR and wait for the TidbCluster to be ready
3. check an LB service is created
4. check the log of tidb-controller-manager, no repeated error log as #5543
5. update the `replicas` of TiDB to `+1`
6. wait for the TidbCluster to be ready again
7. check the log of tidb-controller-manager, no repeated error log as #5543
```release-note
```

opt: add LoadBalancerClass support for TiDB service

---

pkg/controllers/pd/tasks/cm.go
pkg/controllers/tidb/tasks/cm.go
pkg/controllers/tiflash/tasks/cm.go
pkg/controllers/tikv/tasks/cm.go
pkg/utils/hasher/hasher.go
pkg/utils/hasher/hasher_test.go
pkg/utils/toml/toml.go
pkg/utils/toml/toml_test.go

- move `GenerateHash` to hasher pkg
- add more UTs for toml pkg

refactor(utils): add hasher pkg and add more uts for toml

---

apis/core/v1alpha1/common_types.go
manifests/crd/core.pingcap.com_pdgroups.yaml
manifests/crd/core.pingcap.com_pds.yaml
manifests/crd/core.pingcap.com_tidbgroups.yaml
manifests/crd/core.pingcap.com_tidbs.yaml
manifests/crd/core.pingcap.com_tiflashes.yaml
manifests/crd/core.pingcap.com_tiflashgroups.yaml
manifests/crd/core.pingcap.com_tikvgroups.yaml
manifests/crd/core.pingcap.com_tikvs.yaml
pkg/configs/pd/config.go
pkg/configs/pd/config_test.go

chore(pd): add UT; update data path

---

.gitignore
apis/core/v1alpha1/tidb_types.go
apis/core/v1alpha1/tikv_types.go
pkg/configs/pd/config.go
pkg/configs/pd/config_test.go
pkg/configs/tidb/config.go
pkg/configs/tidb/config_test.go
pkg/configs/tiflash/config.go
pkg/configs/tiflash/config_test.go
pkg/configs/tiflash/proxy_config_test.go
pkg/configs/tikv/config.go
pkg/configs/tikv/config_test.go
pkg/controllers/tidb/tasks/pod.go

chore: add UT for config pkg; mirror fix

---

cmd/testing-workload/main.go
hack/lib/build.sh
hack/lib/e2e.sh
image/Dockerfile
pkg/configs/tidb/config.go
pkg/controllers/tidb/tasks/cm_test.go
tests/e2e/cluster/cluster.go
tests/e2e/utils/tidb/tidb.go

The e2e case `should be able to gracefully shutdown tidb` is not stable, because we use port-forward to connect to tidb.
According to `kubectl port-forward` doc:
> If there are multiple pods matching the criteria, a pod will be selected automatically. The forwarding session ends when the selected pod terminates, and a rerun of the command is needed to resume forwarding.
https://kubernetes.io/docs/reference/kubectl/generated/kubectl_port-forward/#synopsis
This PR adds a binary and deploy it to KinD to test the graceful shutdown case. The binary acts as a mysql client, it connects to the tidb cluster via k8s service's cluster IP.
Please refer to [Release Notes Language Style Guide](https://github.com/pingcap/tidb-operator/blob/master/docs/release-note-guide.md) before writing the release …

Fix(e2e): run a mysql client in kind to test graceful shutdown case

---

Makefile
pkg/action/upgrader_test.go
pkg/overlay/overlay_test.go
pkg/pdapi/pd/duration.go
pkg/pdapi/pd/duration_test.go
pkg/pdapi/pd/size_test.go

chore: add some UT for some pkgs

---

pkg/client/alias.go
pkg/client/fake.go
pkg/controllers/cluster/tasks/finalizer_test.go
pkg/controllers/common/cond.go
pkg/controllers/common/cond_test.go
pkg/controllers/common/interfaces.go
pkg/controllers/common/interfaces_test.go
pkg/controllers/common/resource.go
pkg/controllers/common/resource_test.go
pkg/controllers/common/task.go
pkg/controllers/common/task_test.go
pkg/controllers/pd/builder.go
pkg/controllers/pd/controller.go
pkg/controllers/pd/tasks/cm.go
pkg/controllers/pd/tasks/ctx.go
pkg/controllers/pd/tasks/finalizer.go
pkg/controllers/pd/tasks/pod.go
pkg/controllers/pd/tasks/pvc.go
pkg/controllers/pd/tasks/state.go
pkg/controllers/pd/tasks/status.go
pkg/utils/fake/fake.go
pkg/utils/task/v3/runner.go
pkg/utils/task/v3/runner_test.go
pkg/utils/task/v3/task.go
pkg/utils/task/v3/task_test.go

- Add ut for common task
- Add ctx into task v3
- Rename ctx to state in pd tasks
- Add State interface in pd tasks

feat(common): add ut for common tasks and refactor task utils

---

pkg/pdapi/v1/client_test.go
pkg/tidbapi/v1/client_test.go
pkg/tidbapi/v1/control.go
pkg/tidbapi/v1/control_test.go
pkg/tiflashapi/v1/client_test.go
pkg/tiflashapi/v1/control.go
pkg/tiflashapi/v1/control_test.go
pkg/tikvapi/v1/client_test.go
pkg/tikvapi/v1/control.go
pkg/tikvapi/v1/control_test.go

chore: add UT for PD/TiKV/TiDB/TiFlash APIs

---

.codecov.yml

ref https://docs.codecov.com/docs/codecovyml-reference#parsersgo
in `go tool cover`, partial coverage is considered as covered, but codecov doesn't by default
```release-note
```

chore: partials_as_hits for codecov

---

pkg/controllers/common/cond.go
pkg/controllers/common/cond_test.go
pkg/controllers/common/interfaces_test.go
pkg/controllers/pd/builder.go
pkg/controllers/pd/tasks/ctx.go
pkg/controllers/pd/tasks/finalizer.go
pkg/controllers/tiflashgroup/tasks/state_test.go
pkg/controllers/tiflashgroup/tasks/svc_test.go
pkg/controllers/tiflashgroup/tasks/updater_test.go

- add uts for tiflashgroup
- add uts for common

chore(ut): add some uts for tiflashgroup and pd

---

docs/api-references/docs.md
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/tidbcluster.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/manager/member/pd_member_manager.go
pkg/manager/member/pd_ms_member_manager.go
pkg/manager/member/pd_ms_scaler.go
pkg/manager/member/pd_ms_upgrader.go
pkg/manager/member/pvc_resizer.go
pkg/manager/member/startscript/v2/common.go
pkg/manager/member/startscript/v2/pd_start_script.go
pkg/manager/member/startscript/v2/pd_start_script_test.go
pkg/manager/member/tikv_member_manager.go
pkg/pdapi/pdapi.go

*: fix typo

---

Makefile
pkg/controllers/tidb/tasks/pod.go
pkg/controllers/tidb/tasks/pod_test.go

Opt(tidb): do not use sleep action for better compatibility

---

pkg/controllers/pd/tasks/pod.go
pkg/controllers/tidb/tasks/pod.go
pkg/controllers/tiflash/tasks/pod.go
pkg/controllers/tikv/tasks/pod.go
pkg/utils/k8s/annotation.go
pkg/utils/k8s/annotation_test.go

feat: add annotations for Prometheus

---

pkg/configs/tiflash/config.go
pkg/configs/tiflash/config_test.go

opt(tiflash): only report error if there are not equal to the managed fields for some dir config items

---

pkg/controllers/common/interfaces.go
pkg/controllers/common/resource.go
pkg/controllers/common/revision.go
pkg/controllers/common/revision_test.go
pkg/controllers/pdgroup/builder.go
pkg/controllers/pdgroup/tasks/state.go
pkg/controllers/tidbgroup/builder.go
pkg/controllers/tidbgroup/tasks/state.go
pkg/controllers/tidbgroup/tasks/state_test.go
pkg/controllers/tiflashgroup/builder.go
pkg/controllers/tiflashgroup/tasks/state.go
pkg/controllers/tiflashgroup/tasks/state_test.go
pkg/controllers/tikvgroup/builder.go
pkg/controllers/tikvgroup/tasks/state.go
pkg/utils/k8s/revision/controller_revision.go
pkg/utils/k8s/revision/controller_revision_test.go
third_party/kubernetes/pkg/controller/history/controller_history.go

- add component name into controller revision name

fix(controllerrevision): add component into revision name

---

apis/core/v1alpha1/cluster_types.go
apis/core/v1alpha1/common_types.go
cmd/operator/main.go
manifests/crd/core.pingcap.com_clusters.yaml
pkg/controllers/cluster/controller.go
pkg/controllers/cluster/tasks/status.go
pkg/controllers/cluster/tasks/status_test.go
pkg/controllers/pd/tasks/ctx.go
pkg/controllers/pd/tasks/pod.go
pkg/controllers/pd/tasks/pod_test.go
pkg/controllers/pd/tasks/pvc.go
pkg/controllers/pd/tasks/pvc_test.go
pkg/controllers/pd/tasks/status.go
pkg/controllers/tidb/handler.go
pkg/controllers/tidb/tasks/pod.go
pkg/controllers/tidb/tasks/pod_test.go
pkg/controllers/tidb/tasks/pvc.go
pkg/controllers/tidb/tasks/pvc_test.go
pkg/controllers/tiflash/handler.go
pkg/controllers/tiflash/tasks/pod.go
pkg/controllers/tiflash/tasks/pod_test.go
pkg/controllers/tiflash/tasks/pvc.go
pkg/controllers/tiflash/tasks/pvc_test.go
pkg/controllers/tikv/handler.go
pkg/controllers/tikv/tasks/pod.go
pkg/controllers/tikv/tasks/pod_test.go
pkg/controllers/tikv/tasks/pvc.go
pkg/controllers/tikv/tasks/pvc_test.go
pkg/timanager/apis/pd/v1/types.go
pkg/timanager/pd/member.go

- add cluster/member/store ID for Pod and PVC
- also add K8s labels for PVC as #6047
```release-note
```

feat: add cluster/member/store ID for Pod and PVC

---

.golangci.yml
hack/lib/kind.sh
pkg/updater/policy/topology.go
tests/e2e/cluster/cluster.go
tests/e2e/data/tikv.go
tests/e2e/e2e_test.go
tests/e2e/framework/tikv.go
tests/e2e/pd/pd.go
tests/e2e/tikv/tikv.go
tests/e2e/tikv/topology.go
tests/e2e/utils/waiter/pod.go

- init topology policy by `Add` unexpectedly changes the topology info
- add evenly spread in multiple az test cases

fix(updater): fix topology policy

---

go.mod
pkg/client/client.go
pkg/scheme/scheme.go
third_party/kube-openapi/LICENSE
third_party/kube-openapi/pkg/util/proto/document.go
third_party/kube-openapi/pkg/util/proto/document_v3.go

Fix bugs like https://github.com/kubernetes/kubernetes/issues/103597

feat(client): use openapi v3 to generate client

---

pkg/manager/volumes/pvc_replacer.go
pkg/manager/volumes/pvc_replacer_test.go

Volume Replacement causes high latency/jitter to the clients due to excessive IO and CPU usage  because schedule.store-limit.xyz.remove-peer limit is being set to unlimited. Effectively the limit becomes num_available_tikv_pods *  schedule.store-limit.xyz.add-peer. The problem is the TIKV store is still serving active leaders causing a high latency impact to clients.
This fix evicts the leaders from the TIKV pod/store before proceeding with volume replacement on the pod.
Ref: https://github.com/tikv/pd/issues/4099
Evict region leaders from the TIKV store before proceeding with volume replacement
- [X ] Has Go code change …

Volume Replacement causes high latency/jitter to the clients due to excessive IO and CPU usage

---

pkg/backup/backup/backup_manager.go
pkg/backup/backupschedule/backup_schedule_manager.go
pkg/backup/backupschedule/backup_schedule_manager_test.go
pkg/controller/backup/backup_controller.go
pkg/fedvolumebackup/backup/backup_manager.go
pkg/fedvolumebackup/backup/backup_test.go
pkg/fedvolumebackup/backupschedule/backup_schedule_manager_test.go

Closes #6090 
When some tidb cluster TC is invalid, its backup member goes into InvalidSpec status and fails. While the volumebackup status keeps as running.
Let volume backup detect the failure of the backup member due to invalid tc and fail itself.
```release-note
```

ebs br: fail the ebs volume backup when some backup member tc is invalid

---

docs/api-references/docs.md
pkg/apis/pingcap/v1alpha1/types.go
pkg/backup/restore/restore_manager.go
tests/e2e/br/br.go

Make --pitrRestoredTs optional in restore CR

---

api/core/v1alpha1/tikv_types.go
pkg/controllers/common/interfaces.go
pkg/controllers/tiflash/tasks/ctx.go
pkg/controllers/tiflash/tasks/finalizer.go
pkg/controllers/tiflash/tasks/finalizer_test.go
pkg/controllers/tiflash/tasks/state.go
pkg/controllers/tiflash/tasks/status.go
pkg/controllers/tiflash/tasks/status_test.go
pkg/controllers/tiflash/tasks/store_labels.go
pkg/controllers/tikv/tasks/ctx.go
pkg/controllers/tikv/tasks/finalizer.go
pkg/controllers/tikv/tasks/finalizer_test.go
pkg/controllers/tikv/tasks/state.go
pkg/controllers/tikv/tasks/status.go
pkg/controllers/tikv/tasks/status_test.go
pkg/controllers/tikv/tasks/store_labels.go

Fix: consider the store state `Preparing` as healthy

---

pkg/timanager/apis/pd/v1/types.go
pkg/timanager/informer.go
pkg/timanager/pd/pd.go
pkg/timanager/poller.go

TiManager: fix refresh did not work

---

pkg/controllers/pdgroup/tasks/updater.go
pkg/controllers/ticdcgroup/tasks/updater.go
pkg/controllers/tidbgroup/tasks/updater.go
pkg/controllers/tiflashgroup/tasks/updater.go
pkg/controllers/tikvgroup/tasks/updater.go
pkg/updater/policy/topology.go
pkg/updater/policy/topology_test.go
pkg/updater/state.go
pkg/utils/topology/scheduler.go
pkg/utils/topology/scheduler_test.go
tests/e2e/data/tidb.go
tests/e2e/data/tikv.go
tests/e2e/framework/tidb.go
tests/e2e/tidb/topology.go
tests/e2e/tikv/topology.go

- prefer evenly spread updated instances if there are more than one choices of topology. 
See https://github.com/pingcap/tidb-operator/issues/6136
It is not fully fixed because we always prefer scale in unavailable instances which may be not the best choice for topology spread.

fix(tidb): fix topology spread issue of tidb

---

pkg/backup/backup/backup_tracker.go

br: specify namesapce to track log backup if not cluster scoped

---

docs/api-references/docs.md
manifests/crd.yaml
manifests/crd/v1/pingcap.com_backupschedules.yaml
manifests/crd/v1/pingcap.com_compactbackups.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/controller/compactbackup/compact_backup_controller.go

Allow user use a new field named `tikvImage` to customize their own tikv image in compact.
```release-note
```

br: allow user to customize tikv image in compact

---

Makefile
pkg/timanager/manager_test.go
pkg/timanager/poller_test.go
pkg/timanager/util.go

- fix ut race
- remove unused cancel func in cache

fix(race): fix race

---

api/meta/v1alpha1/feature.go
pkg/controllers/pd/tasks/pod.go
pkg/controllers/pd/tasks/pod_test.go
tests/e2e/data/cluster.go

- add a feature to disable pd's default readiness probe
It's not useful and produce too many wan logs in pd's stdout/stderr

feat(pd): add feature to disable pd's default readiness probe

---

.golangci.yml
Makefile
cmd/tidb-backup-manager/app/backup/backup.go
cmd/tidb-backup-manager/app/restore/restore.go
cmd/tidb-backup-manager/app/util/util.go
pkg/controllers/br/manager/backup/backup_tracker.go
pkg/controllers/br/manager/util/remote.go
pkg/controllers/common/job.go
pkg/overlay/overlay_test.go
pkg/pdapi/v1/client_test.go
pkg/runtime/br.go
pkg/ticdcapi/v1/client_test.go
third_party/kubernetes/pkg/controller/history/controller_history.go

Fixes https://github.com/pingcap/tidb-operator/issues/6194
```release-note
```

Chore: bump golangci-lint to v2

---

api/core/v1alpha1/common_types.go
manifests/crd/core.pingcap.com_pdgroups.yaml
manifests/crd/core.pingcap.com_pds.yaml
manifests/crd/core.pingcap.com_schedulergroups.yaml
manifests/crd/core.pingcap.com_schedulers.yaml
manifests/crd/core.pingcap.com_ticdcgroups.yaml
manifests/crd/core.pingcap.com_ticdcs.yaml
manifests/crd/core.pingcap.com_tidbgroups.yaml
manifests/crd/core.pingcap.com_tidbs.yaml
manifests/crd/core.pingcap.com_tiflashes.yaml
manifests/crd/core.pingcap.com_tiflashgroups.yaml
manifests/crd/core.pingcap.com_tikvgroups.yaml
manifests/crd/core.pingcap.com_tikvs.yaml
manifests/crd/core.pingcap.com_tiproxies.yaml
manifests/crd/core.pingcap.com_tiproxygroups.yaml
manifests/crd/core.pingcap.com_tsogroups.yaml
manifests/crd/core.pingcap.com_tsos.yaml
tests/validation/common_test.go
tests/validation/pd_test.go
tests/validation/scheduler_test.go
tests/validation/tidb_test.go
tests/validation/tso_test.go

- add validation rule to forbid overlaying pod labels starting with `pingcap.com/`

feat(validation): cannot overlay pod labels starting with pingcap.com/

---

cmd/tidb-operator/main.go

Fix: register TiProxy and TiProxyGroup controllers

---

api/br/v1alpha1/tibr_types.go
api/br/v1alpha1/zz_generated.deepcopy.go
api/core/v1alpha1/cluster_types.go
charts/tidb-operator/templates/rbac.yaml
cmd/tidb-operator/main.go
manifests/crd/br.pingcap.com_tibrs.yaml
manifests/crd/core.pingcap.com_clusters.yaml
pkg/controllers/br/tibr/builder.go
pkg/controllers/br/tibr/controller.go
pkg/controllers/br/tibr/handler.go
pkg/controllers/br/tibr/tasks/cluster.go
pkg/controllers/br/tibr/tasks/cm.go
pkg/controllers/br/tibr/tasks/constants.go
pkg/controllers/br/tibr/tasks/ctx.go
pkg/controllers/br/tibr/tasks/pvc.go
pkg/controllers/br/tibr/tasks/status.go
pkg/controllers/br/tibr/tasks/status_test.go
pkg/controllers/br/tibr/tasks/sts.go
pkg/controllers/br/tibr/tasks/sts_test.go
pkg/controllers/br/tibr/tasks/svc.go
pkg/controllers/br/tibr/tasks/tibr.go
pkg/controllers/br/tibr/tasks/utils.go
pkg/overlay/overlay.go
pkg/utils/task/v3/task.go
pkg/utils/task/v3/task_test.go

Support following operations
1. create / delete with/without tls
2. support pod and pvc overlay
3. cluster deleted
4. cluster suspend
5. cluster pause
what is not?
1. support tibr update. ps: recreate as workround
2. e2e test
```release-note
```

add tibr controller

---

docs/api-references/docs.md
manifests/crd.yaml
manifests/crd/v1/pingcap.com_tidbclusters.yaml
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/types.go
pkg/apis/pingcap/v1alpha1/zz_generated.deepcopy.go
pkg/manager/member/node.go
pkg/manager/member/tidb_member_manager.go
pkg/manager/member/tiproxy_member_manager.go
pkg/util/map/map.go
pkg/util/map/map_test.go

Support to set Server Labels for tidb and tiproxy by adding a spec field for both tiproxy and tidb.
Newly added spec files
* .spec.tidb.serverLabels
* .spec.tiproxy.serverLabels
Reserved keys:
* tiproxy: zone, topology.kubernetes.io/zone
* tidb: zone, topology.kubernetes.io/zone
* Create a TC
* Update the TC CRD `k replace -f ./manifests/crd/v1/pingcap.com_tidbclusters.yaml`
* Deploy new tidb-operator binary, NO existing pods of this TC would be restarted or impacted
* Edit TC to set `.spec.tiproxy.serverLabels` with `group: db`, the label kv should be labeled and tiproxy pods shouldn't be restarted
```bash
curl -k --cert ./tls.crt --key ./tls.key --cacert ca.crt https://db-tiproxy-0.db-tiproxy-peer:3080/api/admin/config/ | grep labels -C 7
max-size = 300
max-days = 3
max-backups = 3 …
```

Support setting Server Labels for tidb and tiproxy via spec

---

pkg/apis/label/label.go
pkg/manager/member/tikv_scaler.go
pkg/manager/member/tikv_scaler_test.go
pkg/manager/member/utils.go

- Evict all leaders before deleting store. It can improve the jitter of TiKVs.
- Not all leaders can be evicted. If replicas of a region is all located in these deleting stores, the leader of this region cannot be evicted to other stores. We use an arbitrary timeout(5min) to avoid hanging in this case.
```release-note
```

feat(tikv): try to evict leaders before deleting stores

---

pkg/controller/pd_control.go
pkg/controller/pd_control_test.go
pkg/manager/member/pd_upgrader.go
pkg/manager/member/pd_upgrader_test.go
pkg/pdapi/fake_pdapi.go
pkg/pdapi/pd_control.go
pkg/pdapi/pd_control_test.go
pkg/pdapi/pdapi.go

Use PD ready API to check if PD members are ready during upgrading/updating, ref https://github.com/tikv/pd/pull/8749
- upgrade PD from 8.5.0 to 8.5.1 then to 8.5.2 (without mTLS enabled) successfully, and check log
```
I0612 03:40:35.851728       1 pdapi.go:820] ready API is not found, assuming PD is ready
```
- upgrade PD from 8.5.0 to 8.5.1 then to 8.5.2 (without mTLS enabled) successfully, and check log
```
I0612 06:40:23.794992       1 tidb_cluster_controller.go:142] TidbCluster: default/basic, still need sync: tidbcluster: [default/basic]'s pd member: [basic-pd-1] is not ready, error: pd upgrader: failed to check if pd member basic-pd-1 is ready: Get "https://basic-pd-1.basic-pd-peer.default.svc:2379/pd/api/v2/ready": context deadline exceeded (Client.Timeout exceeded while awaiting …
```

opt: check PD member ready when upgrading

---

api/meta/v1alpha1/feature.go
manifests/crd/core.pingcap.com_clusters.yaml
manifests/crd/core.pingcap.com_pdgroups.yaml
manifests/crd/core.pingcap.com_pds.yaml
manifests/crd/core.pingcap.com_schedulergroups.yaml
manifests/crd/core.pingcap.com_schedulers.yaml
manifests/crd/core.pingcap.com_ticdcgroups.yaml
manifests/crd/core.pingcap.com_ticdcs.yaml
manifests/crd/core.pingcap.com_tidbgroups.yaml
manifests/crd/core.pingcap.com_tidbs.yaml
manifests/crd/core.pingcap.com_tiflashes.yaml
manifests/crd/core.pingcap.com_tiflashgroups.yaml
manifests/crd/core.pingcap.com_tikvgroups.yaml
manifests/crd/core.pingcap.com_tikvs.yaml
manifests/crd/core.pingcap.com_tiproxies.yaml
manifests/crd/core.pingcap.com_tiproxygroups.yaml
manifests/crd/core.pingcap.com_tsogroups.yaml
manifests/crd/core.pingcap.com_tsos.yaml
pkg/features/reload.go
pkg/volumes/utils.go
tests/validation/common_test.go

Chore: Rename `VolumeAttributeClass` to `VolumeAttributesClass`

---

pkg/manager/member/tiproxy_member_manager.go
pkg/manager/member/tiproxy_member_manager_test.go

Currently, tiproxy spec has field `readinessProbe` but operator doesn't implement it yet. This PR addresses this.
Manual test cases
- spec
```yaml
tiproxy:
readinessProbe:
type: command
```
-  pod spec
```yaml
readinessProbe:
exec:
command:
- curl
- https://127.0.0.1:3080/api/debug/health
- --fail
- --location
- --cacert
- /var/lib/cluster-client-tls/ca.crt
- --cert
- /var/lib/cluster-client-tls/tls.crt
- --key
- /var/lib/cluster-client-tls/tls.key
failureThreshold: 3
initialDelaySeconds: 10
periodSeconds: 10
successThreshold: 1
timeoutSeconds: 1
```
- spec
```yaml
tiproxy:
readinessProbe:
type: tcp
```
-  pod spec
```yaml
readinessProbe:
failureThreshold: 3
initialDelaySeconds: 10
periodSeconds: 10
successThreshold: 1
tcpSocket:
port: 6000
timeoutSeconds: 1
```
Please refer to [Release …

feat(tiproxy): support readiness probe

---

tests/images/e2e/Dockerfile
tests/images/kubekins-e2e/Dockerfile

```
[2025-07-17T03:34:29.074Z]  ---> Running in 774eba915a6b
[2025-07-17T03:34:29.997Z] Ign:1 http://deb.debian.org/debian buster InRelease
[2025-07-17T03:34:29.997Z] Ign:2 http://deb.debian.org/debian-security buster/updates InRelease
[2025-07-17T03:34:29.997Z] Ign:3 http://deb.debian.org/debian buster-updates InRelease
[2025-07-17T03:34:29.997Z] Err:4 http://deb.debian.org/debian buster Release
[2025-07-17T03:34:29.997Z]   404  Not Found [IP: 151.101.194.132 80]
[2025-07-17T03:34:30.252Z] Err:5 http://deb.debian.org/debian-security buster/updates Release
[2025-07-17T03:34:30.252Z]   404  Not Found [IP: 151.101.194.132 80]
[2025-07-17T03:34:30.252Z] Err:6 http://deb.debian.org/debian buster-updates Release
[2025-07-17T03:34:30.252Z]   404  Not Found [IP: 151.101.194.132 80] …
```

CI: update debian image in for E2E

---

api/core/v1alpha1/pd_types.go
api/core/v1alpha1/scheduler_types.go
api/core/v1alpha1/ticdc_types.go
api/core/v1alpha1/tidb_types.go
api/core/v1alpha1/tiflash_types.go
api/core/v1alpha1/tikv_types.go
api/core/v1alpha1/tiproxy_types.go
api/core/v1alpha1/tso_types.go
manifests/crd/core.pingcap.com_pdgroups.yaml
manifests/crd/core.pingcap.com_pds.yaml
manifests/crd/core.pingcap.com_schedulergroups.yaml
manifests/crd/core.pingcap.com_schedulers.yaml
manifests/crd/core.pingcap.com_ticdcgroups.yaml
manifests/crd/core.pingcap.com_ticdcs.yaml
manifests/crd/core.pingcap.com_tidbgroups.yaml
manifests/crd/core.pingcap.com_tidbs.yaml
manifests/crd/core.pingcap.com_tiflashes.yaml
manifests/crd/core.pingcap.com_tiflashgroups.yaml
manifests/crd/core.pingcap.com_tikvgroups.yaml
manifests/crd/core.pingcap.com_tikvs.yaml
manifests/crd/core.pingcap.com_tiproxies.yaml
manifests/crd/core.pingcap.com_tiproxygroups.yaml
manifests/crd/core.pingcap.com_tsogroups.yaml
manifests/crd/core.pingcap.com_tsos.yaml
tests/validation/cluster_test.go
tests/validation/common_test.go

Chore: adjust name length limit

---

pkg/controllers/common/task.go
pkg/controllers/pdgroup/builder.go
pkg/controllers/replicationworkergroup/builder.go
pkg/controllers/schedulergroup/builder.go
pkg/controllers/ticdcgroup/builder.go
pkg/controllers/tidbgroup/builder.go
pkg/controllers/tiflashgroup/builder.go
pkg/controllers/tikvgroup/builder.go
pkg/controllers/tiproxygroup/builder.go
pkg/controllers/tsogroup/builder.go

Now features in group spec may be unset by users, we should ensure that features have been synced before reconciling.

fix(group): ensure feature gates should sync before reconciling

---

pkg/updater/builder.go

If an instance is marked to defer delete, it just like an deleting instance. Defer deletion is not revertible now.
A defer delete instance should not be counted into the update set.

fix(updater): defer delete instance should not be counted as update

---

pkg/updater/executor.go
pkg/updater/executor_test.go

- wait forever if `update == desired` and there are still unavailable outdated

fix(updater): fix executor if outdated is unavailable

---

api/core/v1alpha1/tidb_types.go
manifests/crd/core.pingcap.com_tidbs.yaml
pkg/configs/tidb/config.go
pkg/configs/tidb/config_test.go
tests/validation/tidb_test.go

- support keyspace in config file if spec.keyspace is unset 
- remove unnecessary validation
- for a tidb instance, it's ok to back to StandBy mode or change keyspace name by restarting

fix(tidb): support keyspace in config file if spec.keyspace is unset

---

docs/api-references/docs.md
pkg/apis/pingcap/v1alpha1/openapi_generated.go
pkg/apis/pingcap/v1alpha1/tidbinitializer_types.go

https://github.com/pingcap/tidb-operator/blob/v1.6.3/docs/api-references/docs.md#tidbinitializer currently doesn't explain what this field does. 
I added a comment to make it more obvious that this isn't a literal secret, but the name of the Kubernetes secret that is used to initialize the cluster.
Note that the `tidb-secret` can store a list of secrets as demonstrated on https://docs.pingcap.com/tidb-in-kubernetes/stable/initialize-a-cluster/#set-initial-account-and-password so it is not restricted to the root account.
```release-note
```

Add comment for passwordSecret

---

cmd/testing-workload/pd_region.go

- adjust leader transfer time to 200ms
100ms is not very stable

fix(e2e): adjust default leader transfer time to 200ms
